### ISSUE TITLE
[feature request] Use composable function name as route

### ISSUE THREAD

**Issue by stewe93** [raamcosta/compose-destinations#10]
Hi! 

What do you think about generating the route from the composable function name? Keep the current `route` parameter but generate a default value for it , maybe adding a pre- or postfix to the generated string, something like this.

**Comment by raamcosta** [comment]
Why so you come here to reveal future features that are supposed to be a secret? 🤫

Just kidding 😁
But yeah, next version will come with this feature: you won't have to specify route parameter (you can if for whatever reason you want a route different from the Composable name, for example could be useful in nested nav graphs).

Composable names like:
`ProfileScreen`

Will generate routes like:
`profile_screen`

**Comment by raamcosta** [comment]
Thanks for opening the feature request! Please keep it up if you have other ideas :)
