### ISSUE TITLE
Nested Graph, LoginScreen/authGraph, HomeScreen/,mainGraph

### ISSUE THREAD

**Issue by ismai117** [raamcosta/compose-destinations#101]
Hi Rafael,

 I've created 2 navGraphs  authGraph / mainGraph and i'm trying to implement the following 

AuthGraph includes LoginScreen
MainGraph includes HomeScreen / other screens

Sign in 

Login -> Home 

-------------------------------

Sign out

Home / other screens -> Login

appreciate all the help!

**Comment by huaweikai** [comment]
I have the same problem.

If I have a AppNavHost, it has AlbumScreen, ArtistScreen, LoginScreen..

There is also a HomeNavHost, AppNavHost contains HomeNavHost, so how do I jump from HomeNavHost to AppNavHost AlbumScreen? I mean using DestinationsNavigator

**Comment by huaweikai** [comment]
I have an idea. Define a staticCompositionLocalOf .

And then when you go from AppNavHost to HomeNavHost, HomeNavHost still belongs to AppNavHost, then you get the DestinationsNavigator of AppNavHost. CompositionLocalProvider is used to assign to it, and then HomeNavHost gets the DestinationsNavigator of AppNavHost.

```
val appNavigator = staticCompositionLocalOf<DestinationsNavigator> { error("!!!!!!num") }

class DesinationsActivity : ComponentActivity() {
    @OptIn(ExperimentalMaterialNavigationApi::class, ExperimentalAnimationApi::class)
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            DestinationsNavHost(
                navGraph = NavGraphs.root
            )
        }
    }
}
@Destination(
    start = true
)
@Composable
fun AppOneScreen(
    navigator: DestinationsNavigator
) {
    Column {
        Button(onClick = {
            navigator.navigate(HomeScreenDestination())
        }) {
            Text(text = "toHome")
        }
        Button(onClick = {
            navigator.navigate(AlbumScreenDestination())
        }) {
            Text(text = "to Album Screen")
        }
    }
}

@Destination
@Composable
fun AlbumScreen() {
    Text(text = "this is AlbumScreen")
}

@Destination
@Composable
fun HomeScreen(
    navigator: DestinationsNavigator /*appNavigator*/
) {
    CompositionLocalProvider(
        appNavigator provides navigator
    ) {
        DestinationsNavHost(navGraph = NavGraphs.home)
    }
}

@Destination(
    start = true,
    navGraph = "home"
)
@Composable
fun HomeStartScreen() {
    val navigator = appNavigator.current
    Column {
        Text(text = "this is homeStartScreen")
        Button(onClick = {
            navigator.navigate(AlbumScreenDestination())
        }) {
            Text(text = "to AppNavHost album")
        }
    }
}
```
But I don't think it's a good idea

**Comment by raamcosta** [comment]
Hi guys 👋
I’ll help you!

Starting with your code @huaweikai. Why do you need multiple NavHosts? There is a difference between NavHosts and Nav graphs. One NavHost receives one nav graph, but that nav graph may contain multiple nested nav graphs.
So I would always prefer to use only one NavHost, except some very specific use case. In fact, the way you have that setup, the home graph is nested in root one. So when you call DestinationsNavHost passing root, the home graph is also being registered in that NavHost!

Let me know if you really want to use multiple NavHosts. It’s definitely doable, but there is a better way to not use local compositions. And you need to disable nav graphs generation so that you can define two completely separate nav graphs.

**Comment by raamcosta** [comment]
Sorry @ismai117, I had to take a break and this is when I could come to answer you :) 

So you'll want to annotate your LoginScreen composable with `@Destination(navGraph = "login")`, and all others with `@Destination(navGraph = "main")`. 

Then these are your nav graphs:
"Root" contains both main and login nested nav graphs.
```mermaid
  graph LR;
      root-->main;
      root-->login;
```
 
After this, you'll want to pass `NavGraphs.root`  to your `DestinationsNavHost` call since it is the one that contains all your destinations you want to register in there.

Finally, there are a lot of ways you can go about managing log in status and making sure the user is not on a screen where he needs to be logged in. I won't cover everything here. 
The most basic way to do this is to set your LoginScreen as the start destination (`@Destination(start = true, navGraph = "login")`). Then if the user successfully logs in, you'll want to navigate to your other nav graph (`navigator.navigate(NavGraphs.main)`). Whenever the user logs out, you navigate to the login screen (`navigator.navigate(NavGraphs.login)`). Both these navigations should pop out all other screens from the back stack so that the user cannot go back to previous screen.  You can use the builder to do that:

```kotlin
@Destination
@Composable
fun LoginScreen(
     navigator: DestinationsNavigator
) {
    // uppon successful login:
    navigator.navigate(NavGraphs.main) {
        popUpTo //....
    }

}
```

This is just something to get you started, it may **NOT** be the best way to handle login flows if your login expires for example. Because if the process is killed and the user is restored to a screen where he needs login, but his login expired, you need to explicitly go back to the login screen.

I'll close this, but feel free to add more follow up questions below!

**Comment by ismai117** [comment]
Hi Raam, thank you very much! 

I have 2 more questions and I would highly appreciate it if you could help me with it. 

1) what is the best way to save a user status if they signed in but the app got destroyed?.

2) how do add a Drawer using your library? I tried implementing it but the topbar shows up in the login screen - scaffold

thanks!

**Comment by raamcosta** [comment]
1. Probably save something in a persistent way (db, shared prefs, etc)
2. You need to check if the current destination is the login screen, then you don’t show the top bar. You can check the file from sample app named DestinationsSampleScaffold for a way to update elements given the current Destination.

**Comment by ismai117** [comment]
Thanks!, I will check that out

I followed through the first answer you gave me. but its not working for me, 

I annotated  the screens such as (home, messages) with "main" and LoginScreen with "login"

I set LoginScreen - start destination to true but when I run it it's asking me to set start for main Graph, when I set login screen and home screen to true. The background is white, its not showing anything

**Comment by ismai117** [comment]
I've solved it. Thanks

**Comment by ismai117** [comment]
inside MainActivity Class

@AndroidEntryPoint
class MainActivity : ComponentActivity() {

    private val scannerViewModel: ScannerViewModel by viewModels()
    private val barcode = StringBuffer()

    @SuppressLint("UnrememberedMutableState")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)


        setContent {

            actra_appTheme() {

                Column(
                    Modifier.fillMaxSize(),
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.Center
                ) {

                    ContainerScreen()

                }
            }
        }
    }

    @Composable
    fun ContainerScreen() {

        val scaffoldState = rememberScaffoldState()
        val coroutineScope = rememberCoroutineScope()


        Scaffold(
            scaffoldState = scaffoldState,
            topBar = {

            }
        ) {
            RootNavigation()
        }


    }

}

**Comment by ismai117** [comment]
Caused by: java.lang.RuntimeException: No found destinations for 'root' navigation graph
        at com.example.myfirstapp.presentation.screens.NavGraphs.<clinit>(NavGraphs.kt:37)

**Comment by raamcosta** [comment]
Oops this is maybe my bad sorry
I did not have my computer with me 😄 

Remove all navGraph = main and use NavGraphs.root as your main instead.

**Comment by ismai117** [comment]
it works now, thank you! 

just one final question, I'm a  junior so sorry if i'm asking a lot :) 

Can you show me an easy way of Implementing a drawer navigation with the library, I tried doing it but im confused.

Thanks

**Comment by ismai117** [comment]
Hi Rafeal, I've looked at the examples, I do understand a little but the DestinationsSampleScaffold.kt is just too confusing for me. Sorry 

Can we implement the drawer navigation/scaffold the usual way but with the library or do we have to follow your example?

**Comment by raamcosta** [comment]
If you're not using bottom sheet screens, all you need there is this:

```kotlin
@Composable
fun MyScaffold(
    navController: NavHostController,
    scaffoldState: ScaffoldState,
    topBar: @Composable (Destination) -> Unit,
    bottomBar: @Composable (Destination) -> Unit,
    drawerContent: @Composable ColumnScope.(Destination) -> Unit,
    content: @Composable (PaddingValues) -> Unit
) {
    val currentBackStackEntryAsState by navController.currentBackStackEntryAsState()
    val destination = currentBackStackEntryAsState?.navDestination
        ?: NavGraphs.root.startRoute.startDestination

    Scaffold(
        scaffoldState = scaffoldState,
        topBar = { topBar(destination) },
        bottomBar = { bottomBar(destination) },
        drawerContent = { drawerContent(destination) },
        content = content
    )
}
```

And then you use it instead of using Scaffold directly:

```kotlin
//...

MyScaffold(
    scaffoldState = scaffoldState,
    navController = navController,
    drawerContent = { currentDestination ->
        MyDrawer(
            currentDestination
        )
    }
) {
    DestinationsNavHost//...
}
```

And know your `MyDrawer` Composable receives the current destination. You can use that to adapt it (for example, I write the current selected destinationin bold). And you can check how I do navigation there :)

**Comment by ismai117** [comment]
Hi Rafael, when I click on the item it doesn't navigate, I've attached below what I implemented.. Forgive me for my questions!

@Composable
fun Container() {

    val navController = rememberNavController()
    val scaffoldState = rememberScaffoldState()
    val coroutineScope = rememberCoroutineScope()

    MyScaffold(
        navController = navController,
        scaffoldState = scaffoldState,
        topBar = {
            TopBar(destination = it) {
                coroutineScope.launch {
                    scaffoldState.drawerState.open()
                }
            }
        },
        bottomBar = {},
        drawerContent = { currentDestination ->
            MyDrawer(
                currentDestination,
                navController,
                coroutineScope,
                scaffoldState
            )
        }
    ) {
        DestinationsNavHost(navGraph = NavGraphs.root)
    }


}



@Composable
fun DirectionDestination.DrawerContent(
    isSelected: Boolean,
    onDestinationClick: (DirectionDestination) -> Unit
) {
    when (this) {
        HomeScreenDestination,
            MessagesScreenDestination -> {
                Text(
                    text = stringResource(id = requireTitle),
                    modifier = Modifier
                        .padding(8.dp)
                        .clickable{
                            onDestinationClick(this)
                        },
                    fontWeight = if (isSelected) FontWeight.Bold else null
                )
            }
    }
}

@get:StringRes
val Destination.requireTitle
    get(): Int {
        return title ?: throw RuntimeException("Destination $this, doesn't contain title")
    }

@get:StringRes
val Destination.title
    get(): Int ? {
        return when (this) {
            HomeScreenDestination -> R.string.home_screen
            MessagesScreenDestination -> R.string.messages_screen
            else -> null
        }
    }


@Composable
fun MyDrawer(
    destination: Destination,
    navController: NavHostController,
    coroutineScope: CoroutineScope,
    scaffoldState: ScaffoldState
) {
    NavGraphs.root.destinations
        .filterIsInstance<DirectionDestination>()
        .forEach {
            it.DrawerContent(
                isSelected = it == destination,
                onDestinationClick = { clickedDestination ->
                    if (navController.currentBackStackEntry?.lifecycle?.currentState == Lifecycle.State.RESUMED
                        && navController.currentBackStackEntry?.navDestination != clickedDestination
                    ) {
                        navController.navigateTo(clickedDestination)
                        coroutineScope.launch { scaffoldState.drawerState.close() }
                    }
                })
        }
}



Thanks

**Comment by ismai117** [comment]
@Composable
fun DirectionDestination.DrawerContent(
    isSelected: Boolean,
    onDestinationClick: (DirectionDestination) -> Unit
) {
    when (this) {
        HomeScreenDestination,
            MessagesScreenDestination -> {
                Text(
                    text = stringResource(id = requireTitle),
                    modifier = Modifier
                        .padding(8.dp)
                        .clickable{
                            onDestinationClick(this)
                        },
                    fontWeight = if (isSelected) FontWeight.Bold else null
                )
            }
    }
}

@get:StringRes
val Destination.requireTitle
    get(): Int {
        return title ?: throw RuntimeException("Destination $this, doesn't contain title")
    }

@get:StringRes
val Destination.title
    get(): Int ? {
        return when (this) {
            HomeScreenDestination -> R.string.home_screen
            MessagesScreenDestination -> R.string.messages_screen
            else -> null
        }
    }

**Comment by raamcosta** [comment]
You need to pass the NavController to the DestinationsNavHost for that NavController to be used!

Then it should work 🙂

**Comment by ismai117** [comment]
@Composable
fun MyDrawer(
    destination: Destination,
    navController: NavHostController,
    coroutineScope: CoroutineScope,
    scaffoldState: ScaffoldState
) {
    NavGraphs.root.destinations
        .filterIsInstance<DirectionDestination>()
        .forEach {
            it.DrawerContent(
                isSelected = it == destination,
                onDestinationClick = { clickedDestination ->
                    if (navController.currentBackStackEntry?.lifecycle?.currentState == Lifecycle.State.RESUMED
                        && navController.currentBackStackEntry?.navDestination != clickedDestination
                    ) {
                        navController.navigateTo(clickedDestination)
                        coroutineScope.launch { scaffoldState.drawerState.close() }
                    }
                })
        }
}

**Comment by raamcosta** [comment]
To be clear the navcontroller you get from calling rememberNavController, you need to pass it to the DestinationsNavHost call 🙂

**Comment by ismai117** [comment]
ohh it works now, thank you so much! You've created an amazing library!

**Comment by ismai117** [comment]
Hi Rafael

I implemented the login flow to see if the user is logged in or not and then navigate to login screen or Home Screen

![Screenshot 2022-04-18 at 01 55 10](https://user-images.githubusercontent.com/88812838/163738948-16118e35-6dfc-4837-ab2c-d001bed98f2a.png)

The code above works but  if user is already logged in and the app gets recreated, the login screen (start destination) shows up first before it navigates to the Home Screen.

I'm trying to figure out how I can  show the home screen only if user is logged in without the login screen showing again. 


thanks!

**Comment by raamcosta** [comment]
Hi there!

You found one of the reason why the simplest approach is not the best :D 

Check this video:
https://www.youtube.com/watch?v=09qjn706ITA&t=286s

**Comment by ismai117** [comment]
HI Rafael, thanks for sending that video 

After watching it, I noticed that a fragment was being used rather than a composable. Do you have any simple apps or documentation which shows how to implement it? 

I usually work with Firebase Auth but I'm currently building an app for someone who doesn't want firebase auth and I haven't got a clue on how to handle it user is already logged in

**Comment by raamcosta** [comment]
Yeah but the principle is the same, maybe you need a way to always check if you need to show login and if so show it above whatever is the current screen. 

Sorry @ismai117 , other than this I don’t know myself. I honestly haven’t implemented this flow yet. Just know that this is not an issue with Compose Destinations, you would be in the same position if you were using official compose navigation.

So whatever solution you may find out there for official navigation library, will be easily doable with Compose Destinations too 🙂

**Comment by ismai117** [comment]
no worries Rafael, thanks. 

is there a way I can pass the NavController inside the composable from DesitnationNavHost() like we did with NavHost() ?
