### ISSUE TITLE
request for: multiple navGraphs example 

### ISSUE THREAD

**Issue by DAT4** [raamcosta/compose-destinations#105]
Hi - I just want to ask for an example of a use case with multiple navgraphs.

I am using jetpack compose navigation - and I have divided my app into different areas - for instance I have one part of the app with a dashboard where I have a list of newsItems, then when I click one of the news items I want to navigate to the newsDetailView which is fullscreen, so I have it in the outer navigation graph.

With normal compose navigation I would have 2 different navControllers and pass the rootNavController into the newsList, so that I get control of the outer navGraph and is then able to navigate on 2 different levels. 

I have some dificulties doing the same with compose destinations. And I am wondering what the point of multiple navGraphs is if you cannot jump up and down in the navigation tree? 

Best Regards Martin

**Comment by DAT4** [comment]
Thank you very much, your answer was very helpful. 

I tried out the manual creation of NavGraph for a bit, but it seemed much easier just to pass in a lambda to the dependencies for the inner navHost.

```kotlin
@Destination(start = true)
@Composable
fun DashBoardScreen(
    modifier: Modifier = Modifier,
    navigator: DestinationsNavigator
) {
    val navController = rememberNavController()
    Scaffold(
        modifier = modifier,
        bottomBar = {
            DashBoardBottomBar(navController = navController)
        },
    ) { paddingValues ->
        DestinationsNavHost(
            modifier = Modifier.padding(paddingValues = paddingValues),
            navGraph = NavGraphs.dashboard,
            navController = navController,
            dependenciesContainerBuilder = {
                dependency { direction: Direction -> navigator.navigate(direction = direction) }
            }
        )
    }
}
```

**Comment by arunjoseph-tomtom** [comment]
A question related to this issue. @raamcosta , Do you suggest the same multiple `NavHost` approach for [BottomSheetScaffold](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#BottomSheetScaffold(kotlin.Function1,androidx.compose.ui.Modifier,androidx.compose.material.BottomSheetScaffoldState,kotlin.Function0,kotlin.Function1,kotlin.Function0,androidx.compose.material.FabPosition,kotlin.Boolean,androidx.compose.ui.graphics.Shape,androidx.compose.ui.unit.Dp,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.unit.Dp,kotlin.Function1,kotlin.Boolean,androidx.compose.ui.graphics.Shape,androidx.compose.ui.unit.Dp,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,kotlin.Function1)) as well?
![image](https://user-images.githubusercontent.com/83452786/163674225-0f3199f5-b7c5-41d0-8eff-67e94a7132cc.png)

I have a drawer with settings and a bottom sheet content with different modes(screens). I have tried this [approach](https://github.com/raamcosta/compose-destinations/issues/105#issuecomment-1099763429) and it works.
```
    DestinationsNavHost(
        navController = navController,
        navGraph = HomeNavGraph,
        dependenciesContainerBuilder = {
            dependency(navigationProvider)
        }
    )
    {
        composable(HomeScreenDestination) {
            HomeScreen(
                navigator = navigationProvider,
                drawerContent = {
                    val drawerNavController: NavHostController = rememberNavController()
                    DestinationsNavHost(
                        navController = drawerNavController,
                        navGraph = DrawerNavGraph,
                        dependenciesContainerBuilder = {
                            dependency(navigationProvider)
                        }
                    )
                },
                bottomPanelContent = {
                    val bottomPanelNavController: NavHostController = rememberNavController()
                    DestinationsNavHost(
                        navController = bottomPanelNavController,
                        navGraph = BottomNavGraph,
                        dependenciesContainerBuilder = {
                            dependency(navigationProvider)
                            dependency(DefaultBottomPanelNavigationProvider(bottomPanelNavController))
                        }
                    )
                }
            )
```

**Comment by raamcosta** [comment]
Basically, my answer is: if it works for you, I don't see why not.
I personally tend to use a single NavHost and show/hide top-level widgets (drawer, bottomNav bar, top bar, etc) depending on which screen is currently opened.
I also think I've seen somewhere a comment from Ian lake saying that we should only use one NavHost, but don't quote me on this 😛 

My job with the library is to provide ways to support both approaches, and I want to believe I'm doing that. Even though as I said before, I am working on a way to have automatic nav graphs generation way better and more extensible (looking at your code it looks like you are manually creating the nav graphs, you probably won't need to anymore after the next version 😉 )

**Comment by arunjoseph-tomtom** [comment]
Thanks, waiting for the next version!
Another reason for me to make each drawer view(`composable`) and bottom bar view (`composable`) as navigation destinations is because I can get separate android viewmodels per drawer or per bottom bar mode. (It should have been just possible to get `viewmodel` per `composable`).

**Comment by DAT4** [comment]
@raamcosta - I am now trying only having one NavHost, and showing/hiding a top bar on screens depending on which screen is currently opened, while using sliding transitions between the screens. A problem I have is that the "old" screen is still shown for 200ms while the animation is going and the if statement runs in ~0ms, so there is a small jump happening with some of the elements on the "old" screen while it is transitioning away.

**Comment by DAT4** [comment]
Thank you for the quick reply - I will definitely try out the multiple DestinationsNavHost's as well. :) 

Another solution could also be to wrap every single "dashboard" screen with their own dashboard, that way it will look like it is the same even though its alot of different dashboards. And probably it will not be that good for performance.

Probably I should post this on stackoverflow or something else. :) I don't know any compose slack channel :)

**Comment by raamcosta** [comment]
It’s part of the official Kotlin channel. You can Google it :) sorry I’m on my smartphone eheh 😁
