### ISSUE TITLE
[BUG] Launching explicit deep link caused duplicate of Activity

### ISSUE THREAD

**Issue by risalfajar** [raamcosta/compose-destinations#106]
I have this composable inside `MainActivity`
```kotlin
@Destination(deepLinks = [DeepLink(uriPattern = "appname://notifications")], navGraph = "main")
@Composable
fun NotificationScreen(navigator: DestinationsNavigator) {}
```

Then I'm trying to launch show a notification with an intent containing explicit deep link as taught by the official [documentation](https://developer.android.com/jetpack/compose/navigation#deeplinks)
```kotlin
val intent = Intent(Intent.ACTION_VIEW, "appname://notifications".toUri(), this, MainActivity::class.java)
val pendingIntent = PendingIntent.getActivity(context, 0, intent, PendingIntent.FLAG_IMMUTABLE)
// then show notification as usual
```

This is what happens when I click the notification:
1. It starts a new `MainActivity` (I know this is new because the splash screen showed up)
2. It opens the correct destination
3. But when I press back I get the home screen twice (another sign of duplicate activity)

This is my manifest:
```xml
        <activity
            android:name=".ui.MainActivity"
            android:exported="true"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.SplashScreen"
            android:windowSoftInputMode="adjustResize"
            tools:ignore="LockedOrientationActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

**Comment by raamcosta** [comment]
Hi @risalfajar!

This is not a bug with Compose Destinations. All the library does is take the deep links from the annotation and pass them to the correct APIs of the official library.

So, my advice is that you Google about this use case and see how people do to avoid the duplicate activity. (Could it be a flag like singleTop in the activity for example?? Don’t quote me on this 😃)

Let me know if this makes sense to you 🙂

**Comment by risalfajar** [comment]
Yes that makes sense.
I've tried all launch mode and intent flags to no avail.
I think I should report this to the Google team.

**Comment by raamcosta** [comment]
Before reporting, I would leave a question on Kotlin slack. There is a channel specifically for navigation component. Other for compose. 

I believe there has to be a way to make this work 🤔

**Comment by risalfajar** [comment]
I very rarely use Slack, how to join the channel?

**Comment by raamcosta** [comment]
Either this:
http://kotlinlang.slack.com/

or this if fails:
https://surveys.jetbrains.com/s3/kotlin-slack-sign-up

**Comment by risalfajar** [comment]
@kserko My workaround that time is like this:

1. Instead of using URI, launch MainActivity directly with a flag that will be handled by MainActivity
```kotlin
val intent = Intent(context, MainActivity::class.java).apply {
  putExtra("type", NOTIFICATION)
}
val pendingIntent = TaskStackBuilder.create(context).run {
  addNextIntentWithParentStack(intent)
  getPendingIntent(0, PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE)
}
// use pendingIntent in the notification
```

2. Handle the extras in MainActivity
```kotlin
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // ... set content

        handleIntent(intent)
    }

    override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        handleIntent(intent)
    }

    private fun handleIntent(intent: Intent?) {
        val extras = intent?.extras
        val type = extras?.getString("type")
        val isFromFcm = extras?.containsKey("google.message_id") == true
        when {
            type == MESSAGE -> launchChatScreen(intent.extras!!)
            type == NOTIFICATION -> launchNotificationsScreen()
            isFromFcm -> launchNotificationsScreen()
        }
    }
```

**Comment by kserko** [comment]
Thanks @risalfajar, I came up with a similar solution too. While still using URI, I had to change my main activity's launchMode to `singleTask` otherwise I noticed `onNewIntent()` wasn't getting called.

**Comment by alitahabundle** [comment]
HI @risalfajar, I am also having the same issue, have you managed to solve it without using the handleDeepLink?

**Comment by winechitpaing-codigo** [comment]
This issue was fixed at compose navigation version 2.7.5, but current compose-destination still used compose navigation version 2.7.2. @raamcosta please could you help to update the latest version? https://developer.android.com/jetpack/androidx/releases/navigation#version_275_3

**Comment by raamcosta** [comment]
@winechitpaing-codigo 
Yes, I’ve been meaning to update it, thanks for reminding me!
I’ll do it today 🙂

**Comment by raamcosta** [comment]
@winechitpaing-codigo should be up! 1.9.55

**Comment by RomanMarinov** [comment]
> https://developer.android.com/jetpack/androidx/releases/navigation#version_275_3

good afternoon, have you found a solution to the problem with deeplink for compose? I redirected the intent but there was no result

**Comment by risalfajar** [comment]
@RomanMarinov the problem has been fixed. Try to update your Compose Destination version.
