### ISSUE TITLE
Keep either route or routeId in generated DirectionDestination code

### ISSUE THREAD

**Issue by vinchamp77** [raamcosta/compose-destinations#110]
The generated code has both `route`, `routeId` and I think we should just keep one to avoid confusion.

```
object LoginScreenDestination : DirectionDestination {
         
    operator fun invoke() = this
    
    override val routeId = "login_screen"

    override val route = routeId    
   ...    
}
```

**Comment by raamcosta** [comment]
Hi @vinchamp77!

In that example where the Destination doesn’t have any navigation arguments, it looks rather silly but consider that when Destinations have nav args they will be different and routeId will serve as the prefix of route.
Besides, the user of the library won’t need to use either of these unless for some more exotic use cases. When the user needs to use it, it will always be route and never routeId.

That said, I do understand your point as I have seen people wrongly using routeId before. So I’ll check what can be done, at the every least maybe I can add a restricted annotation on routeId to deter people from using it (ide will show error).


Thank you! 👍

**Comment by vinchamp77** [comment]
You're welcome!

I see what you meant. If you want to keep the `routeId`, I suggest renaming `route` to `routePath`, then it can be clearly differentiated from `routeId`. If there is no actual use case of `routeId`, maybe don't expose it. Just my 2 cents (with limited knowledge).

My usage is like this:
```
navigator?.navigate(LoginScreenDestination) {
   popUpTo(LoginScreenDestination.route) {inclusive = true}
}
```

Maybe it can be replaced by `popBackStack()` API. I'm not sure. It seems like still required the `route` info. I will play around with it.

**Comment by raamcosta** [comment]
There is a popUpTo that accepts the destination without .route

**Comment by raamcosta** [comment]
Extension function

**Comment by raamcosta** [comment]
I’m not convinced that routePath is necessarily better 😅 All routes are paths of some sort. Maybe `routePrefix`? 

It’s hard not to expose it because I use it internally and it’s through the interface type that  all these Destinations implement. 
It will have to be through annotations of some sort 🙂

**Comment by vinchamp77** [comment]
You're right. `path` has the same meaning as `route`.

`routePrefix` sounds good. Maybe `baseRoute`? Based on the `baseUrl` naming convention for REST API.

You can have an abstract class in between and make it protected? I'm not sure if that makes senses.

**Comment by raamcosta** [comment]
`baseRoute` rocks 👍 

I'll change it and annotate it. Abstract class wouldn't be easy atm. I'm using the fact that this is an interface in multiple places 😛 
I think a restrictApi annotation will serve us good enoguh 😉

**Comment by raamcosta** [comment]
Done on 1.5.2-beta!

**Comment by jasco** [comment]
I am upgrading and bumped into this change.  I was using `routeId` to selectively set system bar colors for certain routes by checking `destination.route?.startwWith(MyScreenDestination.routeId)`.  I am passing parameters so the route is a string template.  Is there another way to robustly map from the route back to the typed destination?

**Comment by raamcosta** [comment]
Hey @jasco 👋 

If you have the destination, I guess you can just do `destination == MyScreenDestination`. But you could also `destination.route == MyScreenDestination.route`. Even with parameters, `Destination.route` is final, it never changes.
Only `Direction` contains the route with arguments.
