### ISSUE TITLE
Add option to choose the nav graph in which a "multi-nav-graph-assigned" Destination is opened through a deep link

### ISSUE THREAD

**Issue by alex-burghuber** [raamcosta/compose-destinations#112]
Hey,
I am developing an app with a navigation structure similiar to that of your tivi fork in which some destinations are part of multiple nav graphs. I now assign a deep link to a destination like this:
```kotlin
@Destination(
    deepLinks = [
        DeepLink(uriPattern = "https://exampleappwebsite.com/?id={id}")
    ]
)
```
When the deep link is now fired the nav graph in which the destination is opened seems to be random. An extra configuration for the nav graph in DeepLink() would be great.

**Comment by raamcosta** [comment]
Hey @alex-burghuber!

Ahhh well found 🙂 I never considered this scenario. I will check into this to find a good way to solve it.
Meanwhile, an ok workaround is having two annotated `@Destinations` calling the same Composable. Then you'll have 2 generated Destinations and you can add DeepLink annotation on one of them only.

**Comment by raamcosta** [comment]
@alex-burghuber if you could test the new APIs to see how you feel about them 🙏

Basically since the routedIn api is used at runtime, the new APIs also needed to be.
You can check an example in the second point of these release notes:
https://github.com/raamcosta/compose-destinations/releases/tag/1.5.2-beta

**Comment by alex-burghuber** [comment]
@raamcosta 
Thank you for implementing this so quickly.
Just tried it and it works great 😁

Your library makes everything so much easier 🙌
