### ISSUE TITLE
Multi-modules and BottomAppBar, how do you include all the destinations?

### ISSUE THREAD

**Issue by nachtien** [raamcosta/compose-destinations#114]
First off, great work on this library!

Say I have the following structure:

``` text
Florida Module
	├FloridaScreen.kt
	│	└@Destination
	│	fun FloridaScreen() {
	│		Scaffold(
	│			bottomBar = bottomAppBar(allDestinations) 
	│		) {
	│		...content
	│		}
	│
	└build.gradle.kts
		ksp {
  			arg("compose-destinations.mode", "destinations")←
			arg("compose-destinations.moduleName", "florida")
		}

Indiana Module
	├IndianaScreen.kt
	│	└@Destination
	│	fun FloridaScreen() {
	│	   Scaffold(
	│		bottomBar = bottomAppBar(allDestinations)
	│		) {
	│		...content
	│		}
	│
	└build.gradle.kts
		ksp {
  			arg("compose-destinations.mode", "destinations")
			arg("compose-destinations.moduleName", "indiana")
		}
```

I'd like to display all destinations in the bottomAppBar (so Indiana and Florida). How would I get these without depending on every module?

My initial thought is creating the destinations in some destinations common module that would depend on the Indiana and Florida modules, create the scaffolding there, then in the Florida and Indiana modules I'd just have some sort of `ScreenContent` function. I don't like the idea of having the screens defined like this in a different module though.
<details>
	<summary>Example code</summary>

build.gradle.kts
```kotlin
 	implementation(project(":indiana"))
 	implementation(project(":florida"))
```
Destinations.kt
```kotlin
	enum class BottomBarDestination(
			val direction: DirectionDestinationSpec,
			val icon: ImageVector,
			@StringRes val label: Int
	) {
		Indiana(IndianaScreenDestination, Icons.Default.Home, R.string.indiana_screen),
		Flordia(FloridaScreenDestination, Icons.Default.Email, R.string.florida_screen),
	}

	@Destination
	@Composable
	fun IndianaScreen(){
		Scaffold(
				bottomBar = allDestinations
		) {
			IndianaContent()
		}
	}
	
	@Destination
	@Composable
	fun FloridaScreen(){
		Scaffold(
				bottomBar = allDestinations
		) {
			FloridaContent()
		}
	}

```  

</details>

**Comment by raamcosta** [comment]
Hey @nachtien!

So, you definitely need a navigation module where you call your DestinationsNavHost and this module needs to depend on all others. But each module outputs either an entire NavGraph or a set of Destinations (with your configuration above, it would be a set of Destinations), meaning you don't need to define the destinations in the common module again, you just use the generated ones from each of your feature modules.

Then in the navigation module, you need to put all those destinations together into a `NavGraphSpec` implementing object and call `DestinationsNavHost` with it.

To me, your configuration looks very similar to what I have in a [Crhis Banes tivi fork](https://github.com/raamcosta/tivi) so I'd recommend you check that out 🙂 

I'll close this, but feel free to add follow-up below.
