### ISSUE TITLE
can't I use viewModel and DestinationsNavigator  at the same time?

### ISSUE THREAD

**Issue by coodin** [raamcosta/compose-destinations#117]
how can I  use both of viewModel which use hilt and navController or DestinationsNavigator as my composable function parameters, by the way I use navArgsDelegate argument  parameter of Destination annotation to clarify arguments passed by navigate function. I am asking this question because I can't provide two of them at the same time, it gave me an error for DestinationsNavigator which was ,  the library have been wanted DestinationsNavigator from me  but as I understood it should have been given by library.

**Comment by raamcosta** [comment]
You most definitely can :)

Can you copy paste the error you get when using both?

**Comment by coodin** [comment]
yes you are 100% right after I realize the gradlew kspDebugKotlin command doesn't work for me to build new or changed function names or any code changes  related to it so I had to rebuild the project and after that it worked. did I misuse command kspDebugKotlin? by the way what does it mean Debug between ksp and Kotlin for this command?

**Comment by raamcosta** [comment]
You can just run the app and it will generate the classes, no need for specific command. But Debug should be a combination of flavour and buildType. Sometimes it’s useful if you need to use a file that was not yet generated.

I’ll close then, let me know below if there is any other issue.

**Comment by coodin** [comment]
thank you very much by the way your library is amazing, I hope android team see your library and select it as default in next major release of navigation compose.

**Comment by raamcosta** [comment]
Never gonna happen ahah 😝 thanks !

**Comment by raamcosta** [comment]
This is not an issue, you need to pass the VM explicitly in some way.
Check here:
https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels

**Comment by HermanAleksey** [comment]
> This is not an issue, you need to pass the VM explicitly in some way. Check here: https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels

Thank you very much!
Now everything is in place. Link is super usefull and explain everything i needed.

**Comment by raamcosta** [comment]
Great! Glad it helped

**Comment by waheed006** [comment]
Sir @raamcosta, I follow the above link, the viewmodel is shared but data is not coming with viewmodel. Can you please help me in this.
