### ISSUE TITLE
Composable is reset when screen turn off and on

### ISSUE THREAD

**Issue by samuele794** [raamcosta/compose-destinations#118]
Hi, i want report a bug,
when you turn off and turn on the screen, Composable destination is resetted.

For test i take sample project of the library
and edited it with
```
@Destination
@Composable
fun AccountScreen(
//    vm: AccountViewModel = viewModel(),
) {

    var abc by remember {
        mutableStateOf("")
    }

    Column {
        TextField(value = abc, onValueChange = {
            abc = it
        }
        )

//        Button(onClick = { vm.onLogoutClick() }) {
//            Text("Logout")
//        }
    }

}
```

when i turn off and turn on the screen i think the navigation restart.

Library version used: `1.5.2-beta`

**Comment by raamcosta** [comment]
Hey. I can't quite understand what is the trigger for this, but I have reproduced it without Compose Destinations too. I'm thinking that it may be expected that it could happen. Both with and without Compose Destinations, it sometimes happens, other times it does not.

Anyway, hoist that state to ViewModel and/or use rememberSaveable instead of remember. That will fix it for you :)

Closing this as it is not an issue with this library, let me know how that went for you!

**Comment by raamcosta** [comment]
The only thing I've noticed (again, also with vanilla official compose navigation) is that the navBackStackEntry passes through ON_CREATE when this happens and it doesn't when it works as expected.

```
onStateChanged NavBackStackEntry@86ef65fd - ON_PAUSE
onStateChanged NavBackStackEntry@86ef65fd - ON_STOP <-- Screen turn off
onStateChanged NavBackStackEntry@86ef65fd - ON_CREATE <-- Screen turn on and text field state is lost
onStateChanged NavBackStackEntry@86ef65fd - ON_START
onStateChanged NavBackStackEntry@86ef65fd - ON_RESUME
```

```
onStateChanged NavBackStackEntry@5be23c59 - ON_PAUSE
onStateChanged NavBackStackEntry@5be23c59 - ON_STOP <-- Screen turn off
onStateChanged NavBackStackEntry@5be23c59 - ON_START <-- Screen turn on and text field state is kept
onStateChanged NavBackStackEntry@5be23c59 - ON_RESUME
```

**Comment by raamcosta** [comment]
I asked a question on Kotlin slack and Ian Lake from Google just told me to use `rememberSaveable` if we want the state to be saved. So I guess that's it then 🙂 

https://kotlinlang.slack.com/archives/CJLTWPH7S/p1651692124686329?thread_ts=1651691130.284029&cid=CJLTWPH7S
