### ISSUE TITLE
Codegen not working for single module extensions

### ISSUE THREAD

**Issue by Kashif-E** [raamcosta/compose-destinations#120]
Hi! I am trying to add a bottom bar navigation but single module extensions file not being generated thus unable to access extension functions such as .appCurrentDestinationAsState()

This is my build.gradle file

```
plugins {
    id("com.android.application")
    kotlin("android")
    id("com.google.devtools.ksp") version "1.6.10-1.0.2"
}
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    kotlinOptions.freeCompilerArgs += "-opt-in=kotlin.RequiresOptIn"
}
android {
    compileSdk = 31
    defaultConfig {
        applicationId = "com.markaz.app"
        minSdk = 21
        targetSdk = 31
        versionCode = 1
        versionName = "1.0"
    }
    ksp {


        arg("compose-destinations.codeGenPackageName", "com.markaz.app")
        arg("compose-destinations.generateNavGraphs", "true")

    }
    buildFeatures {
        compose = true
    }
    applicationVariants.all {
        kotlin.sourceSets {
            getByName(name) {
                kotlin.srcDir("build/generated/ksp/$name/kotlin")
            }
        }
    }

//    packagingOptions {
//        exclude("META-INF/AL2.0")
//        exclude("META-INF/LGPL2.1")
//        exclude("META-INF/**/*")
//        exclude("META-INF/common.kotlin_module")
//        exclude("META-INF/*.kotlin_module")
//    }
    composeOptions {
        kotlinCompilerExtensionVersion = Compose.compose_version
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
}

dependencies {
    implementation(project(":shared"))

    implementation(Androidx.lifecycleRuntime)
    implementation(Androidx.coreKTX) {
        because("Supports lifecycle ktx")
    }
    implementation(Compose.composeActivity) {
        because("We are not using  xml its better to use compose activity")
    }
    implementation(Compose.composeMaterial) {
        because("Supports material design components")
    }

    debugImplementation(Compose.composeTooling) {
        because("Supports previews and other tooling stuff")
    }
    implementation(Compose.commposeUI) {
        because("Supports compose")
    }
    implementation(ComposeDestination.core) {
        because("Compose navigation is not good enough")
    }
    ksp(ComposeDestination.composeDestinationPlugin) {
        because("Ksp plugin for compose destinations")
    }
    implementation(ComposeDestination.composeDestination) {
        because("supports compose destinations")
    }

}
```

Generated files:

<img width="283" alt="Screenshot 2022-05-07 at 6 54 21 PM" src="https://user-images.githubusercontent.com/61690178/167257379-26e50de0-eb81-4df9-9100-5f82fb59d78a.png">

**Comment by raamcosta** [comment]
Hey @Kashif-E!

Looking at the generated files, it looks like you have a configuration of "destinations" like:
`arg("compose-destinations.mode", "destinations")`

But I indeed don't see that in the gradle you pasted 🤔 
I don't see any other way this would happen, can you open `AppDestinations` file and see what's inside? Is it a list of destinations?
Also the name `AppDestinations` suggests you used in this module `arg("compose-destinations.moduleName", "app")`. Is it possible that you pasted a gradle script from a module and the image with the generated files from another module?

**Comment by raamcosta** [comment]
Also, keep in mind that `appCurrentDestinationAsState` as an equivalent method on the library itself which is `currentDestinationAsState` the only difference is that in the first it returns a `State<Destination?>` which is a sealed interface that is only possible in "singlemodule" (the default) mode.

**Comment by Kashif-E** [comment]
Sorry @raamcosta  I added the wrong image. I have updated the screenshot and it is a single module app

**Comment by raamcosta** [comment]
Ahh, now I see. You're using an old version where these functions are inside `CoreExtensions` rather than `SingleModuleExtensions`. Update the library to the new version 🙂 

I'll close but let me know if that worked for you below!
