### ISSUE TITLE
Question: "Hoisting" the DestinationsNavigator to the DestinationsNavHost?

### ISSUE THREAD

**Issue by curioustechizen** [raamcosta/compose-destinations#121]
Hi. Thanks for this library. It eliminates a ton of boilerplate while using compose navigation.

I'm looking for a way to avoid having to pass in the navigator parameter to each destination composable. My motivation is to keep all the `navigateTo` logic in one place. Do you have any pointers on how to do this? Or do you think this ends up fighting the system?

Some pseudocode on how I would achieve it with plain compose navigation:

```kt
@Composable
fun LoginScreen(onProfileClick: () -> Unit) {
    Button(onClick = onProfileClick) {
        Text("Profile")
    }
}

@Composable
fun ProfileScreen(onAboutClick: () -> Unit) {
    Button(onClick = onAboutClick) {
        Text("About")
    }
}

@Composable
fun AboutScreen(){
    Text("About screen")
}

@Composable
fun MyApp() {
    val navController = rememberNavController()
    NavHost(navController = navController, startDestination = "login") {
        composable("login") {
            LoginScreen(onProfileClick = { navController.navigate("profile" } )             
        }
        composable("profile") {
            ProfileScreen(onAboutClick = { navController.navigate("about" } )
        }
        composable("about") {
            AbouScreen()      
        }
    }    
}

```

Note that the MyApp composable is the only one that is aware of the navController and it is the only one that makes decisions on where to navigate next.

**Comment by raamcosta** [comment]
Hi @curioustechizen !

Not fighting the system at all. You can manually call your screens using the last parameter of DestinationsNavHost method.

Check how here:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters#manually-call-your-screen-composable

Keep in mind that in contrast to with official library, you are not building your nav graphs here (that info comes from the navGraph param), so you don’t need to call all composables this way. If for example some of them don’t need any navigation, then you might not call them here and the library will call you annotated Composable directly.

I’ll close this but please let me know below if the solution is good to you 🙂

**Comment by raamcosta** [comment]
Cool 👍

Did you manage to do it the way you wanted to? Calling the screens from NavHost and passing lambdas to navigate?

**Comment by curioustechizen** [comment]
I did achieve it with plain compose navigation. I'll experiment with it using compose-destinations and I'll report my findings here.
