### ISSUE TITLE
llegalDestinationsSetup upgrading to 1.5.* 

### ISSUE THREAD

**Issue by ThomasWilliamMarsh** [raamcosta/compose-destinations#124]
Hi there, me again! 

I am upgrading my project from 1.3.3 to 1.5.5, which no changes to my code, but keep getting  a ksp error

`[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: com.google.devtools.ksp.symbol.impl.kotlin.KSNameImpl@24ae2082: Type serializers must implement DestinationsNavTypeSerializer!`

Is there any way I can debug this further? I have no custom nav types, so it's confusing me

**Comment by ThomasWilliamMarsh** [comment]
Looks like co-worker did add one, sorry! haha

**Comment by raamcosta** [comment]
Yap, this was a breaking change we needed to do a few versions back. Let me know if I can help any further :)
