### ISSUE TITLE
Question: Access to navController from within a destination

### ISSUE THREAD

**Issue by curioustechizen** [raamcosta/compose-destinations#125]
This is regarding an alternative way to [share ViewModels](https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels#share-viewmodels-between-multiple-destinations) between multiple destinations. I want to achieve something like the following:

```kt
@Destination
@Composable
fun ChooseLoginMethodScreen() {
    val authViewModel = getNavGraphViewModel<AuthViewModel>(graph = NavGraphs.auth)
}
```

Here, `ChooseLoginMethodScreen` is part of the "auth" nested nav graph. All screens that are part of this graph share the `AuthViewModel`.

I'm using Koin for this but I think that is not really relevant. As described in your document and in [Google's docs about this topic](https://developer.android.com/jetpack/compose/libraries#hilt-navigation), the key is to obtain the parent `backStackEntry`. This requires a `navController` and a `route`.

We can trivially get the `route` from the `graph` argument above. But how do I get the `navController` here without explicitly passing it to the destination? I know the `DestinationScope` has access to the navController, so I attempted something like this but it doesn't seem to work.

```kt@Composable
inline fun <reified T : ViewModel> DestinationScope<*>.getNavGraphViewModel(
    graph: NavGraphSpec,
): T {
    val navGraphBackStackEntry = navController.getBackStackEntry(navGraphSpec.route)
    //Use this navGraphBackStackEntry to obtain the appropriate ViewModel and return it
}
```

However, it looks like the `destinationScope` is not available inside a composable annotated with `@Destination`. Any pointers?

**Comment by raamcosta** [comment]
There is even a comment right on the Readme saying that we recommend DestinationsNavigator for most cases but NavController can also be provided in the same way :)

**Comment by raamcosta** [comment]
That said, if you read the docs on providing same ViewModel to multiple destinations, you saw that I made use of “dependencyBuilder” parameter which also has access to the DestinationScope being navigated to and then you can check if it belongs to your NavGraph and if so add the dependency ViewModel

**Comment by curioustechizen** [comment]
> So you can just add the “navController: NavController” to the parameters of annotated Composable Screens and the library you pass the NavController slightly_smiling_face

Okay but then I lose the ability to pass an interface like `FooNavigator`. Or I can still pass it in but there is duplication.

> you saw that I made use of “dependencyBuilder” parameter which

I tried with the `dependencyBuilder` parameter and it works fine. I was originally trying to approach it in a way that the Screen requests its ViewModel. However it looks like passing in the `ViewModel` to the Screen is a better option.

Thanks for the help. I'm closing this issue.

**Comment by raamcosta** [comment]
How would you deal with this in official jetpack compose navigation? You can always manually call screens and so same approaches are also valid for compose destinations 🙂
