### ISSUE TITLE
Cannot switch NavGraphs route from inside a nested Destination

### ISSUE THREAD

**Issue by baiorett** [raamcosta/compose-destinations#126]
I need help with figuring out how to navigate to a Destination that is in the route above current one/different route.
The hierarchy looks somewhat like this
```
            root
              |
   |------------------|
   |                main
   |                  |
DialogDest        |-------|
                 Dest1  Dest2
```
I need to navigate to `DialogDest` from `Dest1`, is that possible?

**Comment by raamcosta** [comment]
Hey!

Of course :)
As long as your navcontroller knows both graphs (i.e, you passed in NavGraphs.root when calling DestinationsNavHost), then you should be able to just navigate normally, no additional setup needed.

**Comment by baiorett** [comment]
> Hey!
> 
> Of course :) As long as your navcontroller knows both graphs (i.e, you passed in NavGraphs.root when calling DestinationsNavHost), then you should be able to just navigate normally, no additional setup needed.

Oh…

**Comment by baiorett** [comment]
I got DestinstionNavHost in MainActivity which points to root and root’s start is on MainScreen which utilizes main and if i set it to root, it crashes

**Comment by raamcosta** [comment]
Ok, well first of all, why do you need multiple nav graphs? The simplest the better 😉

Is this an open source project?

**Comment by baiorett** [comment]
> Ok, well first of all, why do you need multiple nav graphs? The simplest the better 😉
> 
> Is this an open source project?

I didnt understand the concept of that thing and used one in MainActivity to display another one plus a dialog 
I thought its more logical like this because it has own AppBar and it has to cover entire screen

Not yet, but its planned to be open sourced soon

**Comment by raamcosta** [comment]
It’s hard to try to explain without looking at all your nav code.. 🙁

**Comment by baiorett** [comment]
> It’s hard to try to explain without looking at all your nav code.. 🙁

I think i can make it public for few minutes if thats fine

**Comment by raamcosta** [comment]
I would just tell you to try to simplify it as much as possible, have a single DestinationsNavHost call in MainActivity passing the root nav graph (make sure all other graphs are nested in root).

**Comment by baiorett** [comment]
> I would just tell you to try to simplify it as much as possible, have a single DestinationsNavHost call in MainActivity passing the root nav graph (make sure all other graphs are nested in root).

Im gonna try doing that tomorrow, thanks for replying and help! Can I reopen this later incase i get stuck again?

**Comment by raamcosta** [comment]
Sure, can’t promise I’ll always be this fast responding 😋

**Comment by baiorett** [comment]
> Sure, can’t promise I’ll always be this fast responding 😋

Alright, thank you again

**Comment by baiorett** [comment]
So I kind of fixed it but now it ends up being in `Scaffold` that was originally intended for `main` and i could not find a way to bring it on actual top of hierarchy

**Comment by raamcosta** [comment]
It's very hard to try to help you with this little info :( 
If you want, send me a link for the repository or some other way to get the source files.

**Comment by baiorett** [comment]
> It's very hard to try to help you with this little info :(
> If you want, send me a link for the repository or some other way to get the source files.

Sure, ill share a link to git repo in few hours

**Comment by baiorett** [comment]
So here is a [mirror of it](https://gitea.advertisement.life/ReVanced/revanced-manager/src/branch/wip) (code is a bit messy)
It's more of a workaround, not an actual solution on showing it on top

**Comment by raamcosta** [comment]
I'll leave some notes as I see them:

- Your MainScreen should not be really a "Screen" in the sense that it doesn't belong to your nav graph, it is just a component that holds all your other screens (via the DestinationsNavHost).
So: remove 
```
@Destination
@RootNavGraph(start = true)
```
and add that `@RootNavGraph(start = true)` to the actual initial screen of your app.

**Comment by baiorett** [comment]
Alright, done that

**Comment by raamcosta** [comment]
☝️ the reason is: whatever you annotate with @Destination and if it belongs to @RootNavGraph or a nested graph inside RootNavGraph, when you then call `DestinationsNavHost` passing in NavGraphs.root, you're adding that destination to the NavHost, but if you navigate to it, you have a new DestinationsNavHost, passing itself yet again :D 

Hope you get that.

**Comment by raamcosta** [comment]
> Alright, done that

And how is it working now?

**Comment by baiorett** [comment]
About the loop of `DestinationsNavHost`s understood
> And how is it working now?

It's about the same
Thing is that i don't wanna nest some screens into `DestinationsNavHost` which is in `Scaffold` but outside
but no condition will work due to it not updating every destination change

**Comment by raamcosta** [comment]
I don't understand.. do you want to update for example your Top bar and bottom bar for each screen you navigate to?

**Comment by baiorett** [comment]
> I don't understand.. do you want to update for example your Top bar and bottom bar for each screen you navigate to?

Kind of. I have that `AppSelectorScreen` which should be on top of everything but still be a destination

**Comment by raamcosta** [comment]
Your mistake is having so many Scaffolds. You need only one on your "MainScreen" (as you called it) and you need to update/hide/show your Top, bottom bar, etc whenever you navigate to a new screen.

You can use `navController.appCurrentDestinationAsState()` before calling your Scaffold to have a Destination that gets recomposed every time you navigate. Then you use that to update your scaffold elements as you prefer.

**Comment by raamcosta** [comment]
OR, alternatively, if you really want to have scaffolds on each screen, then remove Scaffold from MainScreen and have each other screen define its own Scaffold.

**Comment by raamcosta** [comment]
You can't have the cake and eat it to: you either have the same Scaffold on top of all screens and just update its pieces, OR you have each screen define its own Scaffold. I believe the first option is better, but you can try the second and let me know how it goes, I've actually never done it that way :D

**Comment by baiorett** [comment]
Ohhhhhh

**Comment by baiorett** [comment]
Yeah I did a `when` on the thing and now it successfully removes `Scaffold` if Im in `AppSelectorScreenDestination`

**Comment by baiorett** [comment]
Thank you so much for explaining this

**Comment by raamcosta** [comment]
Understand: when you call DestinationsNavHost, this will be whatever each screen is going to be replaced into. (you can picture it this way). So since you're calling it inside Scaffold, then all screens are shown inside that Scaffold.

**Comment by baiorett** [comment]
> OR, alternatively, if you really want to have scaffolds on each screen, then remove Scaffold from MainScreen and have each other screen define its own Scaffold.

I tried this way but it will animate all parts including the `Scaffold`'s top bar and nav bar

**Comment by baiorett** [comment]
> Understand: when you call DestinationsNavHost, this will be where each screen is going to be replaced into. (you can picture it this way). So since you're calling it inside Scaffold, then all screens are shown inside that Scaffold.

Basically a container yeah

**Comment by baiorett** [comment]
Thank you again, I guess this issue may now be closed

**Comment by raamcosta** [comment]
> > OR, alternatively, if you really want to have scaffolds on each screen, then remove Scaffold from MainScreen and have each other screen define its own Scaffold.
> 
> I tried this way but it will animate all parts including the `Scaffold`'s top bar and nav bar

Yeah, I thought so. Gotta go with the single and updating Scaffold 🙂
