### ISSUE TITLE
dependenciesContainerBuilder with ManualComposableCallsBuilder

### ISSUE THREAD

**Issue by margarita-v** [raamcosta/compose-destinations#128]
It seems to be impossible to use both dependenciesContainerBuilder and ManualComposableCallsBuilder, for example:
```
@Composable
private fun AppNavHost(
    navController: NavHostController,
    showMessage: (String, Boolean) -> Unit,
) {
    DestinationsNavHost(
        engine = rememberNavHostEngine(),
        navController = navController,
        navGraph = NavGraphs.root,
        dependenciesContainerBuilder = {
            val appDestinationsNavigator = destinationsNavigator
            val appNavGraph = navGraph()
            // provide interface for navigation for each composable same to tivi fork sample
            dependency(
                object : AppNavigation {
                    override val navGraph: NavGraphSpec = appNavGraph
                    override val destinationsNavigator: DestinationsNavigator =
                        appDestinationsNavigator
                }
            )
        }
    ) {
        // unable to pass AppNavigation to feedComposable
        feedComposable(showMessage = showMessage)
    }
}
```
It seems that for this composable which has custom params that can't be injected and must be provided manually inside of `DestinationsNavHost`, we can't actually use dependencies that are passed via `dependenciesContainerBuilder`.  Is it intended to be this way? 
As for `feedComposable` from example, I will have to pass `showMessage` via `dependenciesContainerBuilder` as well, and I can only define those composables inside of `DestinationsNavHost` which don't require dependencies from `dependenciesContainerBuilder`

**Comment by raamcosta** [comment]
Hi @margarita-v !

So, yes for some reason I have never thought about these two working together... I guess I've always figured that if you're manually calling your composables, you can just get whatever dependencies you need at that point 🤔 
This is very doable in the code, but I still don't know that it is useful. For generated code, I'm able to only call it when there is some parameter type that I don't know how to get. For runtime I'd have to call it every time.

And so I'm thinking that you can just provide the navigator in the manual call on `feedComposable` like you did for `dependenciesContainerBuilder`. You can even extract `object : AppNavigation { .......` to another function and call that function also when calling `feedComposable`.

Does this make sense?

**Comment by margarita-v** [comment]
For some cases it could work (to define required object from above and than pass it as dependency to `dependenciesContainerBuilder` and to manually called composables), but in my case on order to init `AppNavigation` I need `DestinationScope` which I can only recieve inside of `dependenciesContainerBuilder` so I can't init `navigation` value before:
```
var navigation: AppNavigation
    DestinationsNavHost(
        engine = rememberNavHostEngine(),
        navController = navController,
        navGraph = NavGraphs.root,
        dependenciesContainerBuilder = {
            val appDestinationsNavigator = destinationsNavigator // can call here for `this`
            val appNavGraph = navGraph() // can call here for `this`
            navigation = object : AppNavigation {
                override val navGraph: NavGraphSpec = appNavGraph
                override val destinationsNavigator: DestinationsNavigator =
                    appDestinationsNavigator
            }
            dependency(navigation)
        }
    ) {
// error: variable navigation must be initialized. If I make navigation as lateinit from above, I receive runtime error for uninitilized property
        feedComposable(showMessage = showMessage, navigation = navigation) 
    }
```
Seems to be a slight restriction for my case, so when I need `navigation` inside of `feedComposable`, I can't call manually `feedComposable` anymore and I must provide all its dependencies the same way

**Comment by raamcosta** [comment]
(you probably don't care about the type of nav arguments here, so you can just use `DestinationScope<*>` instead. Also, ignore my AccountScreen stuff 😄 )

**Comment by margarita-v** [comment]
The instance of `AppNavigation` will be different for manually-called composable, though I don't see a problem here for now :) (probably depends on `makeNavigator` implementation, singletone could be applied if needed) Thanks a lot, the main problem is solved!

**Comment by raamcosta** [comment]
Not even. dependencyContainerBuilder is also called every time. So you’ll always have a new instance created for each screen that needs it.
So it’s the same situation we have for manual calling screens 🙂
