### ISSUE TITLE
Unresolved reference @NavGraph

### ISSUE THREAD

**Issue by varundroid** [raamcosta/compose-destinations#129]
Hi,

I am fairly new to Compose. Recently started opting it in one of my projects. I was going through the following docs to define custom NavGraph - 

https://composedestinations.rafaelcosta.xyz/defining-navgraphs#manually-defining-navigation-graphs

I am just not able to locate `@NavGraph` in any of Compose navigation lib. Any help would be greatly appreciated here.

**Comment by raamcosta** [comment]
Hey!

What version of the library are you using? 😁

**Comment by varundroid** [comment]
Hi @raamcosta , I was using 1.1.2 🤦 
Just upgraded to 1.5.5 and it all okay now.

Thank you so much !! I love this lib, makes navigation so much easier.

**Comment by raamcosta** [comment]
No problem 😉

And thanks for the nice feedback, glad you like it! Consider starring (if you haven’t yet) and telling your friends 😃 (ok I really summoned the salesman in me ahah)

Closing it! 🙂
