### ISSUE TITLE
Question: What's a proper way to set start destination

### ISSUE THREAD

**Issue by entrealist** [raamcosta/compose-destinations#131]
I've just installed the library and am faced with the following issue.

1) I've assigned `@Destination` annotation to the composable function

2) Added `DestinationsNavHost` to my main screen
```
DestinationsNavHost(
       navGraph = NavGraphs.root
)
```

3) Build the project and faced with the following error
```
[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Use argument `start = true` in the @Destination annotation of the 'root' nav graph's start destination!
```

4) Okay, I've added `start = true` to my destination and have got the following error
```
[ksp] Composable Greeting: Usage of `start` and `navGraph` parameters of @Destination is deprecated.
```
I've also tried to set `startRoute` parameter for `DestinationsNavHost`. It doesn't work out either.

So I'm confused a little bit. What is the proper way to set the default start destination for the "root" graph?

Thank you!

**Comment by raamcosta** [comment]
Hey 👋!

I should definitely update that first error message, sorry for this and thank you for bringing this to my attention 🙂

Anyway, the second one is just a warning, correct? 

Regardless, the new way to do this is to annotate the start destination with `@RootNavGraph(start = true)`. You can see the readme, website docs or sample apps for example.

Since now we have nav graph annotations, and “start” is something that is related to nav graph.

**Comment by raamcosta** [comment]
Let me know if this helps 🙂

**Comment by entrealist** [comment]
> Anyway, the second one is just a warning, correct?
No, it's a compiler error.

> Regardless, the new way to do this is to annotate the start destination with @RootNavGraph(start = true). You can see the readme, website docs, or sample apps for example.

Thank you!

**Comment by raamcosta** [comment]
Interesting, is it possible that you have allWarningsAsErrors turned on in the gradle scripts?

**Comment by raamcosta** [comment]
Btw startRoute is a chance for you to override at runtime your usual start destination. Just in case you were wondering 😁

I’ll close, but let me know if I can help any further.
