### ISSUE TITLE
Accompanist `0.24.x` makes breaking animation API change. 

### ISSUE THREAD

**Issue by kevincianfarini** [raamcosta/compose-destinations#132]
I'm trying to upgrade to project to Kotlin 1.6.21. This necessitates that we bump compose to 1.2.0-beta01, and accompanist to 0.24.x. Accompanist makes the backwards incompatible change to remove `NavGraphBuilder.navigate`. Bumping both of those dependencies in my codebase causes the following runtime error, presumably because `compose-destinations` still depends on accompanist `0.23.x`. 

```
    java.lang.NoSuchMethodError: No static method navigation(Landroidx/navigation/NavGraphBuilder;Ljava/lang/String;Ljava/lang/String;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function1;)V in class Lcom/google/accompanist/navigation/animation/NavGraphBuilderKt; or its super classes (declaration of 'com.google.accompanist.navigation.animation.NavGraphBuilderKt' appears in /data/app/energy.octopus.octopusenergy.android.dev-p-WC31HpQkXr2Tkqenj6zg==/base.apk!classes20.dex)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.navigation(AnimatedNavHostEngine.kt:102)
        at com.ramcosta.composedestinations.DestinationsNavHostKt.addNestedNavGraphs(DestinationsNavHost.kt:124)
        at com.ramcosta.composedestinations.DestinationsNavHostKt.addNavGraphDestinations(DestinationsNavHost.kt:106)
        at com.ramcosta.composedestinations.DestinationsNavHostKt.access$addNavGraphDestinations(DestinationsNavHost.kt:1)
        at com.ramcosta.composedestinations.DestinationsNavHostKt$DestinationsNavHost$2.invoke(DestinationsNavHost.kt:74)
        at com.ramcosta.composedestinations.DestinationsNavHostKt$DestinationsNavHost$2.invoke(DestinationsNavHost.kt:68)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:252)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.NavHost(AnimatedNavHostEngine.kt:83)
        at com.ramcosta.composedestinations.DestinationsNavHostKt.DestinationsNavHost(DestinationsNavHost.kt:68)
```

**Comment by kevincianfarini** [comment]
Depending on it directly!

**Comment by raamcosta** [comment]
What if you remove that dependency? Because we as compose destinations are exposing their library via transitive dependency. 
Could you try that? See if it works?

**Comment by kevincianfarini** [comment]
I can try, but I don't believe that's possible. Accompanist `0.24.x` expects to interop with compose `1.2.x`. The transitive dependency introduced by this library would be accompanist version `0.23.x`.

**Comment by raamcosta** [comment]
But my whole library is built for compose 1.1.1 at this point. So accompanist would interop with the correct compose version.

If this is not the case, it will always be a nightmare for all Compose libraries 😅
But I guess if that is indeed the case, I need to know about it ahah

**Comment by kevincianfarini** [comment]
Yeah that makes sense. A lot of libraries (like Accompanist) provide a compatibility matrix of dependencies for compose. I just wanted to alert you and let you know that this is an upcoming breaking change in accompanist you might want to start investigating 😄

**Comment by kevincianfarini** [comment]
Our entire upgrade is unfortunately necessitated by the upgrade to Kotlin 1.6.21. I really wish Kotlin had a stable compiler plugin API so this nightmare didn't exist!

**Comment by raamcosta** [comment]
Definitely! Thank you for the heads up! 🙏

And do let me know if you can make it work by removing the explicit accompanist dependency. I’m curious if it would work 😋

**Comment by mateuszteteruk** [comment]
Hey @raamcosta! 

I'd like to ask about your plans about updates to `Compose 1.2.x` and `Accompanist 0.24.x`? Are you waiting for stable version of Compose 1.2?

I came across one bug which relates to `AnimatedNavHost` from `Accompanist` which is fixed in here https://github.com/google/accompanist/pull/1025 and it's in `v0.24.x` 😅

**Comment by raamcosta** [comment]
Multiple plans and haven’t had time to even think about which to choose Ahah 😅

Ideally I would start releasing both stable and beta versions using corresponding versions of compose/accompanist.
But yeah if compose 1.2 stable were to come soon, I could delay having to do that a bit more 😋

That said, since I have multiple people interested in this, maybe I just do that release now 🙂

**Comment by raamcosta** [comment]
Done, we now have two versions:

<table>
 <tr>
  <td>Compose 1.1 (1.1.x)</td><td><img alt="Maven Central" src="https://img.shields.io/maven-metadata/v?versionPrefix=1.5&color=blue&metadataUrl=https://s01.oss.sonatype.org/service/local/repo_groups/public/content/io/github/raamcosta/compose-destinations/core/maven-metadata.xml&style=for-the-badge)](https://maven-badges.herokuapp.com/maven-central/io.github.raamcosta.compose-destinations/core)"></td>
 </tr>
 <tr>
  <td>Compose 1.2 (1.2.x)</td><td><img alt="Maven Central" src="https://img.shields.io/maven-metadata/v?versionPrefix=1.6&color=blue&metadataUrl=https://s01.oss.sonatype.org/service/local/repo_groups/public/content/io/github/raamcosta/compose-destinations/core/maven-metadata.xml&style=for-the-badge)](https://maven-badges.herokuapp.com/maven-central/io.github.raamcosta.compose-destinations/core)"></td>
 </tr>
</table>

I'll now close this, but let me know below how things go for you! 🙂

**Comment by raamcosta** [comment]
Hey 👋

it has to be related to the gradle configuration I believe.
Can you show me how you have that source sets thing?

**Comment by raamcosta** [comment]
Is it inside android block? 🤔

Anyway, glad it works now!

**Comment by raamcosta** [comment]
It’s weird I’ve used this setup in multiple projects now and you’re also the first to complain about it.
Maybe something related to your specific setup 🤔

**Comment by andre-artus** [comment]
> It’s weird I’ve used this setup in multiple projects now and you’re also the first to complain about it. Maybe something related to your specific setup 🤔

I'm using Groovy for Gradle and many different flavors and dimensions.

**Comment by andre-artus** [comment]
> > It’s weird I’ve used this setup in multiple projects now and you’re also the first to complain about it. Maybe something related to your specific setup 🤔
> 
> I'm using Groovy for Gradle and many different flavors and dimensions.

It worked when I only had debug and release and no other build types, flavors or dimensions.
