### ISSUE TITLE
New parameter for destination.

### ISSUE THREAD

**Issue by kruid9403** [raamcosta/compose-destinations#135]
I added a new parameter to a destination composable and rebuilt the project but the generated destination object does not recognize it.

**Comment by kruid9403** [comment]
Nevermind, I am an idiot and didn't serialize the object.

**Comment by raamcosta** [comment]
Ok cool 🙂
Yeah for it to be considered a nav arg, it need to have specific types or be annotated with its Serializable

**Comment by raamcosta** [comment]
Closed I guess!
