### ISSUE TITLE
Gen files package name issue when using `in` keyword

### ISSUE THREAD

**Issue by arshdoda** [raamcosta/compose-destinations#137]
I am using a pakage with in.co.... On compiling the project, it shows error Package name must be a '.'-separated identifier list. This is may be due to "in" keyword in the package name. Any solution to this?

**Comment by raamcosta** [comment]
Hey! 
you can set specific package name on build gradle config:

https://composedestinations.rafaelcosta.xyz/codegenconfigs#generated-files-package-name

Let me know if that works 🙂

**Comment by arshdoda** [comment]
Hi,

Its not working. My pakage in file : package `in`.co.geodit.presentation.register. But when compose destinations create the files it takes package as in.co.geodit.presentation.register.

Its not adding backtick ` to the in keyword

**Comment by raamcosta** [comment]
I can add this workaround but until then, if you set a package name as a config like the link I sent above without the in keyword, it should work.

**Comment by arshdoda** [comment]
I used this config
ksp {arg("compose-destinations.codeGenPackageName", "co.geodit")}

The previous error is gone. But it shows new error while creating Destination files. 
Error: Expecting qualified name
Line: import in.co.geodit.presentation.project.ProjectScreen

**Comment by raamcosta** [comment]
Hmmm can you paste a screenshot of the error? I need to see some details

**Comment by arshdoda** [comment]
Error without any configuration:
![default](https://user-images.githubusercontent.com/11732646/169637008-5554725f-58fa-420b-9c31-1fee3f7635ac.png)

Configuration:
![adding_config](https://user-images.githubusercontent.com/11732646/169637045-afcfa239-713e-45be-89eb-a8e8bc1e6775.png)

Error:
![error](https://user-images.githubusercontent.com/11732646/169637058-8c530c01-5d63-4aee-8c43-b7324f941ba2.png)

**Comment by raamcosta** [comment]
Of course! 🤦 
Now I get it :) 

Thank you for reporting. I will look into this later today, expect a release soon with the fix 🙏

**Comment by arshdoda** [comment]
Thanks. Will wait for the update

**Comment by raamcosta** [comment]
Push fixed, I'll make release later today

**Comment by raamcosta** [comment]
@arshdoda could you please test this with 1.5.6-beta release? 🙂 
Let me know if it works for you!

**Comment by arshdoda** [comment]
@raamcosta It's working like a charm.
Thanks a lot for this awesome library
