### ISSUE TITLE
empty IntArray cause java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest ... cannot be found in the navigation graph

### ISSUE THREAD

**Issue by amirzeinaly** [raamcosta/compose-destinations#138]
Hi 
my sample code is here

```
@Composable
@Destination
fun TestScreen(
    items: IntArray,
    ...
    viewModel: TestScreenViewModel = getViewModel()
) {
}
```

if we send empty IntArray as param 
we get IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest ... cannot be found in the navigation graph

**Comment by raamcosta** [comment]
Hey @amirzeinaly !

thank you so much for reporting this 🙏
It does seem like a bug with arrays arguments. I’ll take a look probably still today and hopefully send a release with the fix.

**Comment by raamcosta** [comment]
@amirzeinaly I'd love it if you could test this with 1.5.6-beta! 🙂

**Comment by amirzeinaly** [comment]
Thanks for fixing the bug.
It works right now
