### ISSUE TITLE
Trying to add multiple bottom navigation bars to app

### ISSUE THREAD

**Issue by Hassankhd** [raamcosta/compose-destinations#141]
Hello @raamcosta! 

Before I post a question, I want to thank you for this amazing library, it has helped me loads with developing my app!

I'm very new to Android Development, and I'm using Jetpack Compose since I'm very proficient with SwiftUI. I'm trying to define 2 bottom navigation bars for my app but I'm finding it difficult to do so. There are 2 different types of users within my app (employers and job seekers) and they have a completely different way of using the app.

I'm successfully able to define one bottom nav bar in the MainActivity class like this: 

```
setContent {
            JOBSEEQRTheme {
                val navController = rememberNavController()


                Scaffold(
                    modifier = Modifier.fillMaxSize(),
                    bottomBar = {
                        BottomBarJS(navController = navController)
                    }
                ) {

                }

                DestinationsNavHost(
                    navGraph = NavGraphs.root,
                    navController = navController
                )
            }
        }
```

And everything works perfectly. I just don't know where or how I'll have to add the second bottom nav bar. I've experimented with many methods, the closest I got was including the Scaffold in one of the composables that are inside the second bottom nav bar, but the app crashed every time I clicked on it. I would really appreciate help with this, thanks in advance!

**Comment by raamcosta** [comment]
Hi!

From what I gathered, maybe just an if expression?

if (isJSUser) JSBottomBar else EmployersBottomBar

This inside the bottomBar = of Scaffold.
Sorry for the lack of formatting, I’m on the smartphone 😁

**Comment by Hassankhd** [comment]
Hello again!

I just tried your suggested solution by defining isJSUser as a property, but it seems like I cannot implement it inside the MainActivity class. I'm utilizing Firebase, and in this case, I have a loading screen that checks whether a user is logged in or not:

1) If the user is logged in, a quick lookup into Firebase Realtime Database is done to determine if the user is a job seeker or an employer:

       a) If the user is a job seeker, the app takes them to the job seeker home page

       b) If the user is an employer, the app would redirect them to the employer home page

2) if the user is NOT logged in, they will be taken to a screen where they're asked if they'd like to access the app as an employer or job seeker

```
@RootNavGraph(start = true)
@Destination
@Composable
fun EntryPage(
    navigator: DestinationsNavigator
) {
    LaunchedEffect(Unit) {
        var auth = Firebase.auth
        val currentUser = auth.currentUser

// if the user is logged in
        if(currentUser != null) {
            // check in database if user is a job seeker
            navigator.navigate(
               HomeJSDestination()
            )
           // check in database if user is an employer
            navigator.navigate(
               HomeEmplDestination()
            )
        } 

// if the user is not logged in
else {
            navigator.navigate(
                ChoosePageDestination()
            )
        }
    }
...
}
```

Here's my MainActivity class for reference (including your suggested solution):

```
class MainActivity : ComponentActivity() {
    @ExperimentalMaterialApi
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            JOBSEEQRTheme {
                val navController = rememberNavController()

                Scaffold(
                    modifier = Modifier.fillMaxSize(),
                    bottomBar = {
                        if (isJSUser) {
                            BottomBarJS(navController = navController)
                        } else {
                            BottomBarEmpl(navController = navController)
                        }
                    }
                ) {

                }

                DestinationsNavHost(
                    navGraph = NavGraphs.root,
                    navController = navController
                )
            }
        }
    }
}
```

How would your solution change given what I just mentioned and given that I'm defining the Scaffold inside the MainActivity class, or is there something I'm missing? (if so, I really apologize, I'm still new to this)

**Comment by raamcosta** [comment]
Now I see 🙂

Ok. What you need is a way to know in the MainActivity what type of user is logged in. I’m a reactive way like a StateFlow.
Then you can collectAsState on that flow and check at the BottomBar lambda which user type is logged in and show the corresponding bottom bar.

Another possible way is to check via navigation. For example if the current destination belongs to a nav graph that is meant for employers. Or if the main employers screen is in the back stack.

I’d have to know much more of your app logic to know for sure which is the best way, but you can’t go wrong with the first option. You just need to maybe have a common view model with that state (you can check the sample app on this repository how I do that for login state in the MainActivity)

**Comment by raamcosta** [comment]
I'll close this, but let me know below how that is going :)

**Comment by Hassankhd** [comment]
Hello @raamcosta! I still couldn't manage to get it to work. I'm trying to do your solution in the sample (but with some changes), but the app keeps crashing (I'm getting a "No dependency container provided!" message in Firebase's Crashlytics, from LocalDependencyContainer.

Instead of having two bottom bars, I tried going for one, in which I check via view model if the current user is a job seeker or an employer:

`@Composable
fun BottomBar(
    navController: NavController,
    vm: StartFcnsViewModel
) {
    val currentDestination: co.jobseeqr.JOBSEEQR.destinations.Destination? =
        navController.currentBackStackEntryAsState()
            .value?.appDestination()

    val isJobSeeker by vm.isJobSeekerFlow.collectAsState()

    if(isJobSeeker) {
        // job seeker bar
        BottomNavigation {
            BottomBarDestinationJS.values().forEach { destination ->
                BottomNavigationItem(
                    selected = currentDestination == destination.direction,
                    onClick = {
                        navController.navigate(destination.direction, fun NavOptionsBuilder.() {
                            launchSingleTop = true
                        })
                    },
                    icon = { Icon(destination.icon, contentDescription = destination.lbl) },
                    label = { Text(destination.lbl) },
                )
            }
        }
    } else {
        // employer bar
        BottomNavigation {
            BottomBarDestinationEmpl.values().forEach { destination ->
                BottomNavigationItem(
                    selected = currentDestination == destination.direction,
                    onClick = {
                        navController.navigate(destination.direction, fun NavOptionsBuilder.() {
                            launchSingleTop = true
                        })
                    },
                    icon = { Icon(destination.icon, contentDescription = destination.lbl)},
                    label = { Text(destination.lbl) },
                )
            }
        }
    }
}`

Also, here's the repo:

`
class StartFunctionsRepo {

    private val _isJobSeeker = MutableStateFlow(true)
    val isJobSeeker = _isJobSeeker.asStateFlow()

fun checkUserTypeOnLogIn() = callbackFlow {
        val auth = Firebase.auth
        val currentUser = auth.currentUser
        val jobSeekerDBRef = Firebase.database.getReference("people/$currentUser")
        if(currentUser != null) {
            val snapshotListener = object : ValueEventListener {
                override fun onDataChange(snapshot: DataSnapshot) {
                    _isJobSeeker.update { snapshot.exists() }
                    trySend(_isJobSeeker)
                }

                override fun onCancelled(error: DatabaseError) {
                    Log.e(ContentValues.TAG, "Failed to read job seeker data", error.toException())
                }
            }
            jobSeekerDBRef.addListenerForSingleValueEvent(snapshotListener)
            awaitClose() {
                jobSeekerDBRef.removeEventListener(snapshotListener)
            }
        } else {
            print("no user logged in yet")
        }
    }

    fun setToJobSeeker() = callbackFlow {
        _isJobSeeker.update { true }
        trySend(_isJobSeeker)
    }

    fun setToEmployer() = callbackFlow {
        _isJobSeeker.update { false }
        trySend(_isJobSeeker)
    }
}
`

Finally, my mainactivity file code:
`class MainActivity : ComponentActivity() {
    @ExperimentalMaterialApi
    override fun onCreate(savedInstanceState: Bundle?) {
        FirebaseApp.initializeApp(this)
        super.onCreate(savedInstanceState)
        setContent {
            JOBSEEQRTheme {
                JOBSEEQRApp()
            }
        }
    }
}

@OptIn(ExperimentalAnimationApi::class,
    com.google.accompanist.navigation.material.ExperimentalMaterialNavigationApi::class
)
@Composable
fun JOBSEEQRApp() {
    // val engine = rememberAnimatedNavHostEngine()
    val engine = rememberAnimatedNavHostEngine()
    val navController = engine.rememberNavController()

    val vm: StartFcnsViewModel = activityViewModel<StartFcnsViewModel>()

    val startRoute = EntryPageDestination()

    Scaffold(
        modifier = Modifier.fillMaxSize(),
        bottomBar = {
            BottomBar(navController = navController, vm = vm)
        }
    ) {
        DestinationsNavHost(
            engine = engine,
            navGraph = NavGraphs.root,
            navController = navController,
            startRoute = startRoute
        )
    }
}

// BottomBarEmpl(navController = navController)
@RootNavGraph(start = true)
@Destination
@Composable
fun EntryPage(
    vm: StartFcnsViewModel = activityViewModel(),
    navigator: DestinationsNavigator
) {
    LaunchedEffect(Unit) {
        val auth = Firebase.auth
        val currentUser = auth.currentUser
        if (currentUser == null)
            navigator.navigate(
                ChoosePageDestination()
            )
        else {
            vm.checkUserTypeOnLogIn()
            if (vm.isJobSeeker){
                navigator.navigate(
                    HomeJSDestination()
                )
            } else {
                navigator.navigate(
                    HomeEmplDestination()
                )
            }
        }
    }
    Surface(
        color = Color.Black
    ) {
        Column(
            modifier = Modifier
                .fillMaxHeight()
                .fillMaxWidth(),
            verticalArrangement = Arrangement.Center,
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Image(
                painterResource(R.drawable.webp_net_resizeimage),
                contentDescription = "",
                modifier = Modifier
                    .height(120.dp)
                    .width(120.dp)
            )
        }
    }
}

@Destination
@Composable
fun ChoosePage(
    vm: StartFcnsViewModel = activityViewModel(),
    navigator: DestinationsNavigator
) {
    Surface(
        color = Color.Black
    ) {
        Image(painterResource(R.drawable.introimg),
            contentDescription = "",
            modifier = Modifier
                .fillMaxHeight()
                .fillMaxWidth(), contentScale = ContentScale.FillHeight)
        Surface(
            color = Color.Black.copy(alpha = 0.45f),
            modifier = Modifier
                .fillMaxHeight()
                .fillMaxWidth()
        ) {
            Column(
                modifier = Modifier
                    .fillMaxHeight()
                    .fillMaxWidth()
                    .padding(vertical = 65.dp),
                verticalArrangement = Arrangement.Top,
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Image(
                    painterResource(R.drawable.webp_net_resizeimage),
                    contentDescription = "",
                    modifier = Modifier
                        .height(120.dp)
                        .width(120.dp)
                )
                Text(
                    text = "Welcome to\nJOBSEEQR", fontSize = 34.sp, fontWeight = FontWeight.Bold,
                    color = Color.White, textAlign = TextAlign.Center, modifier = Modifier
                        .padding(vertical = 20.dp)
                        .wrapContentHeight()
                )

            }
            Column(
                modifier = Modifier
                    .fillMaxHeight()
                    .fillMaxWidth()
                    .padding(vertical = 115.dp),
                verticalArrangement = Arrangement.Bottom,
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(
                    text = "Access JOBSEEQR as", fontSize = 30.sp, fontWeight = FontWeight.Bold,
                    color = Color.White, textAlign = TextAlign.Center, modifier = Modifier
                        .padding(vertical = 15.dp)
                        .wrapContentHeight()
                )
                Button(
                    onClick = {
                        vm.setToJobSeeker()
                        navigator.navigate(
                            SignUpJSDestination()
                        )
                              },
                    colors = ButtonDefaults.buttonColors(
                        backgroundColor = Color.White,
                        contentColor = Color.Black
                    ),
                    modifier = Modifier
                        .padding(vertical = 15.dp)
                        .height(50.dp)
                        .width(200.dp)
                ) {
                    Text(
                        text = "a Job Seeker",
                        fontSize = 20.sp,
                        fontWeight = FontWeight.Bold,
                        color = Color.Black
                    )
                }
                Button(
                    onClick = {
                        vm.setToEmployer()
                        navigator.navigate(
                            SignUpEmplDestination()
                        )
                              },
                    colors = ButtonDefaults.buttonColors(
                        backgroundColor = Color.White,
                        contentColor = Color.Black
                    ), modifier = Modifier
                        .padding(vertical = 15.dp)
                        .height(50.dp)
                        .width(200.dp)
                ) {
                    Text(
                        text = "an Employer",
                        fontSize = 20.sp,
                        fontWeight = FontWeight.Bold,
                        color = Color.Black
                    )
                }

            }
        }
    }
}

@Composable
inline fun <reified VM : ViewModel> activityViewModel(): VM {
    val activity = LocalDependencyContainer.current.activity

    return androidx.lifecycle.viewmodel.compose.viewModel(
        VM::class.java,
        activity,
        null,
        factory = ViewModelFactory(
            owner = activity,
            defaultArgs = null,
            dependencyContainer = LocalDependencyContainer.current,
        )
    )
}

class ViewModelFactory(
    owner: SavedStateRegistryOwner,
    defaultArgs: Bundle?,
    private val dependencyContainer: DependencyContainer
) : AbstractSavedStateViewModelFactory(
    owner,
    defaultArgs
) {

    override fun <T : ViewModel> create(
        key: String,
        modelClass: Class<T>,
        handle: SavedStateHandle
    ): T {
        return dependencyContainer.createViewModel(modelClass, handle)
    }
}

class DependencyContainer(
    val activity: MainActivity
) {

    val startFcnsRepo: StartFunctionsRepo by lazy { StartFunctionsRepo() }

    @Suppress("UNCHECKED_CAST")
    fun <T> createViewModel(modelClass: Class<T>, handle: SavedStateHandle): T {
        return when (modelClass) {
            StartFcnsViewModel::class.java -> StartFcnsViewModel(startFcnsRepo)
            else -> throw RuntimeException("Unknown view model $modelClass")
        } as T
    }
}

val LocalDependencyContainer = staticCompositionLocalOf<DependencyContainer> {
    error("No dependency container provided!")
}`

I sincerely apologize for the many lines of code, I just need help getting this to work. I'm pretty sure I'm missing a thing or two, as there's no doubt in my mind that your solution is indeed the proper approach.

**Comment by Hassankhd** [comment]
Hello @raamcosta! 

I still couldn't manage to get it to work. I'm trying to do your solution in the sample (but with some changes), but the app keeps crashing (I'm getting a "No dependency container provided!" message in Firebase's Crashlytics, from LocalDependencyContainer).

Instead of having two bottom bars, I tried going for one, in which I check via view model if the current user is a job seeker or an employer:

`
@Composable
fun BottomBar(
    navController: NavController,
    vm: StartFcnsViewModel
) {
    val currentDestination: co.jobseeqr.JOBSEEQR.destinations.Destination? =
        navController.currentBackStackEntryAsState()
            .value?.appDestination()

    val isJobSeeker by vm.isJobSeekerFlow.collectAsState()

    if(isJobSeeker) {
        // job seeker bar
        BottomNavigation {
            BottomBarDestinationJS.values().forEach { destination ->
                BottomNavigationItem(
                    selected = currentDestination == destination.direction,
                    onClick = {
                        navController.navigate(destination.direction, fun NavOptionsBuilder.() {
                            launchSingleTop = true
                        })
                    },
                    icon = { Icon(destination.icon, contentDescription = destination.lbl) },
                    label = { Text(destination.lbl) },
                )
            }
        }
    } else {
        // employer bar
        BottomNavigation {
            BottomBarDestinationEmpl.values().forEach { destination ->
                BottomNavigationItem(
                    selected = currentDestination == destination.direction,
                    onClick = {
                        navController.navigate(destination.direction, fun NavOptionsBuilder.() {
                            launchSingleTop = true
                        })
                    },
                    icon = { Icon(destination.icon, contentDescription = destination.lbl)},
                    label = { Text(destination.lbl) },
                )
            }
        }
    }
}
`
I cannot test if this solution would work or not because the app keeps crashing on launch.

For reference, I will attach my MainActivity.kt and StartFunctionsRepo.kt files. Let me know if any other files would be of any assistance to you.
[Archive.zip](https://github.com/raamcosta/compose-destinations/files/8799920/Archive.zip)

**Comment by Hassankhd** [comment]
This is the StartFcnsViewModel I created as well: (ignore the sign up functions)

`class StartFcnsViewModel(val startFunctionsRepo: StartFunctionsRepo): ViewModel() {

    fun checkUserTypeOnLogIn() = startFunctionsRepo.checkUserTypeOnLogIn()

    fun signUpJobSeeker(firstName: String, lastName: String,
                            email: String, password: String,
                            desiredJob: String) = startFunctionsRepo.signUpJobSeeker(firstName, lastName, email, password, desiredJob)

    fun signUpEmployer(companyName: String,
                       city: String, email: String,
                       password: String, description: String,
                       basedIn: String) = startFunctionsRepo.signUpEmployer(companyName, city, email, password, description, basedIn)

    fun setToEmployer() = startFunctionsRepo.setToEmployer()

    fun setToJobSeeker() = startFunctionsRepo.setToJobSeeker()

    val isJobSeekerFlow = startFunctionsRepo.isJobSeeker

    val isJobSeeker get() = isJobSeekerFlow.value
}`

**Comment by raamcosta** [comment]
Hey!

From this message "No dependency container provided!", it seems like you copied my dependency container logic from my sample apps. This is for manual dependency injection.. are you not using some DI framework like Hilt?
If yes, then you don't need `LocalDependencyContainer` at all. If you're not, this error means you're not providing any `DependencyContainer`.

On my samples I do:

```kotlin
class MainActivity : ComponentActivity() {

    private val dependencyContainer = DependencyContainer()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContent {
            CompositionLocalProvider(LocalDependencyContainer provides dependencyContainer) {
                PlaygroundApp(
                    testProfileDeepLink = {
                        displayNotification(
                            title = "Test deep link",
                            text = "Profile screen deep link",
                            notificationID = 100,
                            channel = "DEFAULT",
                            pendingIntent = getPendingIntent()
                        )
                    }
                )
            }
        }
    }
```

**Comment by Hassankhd** [comment]
Oh I see, I must've missed that, my bad! I'll give it a try and let you know. Also, looking at the rest of my code, should my solution for two different cases of bottom bars work? Of course, I'll get back to you if I face any different problems at all, but I thought I'd run the question by you before proceeding

**Comment by Hassankhd** [comment]
Quick update: The app works now, thanks for your quick response! However, sadly the solution I tried did not work. Apparently, BottomBar isn't getting the new isJobSeeker value when I come to access the app as an employer (if you recall, I set that value to false when I click on the "an Employer" button in the ChoosePage composable via the shared viewModel), and it keeps the bottom nav bar as that of job seekers instead of changing it to that of employers. I don't know what's wrong now, but I would sincerely appreciate some help with solving this once and for all.

**Comment by raamcosta** [comment]
The best way is to debug it. 
For example: add a log right after this line `val isJobSeeker by vm.isJobSeekerFlow.collectAsState()` does it get called when you change the state on the VM?

Also, log the instance of the vm on both places: where you are calling the method that changes the `isJobSeekerFlow` and where you are observing it. Does it have the same hash after the "@"? If not you have multiple ViewModels, so you're probably not creating/accessing it in the right way.

I don't have time to delve in your source code sorry, but this is where I would start. Because it most definitely should work :)
