### ISSUE TITLE
Bottombar usage on not-root screen

### ISSUE THREAD

**Issue by eksizadam** [raamcosta/compose-destinations#143]
Hello @raamcosta, first of all thank you for such an amazing library! I really like your approach 😄 

I have a use case that I couldn't find in your samples: 

Splash Screen (root): Checks user is authenticated or not, if yes:
I navigate to main screen which has bottom bar. 

We need to create `DestinationsNavHost` inside of scaffold. But I created `DestinationsNavHost` inside of entry Activity class like this, 

```
  override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyTheme { 
                DestinationsNavHost(navGraph = NavGraphs.root)
            }
        }
 }
```

Actually generic question should be like this : How can we use bottom bar if it doesn't hold root screen

**Comment by raamcosta** [comment]
Hi @eksizadam !

The guidelines from Google is that splash screen is not a destination of the navigation library. Check here:
https://developer.android.com/guide/topics/ui/splash-screen

Now, if you still want to do this, it’s possible. You need to show/hide scaffold elements based on which destination is the current resumed one. I do this on the sample app in this repository. I hide things like bottom bar if I’m on the login screen.
You can do that for splash screen.

**Comment by eksizadam** [comment]
Thank you for your response!
Yeah I think I should start using the splash API :) , anyway I saw your sample but I didn't want to rely on scaffold directly but yes I can use the same structure :) Because I need to switch route screen login or main screen for if user logged in or not

**Comment by raamcosta** [comment]
Cool, I will close this, but let me know below if you made that work for you :)
