### ISSUE TITLE
Provide a way to detect inside a screen composable that the transition to it has finished

### ISSUE THREAD

**Issue by alex-burghuber** [raamcosta/compose-destinations#146]
Hey there 👋

I am developing an app with transitions between screens where one of them has a google maps view integrated.
Now the problem is that the google maps view puts quite a load on the ui renderer when it initialises, which happens during the transition to the screen. This causes the transition to lag and skip frames, which isn't really nice to look at. 

My current workaround is to delay the display of the view with a LaunchedEffect that sets a variable showMapView after 500 ms to true.

Maybe some kind of callback or through a CompositionLocal which says that the transition is over would be cool? 
Or maybe a way to delay the actual navigation until the next screen is fully composed, so this won't be a problem at all?

**Comment by raamcosta** [comment]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/80427734/170345184-635af429-f2df-42c2-a2e7-ab179558ef87.png">

https://github.com/raamcosta/compose-destinations/blob/d3721841f6f6f72f3f6f9dc03aefcdc1d83abf06/playground/src/main/java/com/ramcosta/samples/playground/ui/screens/profile/ProfileScreen.kt

**Comment by alex-burghuber** [comment]
This works great, thank you very much!
