### ISSUE TITLE
How to pass a list as an argument ? 

### ISSUE THREAD

**Issue by SaadAziz9956** [raamcosta/compose-destinations#148]
Didnt find a way how do i pass a list to different composable as an argument or a bundle ?

**Comment by raamcosta** [comment]
Hi @SaadAziz9956 !

Just like all other navigation arguments. But notice the available list/array types here:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments#basics

**Comment by raamcosta** [comment]
Hint: you need to use ArrayList type for Lists

**Comment by SaadAziz9956** [comment]
Thanks Man!
