### ISSUE TITLE
KSP generated package name

### ISSUE THREAD

**Issue by hrach** [raamcosta/compose-destinations#15]
Currently the generated files are stored in `com.ramcosta.composedestinations` package name. It seems to be it would be better it generated the classes to the app's package name and ideally keep the package name of the destination.

**Comment by raamcosta** [comment]
Hi again @hrach!

The first thing on my mind here is that the generated Destinations must be in the same package in order the be able to use the `Destination` as a sealed interface. So, unless we're ok to give that up, they cannot be in the same package as the annotated Composable.

As for the package name, I guess we could use some other. Is there a specific reason why you think that would be better?

Thanks in advance!

**Comment by hrach** [comment]
I'd say this is somehow coupled with the modularization support. From that POV sealed will have to be sacrificed anyway.

> Is there a specific reason why you think that would be better?

First, navigation inside package does not require an import. Second, having the import (i.e. namespace target) helps to see (un)wanted navigation coupling. But definitely not a deal-breaker.

Also I'd say it is a standard -> databindings impls gets generated in the same package, the same for Room dao's impls, database's impl.

Definitely not a deal-breaker for now. But with the modularization support I expect this will get changed anyway.

**Comment by raamcosta** [comment]
I could also make this configurable at gradle level. Users would have to choose between a sealed `Destination` interface or generated `Destinations` to be generated in the corresponding annotation package.

At the very least, it would provide a smoother transition. If later on, we see that the sealed thing is being overvalued by me, we can simply drop it and the configuration altogether.

What do you think?

**Comment by raamcosta** [comment]
I'll close this as I believe that if this ever becomes a necessity, it will be due to multi module features.
