### ISSUE TITLE
Get result from ResultRecipient.onNavResult during screen transition

### ISSUE THREAD

**Issue by alex-burghuber** [raamcosta/compose-destinations#151]
Hey there again 😄

Currently the onNavResult() is only called when the screen transition finishes, which causes the following:
onBack -> Screen transition -> Transition finishes: Screen is shown like previously -> Ui is updated after some ms with the result.
This makes the Ui look like it is updated in stages, which isn't very smooth.

Is there a way to get the result already during the transition? Or do you have another idea?

**Comment by alex-burghuber** [comment]
@raamcosta Just tagging you here in case you missed this issue

**Comment by raamcosta** [comment]
Thanks a lot @alex-burghuber !

So, I’m thinking… what if I provide a StateFlow inside the recipient that lets you listen as values are set on the other screen? Does that sound ok?

This will mean I could keep current behaviour but also allow users to get result immediately if they prefer it that way.

**Comment by alex-burghuber** [comment]
Sounds good, definitely worth a try. 

But does this cause any issues with process recreation? E.g. A screen gets the result from the stateflow but then the app has a process death and the screen gets recreated. The screen would need to get the result from the stateflow again to correctly keep its state and the set value of the stateflow would need to be serialized before hand. Is this possible?

**Comment by raamcosta** [comment]
The idea would be to also put the result in the SavedStateHandle every time it changes. So when recreating after process death, we get it from there and set it on the flow. Definitely need to test things but it should be possible 🙂

**Comment by alex-burghuber** [comment]
Very nice, I will look forward to it 🙌 Thank you!

**Comment by raamcosta** [comment]
Fixed on latest release! You'll now get notified at first chance (usually ON_START event).
