### ISSUE TITLE
Conflict with androidx.media3

### ISSUE THREAD

**Issue by 4nk1r** [raamcosta/compose-destinations#152]
After some time I decided to build my abandoned pet-project, I started with upgrading dependencies, including your library (from `1.4.0-beta` to `1.5.8-beta`). And I got an build error, which said there's a mistake in generated sources. Here it is:

![tg_image_2158970670](https://user-images.githubusercontent.com/63253661/171987179-cb76f5e3-1994-4f59-938e-297695c20da2.jpeg)
![tg_image_2303524201](https://user-images.githubusercontent.com/63253661/171987185-d3e7d7f0-5c95-4f7a-ae50-03b2488dab00.jpeg)

I understand, it's not your-side problem, but please fix this :)

![tg_image_3857314952](https://user-images.githubusercontent.com/63253661/171987226-9395de3b-b93d-40a4-b325-26b6d1d0e333.jpeg)

**Comment by raamcosta** [comment]
Hey @4nk1r !

Thank you for reporting. 🙏
I’ll be fixing this today and I want to release a new version later today still.

I’ll update here when the new version is available

**Comment by raamcosta** [comment]
1.5.9-beta released!

Thank you again 🙂
