### ISSUE TITLE
Error with defaulted nullable navArg and import

### ISSUE THREAD

**Issue by philipk99** [raamcosta/compose-destinations#154]
Hello,

I have a weird issue when having a nullable navArg with a default of null combined with the import of "androidx.compose.foundation.layout.*".

When both are together, I get an "Unresolved reference: Direction" error. I do not know which specific part of ".layout" is causing the problem, but when I imported the ones I needed (Column, fillMaxSize, fillMaxWidth, requiredHeightIn, aspectRatio) separately, it worked fine.

**Comment by raamcosta** [comment]
Hey @philipk99 !

Is there a way for me to see the code? If it’s private repo, can you please try to make small reproduction repo? 🙏

**Comment by raamcosta** [comment]
Nevermind! I was able to reproduce it! Thanks, I'll take a look into this today! :)

**Comment by raamcosta** [comment]
Guys super weird issue. It seems like on Kotlin if you have multiple wildcard imports and both have a class with the same name, and you then use that name in the code, it gets confused even if (and this is the weird part) one of them is internal (and so, not accessible).

I already know the fix, just need some time. Maybe I can only do it tomorrow. Tough few days!

**Comment by StephenVinouze** [comment]
No need to pressure yourself :) That's an open source project after all. If someone feels really impacted by this, he/she can look into it as well as make a PR. It's not critical anyway, since you can work around it by making the param non-optional. For the time being, I can live with that :p

**Comment by raamcosta** [comment]
Yeah but I don’t like open bugs 😁

**Comment by raamcosta** [comment]
Fixed! :) Please try version 1.5.10-beta and let me know guys!

**Comment by StephenVinouze** [comment]
Fixed :) 👏
