### ISSUE TITLE
How get which route I'm on in a normal class method

### ISSUE THREAD

**Issue by jinjiafeng** [raamcosta/compose-destinations#155]
i want to get compose current route in a normal method . before I used to judge which fragment I was in . Help :(

**Comment by jinjiafeng** [comment]
I want to know which destination is the current one  in a not Composable function,like in a activity function

**Comment by raamcosta** [comment]
Hmm, mostly you should need this inside Composable functions 🤔  

Anyway, there is `NavController.currentDestinationFlow` that you can collect, but you need to get a hold of the NavController that you're passing to DestinationsNavHost.

**Comment by jinjiafeng** [comment]
This works great, thank you very much!
