### ISSUE TITLE
DeepLink related 

### ISSUE THREAD

**Issue by miduch** [raamcosta/compose-destinations#157]
Hi, 

I have @Destination with a Webview inside composable. I'm trying to open this Destination and passed received url to webview for showing webpage. 

If i define a full/ exact path as deeplink for this destination then it can open it in webview e.g. 

https://www.domain.com  <- works 
https://www.domain.com/path/somepage.html  <- works 

If let's say Deeplink is : https://www.domain.com  
and i try : https://www.domain.com/page.html  <- doesn't work   

Q: Is it possible to define Deeplink so that it can handle any path/pages from https://www.domain.com? can i use regex here?

**Comment by raamcosta** [comment]
I honestly don’t know. You should Google if that works for official compose navigation which gets used by this lib.
Whatever the deep link value we pass it to the official APIs, so the end result will be the same regardless of if you’re using this lib or official compose navigation 🙂

I’m closing as this is not an issue or question for this library.

Let me know if you find the solution! And thanks for choosing Compose Destinations!

**Comment by miduch** [comment]
thanks anyway

**Comment by raamcosta** [comment]
Sorry for not being helpful but since this is really not of this library I don’t know and I’d have to investigate myself just like you need to. 

And I’m struggling with time 😅 I’m still interested if you find what you’re looking for so let me know 🙂

**Comment by miduch** [comment]
I looked for it before posting, still looking but so far no success. Will let know if I find something. 

Cheers

**Comment by miduch** [comment]
got it working with : 

composable(
            route = "deeplinktest",
            deepLinks = listOf(navDeepLink { uriPattern = "https://www.example.com/.*" })  // <---- notice `.*` after '/'
        ) {
                ...... 
        }

OR with compose destinations

@Destination(
    deepLinks = [
        DeepLink(uriPattern = "https://www.example.com/.*")
    ]
)

in AndroidManifest.xml 

```
<intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="https"
                    android:host="www.example.com" />
</intent-filter>
```

All of these work now 

adb shell am start -d "https://www.example.com/" -a android.intent.action.VIEW
adb shell am start -d "https://www.example.com/blabla/" -a android.intent.action.VIEW
adb shell am start -d "https://www.example.com/test/hello.html" -a android.intent.action.VIEW

full url can be retrieved like this : 

backStackEntry.arguments?.get("android-support-nav:controller:deepLinkIntent") as? Intent)?.data
OR
savedStateHandle.get<Intent>("android-support-nav:controller:deepLinkIntent")?.data?.toString()

**Comment by raamcosta** [comment]
Great! 
Thanks a lot for letting me know! Today I learnt, I didn’t know you could use regex?

glad you found the answer 🙂

**Comment by miduch** [comment]
if possible please add these findings to compose-destinations's wiki, hopefully helps someone

**Comment by miduch** [comment]
Look in fun buildPathRegex()(androidx/navigation/NavDeepLink.kt)

**Comment by miduch** [comment]
> Today I learnt, I didn’t know you could use regex?
> 

Look in fun buildPathRegex()(androidx/navigation/NavDeepLink.kt)
