### ISSUE TITLE
Android 14. Predictive back gesture

### ISSUE THREAD

**Issue by TemMax** [raamcosta/compose-destinations#158]
In Android 14 would be changed "back" behavior. Is there a need for some changes for this update?
We can test this changes on Android 13 with flag `android:enableOnBackInvokedCallback="true"` in the `<application>` tag in manifest.
More about the update here: https://developer.android.com/about/versions/13/features/predictive-back-gesture

**Comment by raamcosta** [comment]
Hey @TemMax !

Hmm I believe if some change needs to be done, it should be done on official compose navigation. We will likely get that indirectly without doing anything 🙂

Or are you seeing any issue with this?

**Comment by TemMax** [comment]
> Or are you seeing any issue with this?

No. At this time no. But I'm just worried about the future :)
It's super if we should get it indirectly from official compose navigation.
Thanks a lot!
