### ISSUE TITLE
LongArray in input param cause java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by amirzeinaly** [raamcosta/compose-destinations#160]
Hi

my sample code that cause Exception

```
@Composable
@Destination
fun TestScreen(
    input: LongArray,
) {
    ///rest of my code
}
```

after calling navigator.navigate(TestScreenDestination(input = longArrayOf(152L,152L,152L,3256L,362L,362L))
this exception thrown

`
java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/test_screen/[152,152,152,3256,362,362] } cannot be found in the navigation graph NavGraph(0x78dcd1ef) route=root startDestination={Destination(0x142feed7) route=splash_screen}`

thanks for your good job

**Comment by raamcosta** [comment]
I did a change on all nav types except long array 🤦 

Fixed! It will be in the next release! 🙂 

Thank you for reporting 🙏

**Comment by raamcosta** [comment]
Please try 1.5.11-beta (should be up soon on maven central) and let me know if it fixed this for you! 

Thanks again for reporting! 🙏
