### ISSUE TITLE
Conditional navigation

### ISSUE THREAD

**Issue by andre-artus** [raamcosta/compose-destinations#164]
Is there a conditional navigation mechanism within CD?

Meaning is there a way to handle, for instance, navigate to login based on some global state (e.g. not logged in) that can be in effect for all destinations (or all destinations in a sub-graph)?

I have a way I can implement this requirement by doing the check in a intermediate composable, but I wanted to know if this is something that already exists that I can make use of, so as not to reinvent the wheel.

**Comment by raamcosta** [comment]
Hey! 👋 

Check this:
https://github.com/raamcosta/compose-destinations/blob/main/sample/src/main/java/com/ramcosta/destinations/sample/SampleApp.kt

Method `ShowLoginWhenLoggedOut`.

This is one way to do it. I believe this is the same with Compose Destinations as it is with vanilla jetpack navigation. We just have a couple more tools to help, but conceptually the same.

**Comment by andre-artus** [comment]
Thank you very much.
