### ISSUE TITLE
Dismiss BottomsSheet styled destination

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [raamcosta/compose-destinations#165]
I have the bottom sheet destination. On clicking outside, it is being dismissed with animation. I want to dismiss it after a specific action. Now I'm using `navigator.navigateUp()`, but it has no animations.

**Comment by raamcosta** [comment]
https://github.com/raamcosta/compose-destinations/issues/57#issuecomment-1039544207

Hey 👋 
This is an issue with accompanist which I explain here in the link above👆
