### ISSUE TITLE
1.6.12-beta crashes due to official navigation library bug

### ISSUE THREAD

**Issue by polivmi1** [raamcosta/compose-destinations#166]
This issue causes the apps to crash after upgrade https://github.com/google/accompanist/issues/1162

**Comment by polivmi1** [comment]
@raamcosta this should be fixed with the latest accompanist release

**Comment by raamcosta** [comment]
Great! I’ll make a new release today to update to compose 1.2 stable and the new accompanist version.

Thank you for letting me know 🙂
