### ISSUE TITLE
Destination within multiple NavGraphs is only added to the first one

### ISSUE THREAD

**Issue by AhmedMourad0** [raamcosta/compose-destinations#167]
Hello there! hope you're doing well,

```kotlin

@NavGraph
annotation class NavGraph1(val start: Boolean = false)

@NavGraph1(start = true)
@Destination(/*...*/)
@Composable
fun NavGraph1StartScreen(navigator: DestinationsNavigator) {
    //...
}

@NavGraph
annotation class NavGraph2(val start: Boolean = false)

@NavGraph2(start = true)
@Destination(/*...*/)
@Composable
fun NavGraph2StartScreen(navigator: DestinationsNavigator) {
    //...
}

@NavGraph1
@NavGraph2
@Destination(/*...*/)
@Composable
fun MyScreen(navigator: DestinationsNavigator) {
    //...
}
```

`MyScreenDestination` is only being added to the destinations of `NavGraph1`

**Comment by raamcosta** [comment]
At the moment this is expected.
Each Destination can only have a single NavGraph. If you want that behaviour you need to make two Composables one for each NavGraph and both call a common composable.
This forces you to give different names, which creates two different generated Destinations, which in turn makes you be able to navigate to specific one you want 🙂

**Comment by raamcosta** [comment]
I’ll leave it open but it’s probably low priority enhancement at best 🙂

**Comment by Vahalaru** [comment]
I don't even know if this would be possible but is there a way to check if a destination is used multiple times? If so it should be easy to generate a wrapper composable with the same name plus adding a numeric value at the end that contains that composable.  

It's not perfect and could eventually be optimized to specify more details but would allow this action without having to manually create said files.

**Comment by yallam08** [comment]
I think this is actually a very useful feature, it'll enable navigating to the same destination from multiple graphs without any workarounds, right? or i'm missing something?

**Comment by raamcosta** [comment]
Hi @yallam08!

You can already do that 🤔
Unless with graphs you mean root level graphs aka the ones passed in to DestinationsNavHost calls?
In that case, no this doesn’t help to do it more easily than we can also already do it.

This feature would literally create one destination  for each graph and all would call your composable, that’s it. 

You can achieve the same thing by defining multiple destinations which just calls a common composable. Each assigned to its own graph.

**Comment by yallam08** [comment]
@raamcosta 

yes, with graphs i mean the root level.
i'm currently using a serparate graph for a flow within my app. e.g, @SignInSignUpGraph , @HomeGraph , @PaymentGraph , etc..
and in many cases i have a screen that's accessed from 3 graphs or more.

now i'll need to define 3 wrapper destinations for the same screen. i'd prefer if the library does this for me and use the same destination. what do you think?

thanks for the great lib btw

**Comment by maggud** [comment]
Just came here to say that I just tried to do this exact thing and was looking to open a new question about it, so essentially a +1.

Just adding my scenario to it:

I have two separate bottom navigation layouts that is the main navigation, but looks different for different users. Some tabs are shared between the bottom navigations, and I would have liked to just share those destinations. I can't put them to the same NavGraph because they have different starting tabs, among other things.

I think it would be a nice addition, but I understand that it might not feel that high prio :)

I had thought it would just add the same destination to two different NavGraphs, but I guess this could mess up things in ways I'm not familiar with 😅

**Comment by lolafhkahfkjsghd** [comment]
would be nice if this is implemented

**Comment by lmiskovic** [comment]
Also +1 although we are currently going with multiple destinations calling common composable and it is totally fine

**Comment by raamcosta** [comment]
Implemented for v2! Closing this one.
