### ISSUE TITLE
How to get current destination in non-composable function?

### ISSUE THREAD

**Issue by mainrs** [raamcosta/compose-destinations#168]
I wanted to add some extension functions to `NavController` to check on which route I am currently on. Depending on the route I change my Scaffold's TopBar title.

Maybe there exists a beter way to do this, but I didn't find anything that was library-specific.

```kotlin
// Used to activate the back icon.
@Composable
fun NavController.isNotMainView(): Boolean =
    this.currentDestinationAsState().value != NavGraphs.root.startAppDestination

// Used to set the title of the TopBar.
@Composable
fun NavController.isTrackingRoute(): Boolean =
    this.currentDestinationAsState().value == TrackingScreenDestination
```

**Comment by raamcosta** [comment]
If you only want the current Destination you can also do:

```kotlin
navController.currentBackStackEntry?.appDestination()
```

But to be honest, if your use case is to update the top bar every time the destination changes, why not use the `currentDestinationAsState()`?

Check here how I update my top level composables when destination changes:
https://github.com/raamcosta/compose-destinations/blob/main/sample/src/main/java/com/ramcosta/destinations/sample/ui/composables/SampleScaffold.kt

**Comment by mainrs** [comment]
Thanks!
