### ISSUE TITLE
Is there any way to listen for bottomsheet destination drag down?

### ISSUE THREAD

**Issue by AzizbekRasulmetov** [raamcosta/compose-destinations#171]
I am using @Destination(style = BottomSheet) and I would like to know whether user dragged it down to close bottom sheet and do some actions based on this. Is there any way to listen for such events?

**Comment by raamcosta** [comment]
Hey 👋 

Yes, there is a way, I’ll post it here in a hour or so 🙂

**Comment by raamcosta** [comment]
I will close this.
Please let me know if you managed to make it work 😉
