### ISSUE TITLE
How to send kotlin callback to activity from jetpack compose start destination screen 

### ISSUE THREAD

**Issue by yadavraju** [raamcosta/compose-destinations#182]
I have start Destination @Destination(start = true) I want to send a callback function to do some native android intent call from activity. How can I do that? please help me @raamcosta

Here is a screenshot required class interaction. I want to send `logoutFinish: () -> Unit = {}` back to activity from start destinatio
<img width="1786" alt="rama" src="https://user-images.githubusercontent.com/9611971/178130775-601a8eb8-b9f3-4416-b48b-b8eb50b2d79c.png">

**Comment by raamcosta** [comment]
Hey @yadavraju 

For all parameters you want to pass from the NavHost call, you can either create a class type so you can pass it via “dependencyContainerBuilder” or you can manually call your destination.
Check here how to do that:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters#manually-call-your-screen-composable

the link takes you directly to what I believe is the simplest way for you but you can read the whole page to understand both approaches.

Let me know if there is any question regarding it 🙂
