### ISSUE TITLE
Pass argument to saveStateHandle

### ISSUE THREAD

**Issue by sparjapati** [raamcosta/compose-destinations#187]
I'm working on compose navigation using the traditional method 
```
composable(
    Screen.AddEditNoteScreen.route + "?noteId={noteId}&noteColor={noteColor}",
     arguments = listOf(
         navArgument("noteId") {
             type = NavType.IntType
             defaultValue = -1
         }
     )) {
           AddEditNoteScreen(
               navController,
               noted
               )
         }
)
```
and getting that argument using saveStateHandle in ViewModel
```
class AddEditViewModel @Inject constructor(
    private val savedStateHandle: SavedStateHandle,
){
  init {
        savedStateHandle.get<Int>("noteId")?.let { noteId ->
               // use noteId
        }
    }
}
```

But later switched to your library, so how can I get into some object similar to saveStateHandle like DestinationSaveStateHandle.
expected like->
```
class AddEditViewModel @Inject constructor(
    private val addEditScreenSavedStateHandle: AddEditScreenSavedStateHandle,
){
   init {
        addEditScreenSavedStateHandle.node?.let{
                  // use note here  
             }
         }
}
```

**Comment by raamcosta** [comment]
Hi!

https://github.com/raamcosta/compose-destinations/blob/main/playground/src/main/java/com/ramcosta/samples/playground/ui/screens/profile/ProfileViewModel.kt

line 39

**Comment by raamcosta** [comment]
Also check this:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments#navigation-arguments-class-delegate

**Comment by raamcosta** [comment]
Let me know if you managed to do what you wanted! 🙂

**Comment by sparjapati** [comment]
Ya, I got it.
