### ISSUE TITLE
Composable which requires parameter is not getting a NavArgs-enabled destination

### ISSUE THREAD

**Issue by b4ux1t3** [raamcosta/compose-destinations#189]
I have a composable that takes an object as a parameter. here's the function signature:

``` kotlin
@Composable
@Destination
fun CreatureGenerator(
    user: User,
    viewModel: CreatureGeneratorViewModel = hiltViewModel()
)
```

However, I had previously not required that `user` parameter, so when I navigated to it with a user passed as an argument, it threw an error. Okay, no big deal. I figured I just needed to re-run the build to get code generation to kick in. 

I re-ran the build, and I still get the error of expecting `Unit` instead of `User`.

I deleted the generated code (the entire `kotlin` code generation directory, just to be sure), and re-ran the build again. . .and I'm still not getting a NavArgs-enabled destination. Here's the generated code for the above composable:

``` kotlin
object CreatureGeneratorDestination : DirectionDestination {
         
    operator fun invoke() = this
    
    @get:RestrictTo(RestrictTo.Scope.SUBCLASSES)
    override val baseRoute = "creature_generator"

    override val route = baseRoute
    
    @Composable
    override fun DestinationScope<Unit>.Content(
		dependenciesContainerBuilder: @Composable DependenciesContainerBuilder<Unit>.() -> Unit
    ) {
		val dependencyContainer = remember { DestinationDependenciesContainer(this) }
		dependencyContainer.apply { dependenciesContainerBuilder() }

		CreatureGenerator(
			user = dependencyContainer.require()
		)
    }
    
}
```

The thing is, I have another project, using the exact same version of the library, which isn't having any trouble detecting the required parameter and generating a navArgs-enabled destination (snippet for comparison to above):

``` kotlin
object ItemDetailsDestination : TypedDestination<ItemDetailsDestination.NavArgs> {
    
    override fun invoke(navArgs: NavArgs): Direction = with(navArgs) {
        invoke(identifier)
    }
```

Is there any more information I can give to get to the bottom of what's going on?

**Comment by raamcosta** [comment]
Hi there 👋

Is User class type a navigation argument type? (You know Parcelable, Serializable,etc?

**Comment by b4ux1t3** [comment]
It's not an overly complicated class, at this point it's literally just an ID and a username.

I kind of assumed that was all getting done by the code gen, but just re-read the README (doh!). 

That's on me, I didn't read the docs hard enough! Sorry for wasting your time.

**Comment by b4ux1t3** [comment]
Ah, that actually makes a lot of sense. Thanks for the help!
