### ISSUE TITLE
Share ViewModel in nestedgraph

### ISSUE THREAD

**Issue by sinadalvand** [raamcosta/compose-destinations#19]
I'm working on register part of my application.
I need to share Viewmodel between RegisterPage and MapPage, and also I want to clear ViewModel after closing all Pages in this graph , but when I use ``dependenciesContainerBuilder`` for keep ViewModel shared , it's like singleton and prevent making new instance of ViewModel for new nestedgraph , is nay another approach here ?

**Comment by raamcosta** [comment]
Hi @sinadalvand !

Did you manage to make it work like you wanted to?
This is actually super easy and elegant. I have an app with this exact case. I do it like this:

```kotlin
DestinationsNavHost(
    navController = navController
) { navBackStackEntry ->
    val navDestination = navBackStackEntry.navDestination ?: return@DestinationsNavHost

    if (NavGraphs.newPayment.allDestinations.contains(navDestination)) {
        val parentEntry = remember {
            navController.getBackStackEntry(NavGraphs.newPayment.route)
        }
        val parentViewModel = viewModel<NewPaymentFlowViewModel>(parentEntry)
        dependency(parentViewModel)
    }
}
```

And that's it! All destinations that belong to the `newPayment` nested nav graph can now declare a `NewPaymentFlowViewModel` and the lib will provide it when it gets navigated to.

**Comment by nrobi144** [comment]
@raamcosta the above example seems broken in `v1.3.1` as `dependenciesContainerBuilder: DependenciesContainerBuilder<*>.() -> Unit` is not a `@Composable` lambda
