### ISSUE TITLE
Provide dependencies throughout NavGraphs

### ISSUE THREAD

**Issue by MaxMichel2** [raamcosta/compose-destinations#193]
Hello (again 😉)

I was looking through a project I'm working on and found a small issue where having a ViewModel dependency on a NavGraph isn't provided to screens in sub NavGraphs.

Looking through existing issues I found #19 in which you provide an example solution (which as you said is rather elegant).

I was wondering if it's possible for the dependency to be automatically provided to sub NavGraphs ? Something like the following:

```kotlin
dependency(NavGraphs.nested) {
    val parentEntry = remember(navBackStackEntry) {
        navController.getBackStackEntry(NavGraphs.nested.route)
    }
    hiltViewModel<NestedViewModel>(parentEntry)
}

/* Currently:
val root = NavGraph(
    route = "root",
    startRoute = StartScreenDestination,
    destinations = listOf(
        StartScreenDestination
    ),
    nestedNavGraphs = listOf(
        nested
    )
)

val nested= NavGraph(
    route = "nested",
    startRoute = NestedScreenDestination,
    destinations = listOf(
        NestedScreenDestination <-- This has access to NestedViewModel
    ),
    nestedNavGraphs = listOf(
        subNested
    )
)

val subNested= NavGraph(
    route = "sub_nested",
    startRoute = SubNestedScreenDestination,
    destinations = listOf(
        SubNestedScreenDestination <-- This doesn't have access to NestedViewModel even though it belong to NavGraphs.nested
    )
)
*/
```

I'm not too familiar with the library so haven't been able to identify where this dependency split occurs but It would be a more logical behaviour in my opinion (and would avoid having an if in the dependenciesContainerBuilder)

**Comment by raamcosta** [comment]
Hey @MaxMichel2!

Thank you for continuing to contribute to the project! It really makes a difference :) 
If you ever want to talk a bit about the code, I would definitely be up for that!

Regarding this, yeah I can see how that could be expected here. I'll check it out, it is an easy change :)

**Comment by MaxMichel2** [comment]
Hey @raamcosta!

I'll gladly take you up on that offer! I'll message you soon hopefully!

**Comment by raamcosta** [comment]
Solved in versions 1.x.15. Releasing them to maven central!
