### ISSUE TITLE
Compose 1.3 (1.3.x) version

### ISSUE THREAD

**Issue by miduch** [raamcosta/compose-destinations#196]
Any plans to create version which targets compose 1.3? 

tried following in my project and seems to work fine 

compose-compiler = "1.3.0-rc01"
compose-core = "1.3.0-alpha02"
compose-destinations = "1.6.14-beta"
accompanist = "0.26.0-alpha"
kotlin = "1.7.10"

**Comment by raamcosta** [comment]
Yes! Will do it today 🙂
I was waiting on accompanist version for 1.3 and 1.2 stable compose. Both happened very recently.

**Comment by raamcosta** [comment]
Done! version 1.7.15-beta should be up in maven very sson :)

**Comment by miduch** [comment]
thanks!

**Comment by miduch** [comment]
this seems to have caused regression for me. 

Our app need to hide TopAppBar when navigating to some destinations, before bumping to version 1.7.15-beta everything was working fine but after 1.7.15-beta expandVertically animation doesn't seem to work anymore in following code. 

I doubled checked by downgrading to 1.6.14-beta and it starts to work again,  v1.7.15-beta seems to break this somehow :) 


```
AnimatedVisibility(
                visible = visibilityState,
                enter = expandVertically(animationSpec = tween(durationMillis = 100)),
                exit = shrinkVertically(animationSpec = tween(durationMillis = 200)),
                modifier = Modifier.onSizeChanged {
                            Log.d("AnimatedVisibility - onSizeChanged $it")
                        }
            ) {
                TopAppBar(......)
            }
```

on v1.6.14-beta upon expand :  
AnimatedVisibility - onSizeChanged 1080 x 259


on v1.7.15-beta upon expand :  
AnimatedVisibility - onSizeChanged 1080 x 0

Other:
compose.ui : 1.3.0-alpha02
compose.compiler:  1.3.0-rc01
kotlin 1.7.10
