### ISSUE TITLE
The screen does not jump when the app is launched

### ISSUE THREAD

**Issue by xiayuyu** [raamcosta/compose-destinations#197]
When I launch the app, the screen doesn't automatically jump, it stays on a blank screen, I have to tap the phone screen with my hand to jump, and I had the same problem running Compose - Destinations. My phone system version is Android12

**Comment by raamcosta** [comment]
Can you upload a video of the device while this happens?

Can we access the code also?

**Comment by xiayuyu** [comment]
https://user-images.githubusercontent.com/32577970/181867052-6b842889-23e2-4573-8abf-e0a364aa4710.mp4

I ran your Sample app. After starting the app, you must click the blank screen, and then the content can be displayed

**Comment by raamcosta** [comment]
This is the weirdest thing I’ve seen 😅
Do you mind trying it in the emulator? I’ve run this sample on multiple different devices it is working fine 🤔

**Comment by xiayuyu** [comment]
![6b8f0a0348e7306fa9533332f960774](https://user-images.githubusercontent.com/32577970/181903251-aa63f652-ca9d-46f0-b3b0-385f2b62e75d.jpg)
Yes, can you try this mobile phone system, only this phone has this problem, my other phones are OK

**Comment by raamcosta** [comment]
If it only happens on one device, i don’t know what I can do 🤷‍♂️
Seems like an issue which would happen also with official compose navigation? Have you tried that?

**Comment by raamcosta** [comment]
I’ll close this as I really don’t think this is an issue with this library. Let me know if you find it also does this with official navigation (pretty sure it will)

**Comment by xiayuyu** [comment]
At first I thought it was a problem with the official navigation, but after I tried it, it was fine, so I asked the question

**Comment by raamcosta** [comment]
Does it only happen with my sample app?

**Comment by xiayuyu** [comment]
![image](https://user-images.githubusercontent.com/32577970/182275337-5f66f693-0e54-4718-9a3a-5791b1cf746c.png)
I compared the official demo and found that I had to add this code to make the screen jump OK when the App started, but I don't know why😅
