### ISSUE TITLE
[PlayGround] when expression must be exhaustive.

### ISSUE THREAD

**Issue by sumanabhi** [raamcosta/compose-destinations#198]
**`when`** expression must be exhaustive, add the necessary **`ProfileSettingsScreenDestination`** branch or **`else`** branch instead. [DestinationsAppExtensions.kt --> Line 20](https://github.com/raamcosta/compose-destinations/blob/c72980bfa48dbd92a87360fa1b7eb1bf3eca857c/playground/src/main/java/com/ramcosta/samples/playground/commons/DestinationsAppExtensions.kt)

**Comment by raamcosta** [comment]
Opah, will fix. Thank you 🙏

**Comment by sumanabhi** [comment]
@raamcosta Thanks for the Quick Reply. I have already fixed it. if you are okay, I can go ahead with PR.
