### ISSUE TITLE
Need help in nesting graphs

### ISSUE THREAD

**Issue by ghulammohiuddin2398** [raamcosta/compose-destinations#204]
I am new to android development and I am trying to show splash screen after 3s want to show the main screen with a bottom bar. I have implemented first bottom bar and it was working fine. Now i have create `mainnavgraph `using annotation and nested it in root. In splash screen i am using a `LaunchedEffect `and after 3s delay navigating to `mainnavgrapgh`. But app crashes with `java.lang.NullPointerException` on the same line where i am calling `navController.navigate(NavGraphs.main.route)` method in `LaunchedEffect `.
Here my code of splash screen:
```
@RootNavGraph(start = true)
@Destination
@Composable
fun SplashScreen() {
    val navController = rememberNavController()
    val systemUiController: SystemUiController = rememberSystemUiController()

    DestinationsNavHost(navGraph = NavGraphs.root) {
        composable(SplashScreenDestination) {
            systemUiController.isSystemBarsVisible = false
            systemUiController.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE

            LaunchedEffect(true) {
                delay(3000L)
                navController.navigate(NavGraphs.main.route)
            }
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .wrapContentSize(Alignment.Center)
            ) {
                Image(
                    painter = painterResource(id = R.drawable.ic_launcher_foreground),
                    contentDescription = null,
                    modifier = Modifier
                        .align(Alignment.CenterHorizontally))
            }
        }
    }
}
```

Here's code of main screen with bottom bar:
```
@MainNavGraph(start = true)
@Destination
@Composable
fun MainScreen() {
    val navController = rememberNavController()
    Scaffold(
        bottomBar = {
            BottomBar(navController = navController)
        }
    ) { contentPadding ->
        DestinationsNavHost(navGraph = NavGraphs.main, navController = navController, modifier = Modifier.padding(contentPadding)) {
            composable(HomeScreenDestination) {
                HomeScreen(navController = navController)
            }
            composable(SearchScreenDestination) {
                SearchScreen()
            }
            composable(LocationScreenDestination) {
                LocationScreen()
            }
            composable(TimesScreenDestination) {
                TimesScreen()
            }
        }
    }

}
```

All other screens in main screen are also belong to same mainnavgragh.

Here's main navgraph code:
```
@RootNavGraph
@NavGraph
annotation class MainNavGraph(
    val start: Boolean = false
)
```

I am unable to understand why i am getting null pointer exception and how can i achieve this. There should be an article about it somewhere or it should be wikis.

**Comment by raamcosta** [comment]
Hi @ghulammohiuddin2398 👋 

Sorry for the brief response, I’m not on the pc atm.
But let me try to help you a bit. 

Your SplashScreen does not belong itself to any nav graph. It just contains the NavHost that then contains all nav graphs and destinations.

And then your MainScreen doesn’t belong to Main nav graph. It belongs to the root one, and then it calls NavHost passing in the main nav graph.

Start with that and let me know how it goes. Btw what exactly is null? Can you paste the stack trace?

**Comment by ghulammohiuddin2398** [comment]
Hi. First of all, thanks man for your help. I think the problem was MainScreen should have been part of RootNavGraph. All i had to do was add SplashScreen and MainScreen in RootNavGraph and move NavHost is SplashScreen to its parent and it worked like magic .
Secondly, I was really happy to find your library. I am an iOS developer. In `SwiftUI`, there is a `NavigationLink `in which we just pass the view which makes is easy to pass any data to next view as arguments/parameters and a state parameter that tells when to navigate. I was missing that in compose navigation. But then I learned about your lib and its really wonderful. I can now pass data to next view easily.
Thanks for this library.

**Comment by ghulammohiuddin2398** [comment]
Hi. First of all, thanks man for your help. I think the problem was MainScreen should have been part of RootNavGraph. All i had to do was add SplashScreen and MainScreen in RootNavGraph and move NavHost is SplashScreen to its parent and it worked like magic .
Secondly, I was really happy to find your library. I am an iOS developer. In `SwiftUI`, there is a `NavigationLink `in which we just pass the view which makes is easy to pass any data to next view as arguments/parameters and a state parameter that tells when to navigate. I was missing that in compose navigation. But then I learned about your lib and its really wonderful. I can now pass data to next view easily.
Thanks for this library.
