### ISSUE TITLE
Channel is unrecoverably broken and will be disposed!

### ISSUE THREAD

**Issue by mykola-dev** [raamcosta/compose-destinations#205]
Hey! First of all i'd like to admit this is the most elegant navigation API I ever used. Good job man!

I'm trying to store shared viewmodel as navigation dependency:
```
@Composable
fun ComposeApp() {

    val mainViewModel: MainViewModel = hiltViewModel()

    MyTheme {
        DestinationsNavHost(
            navGraph = NavGraphs.root,
            dependenciesContainerBuilder = {
                dependency(mainViewModel)
            }
        )
    }
}
```
And when I navigate to the composable
```
@Destination
@Composable
fun ViewerScreen(navigator: DestinationsNavigator, mainViewModel: MainViewModel)
...
```
my app is crashing with 1 single log output:
```
 channel '61d1ab1 xxx.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

And it looks like some kind of memory leak error. when I swap it to:
```
 dependenciesContainerBuilder = {
                dependency(hiltViewModel<MainViewModel>())
            }
```
it works, but the ViewModel becomes not shared (each time new instance is being created).

any suggestions?

**Comment by raamcosta** [comment]
Hi!
You need to pass the activity to the hiltViewModel method.

Check this:
https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels#share-viewmodels-between-multiple-destinations

**Comment by raamcosta** [comment]
Let me know if it fixes it for you 🙂

**Comment by mykola-dev** [comment]
i forgot to mark my vm with @HiltViewModel annotation! sorry for the disturbance :)
thanks again for the great product.
google should learn how to create beautiful APIs by this example.
