### ISSUE TITLE
Use @Destination(start = true) error multi module

### ISSUE THREAD

**Issue by cholwell** [raamcosta/compose-destinations#206]
Every build I get the same error

`com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Use argument `start = true` in the @Destination annotation of the 'root' nav graph's start destination!`

Despite having @RootNavGraph(start = true). Doing as the prompt says makes no difference the error is always present.

Is it just not possible to contribute @Destination annotated composables from other modules?

**Comment by raamcosta** [comment]
Hi @cholwell 👋

Let me know how this ended, did you manage to work it out?
