### ISSUE TITLE
Sample is Broken/Missing Methods

### ISSUE THREAD

**Issue by hscissors** [raamcosta/compose-destinations#207]
I'm trying to reproduce this `SampleScaffold` in my app. In particular the hiding and showing of the `bottomBar` by destination. Here is the code from the sample: 
```
@OptIn(ExperimentalMaterialNavigationApi::class)
@Composable
fun SampleScaffold(
    startRoute: Route,
    navController: NavHostController,
    topBar: @Composable (Destination, NavBackStackEntry?) -> Unit,
    bottomBar: @Composable (Destination) -> Unit,
    content: @Composable (PaddingValues) -> Unit,
) {
    val destination = navController.appCurrentDestinationAsState().value
        ?: startRoute.startAppDestination
    val navBackStackEntry = navController.currentBackStackEntry

    // 👇 only for debugging, you shouldn't use backQueue API as it is restricted by annotation
    navController.backQueue.print()

    val bottomSheetNavigator = rememberBottomSheetNavigator()
    navController.navigatorProvider += bottomSheetNavigator

    // 👇 ModalBottomSheetLayout is only needed if some destination is bottom sheet styled
    ModalBottomSheetLayout(
        bottomSheetNavigator = bottomSheetNavigator,
        sheetShape = RoundedCornerShape(16.dp)
    ) {
        Scaffold(
            topBar = { topBar(destination, navBackStackEntry) },
            bottomBar = { bottomBar(destination) },
            content = content
        )
    }
}
```
 Not only is `appCurrentDestinationAsState` missing (perhaps renamed?) the return type is `DestinationSpec<*>` which is not a `Destination` which is passed to the `bottomBar`. More over, In the `SampleApp`, there is a reference to `Destination.shouldShowScaffoldElements` which also doesn't exist.

**Comment by raamcosta** [comment]
Hi 👋 

`shouldShowScaffoldElements` is an extension getter created in the sample itself, so it’s normal you won’t have it 😁

Regarding Destination and appCurrentDestinationAsState, these are only created in singleModule mode so I’m guessing you’re using some other mode in the ksp block of your build.gradle? 
But there is absolutely no issue, you can replace with DestinationSpec and currentDestinationAsState and it will do the same for you, except that DestinationSpec won’t be sealed, which is impossible given that implementations are spread in different modules (again, assuming that you are using some multi module mode in ksp build.gradle).

Let me know if this helps 🙂

**Comment by raamcosta** [comment]
I'll close due to lack of feedback. Hope this is solved @hscissors !
