### ISSUE TITLE
Manual decoding while using @NavTypeSerializer 

### ISSUE THREAD

**Issue by luanbarbosa-sanoma** [raamcosta/compose-destinations#208]
While using `@NavTypeSerializer` or `@kotlinx.serialization.Serializable`, the encoding of NavArgs works just fine for custom objects. However, the decoding side in the ViewModel using `savedStateHandle.get<ArrayList<CustomType>>()` does not work "ClassCastException" since the values added to the SavedStateHandle are String.

Either using `@kotlinx.serialization.Serializable` or `@NavTypeSerializer` the result is the same: Manual decoding needed.

From the documentation we have  this:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments/#custom-navigation-argument-types
> After this, you can pass androidx.compose.ui.graphics.Color as you would any other navigation argument.

Am I missing something or do we always need to decode custom objects manually?

**Comment by luanbarbosa-sanoma** [comment]
Example code:


``` 
@kotlinx.serialization.Serializable
data class Filter(
    val queryParamKey: String,
    ...
)
```

NavTypeSerializer
```
@NavTypeSerializer
class FilterTypeSerializer: DestinationsNavTypeSerializer<Filter> {
    override fun toRouteString(value: Filter): String = ...
    override fun fromRouteString(routeStr: String): Filter = ...
}
```

NavArgs
```
data class SearchFilterScreenNavArgs(
    val filters: ArrayList<Filter>
    ...
)
```

ViewModel (decoding)
```
savedStateHandle.get<List<Filter>>(ARG_FILTERS)?.let { 
     // cannot cast String to Filter
}
```

**Comment by raamcosta** [comment]
Hi 👋 

Yea this is expected, right above in that same doc page you have this:

> Do not try to access a specific navigation argument by its string key from the SavedStateHandle or the NavBackStackEntry. Compose Destinations is here to abstract you from this and so internally it may be using different types than what you expect.
If you really need to do it for some reason, use the corresponding NavType class get methods. You can check in the generated Destination how it does it in the argsFrom methods.

So, use the argsFrom of the destination or the generated reified “navArgs” methods.

Compose destinations is abstracting this for you, you don’t even necessarily know which key is used in the SavesStateHandle 🙂
