### ISSUE TITLE
Is it possible to declare generated build files in another module?

### ISSUE THREAD

**Issue by TomaszSieber** [raamcosta/compose-destinations#209]
Hi,

first of all thx for this amazing plugin. It really helps a lot!

But I do have one question...

Lets say I have the following Module Structure:
- App
- Feature Module A
- Feature Module B

Both Feature Modules have Composables and are using Destinations to generate the Code. They also are completely independent and have no reference to each other.

But what if I want to navigate to Feature Module B from Feature Module A? I could use Deeplinks, but then I would need to declare it somewhere manually.

What I was thinking about, is it possible to create a some sort of "Library-Navigation-Module" which both Feature Modules are depending on, and tell the plugin to generate the Destinations into this Library-Navigation-Module instead of the build-folder of the Feature-Module? So the Feature Modules still do not need to know about each other, but can navigate there.

**Comment by raamcosta** [comment]
Hi 👋 

No it’s not possible with ksp to generate files in modules other than the module actually running ksp.

To be honest I provided some configs to allow multi module usage of ksp, but I’m starting to regreat it.
The best solution imo is to have a navigation module like you said but have all @Destinations there in that module. Then these just call your feature module normal Composables, and they can pass lambdas for navigating for example. This is my recommendation of multi module apps going further.

I know it may seem weird to have Composables annotated with Destination and then have actual real Composables with the screen logic, but this is not far from a well organised source code using official compose navigation (except better in all type safetyness and boiler plate still) where you also move screens to its own function near the NavHost and those call the actual screen composables.

**Comment by raamcosta** [comment]
Let me know if this helped, I’ll be paying attention in the comments below.
