### ISSUE TITLE
ViewModel unit test problems with SavedStateHandle.navArgs()

### ISSUE THREAD

**Issue by luanbarbosa-sanoma** [raamcosta/compose-destinations#210]
Hi,

I'm using `SavedStateHandle.navArgs()` to get the navigation arguments on my ViewModel. However, on my Unit tests the call fails with `NoClassDefFoundError: Could not initialize class` error. I've added the value directly in my `SavedStateHandle` with no success.

How can I manage to test the ViewModel with the navigation arguments without having to do a UI test?

```
Could not initialize class com.ramcosta.composedestinations.navargs.primitives.DestinationsStringNavType
java.lang.NoClassDefFoundError: Could not initialize class com.ramcosta.composedestinations.navargs.primitives.DestinationsStringNavType
```

Code snippets:

> ViewModel
```
class SearchViewModel @Inject constructor(
    savedStateHandle: SavedStateHandle,
    ...
) {

    init {
        // Test fails here
        val initialQuery = savedStateHandle.navArgs<SearchScreenNavArgs>().initialQuery
    }
```

> Unit test
```
@Before
fun setup() {
    viewModel = SearchViewModel(
            savedStateHandle = SavedStateHandle().apply {
                set("initialQuery", "")
            },
            ...
    )
}
```

**Comment by raamcosta** [comment]
Hi 👋 

You can receive the initial query in the constructor of the ViewModel, making use of dependency injection principles.
Then in the test you can inject whatever you want.

Let me know if this helped 🙂

**Comment by raamcosta** [comment]
I closed this but I’ll be paying attention to your replies here 😃

**Comment by luanbarbosa-sanoma** [comment]
Do you mean I'm not able to use either? When is the case I can use them in the ViewModel and also be able to Unit test it?

```
SearchScreenDestination.argsFrom(savedStateHandle)
```

```
savedStateHandle.navArgs<SearchScreenNavArgs>()
```

```
data class SearchScreenNavArgs(
    val initialQuery: String = ""
)

@Suppress("LongMethod")
@Destination(
    navArgsDelegate = SearchScreenNavArgs::class,
)
@Composable
fun SearchScreen(...)
```

**Comment by luanbarbosa-sanoma** [comment]
One option would be passing by the compose screen... which looks a bit bad.

```
@Destination
SearchScreen(initialQuery: String) { 
    vm.loadNavArgs(initialQuery) 
}
```

**Comment by raamcosta** [comment]
No, you can and should use one of those options, but do it before calling the ViewModel constructor and pass the result to it.

Are you using Hilt or any other DI framework?

**Comment by raamcosta** [comment]
Ok, so search for assisted injection. This is a good practice either way, it’s not just a workaround to this issue 😁

**Comment by raamcosta** [comment]
Let me try to find you an example of this

**Comment by raamcosta** [comment]
Coming from Manuel himself ☝️

**Comment by luanbarbosa-sanoma** [comment]
I'll give it a try. Thank you for the fast responses!

**Comment by raamcosta** [comment]
Hmm I actually went through this and gave a quick DM to Manuel, and it seems this is not recommended 🤔

https://github.com/google/dagger/issues/2287

**Comment by raamcosta** [comment]
So.. you can either use a setter and call it from the Composable, or you can mock the navArgs method.. Are you using a mocking library?

**Comment by luanbarbosa-sanoma** [comment]
Yes, Mockito.

**Comment by raamcosta** [comment]
Hmm not sure how to mock these methods with mockito 🤔

Maybe your best bet until they fix the assisted injection in Hilt is to use a setter like you said before. If you were using manual dep injection this would be trivial, so yeah, it’s annoying that this issue is worse because Hilt is missing this support.

**Comment by epool** [comment]
@raamcosta should this issue be reopened? I'm facing the same issue and seems related with `DestinationsStringNavType`, when I use the `SavedStateHandle` directly it works.

**Does NOT work**
```
@HiltViewModel
class CountryLocalIdConfirmationViewModel @Inject constructor(
    savedStateHandle: SavedStateHandle,
) : ViewModel() {

    private val _viewState = MutableStateFlow<ViewState>(savedStateHandle.navArgs()) // <======= Unit tests fail here
}
```

**Does work**
```kotlin
@HiltViewModel
class CountryLocalIdConfirmationViewModel @Inject constructor(
    savedStateHandle: SavedStateHandle,
) : ViewModel() {

    private val _viewState = MutableStateFlow(
        ViewState(
            countryLocalIdType = savedStateHandle.getOrThrow("countryLocalIdType"),
            countryLocalId = savedStateHandle.getOrThrow("countryLocalId"),
            checkBoxValue = savedStateHandle.getOrThrow("checkBoxValue"),
        )
    )
}
```

This is the current generated code
```kotlin
	override fun argsFrom(savedStateHandle: SavedStateHandle): ViewState {
	    return ViewState(
			countryLocalIdType = countryLocalIdTypeEnumNavType.get(savedStateHandle, "countryLocalIdType") ?: throw RuntimeException("'countryLocalIdType' argument is mandatory, but was not present!"),
			countryLocalId = DestinationsStringNavType.get(savedStateHandle, "countryLocalId") ?: throw RuntimeException("'countryLocalId' argument is mandatory, but was not present!"),
			checkBoxValue = DestinationsBooleanNavType.get(savedStateHandle, "checkBoxValue") ?: throw RuntimeException("'checkBoxValue' argument is not mandatory and not nullable but was not present!"),
	    )
	}
```
maybe should generate something like this?
```kotlin
	override fun argsFrom(savedStateHandle: SavedStateHandle): ViewState {
	    return ViewState(
			countryLocalIdType = savedStateHandle["countryLocalIdType"] ?: throw RuntimeException("'countryLocalIdType' argument is mandatory, but was not present!"),
			countryLocalId = savedStateHandle["countryLocalId"] ?: throw RuntimeException("'countryLocalId' argument is mandatory, but was not present!"),
			checkBoxValue = savedStateHandle["checkBoxValue"] ?: throw RuntimeException("'checkBoxValue' argument is not mandatory and not nullable but was not present!"),
	    )
	}
```
or maybe making `DestinationsStringNavType` a class instead of an object? the generated
```
val countryLocalIdTypeEnumNavType = DestinationsEnumNavType(CountryLocalIdType::class.java)
```
seems to work fine.

**Comment by epool** [comment]
> @raamcosta should this issue be reopened? I'm facing the same issue and seems related with `DestinationsStringNavType`, when I use the `SavedStateHandle` directly it works.
> 
> **Does NOT work**
> 
> ```kotlin
> @HiltViewModel
> class CountryLocalIdConfirmationViewModel @Inject constructor(
>     savedStateHandle: SavedStateHandle,
> ) : ViewModel() {
> 
>     private val _viewState = MutableStateFlow<ViewState>(savedStateHandle.navArgs()) // <======= Unit tests fail here
> }
> ```
> 
> **Does work**
> 
> ```kotlin
> @HiltViewModel
> class CountryLocalIdConfirmationViewModel @Inject constructor(
>     savedStateHandle: SavedStateHandle,
> ) : ViewModel() {
> 
>     private val _viewState = MutableStateFlow(
>         ViewState(
>             countryLocalIdType = savedStateHandle.getOrThrow("countryLocalIdType"),
>             countryLocalId = savedStateHandle.getOrThrow("countryLocalId"),
>             checkBoxValue = savedStateHandle.getOrThrow("checkBoxValue"),
>         )
>     )
> }
> ```
> 
> This is the current generated code
> 
> ```kotlin
> 	override fun argsFrom(savedStateHandle: SavedStateHandle): ViewState {
> 	    return ViewState(
> 			countryLocalIdType = countryLocalIdTypeEnumNavType.get(savedStateHandle, "countryLocalIdType") ?: throw RuntimeException("'countryLocalIdType' argument is mandatory, but was not present!"),
> 			countryLocalId = DestinationsStringNavType.get(savedStateHandle, "countryLocalId") ?: throw RuntimeException("'countryLocalId' argument is mandatory, but was not present!"),  // <======= Unit tests fail here
> 			checkBoxValue = DestinationsBooleanNavType.get(savedStateHandle, "checkBoxValue") ?: throw RuntimeException("'checkBoxValue' argument is not mandatory and not nullable but was not present!"),
> 	    )
> 	}
> ```
> 
> maybe should generate something like this?
> 
> ```kotlin
> 	override fun argsFrom(savedStateHandle: SavedStateHandle): ViewState {
> 	    return ViewState(
> 			countryLocalIdType = savedStateHandle["countryLocalIdType"] ?: throw RuntimeException("'countryLocalIdType' argument is mandatory, but was not present!"),
> 			countryLocalId = savedStateHandle["countryLocalId"] ?: throw RuntimeException("'countryLocalId' argument is mandatory, but was not present!"),
> 			checkBoxValue = savedStateHandle["checkBoxValue"] ?: throw RuntimeException("'checkBoxValue' argument is not mandatory and not nullable but was not present!"),
> 	    )
> 	}
> ```
> 
> or maybe making `DestinationsStringNavType` a class instead of an object? the generated
> 
> ```
> val countryLocalIdTypeEnumNavType = DestinationsEnumNavType(CountryLocalIdType::class.java)
> ```
> 
> seems to work fine, also `DestinationsBooleanNavType`.

I just realised that `DestinationsStringNavType` uses
```kotlin
import android.net.Uri
import android.os.Bundle
....
internal val DECODED_EMPTY_STRING: String = Uri.decode(ENCODED_EMPTY_STRING)
...
private val DECODED_DEFAULT_VALUE_STRING_PREFIX: String = Uri.decode(ENCODED_DEFAULT_VALUE_STRING_PREFIX)
```
that might be the reason we are not able to access it in the unit tests.

**Comment by raamcosta** [comment]
That is the reason, yes.

I can make it a lazy initialized field, and if the tests don't need it (it seems like that is your case) then that would work.
But I still need to think more about it since what if the tests do need it? 🤔 

I'll reopen this to see if I can come up with a better solution. Thanks @epool

**Comment by raamcosta** [comment]
Until then, use assited injection and pass the arguments to the ViewModel (this is much better from a clean code perspective in my opinion).

If not, you can set the args from the outside with some setter.

**Comment by raamcosta** [comment]
This should be fixed guys @epool @luanbarbosa-sanoma please test version 1.x.20 and let me know!
