### ISSUE TITLE
How do I hold a global DestinationsNavigator object？

### ISSUE THREAD

**Issue by xiayuyu** [raamcosta/compose-destinations#211]
How do I hold a global DestinationsNavigator object, for example in the network Request Uniform error handling class, and jump to the specified screen if there is an error

**Comment by raamcosta** [comment]
Hi 👋 

Same as with official compose navigation, it’s not possible.

What you can do is make some kind of publisher subscriber pattern (like a flow for example) in a global navigator and then collect those events in the same place as the NavHost and navigate with the NavController.

let me know if this helped 🙂
