### ISSUE TITLE
Improvements of multi module configuration modes

### ISSUE THREAD

**Issue by raamcosta** [raamcosta/compose-destinations#216]
# 🚧 TBD given comments from community like this https://github.com/raamcosta/compose-destinations/issues/216#issuecomment-1221579373

<details>
  <summary>OLD proposal</summary>
  
# Proposal

I am considering removing both "navgraphs" and "destinations" modes from the library. For anyone who doesn't know what these are, read about them here:
https://composedestinations.rafaelcosta.xyz/codegenconfigs#multi-module-configs

This would be done in the incoming major version 2.0 and the plan is to support 1.x version for some time to let people move to 2.0 at their own pace (Compose and Navigation updates and bug fixes - only this, new features will only be added to 2.0). 

This issue is here so I can present my decision beforehand to the community and give users of the feature a chance to tell me why I shouldn't do this. 
I also totally appreciate it if you let me know in the comments if you agree with my reasonings.

# Reasonings

These modes were introduced as a tentative to help multi-module applications define their screens directly inside each feature module. The issue with it is that they ultimately require a lot of manual code to be written and developers lose a lot of the benefits of using Compose Destinations. Also, I don't think the end result is better than just having a navigation module (same that would call `DestinationsNavHost` even with these configs) that defines all the destinations and navigation graphs and just calls normal Composables (i.e, not annotated with `@Destination`) of the feature modules.
I would say that the amount of code you have to write is actually less and Compose Destinations can help you a lot more since it can infer the structure around the destinations and their navigation graphs.
It also puts a lot of strain on the future development of Compose Destinations (which I already have been feeling) because these configurations change the flow of generating the classes in the very core and it's very difficult to always keep in mind with all changes I do how it may affect these modes.

> **Note**: **I will keep the "generateNavGraphs" config still. This can somewhat be used for achieving the same goal as these modes. You can disable navigation graph to be generated on all feature modules and then gather all of them in the central nav module and call DestinationsNavHost. 
I don't really recommend this approach though, "generateNavGraphs" is here more for people who don't want to use DestinationsNavHost and they just want the type safety of the library and call the normal NavHosts.**

# Pros of removing them

- Easier development of the library going further
- Arguably better end result for all code bases that migrate to the one navigation module approach (this is also what Jetpack Compose Navigation advocates for which we ultimately are very dependent on and have very similar setup to it)
- Compose Destinations can do more for the developers if all the generation happens in a single module and it doesn't really become a "monolith", the actual UI can still be composed in different modules. In regards of coupling, it's actually better because navigation is not tied to all your feature modules

# Cons of removing them

-  Migration for active users of the feature. By now, I hope you guys know that I am super helpful to anyone who asks me for help and I will be willing to help everyone with the transition. I am also planning to do this migration myself on the two repositories I provided as examples of this feature (https://github.com/raamcosta/tivi and https://github.com/raamcosta/CalorieTracker). This way, they will be examples of this migration.
I want to avoid as much as possible to have breaking changes, but I also still for now want the freedom to do them if I really feel it will be better in the long run. Please stay with me through these discovery times 🙏 😅 

Honestly, I can't see any other benefit of keeping them. But please let me know in the comments if you use this feature and you like it and why. 

# Some code examples

### Before:

<details>
  <summary> 👉 Click me</summary>
  
```kotlin
// 👉 feature module "A"

// 👇 here to allow this module to navigate to where it needs to without knowing the other modules
interface ModuleANavigator {

    fun navigateUp()

    fun navigateToScreenX()

    //....
}

@Destination
@Composable
fun MyScreenA(
    moduleANavigator: ModuleANavigator
) {
    //...
}


// 👉 navigation module

object RootNavGraph: NavGraphSpec {

    val destinations = listOf(
        MyScreenADestination,
        //.... other destinations from other modules
    )

    val startDestination = MyScreenADestination

    // ...
}

// ...

DestinationsNavHost(
    navGraph = RootNavGraph,
    dependencyContainerBuilder = {
        dependency(instanceOfModuleANavigator) // 👈 we could have a single navigator that would implement all interfaces of the different modules, but still a lot of manual work
    }
)
```

</details>

### After:

<details>
  <summary> 👉 Click me</summary>

```kotlin
// 👉 feature module A

@Composable
fun MyScreenAContent(
    navigateUp: () -> Unit,
    navigateToScreenX: () -> Unit
) {
    // ...
}

// 👉 navigation module

// RootGraphDestinations.kt // 👈 since we have very small Destinations code, it's totally fine to group them by nav graph in a single // file for example

@Destination
@Composable
fun MyScreenA(
    navigator: DestinationsNavigator
) {
    MyScreenAContent(
        navigateUp = { navigator.navigateUp() },
        navigateToScreenX = { navigator.navigate(ScreenXDestination) }
    )
}

// ...

DestinationsNavHost(
   navGraph = NavGraphs.root
)

```

</details>

> **Warning:** just example code, I actually wrote all of that directly in Github, I may be missing some details, but I think they probably aren't important enough in this discussion. But if you see a detail missing that might be relevant, let me know in the comments 🙂 
> To note that I removed the interface in the "After" example, but you can keep it too. It will make the migration easier to do and there is nothing wrong with passing an interface impl with a bunch of methods to navigate, vs a lambda.

</details>

**Comment by Nek-12** [comment]
Although this change looks fine, I actually don't feel like performing this kind of large-scale refactoring in my project, first of all.

I really like the way destinations are defined in the feature module as they are right now. 
The issue with the code above is that I actually already do this kind of thing in my own repository, i.e:

My composables are defined in the feature module, annotated as @Destination and look like this:

```
@Composable
@Destination
internal fun OverviewScreen(
    ritualId: Long, // <- nav param
    navigator: AppNavigator, // <- huge interface defined in the navigation module that has functions to navigate to each screen in the app (will be split by nav graph in the future)
) = MVIComposable(getViewModel<OverviewViewModel>()) { state -> 

    // some MVI event handling
    
    OverviewScreenContent(state)
}
```
The problem with migrating the block of code above is, there are 8 (!) navigation events in the screen above. I'd need to add lambdas to navigate to all of those. This essentially means "defining" a "function" each time I'd like to navigate to the same destination. Basically like the approach with yours "before" example, but on a large scale. 9+ parameters of a function seems a bit over the top for me. (also what about the stability (`@Stable`) of the destination and performance impacts?

I also use some utility stuff that does not really apply to the usecase above, like using AppNavigator to determine the `canGoBack` property in a specific screen. Again, using your approach would mean defining this property in every single composable. 

So all that stuff above means that the refactoring for my app would be quite... Extensive. From adding another layer to my composable screen layout (`OverviewScreenContentContent` xD (I know, I'll use proper naming)) to shuffling a bunch of stuff around. 

What I suggest is deprecating these values for a reasonable time. I might not get around to that kind of refactoring in a couple of months, and there may be people with larger projects out there.

**Comment by raamcosta** [comment]
Hi @Nek-12 ! 👋 

Thank you so much for taking the time to write your feedback, it is really really appreciated!

Let me counter-argument some of your points, but don't take this like "ok he is set on doing this, no need to counter argument again" - I want you to tell me why I am wrong in these 🙂 

> The problem with migrating the block of code above is, there are 8 (!) navigation events in the screen above. I'd need to add lambdas to navigate to all of those. This essentially means "defining" a "function" each time I'd like to navigate to the same destination. Basically like the approach with yours "before" example, but on a large scale. 9+ parameters of a function seems a bit over the top for me. (also what about the stability (@Stable) of the destination and performance impacts?

If you like the interface approach vs the lambdas, you can still use that. The only difference is where the `@Destination` is used. Your feature module can ask for whatever type that you can provide (like f.e an interface to navigate) and when you call the feature module's Composable, you just pass that along.
Sorry for misleading you with my examples, I'll add a note explaining this in the proposal.

> So all that stuff above means that the refactoring for my app would be quite... Extensive. From adding another layer to my composable screen layout (OverviewScreenContentContent xD (I know, I'll use proper naming)) to shuffling a bunch of stuff around.

The idea is that you still only need 2 Composables, the Destination and the Content one. So you'd just move your Screen example to the navigation module. I feel like this further separates from Android specific code, to a "Content Composable" that just receives state and lambdas (or interfaces) for actions. Having that separation in the same place as the module separation has a lot of benefits, for example maybe in your case your feature modules won't need to depend all on the MVI framework you're using.
I do recognize how for some this won't be possible right away as **this would be the actual migration effort** (maybe it's your case), but at that point yes, you would have 1 Destination, 1 Setup Composable inside the feature module and the actual Content Composable (also in feature module ofc).

I believe you can make this migration with minimal changes (if you don't do the MVI migration as well. Like I outlined above in bold, that would probably be way harder).

> What I suggest is deprecating these values for a reasonable time. I might not get around to that kind of refactoring in a couple of months, and there may be people with larger projects out there.

Again, I'll add a note to the proposals about this. The idea is that these will be a part of a new major version that would co-exist with 1.x for some time. So technically, no one is forced to move to v2 right away. New features will only exist in v2, but I plan to still make new releases in v1 for stuff like new versions of navigation or Compose.

**Comment by Nek-12** [comment]
I can't use the screen example to the navigation module because it has a bunch of logic inside for handling MVI Actions. Feature modules can't not depend on the framework since it permeates the viewmodel layer too. But the navigation module can __not__ depend on it, I do agree here. If I add another wrapper though. 

Am I right in my assumption that you can't deprecate these modes without removing them because some internal improvements you mentioned are not possible with this functionality present?

**Comment by raamcosta** [comment]
> Am I right in my assumption that you can't deprecate these modes without removing them because some internal improvements you mentioned are not possible with this functionality present?

The issue with actual deprecation is that since these are configs in gradle, the IDE won't help developers understand that they are deprecated. 
Also compared to just releasing a new major version and giving people time to migrate, I don't think is worse for anyone. It's basically the same thing I believe 😄 

> I'm also confused about the naming. Do you have a proper name for the destination composable (*Screen in my example) if the "Screen" name is already taken?

Hmm.. I guess you can call *Screen in the nav module, *Setup and *Content for example. I don't know naming is hard ahah. Basically something that conveys 1st is NavigationDestination, 2nd is the Screen Setup, and 3rd is the actual screen Content.

**Comment by Nek-12** [comment]
> Also compared to just releasing a new major version and giving people time to migrate, I don't think is worse for anyone. It's basically the same thing I believe 😄

if you believe you won't be releasing any bug fixes or other improvements until most people migrate, then that would be possible. Regarding gradle, we could just print a message to the build log.

I guess we can call what we call *ScreenContent a "*ScreenLayout" instead

**Comment by ianhanniballake** [comment]
> Arguably better end result for all code bases that migrate to the one navigation module approach (this is also what Jetpack Compose Navigation advocates for which we ultimately are very dependent on and have very similar setup to it)

This is absolutely **not** what Navigation Compose advocates for. In fact, it is the exact opposite, where each module is encouraged to define its own [nested navigation graph](https://developer.android.com/jetpack/compose/navigation#nested-nav):

> It is strongly recommended that you split your navigation graph into multiple methods as the graph grows in size. **This also allows multiple modules to contribute their own navigation graphs.**

While it is true that at some point you combine the graphs from various modules together into a single combined graph (generally at the construction time of the `NavHost`), a key part of scaling your application into multiple modules is to have each module control its own set of destinations, providing the right level of encapsulation to not expose internal implementation details (i.e., no module outside of the `login` module should have to know how many screens are involved in user registration).

**Comment by Zhuinden** [comment]
> Arguably better end result for all code bases that migrate to the one navigation module approach (this is also what Jetpack Compose Navigation advocates for which we ultimately are very dependent on and have very similar setup to it)

No, each module should expose its own `<navigation` which is then all `<include`ed together in the `:app` root parent, allowing a hierarchy of destinations in a graph.

I didn't read everything, might do later.

**Comment by raamcosta** [comment]
Interesting I may have been too influenced by Chris Bane's tivi project I guess 😅 
But now that I think of it, nowinandroid uses the approach you guys are saying.

I will rethink this then, maybe the answer is to keep only the "navgraphs" mode and delete the other, or maybe actually keep both. Or maybe a 3rd option would be to improve them even more somehow, as one of the reasons I have is also how they're a bit of work to whoever uses them atm.

Thanks @ianhanniballake and @Zhuinden! Glad I had your opinions 🙏

**Comment by harry248** [comment]
The encapsulation the "navgraphs" mode provides is nice and important but cross-module navigation is pretty hard. It would be nice if we could flag a @Destination as public and have such destinations then be aggregated within a specific module that all feature modules depend on. Is this even possible? 😄

**Comment by Nek-12** [comment]
One benefit I'm thinking of while using the approach described by @raamcosta is that KSP will only be needed in a single navigation module, and we can remove both the dependency and ksp task from all the feature branches, thus reducing build time. 
Not sure about this though, because now a ksp-heavy task will be compiled on a single thread __before__ all the feature modules will be able to compile. Although, the navigation module is still included in most feature branches, it's just that it will be a little more heavy on time to compile.
