### ISSUE TITLE
Annotations not imported in the generated files

### ISSUE THREAD

**Issue by cloneconf** [raamcosta/compose-destinations#22]
Hello @raamcosta !

I want to use some experimental things in compose and they requires some annotations.
For example here i am using `ListItem` which is experminal currently:
```kotlin
@ExperimentalMaterialApi
@Destination
@Composable
fun SimpleScreen() {
    ListItem { Text("Hello") }
}
```

When i try to build the app, i get an error in the generated `NavGraphs` file: `Unresolved reference: ExperimentalMaterialApi` like this:

![Screenshot_2021-12-05_23-49-45](https://user-images.githubusercontent.com/88058138/144767029-6e5b9017-d64a-4e11-9966-4881c0220c30.png)

And when i import it, and try again, it regenerate the same file and recreate the same issue.
The build stuck there...

I guess that the code generator doesn't import these annoations.

Is there a work around or am i doing it wrong?

Finally, i really enjoy the library, great work :)

**Comment by raamcosta** [comment]
Hi @cloneconf 👋 

Thanks for reporting. I will fix this for the next version!
Meanwhile, you can opt-in in the Composable to make this go away.
You can do this, like this:

```kotlin
@OptIn(ExperimentalMaterialApi::class)
@Destination
@Composable
fun SimpleScreen() {
    ListItem { Text("Hello") }
}
```

**Comment by raamcosta** [comment]
Even after my fix, you probably want to opt in anyway, otherwise you'll have to add the Experimental annotation in a lot of places.

Thank you again for reporting and the kind words 🙂  👍

**Comment by cloneconf** [comment]
Thank you @raamcosta !

> I will fix this for the next version!

I will be waiting for it ! :)

>  Meanwhile, you can opt-in in the Composable to make this go away.
 
 It works :smiley:  

> you probably want to opt in anyway, otherwise you'll have to add the Experimental annotation in a lot of places.

Seems right, thanks for the advice!

And yeah did mistype the example, it should be:
```kotlin
...
ListItem(
   text = { Text("Hlll") }
)
...
```

Thanks you again :smile:
