### ISSUE TITLE
How to dynamically choose Destination?

### ISSUE THREAD

**Issue by Jalson1982** [raamcosta/compose-destinations#220]
Hello. I am trying to implement function that will base on string provided return me destination. Here how it looks like very basic for now:

`fun matchNavByString(nav:String): DirectionDestination {
    return when(nav) {
        //"Community" -> PostGalleryViewDestination
        "Community1" -> CommunityFeedDestination
        "Community2" -> ProfileDestination
        else -> CommunityFeedDestination
    }
}`

Problem with this is that return type DirectionDestination does not work if Destination expect navigation params. Any maybe idea what type I can return ?

**Comment by raamcosta** [comment]
Of course! You can return just Destination 🙂

DirectionDestination is a subset that contains only those that don’t need nav args
