### ISSUE TITLE
Get full url of DeepLink 

### ISSUE THREAD

**Issue by pboulch** [raamcosta/compose-destinations#222]
Hi ! A small question :) 

I have a composable with two deeplink : 

```
@Destination(
    deepLinks = [
        DeepLink(uriPattern = "https://domain1.com/?email={email}&from={from}"),
        DeepLink(uriPattern = "https://domain2.com/home?token={token}&urlRedirection={urlRedirection}")
    ]
)
@Composable
fun HandleDeepLinkView(navigator: DestinationsNavigator,
                       token: String = "",
                       urlRedirection: String = "",
                       email: String = "",
                       from: String = "",
                       c: String = "",
                       b: String = "",
                       uuid: String = ""
                       ) {
// Content of composable : a loader

}
```

And I would like to have the full URL in the composable so I can do different processing depending on the URL. Is it possible ? 
Thanks !

**Comment by raamcosta** [comment]
Hi @pboulch !

This is more of a question for official jetpack compose navigation, as this has very little to do with Compose Destinations.
From what I know, you'll only get the arguments here, but I think you might be able to intercept the intent in the activity (which btw seems like a better place to do this sort of thing that you're trying to do -  deep links are better suited to direct users to some screen directly).

I'll close, hope it helps somewhat and that you find your answer 🙂
