### ISSUE TITLE
Navigation graphs information in one place with links to screen Composables and generated Classes

### ISSUE THREAD

**Issue by raamcosta** [raamcosta/compose-destinations#223]
# Proposal

Generate a file where all information about navigation graphs and their destinations and nested graphs will be available as well as linking to the screen Composables and generated classes.

# Context

A common negative point some people have expressed about Compose Destinations is how it is harder to get a glance of the whole navigation graph(s).
My answer to this has been that in single module mode (the default and [the only one we want on v2](https://github.com/raamcosta/compose-destinations/issues/216), there is a generated object where we can see the nav graphs and their destinations.
Currently that looks something like this:

```kotlin
object NavGraphs {

    val profileSettings = NavGraph(
        route = "profile_settings",
        startRoute = ProfileSettingsScreenDestination,
        destinations = listOf(
            ProfileSettingsScreenDestination
        )
    )

    val settings = NavGraph(
        route = "settings",
        startRoute = SettingsScreenDestination,
        destinations = listOf(
            SettingsScreenDestination,
            ThemeSettingsDestination
        ),
	nestedNavGraphs = listOf(
	    profileSettings
	)
    )

    val root = NavGraph(
        route = "root",
        startRoute = GreetingScreenDestination,
        destinations = listOf(
            FeedDestination,
	    GoToProfileConfirmationDestination,
	    TestScreenDestination,
	    TestScreen2Destination,
	    GreetingScreenDestination,
	    ProfileScreenDestination
        ),
	nestedNavGraphs = listOf(
	    settings
	)
    )
}
```

This is not ideal for some reasons:
- It's hard to see the hierarchy tree of the graphs. In the above example only after some time we can see that "root" is at the top, then "settings" is a child and "settings" as a "profileSettings" as its own child;
- It's not easy to navigate from here to the screen Composables;
- There is still some info that is not necessarily needed. We'd like this to be as lean as possible only with graphs and their destinations and nested graphs.

Besides, with the task #217 each nav graph will be its own object type, so the most we could do here would be pointing to the object, and so we'd have even more scattered information. This was actually what made me think it was time to come up with a better solution here.

# Possible solutions

In pursue of the best solution to reach the goal outlined in "Proposal", I've been looking at some alternatives and approaches which could also complement each other.

## 1. Kotlin DSL with kdocs for screen Composable linking

This was the first thing I came up with. We would generate some Kotlin code using some DSL that didn't actually ever run, all it would do is document the nav graphs while linking to the real generated classes.
This would look something like:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/80427734/185745114-7c789025-285b-40a0-9b9c-fa4186b153c3.png">

This lets developers see their navigation graphs and destinations while also linking to the corresponding Composable via the documentation linking elements in the right. The `@Start` annotation marks the start destination (or graph) that is the start of the parent graph.

This feels a bit weird as this code doesn't actually run or do anything, but it does serve the purpose we wanted it to. I don't think the code would be a part of release builds since nothing calls it, proguard probably scraps it (if someone can confirm, that's awesome), but even if that's not the case, I don't think it's ever an issue 🤔 but let me know if I'm wrong here.

## 2. Formatted kdocs with links to generated classes and screen Composables

This could look something like:

<img width="879" alt="image (1)" src="https://user-images.githubusercontent.com/80427734/185745358-121e75a0-607b-4ac7-a9a6-9dbde0539189.png">

I don't know if this would be the final formating. I accept suggestions on how I could improve it 😅 
The advantage here is that we're not generating code, but at least in my eye it looks a bit more cluttered. Also we can put the screen Composable link first which is probably the more important information to the developer looking at this (he probably doesn't care too much about the generated Destinations).

Both of the above approaches would work when inside the IDE. Anytime the developer wants to check how the nav graph is looking, they can open this file and then easily navigate to the screen composables he wants to.

## 3. [Mermaid flowchart](https://mermaid-js.github.io/mermaid/#/flowchart)

This would be more of a complementary document since it isn't really helpful inside the IDE since no rendering(at least that I know of, but maybe there is some plugin?) and no links to the wanted Composables and classes, but it is a document that some teams might want to include in their git repositories. This way they can check for example inside the PRs how the navgraphs look like, especially with Github which now renders these graphs, example:

```mermaid
flowchart LR
root([Root]) -- start --- greeting
root([Root]) --- settings([Settings]) -- start --- settings_main
settings([Settings]) --- settings_profile

click root "https://github.com/raamcosta/compose-destinations" "Open this in a new tab" _blank

classDef navgraph fill:#f96;
class root,settings navgraph;
```

Inside Github repos, we could link the destinations to the corresponding Composable screen files as well.

> The ideal solution would probably be an Android Studio plugin that would render the mermaid tree and let users click on nodes to navigate to the corresponding screen Composable. This way we had a single file for both IDE and github repo.
If someone has a good idea of how to do this, it would be a good interesting side project 😄 

**I also accept other suggestions here, these are only the options I thought about! So let me know in the comments, any feedback is appreciated!**

**Comment by alexzaitsev** [comment]
I have several subgraphs with subgraphs and to distinguish them I have to add prefixes now. 

Like:
* root
    * onboarding
         * createWallet
         * connectWallet
    * settings
        * createWallet
        * importWallet
 
So it would be super useful to see all of the graphs in one place because now I have to write side documentation for other developers. 

Another point that is not so clear but I faced it is same screens on the different sub graphs. Now I have to add prefixes to make it impossible to mix same screens from different graphs. 

Example: 
`OnboardingCreateWalletProtectScreen` -> generates `OnboardingCreateWalletProtectScreenDestination`
`OnboardingConnectWalletProtectScreen` -> generates `OnboardingConnectWalletProtectScreenDestination`

So I have to use prefixes to prevent accidental usage of the same screen on another nav graph. It would be great to introduce some concept to make destination private to specific nav graph.
