### ISSUE TITLE
Screen orientation crashes navController

### ISSUE THREAD

**Issue by getobazooka** [raamcosta/compose-destinations#224]
As soon as the device orientation changes, the navController crashes the app.
`
class MainActivity : ComponentActivity() {

    private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "settings")

    @OptIn(ExperimentalAnimationApi::class, ExperimentalMaterialNavigationApi::class)
    @SuppressLint("UnusedMaterialScaffoldPaddingParameter")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //dataModel = DataModel(application)

        installSplashScreen().apply {
            setKeepOnScreenCondition {
                AppViewModel.instance.preferences.isLoading.value
            }

        }
        setContent {

            val systemUiController: SystemUiController = rememberSystemUiController()
            val scope = rememberCoroutineScope()
            val navController = rememberAnimatedNavController()

            val state: ScaffoldState = rememberScaffoldState(
                snackbarHostState = SnackbarHostState()
            )

            val animationSpeed = AppViewModel.instance.animationSpeed
            val context = LocalContext.current

            AppViewModel.instance.initialize(
                this,
                context,
                scope,
                dataStore = dataStore,
                navController = navController,
                systemUiController = systemUiController
            )

            SSTSurgeryTheme {
                CompositionLocalProvider(LocalLayoutDirection provides if (AppViewModel.instance.rightToLeft) LayoutDirection.Rtl else LayoutDirection.Ltr) {
                    //every time the app start we set the locale here, because if we only apply it in language screen than it is skippable
                  SetLanguage(language = AppViewModel.instance.language, context)
                   // updateConfig(this)
                    BoxWithConstraints {
                        val width = constraints.maxWidth
                        val navHostEngine = rememberAnimatedNavHostEngine(

                            rootDefaultAnimations =

                            navAnimationSpecs(width, animationSpeed)

                        )

                        Surface(
                            modifier = Modifier.fillMaxSize(),
                            color = MaterialTheme.colors.background
                        ) {

                            Scaffold(
                                scaffoldState = state,
                                topBar = {
                                    ScaffoldTobAppBar(navController)
                                },
                                snackbarHost = {
                                    if (AppViewModel.instance.snacker.toggle) {
                                        TransientSnackbar(
                                            snackbarState = state.snackbarHostState,
                                            snakcbarMessage = AppViewModel.instance.snacker.message,
                                            onAction = {
                                                AppViewModel.instance.snacker.toggle = false
                                            },
                                            onDismiss = {
                                                AppViewModel.instance.snacker.toggle = false
                                            },
                                        )
                                    }
                                },
                                bottomBar = {
                                    BuildBottomNavigator(
                                        navController = navController,
                                    )
                                }
                            ) {

                                Box(
                                    modifier = Modifier
                                        .padding(it)
                                        .background(WhiteSmoke)
                                ) {

                                    Column {

                                        DestinationsNavHost(
                                            navGraph = NavGraphs.root,
                                            navController = navController,
                                            engine = navHostEngine,
                                            dependenciesContainerBuilder = {
                                            },
                                            startRoute = StartScreenDestination()
                                        ) {

                                        }
                                    }

                                }

                            }

                        }
                    }
                }
            }
        }
    }
}`

and this is the error

`

    java.lang.IllegalArgumentException: No destination with ID 2027737583 is on the NavController's back stack. The current destination is Destination(0x5a224613) route=no_profile_screen
        at androidx.navigation.NavController.getBackStackEntry(NavController.kt:2209)
        at androidx.navigation.NavController.onGraphCreated(NavController.kt:1142)
        at androidx.navigation.NavController.setGraph(NavController.kt:1086)
        at androidx.navigation.NavController.setGraph(NavController.kt:100)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:146)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:88)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.NavHost(AnimatedNavHostEngine.kt:83)
        at com.ramcosta.composedestinations.DestinationsNavHostKt.DestinationsNavHost(DestinationsNavHost.kt:71)
        at com.akar.sstsurgery.MainActivity$onCreate$2$1$1$1$1$4.invoke(MainActivity.kt:173)
        at com.akar.sstsurgery.MainActivity$onCreate$2$1$1$1$1$4.invoke(MainActivity.kt:146)
`

Unfortunately after a long search could not find a way to fix this issue.
Is there a way to fix this?

**Comment by raamcosta** [comment]
Hi 👋 

This is not directly related with compose destinations, it’s a behaviour we inherit from official compose navigation which we use under the hood. 
Anyway, it seems to me that you’re misusing the library. You cannot pass the NavController to any component that outlives the activity. That is probably why you’re having this error.

Let me know if this helped down below!

**Comment by getobazooka** [comment]
Thanks. 
It definitely resolved the issue.
My idea was that passing the declared navigator in the Activity to a singleton class (AppviewModel) would ease the navigation overall inside the app.
This had one major benefit: Anywhere inside the app I can navigate to any destination I want.
But it caused to major issues: 
1- Whenever the device orientation changed the app would crash and causing this error:
 No destination with ID <>is on the NavController's back stack. The current destination is Destination(<>) route=<>
 
 2- The live edit feature (that was added to Android Studio Electric Eel Build) would confuse the navigation when a simple:
 Meaning: when a change made, the live edit feature would bring back the navigator to the first screen. I thought this a very strange behavior and maybe it was a bug. 
 
 But thanks to your explanation, both issues were  resolved.

**Comment by getobazooka** [comment]
Also, I have a suggestion/feature request for this library:
Is it possible to make the Destination_Navigator available everywhere for any composable to use it?

I mean, every time I want to navigate via a composable, not the one with @Destination, I have to pass the destination navigator.
I think it would much easier to expose destination navigator to every composable without passing it via  a parameter.


Anyhow, I am very grateful for your help. We very much appreciate your hard work on the library.

**Comment by raamcosta** [comment]
It’s not possible. The library calls the one annotated with destination.

You can use composition local to get it though with a bit of setup. I don’t really recommend it though from a perspective of clean architecture and code, it’s just better if your complements have explicit dependencies.

**Comment by getobazooka** [comment]
Thanks.
I'll research it.
