### ISSUE TITLE
Preview an screen with arguments

### ISSUE THREAD

**Issue by rogersixtemia** [raamcosta/compose-destinations#225]
I'm trying to preview screen with a navArgsDelegate but it's not working since viewModel's navArgs method is not finding username argument

`java.lang.RuntimeException: 'username' argument is mandatory, but was not present!`

So I tried that but still don't manage to get it work.
```
@Destination(
    style = LeftRightTransition::class,
    navArgsDelegate = UserArgs::class
)
@Composable
fun SelectorScreen(
    navigator: DestinationsNavigator,
    viewModel: SelectorViewModel = viewModel()
) {
/// More stuff here
}

@Preview
@Composable
fun SelectorScreenPreview() {
    GMTheme {
        val savedStateHandle = SavedStateHandle()
        savedStateHandle["username"] = "X"
        savedStateHandle["password"] = "X"
        val viewModel = SelectorViewModel(savedStateHandle)
        SelectorScreen(
            EmptyDestinationsNavigator,
            viewModel
        )
    }
}
```
Is there a solution for that use case?

Thanks in advance, 
Roger R.

P.S: this library is pretty cool!

**Comment by raamcosta** [comment]
Hi 👋 

Yeah, what you should do here is to instead preview an inner Content (we usually call it) Composable that just receives state and lambdas.
So your screen composable simply takes viewModel and observes the state on it, then calls that other Composable.
And then inside Preview you call that one instead!

let me know if this works for you!

**Comment by rogersixtemia** [comment]
Hello Rafael,
Thanks for the answer, is there a way to avoid extracting content as a function? If there is not I think It will be useful as an enchantment to find a way to set this info in preview mode. I was specting that savedStateHandle.navArgs() got the values from savedStateHandle so can be a way to put them into.

Thanks!

**Comment by rogersixtemia** [comment]
Fixed, is working now, it was a problem of my cache...

**Comment by rogersixtemia** [comment]
As long as I'm doing that on the preview they work as initial values of the screen preview, maybe with more complex values might be a problem because the generated Destinations will be structured in another way

**Comment by raamcosta** [comment]
Exactly, so it’s not a good habit to get into 😛

Previewing the composable with no dependencies on navigation or any Android construct (like ViewModel) is the better practice here 🙂
