### ISSUE TITLE
Template Generation Bug in ParcelableArrayListNavTypeTemplate

### ISSUE THREAD

**Issue by Windisch94** [raamcosta/compose-destinations#226]
Hello, just found out that you have a small typo in ParcelableArrayListNavTypeTemplate line 58:
`                "[" + value.joinToString(encodedComma) { serializer.toRouteString(it) } + ]"`

it ends in a compilation error, so it is currently not possible to use an ArrayList with a Parcelable as a destination argument.
Please fix the missing ":
`                "[" + value.joinToString(encodedComma) { serializer.toRouteString(it) } + "]"`

**Comment by raamcosta** [comment]
Thanks for reporting and checking the root cause 👏

That probably took you some time!

Will fix it today still probably!

**Comment by raamcosta** [comment]
Fixed, will be in today's release. Sorry it took me way longer than expected.. these days have been crazy with time 😕
