### ISSUE TITLE
Allow @kotlinx.serialization.Serializable for Navigation Results

### ISSUE THREAD

**Issue by cvb941** [raamcosta/compose-destinations#235]
Kotlin's `@Serializable` types currently work as navigation arguments, but not for navigating back with a result using `ResultBackNavigator` and `ResultRecipient`.

Is it possible to add support for `@Serializable` there as well?

**Comment by petrstetka** [comment]
Hello @raamcosta, Is there any way I can help implement this? I would like to see a support for this, or rather I need it because without this kotlinx.serializable is not possible to fully use with this library and I don't want to resort to using parcelable or other serializers when the official kotlinx.serializatio is here with us today.

You wrote last this:
> kotlin("plugin.serialization")

> Hmmm I'd like to avoid this if possible. I don't known yet exactly how.. I'm guessing we can also generate the serializers like we do for navigation on the user's module and have them point to them by passing their instance or something like this.
> To be honest, if this is the only way, I'd rather not do it. I don't want to force this dependency on all users of the library. Maybe we could make this a separate dependency, but that also comes with additional overhead for all maintainers...

So do you have an idea how it should work and how to implement it?
From what I've seen in the code for resultRecipients / resultNavigator there is no generating the serializers now as in the case of navigation arguments, is that right?

**Comment by LukasAnda** [comment]
@raamcosta any updates on this please? It forces me to not to pass data back as originally intended but only by ID or serialize to String since I removed all Parcelable/serializable imports due to KMM

**Comment by ryanholden8** [comment]
+1 for this request. When reading the docs I thought this was already implemented but we get this error:

> com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Composable Screen, ResultDataModel: Result types must be one of: String, Long, Boolean, Float, Int, Parcelable, Serializable

I guess `Serializable` here is referring to `java.io.Serializable` ? I had to dive into the source code to figure that out.. I think `Serializable` referring to `@kotlinx.serialization.Serializable` would be a more natural conclusion for most Kotlin projects..

**Comment by ryanholden8** [comment]
Ah seems like `java.io.Serializable` vs `@kotlinx.serialization.Serializable` is a common mistake: https://github.com/raamcosta/compose-destinations/pull/266#issuecomment-1588719190

**Comment by whitescent** [comment]
Any updates on this? @raamcosta

**Comment by raamcosta** [comment]
Hi 👋 

No, this is not a priority for v2 at the moment.

**Comment by raamcosta** [comment]
No efforts done here so far.

Given this is for now an Android only library, I don’t think it’s a big deal, just mark the class as Java Serializable and move on (or Parcelable but that’s a bit more work I guess).

That said, I am working on KMP support and this will be needed for the feature to work, so it will probably force me to look at this again.

**Comment by raamcosta** [comment]
Good news!

As expected while adding KMP support, it made me look into this.

I already know how I'm going to make this work and it will be even better than allowing Kotlinx Serializable. Basically, any supported navigation argument type will also work in the back navigation case.

I do need quite some changes to make this happen, but I think the result will be pretty great!
Stay tuned!

**Comment by petrstetka** [comment]
@raamcosta That's great news. I look forward to it. Thank you

**Comment by raamcosta** [comment]
This is done, available on today's releases.

Check release notes for more info, but most likely you won't need to do anything special, just use it like you'd expect and it will work :)

**Comment by raamcosta** [comment]
Please let me know once you try it 🙏 

I'll be waiting for feedback!

**Comment by petrstetka** [comment]
@raamcosta Working well for me. Thank you man!
