### ISSUE TITLE
Implementation problem - help

### ISSUE THREAD

**Issue by ArleyPereira** [raamcosta/compose-destinations#236]
I discovered the library through **Philipp Lackner** channel and decided to use it in my project. After all the settings, I'm getting an error with the line of code

**Error code line**
DestinationsNavHost(navGraph = NavGraphs.root)

**Error code line - print**
https://prnt.sc/cq0hfnydErhK

compose_version = '1.1.0-beta01'
kotlin_version = ' 1.6.21'

```
kotlin {
    sourceSets {
        debug {
            kotlin.srcDir("build/generated/ksp/debug/kotlin")
        }
        release {
            kotlin.srcDir("build/generated/ksp/release/kotlin")
        }
    }
}
```

**plugin**
id 'com.google.devtools.ksp' version '1.6.21-1.0.6'

**implementation**
implementation 'io.github.raamcosta.compose-destinations:core:1.5.19-beta'
ksp 'io.github.raamcosta.compose-destinations:ksp:1.1.2-beta'

**Repository**
https://github.com/ArleyPereira/Social-Network---Compse

**Branch**
Compose-Destinations

**Comment by raamcosta** [comment]
Hi @ArleyPereira !


You need to use the same version for the dependencies of this library.
So both 1.5.19-beta in this case.

**Comment by raamcosta** [comment]
Let me know in a comment below if it worked 🙂

**Comment by ArleyPereira** [comment]
Thanks for the feedback. I made the adjustment and it didn't work.

Now I'm using version 1.5.19-beta and it still didn't work.

implementation 'io.github.raamcosta.compose-destinations:core:1.5.19-beta'
ksp 'io.github.raamcosta.compose-destinations:ksp:1.5.19-beta'

Error code line - Print
https://prnt.sc/MWdw4ZFRp9RF

Repository
https://github.com/ArleyPereira/Social-Network---Compse

Branch
Compose-Destinations

**Comment by ArleyPereira** [comment]
After many attempts I got it. Thanks a lot for the help. On your github it looks like you're developing a website to document the API, is that right?

**Comment by raamcosta** [comment]
Good! Yeah it’s live already. Main page of repository has the link for it 🙂
