### ISSUE TITLE
Sharing viewModel?

### ISSUE THREAD

**Issue by SerhiiOst** [raamcosta/compose-destinations#239]
Is there a posibility of sharing a viewModel between the activity and a destination? For example, when changing theme in a SettingsScreen destination to tell the activity to recompose the Theme composable with new colors, typography etc.

**Comment by raamcosta** [comment]
This is same as with normal compose navigation.
To share a VM with activity, just scope it to the activity by passing it to the `viewModel` or `hiltViewModel` method.

Check here:
https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels#share-viewmodels-between-multiple-destinations

where I tie the VM to the activity.
