### ISSUE TITLE
How to navigate from one NavGraph to another NavGraph?

### ISSUE THREAD

**Issue by Buggyy** [raamcosta/compose-destinations#240]
I made a custom NavGraph for the Sign Up process:

```
@RootNavGraph
@NavGraph()
annotation class SignUpNavGraph(
    val start: Boolean = false
)
```
Other composable destinations are making use of the RootNavGraph. I am trying to navigate from:

```
@SignUpNavGraph()
@Destination
@Composable
fun SignUpTwoScreen(
    navigator: DestinationsNavigator,
    scaffoldState: ScaffoldState
) ..
```
to

```
@Destination(
    navArgsDelegate = VerifyScreenNavArgs::class
)
@Composable
fun VerifyScreen(
    navigator: DestinationsNavigator,
    verifyEmailViewModel: VerifyEmailViewModel = hiltViewModel()
) ..
```

with

```
navigator: DestinationsNavigator
..
 navigator.navigate(
     VerifyScreenDestination(viewModel.email, viewModel.password)
 )
 navigator.popBackStack()
```

It seems that I cannot navigate from the SignUpTwoScreen to the VerifyScreen.

**Comment by raamcosta** [comment]
Hi @Buggyy 👋 

What exactly do you observe? Does it crash when navigate method is called?

**Comment by Buggyy** [comment]
Hi Rafael (Nice name),

Thanks for reaching out. There are two issues:

1. When navigating as stated in my orihinal question, it reaches the
correct switch case but nothing happens. Logging and other code works in
the switch case, except for the navigate part.

2. When navigating back though (using the back button) the app crashes
because it doesn't recognize the destination. Probably because it doesn't
know about that navgraph?

So two seperate issues here.

Hope you can help me out, really love the eas of your library. Thanks a lot!


Cheers,

Ragael

**Comment by raamcosta** [comment]
Hi @Buggyy !

I would need to check your full code repo to understand what you're doing wrong. This must be some kind of misconception, I believe.

Is this open source repository? Let me know below.

**Comment by Buggyy** [comment]
Due to company policy I may not share the repo. I will try to explain it as best as I can:

There is a submit button on _SignUpScreen_ composable which calls:
`viewModel.onEvent(SignUpScreenEvent.OnFinishClick)`

This gets picked up by the viewmodel:

```
@HiltViewModel
class SignUpViewModel @Inject constructor(
) : ViewModel() {

    private val _uiEvent = Channel<UiEvent>()
    val uiEvent = _uiEvent.receiveAsFlow()

    fun onEvent(event: SignUpScreenEvent) {
        when (event) {
            is SignUpScreenEvent.OnFinishClick -> {

               // code..

                 viewModelScope.launch {
                    _uiEvent.send(UiEvent.Success)
                }
} ...
```

After the business logic is executed, _SignUpScreen_ composable picks up the UiEvent.Success, which in turn, navigates to a different composable screen, that lives in a different NavGraph:

```
@SignUpNavGraph()
@Destination
@Composable
fun SignUpTwoScreen(
    navigator: DestinationsNavigator,
    scaffoldState: ScaffoldState,
    viewModel: SignUpViewModel
) {

    LaunchedEffect(key1 = true) {
        viewModel.uiEvent.collect { event ->
            when (event) {
                is UiEvent.Success -> {
                    // Any code put here works and gets reached
                 
                   // The navigate action below does nothing..
                    navigator.navigate(
                        VerifyScreenDestination(viewModel.email, viewModel.password)
                    )
                    navigator.popBackStack()
                }
...
```

Let me know if I need to elaborate more. Thanks a lot!

**Comment by Buggyy** [comment]
Hi Rafael,

Unfortunately I still haven't heard from you, is there any more information I can provide?

Cheers!
