### ISSUE TITLE
How to use 1 activity for 2 composable screen

### ISSUE THREAD

**Issue by nero002** [raamcosta/compose-destinations#241]
Is it possible to use 1 activity  and multiple screen if yes then how ?

**Comment by raamcosta** [comment]
Hi!

Just like any other Compose Navigation example you may find out there in the wild, or you can take a look at the sample app present in this repository.

You use @Destination annotated composables, and they are your screens, these will be placed inside the DestinationsNavHost.
Just for a brief explanation 🙂 

Let me know below if you checked the sample and it helped you.
