### ISSUE TITLE
TransactionTooLargeException when go to the background

### ISSUE THREAD

**Issue by PawelSobaszek** [raamcosta/compose-destinations#246]
Hi there 🙂

I have found some problem, when we try send big data, in my example it is very long string. When user go to the background it will get TransactionTooLargeException

`Fatal Exception: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2196356 bytes
       at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
       at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`
       
I have data class with Int, Booleands and Strings. In some cases, my data have very long string and in this case app Is crashes when go to the background.

`navigator.navigate(
                        LectureDetailsScreenDestination(
                            book = it as Book
                        )
                    )`

When I remove book argument inside LectureDetailsScreen my app is working well. Do you know guys how to get around this problem?

Problem exist only on older phones. (2/3+ years)

**Comment by PawelSobaszek** [comment]
I found a certain workaround. To Destination now I'm send object converted to ByteArray, than in VM/Composable I decode it  back to object.

Here is my Zipper

`fun Any.zipToByteArray(): ByteArray {
    val bos = ByteArrayOutputStream()
    GZIPOutputStream(bos).bufferedWriter(StandardCharsets.UTF_8).use { it.write(Gson().toJson(this)) }
    return bos.toByteArray()
}`

`inline fun <reified T> ByteArray.toObject() : T {
    val unzipped = GZIPInputStream(this.inputStream()).bufferedReader(StandardCharsets.UTF_8).use { it.readText() }
    val type = object : TypeToken<T>() {}.type
    return Gson().fromJson(unzipped, type)
}`

This does not solve the problem 100%, but it definitely reduces the number of devices it occurs on.

**Comment by raamcosta** [comment]
@PawelSobaszek Hi!

So this is not a bug. You cannot send big data as navigation arguments, that is an anti pattern and can lead to these sorts of issues. Android Binder has limited space and so passing only ids or very small data structures is very much recommended.

**Comment by raamcosta** [comment]
So in your case, I would find another way to structure screens so that you don't need to pass this as nav argument. Consider saving books (maybe you already do?) in a database, and pass only the book id.
