### ISSUE TITLE
Compose navigation interop with fragment

### ISSUE THREAD

**Issue by MakarenkoVlad** [raamcosta/compose-destinations#250]
do you plan to make support for fragments, so that you can smoothly transfer the project to compose

**Comment by raamcosta** [comment]
Hi @MakarenkoVlad 👋 

I'm not sure what exactly you mean, but there are already official ways to use Fragments with Compose inside and Compose with Fragments inside 🙂 

Take a look here:
https://developer.android.com/jetpack/compose/interop/interop-apis

**Comment by MakarenkoVlad** [comment]
It's okay, it happens to me and in ukrainian)) I meant are you planning to add support for navigation with fragments to your library for smooth transition from navigation on fragments to navigation on your library
