### ISSUE TITLE
Question: What would be the best way to handle screens with optional Bottom Bar Navigations?

### ISSUE THREAD

**Issue by hscissors** [raamcosta/compose-destinations#251]
Just wondering what you're thoughts are on handling an application where some screens have bottom bar navigations (let's say the `startRoute` of a child graph) but other screens in the same graph do not have a bottom nav? 

Is it possible to pass a bottom bar `scope` to destinations that would allow them to hide or show it?

**Comment by raamcosta** [comment]
Hi @hscissors 👋 

So bottom bar is not a part of any specific screen, so it doesn't make sense that screens control if bottom bar is shown or not. Bottom bar is a top-level "widget" that is shown below the actual screens, so the logic to show or hide it should also be there.

It's as easy as listening for the current destination and wrapping your bottom bar with `if(shouldShowBottomBar(currentDestination))`.

You can take a look at my sample in `SampleApp` file and you'll see I hide bottom and top bar in login screen as an example.
