### ISSUE TITLE
navigate from  a main home in a bottom navigation to a new screen with no bootom bar ?

### ISSUE THREAD

**Issue by yousefbeiruty** [raamcosta/compose-destinations#256]
Here i have a bottom nav bar and a home screen when i click on [an]([url]([url](url))) item i want the bottom navigation to disappear ?
![Screenshot_20221008_202344](https://user-images.githubusercontent.com/57751619/194719995-cea7e48b-e17d-4bd0-9b56-3abdc3dae125.png)
![Screenshot_20221008_202338](https://user-images.githubusercontent.com/57751619/194719998-35fe422f-8879-4611-bde2-b94db8e25d7f.png)

**Comment by raamcosta** [comment]
Hi @yousefbeiruty 

Check the sample app. I hide the bottom bar on the login screen.

Basically you need to listen for current destination changes and have a check on the scaffold to hide the bottom bar when on a particular destination (or a list of destinations).

**Comment by raamcosta** [comment]
Check this line and where that extension property is used:
https://github.com/raamcosta/compose-destinations/blob/main/sample/src/main/java/com/ramcosta/destinations/sample/SampleApp.kt#L60

**Comment by yousefbeiruty** [comment]
It works thank you a lot  @raamcosta .
