### ISSUE TITLE
Request for Wear OS (Compose) support

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [raamcosta/compose-destinations#264]
Hey @raamcosta 
Truly grateful for this library you've created. I use it in all my personal projects and even recommend it to my co-workers on a regular basis 🚀

This issue is created to request support of Wear OS for compose-destinations since Compose is [officially available for Wear OS](https://developer.android.com/training/wearables/compose) now ✅

From the perspective of a user, the code for Compose Wear Navigation is very similar to the Mobile Compose Navigation. A small example is as follows:

```
Dependency for compose mobile navigation:
implementation "androidx.navigation:navigation-compose:2.5.2"

Inside MainActivity.kt:
val navController = rememberNavController()

NavHost(controller = navController, startDestination = "home") {
    composable("home") { HomeScreen() }
    composable("details") { DetailsScreen() }
}
```

```
Dependency for compose wear OS navigation:
implementation "androidx.wear.compose:compose-navigation:1.1.0-alpha07"

Inside MainActivity.kt:
val navController = rememberSwipeDismissableNavController()

SwipeDismissableNavHost(navController = navController, startDestination = "home") {
    composable("home") { HomeScreen() }
    composable("details") { DetailsScreen() }
}
```

I'm not entirely sure how straightforward (or complex) it can be to internally give support for Compose for Wear OS, but it is a humble request that you please have a look into it and check its feasibility.

Thanks a bunch in advance 🙌🏻

**Comment by yschimke** [comment]
@raamcosta Is this a suitable item for someone to pickup? I'd like to use this library myself, but will hit the issue above.  But also I'd like to be able to use this library, but change the composable call.  The http://github.com/google/horologist/ has a scrollable function, that I'd like to use.  It sets up Crown scrolling (RSB), and TimeText scroll away etc.

**Comment by raamcosta** [comment]
Hey @yschimke! 

Sure, I'm totally ok with someone taking this. Just beware that this will require a lot of work, probably we need another dependency for wear os which depends on wear compose navigation dependency and does a similar thing to what we do for normal compose navigation.

**Comment by yschimke** [comment]
It seems very clean to implement.

https://github.com/raamcosta/compose-destinations/pull/322

There is a level above this such as coordinating the TimeText/PositionIndicator with the content of the screen, but that is complex enough that it should be a follow up.  This is functionality equivalent to normal Wear OS navigation usage.

**Comment by raamcosta** [comment]
Thanks to @yschimke this will be on maven central very soon! :)
