### ISSUE TITLE
ViewModel is recreated when activity is recreated

### ISSUE THREAD

**Issue by rogerr99s** [raamcosta/compose-destinations#270]
Hello!

I have an issue which I think doesn't happen in NavController (when implementing the hiltViewModel() in the NavHost). 

Enable developer mode and don't keep activities.

As far as I know if you don't keep the activities, activity is recreated and current state should be recovered. 
The problem is that the current destination is recovered since i'm still in SampleBScreenDestination but for some reason hiltViewModel() is not the same instance because init of the instance is recalled. As far as I know when I tried to implement.
Is there a way to fix that maybe implementing the other implementation which defines a NavHost?

Thank you in advance!

P.S:

```
setContent {
            SampleTheme {
                DestinationsNavHost(
                    navGraph = NavGraphs.root,
                    engine = rememberAnimatedNavHostEngine()
                )
            }
        }


SampleBScreen(
    navigator: DestinationsNavigator,
    viewModel: SampleBViewModel = hiltViewModel()
) {
//
}

@HiltViewModel
class SampleBViewModel @Inject (savedStateHandle : SavedStateHandle) : ViewModel()  {
  init {
    // Recalled
  }
}

```

**Comment by ianhanniballake** [comment]
> As far as I know if you don't keep the activities, activity is recreated and current state should be recovered.

ViewModel instances are destroyed, just like with process death and recreation (which is what 'Don't keep activities' lets you test). The only state that is retained is what is backed by saved instance state - i.e., the values in your `SavedStateHandle`.

This means that `init` is absolutely expected. The only signal that there is an issue with the library would be if you added something to your `SavedStateHandle` and it wasn't there when your activity was recreated.

**Comment by rogerr99s** [comment]
Ok! Thanks for the answer, so i had to check if my uiState backed in savedstatehandle is initialized in order to know if i'm in a recreation.

**Comment by raamcosta** [comment]
Thanks for helping here @ianhanniballake! 🙇
