### ISSUE TITLE
How to get DestinationsNavigator outside of generated Destination?

### ISSUE THREAD

**Issue by alexzaitsev** [raamcosta/compose-destinations#271]
Hello.
I need to find a way how to get DestinationsNavigator outside of generated Destination. 

**Why?**
I have a State<> that can be observed from any Composable. This State can emit something and I need to show AlertDialog in this case.
My AlertDialogs are implemented as Destinations. So I need DestinationsNavigator. How can I get it for example on `DefaultNavHost`'s level of view hierarchy?

```kotlin
@Composable
fun DefaultNavHost() {
    val bottomSheetNavigator = rememberBottomSheetNavigator()
    val navEngine = rememberDefaultNavHostEngine()
    val navController = navEngine.rememberNavController(bottomSheetNavigator)
    ModalBottomSheetLayout(
        bottomSheetNavigator = bottomSheetNavigator,
        sheetShape = defaultSheetShape,
        sheetBackgroundColor = ThemeColorBackground
    ) {
        DestinationsNavHost(
            navController = navController,
            navGraph = NavGraphs.root,
            engine = navEngine
        )
    }
}
```

**Comment by raamcosta** [comment]
You can just use the NavController you have there 🙂

There are extension functions that take Direction so you can use NavController in the same way as you use DestinationsNavigator.

**Comment by alexzaitsev** [comment]
thank you!
