### ISSUE TITLE
How to track AlertDialog destination onDismissed event?

### ISSUE THREAD

**Issue by alexzaitsev** [raamcosta/compose-destinations#272]
Is there such callback? If no - is it hard to add it?

**Comment by raamcosta** [comment]
Hi @alexzaitsev !

What do you mean with AlertDialog? Is it a Destination annotated with `style = DestinationStyle.Dialog::class`?

**Comment by alexzaitsev** [comment]
hey @raamcosta, yes. This is what I meant

**Comment by alexzaitsev** [comment]
Nevermind, I figured it out. The one can use default `androidx.compose.material.AlertDialog` composable and `onDismissRequest` callback there.
