### ISSUE TITLE
How to pass root activity to first destination & other destinations

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#276]
At the 1st destination as well as other destinations I need activity to be passed.
How can I achieve this

App crashes with following error
*****Activity was requested, but it is not present

**Comment by raamcosta** [comment]
Hi! There are multiple ways, check here:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters#use-dependenciescontainerbuilder-to-prepare-dependencies

**Comment by raamcosta** [comment]
Please do let me know if this helped, happy to answer other questions below 🙂

**Comment by UKMIITB** [comment]
Yes that did help
One query, whatever be the current stack situation, I want to move to a specific destination & clear everything else
I tried `navigator.popBackStack(FinalDestination, false)`

This doesn't seem to be working 

Also after using dependeciesContainerBuilder, there was custom viewmodel that is needed in many destinations
So I added the following

DestinationsNavHost(navGraph = NavGraphs.root,
                    dependenciesContainerBuilder = {
                        dependency(this@SomeActivity)
                        dependency(viewmodelInstance)
                    })
                    

But I get the following error
Given component holder class ***someActivity does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager

**Comment by UKMIITB** [comment]
Just to add when using `navigator.popBackStack(FinalDestination, false)` at the start screen, it is giving blank screen
But when using `navigator.navigate(FinalDestination())`, it works fine
