### ISSUE TITLE
Supporting parameters in route

### ISSUE THREAD

**Issue by hblockx** [raamcosta/compose-destinations#277]
Hey, thanks a lot for the nice library! I am currently trying to take over a quite big application from xml to compose and by that I was thinking of how to handle routes like "/weather/city/{cityId}/sensor/{sensorId}"
I am seeing this pattern for websites with restful apis a lot but I am not sure about how to take it over to compose destinations as it seems to only support "/weather/city/sensor/?{cityId}{sensorId}".
Composables having routes with params as /weather/city/{cityId}/sensor/{sensorId}" should receive these as params, this would also solve the issue of passing params to the starting destination of a navgraph as the start-composable could simply define the route-param as function parameter. In the case of "/weather/city/{cityId}/sensor/{sensorId}" it maybe would be needed to have a screen for "/weather", "/weather/city/{cityId}" and "/weather/city/{cityId}/sensor/{sensorId}" where the ids are not changing the presented / chosen composable but instead being passed information and by this changing the shown content of the composable.
"/weather/city/1" and "/weather/city/2" would be the same composable for "/weather/city". While I like the clean style of compose destinations I simply cannot find a nice way of handling such a URL style routing. Is it already supported or actually a missing feature?

**Comment by raamcosta** [comment]
Hi @hblockx 👋

Why do you even need to think about routes? This is internal details when using compose destinations for the most part.

Just think of your screens as screens which take some arguments either mandatory or not and go from there. You don’t need to worry about which routes get used internally, right?

**Comment by hblockx** [comment]
Hey! Thanks for the quick reply! So what I was thinking is that in some cases it would be useful to have an automatically generated backstack. Lets assume the user clicks on a deeplink then maybe he wants to be redirected to GraphA/{id}/details/somefield and with compose navigation I could "go up the navigation" by cutting the last /%something% easily but only as long as I keep the whole hierarchy of the route. It would be possible to check that the backstack is empty and in that case backpress would lead to "GraphA/{id}/details/" further backpressing to "GraphA/{id}" and so on. Of course we could build GraphADetails/{id} but then there is no generic way of knowing where to go back to, is there?

**Comment by Nek-12** [comment]
Yeah I'm actually also interested in how we can build a navigation stack when the user is coming to the app from a deeplink. Say I want to open a deeplink that says `/user/cart/product?id=blah`. It would be reasonable to go back to cart after the user is done viewing a product (for business purposes). But I think now the app activity will just be finished because nothing is in the backstack yet. Please don't tell me about BackHandler {}s, I don't want to go back to the cart __always__. The user could view the product from another place in the app.

**Comment by raamcosta** [comment]
I still don't see why we're talking about routes. None of what you're saying requires routes to function. In fact, up until compose navigation, we never had routes to identify screens and Compose Destinations is built exactly to avoid having to deal with routes.

So, is the question then that you guys want to create a back stack of destinations as the user enters the app using a deep link? If so, isn't this done already automatically? Or the idea is to customize what is done and put intermediate screens? If so, I'm not sure even how to do this with official compose navigation 🤔 

I remember some API for fragments (I think?) that lets you create a back stack as you wish, but I don't know if such a thing exists for compose or at least I haven't seen it.

I would simply create some component to navigate that has all this info and makes the correct navigation given some logic when a user enters via a deep link.

**Comment by raamcosta** [comment]
Closing this guys, let me know if there is still something I can help with! 👍
