### ISSUE TITLE
Activity destinations in DestinationsNavHost

### ISSUE THREAD

**Issue by maggud** [raamcosta/compose-destinations#279]
Hey, 

I was wondering if there is any way to include activity destinations in the DestinationsNavHost like we would in a regular NavHost? I can't see any support for it today, but I don't quite understand why. It seems like the only way to do this is to use a NavHost and manually add all our destinations, instead of doing it with Destinations annotations etc, which seems a bit counter-productive.

For us, we use quite a few Activities today, but are migrating towards using Compose Destinations everywhere. To be able to define destinations for activities instead of using the regular Intent way would be really nice for our migration towards a simpler navigation :)

Simple example use case: Today we have a root navigation with ComposeDestinations defined for a BottomNavigation. However, it's still early in the migration phase, so most of the subpages for each tab take you to a new Activity to handle some detail page.

**Comment by raamcosta** [comment]
Hi @maggud 👋 

You're saying it could be done in a regular NavHost. How? Are we talking compose navigation NavHost?

If it can be done in compose navigation NavHost, then it can be done with Compose Destinations.
For interacting with screens that live on other activities, I would refactor the activities out for fragments and use fragments inside the Composable (I'm sure you can find examples out there).

Having different activities for different destinations doesn't seem like a good idea to me, and refactoring activities into fragments, shouldn't be too difficult. So I would probably go this way, but let me know if there is actually a way to do this on official compose navigation 🙂

**Comment by maggud** [comment]
Hey @raamcosta! Thanks for the swift reply!

Yeah, I'm talking about `androidx.navigation.NavHost`, and more explicitly through the `NavHostBuilder`:

```NavHost(
    navController = navController,
    startDestination = "startDestinationRoute"
) {
    activity("OtherActivityRoute") {
        activityClass = OtherActivity::class
    }
}```

I really couldn't find any good docs on this, and I know it's not ideal, but this would just act as a bridge until we can do it more properly of course, allowing for a bit quicker adoption.

Of course, we could just launch activities with regular Intents, but it would be a lot nicer to be able to make them part of the navigation graph!

For the future, we want to remove all other activities entirely, but that's gonna take some time. Thanks for the idea of doing a middle-step with fragments though! That might be worth taking into consideration, as it removes some need for rewriting a bunch of lifecycle-dependent code :)

**Comment by maggud** [comment]
Official docs:
https://developer.android.com/reference/androidx/navigation/NavGraphBuilder#(androidx.navigation.NavGraphBuilder).activity(kotlin.String,kotlin.Function1)

**Comment by raamcosta** [comment]
Hmmm ok I didn’t know this existed tbh. Thanks for bringing it to my attention.

I’ll investigate and let you know. I seems like something I can easily add to this library

**Comment by maggud** [comment]
That would be awesome, thanks for looking into it!

**Comment by raamcosta** [comment]
Good news and bad news.

Good news: It's done :) Expect it on next release. Sneak peek:

```kotlin
data class OtherActivityNavArgs(
    val otherThing: String,
    val color: Color
)

@SettingsNavGraph
@ActivityDestination(
    navArgsDelegate = OtherActivityNavArgs::class,
)
class OtherActivity: ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val args = OtherActivityDestination.argsFrom(intent)
        println("OtherActivity args = $args")

        setContentView(ComposeView(this).apply {
            setContent {
                Column(
                    modifier = Modifier.background(args.color)
                ) {
                    Text("OTHER ACTIVITY")
                    Text("ARGS: \n$args")
                }
            }
        })
    }
}
```

Imagine annotating the Activity with ActivityDestination, setting the nav args class (if there are nav args) and you're done! More: You can use the generated destination `argsFrom` method which takes an intent and returns the instance of the nav args class defined in the `navArgsDelegate`.
AND: you can also annotate any other class or object and specify an `activityClass` in the annotation if you're targeting an Activity that you don't own or is on another module!

Bad news: It was quite some changes for a very low usage feature 😅 Anyway, it was kinda fun, so no problem. Maybe you can buy me a coffee ahahah (just joking of course, like I said, it was fun exercise 😄 )

**Comment by raamcosta** [comment]
Forgot to mention, you can navigate to this just like any other destination with all type safety features we love, for the above Activity:

```kotlin
navigator.navigate(OtherActivityDestination(otherThing = "testing", color = Color.Magenta))
```

**Comment by maggud** [comment]
Wow, that was fast!

Thank you a lot for this! I'll make sure to buy you a coffee next time we meet on a conference or something 😄

Is there any snapshot build we can test while waiting for the real release? 🙂

**Comment by raamcosta** [comment]
Oh I can release a new version today, no problem ;)

**Comment by raamcosta** [comment]
@maggud you can use the 1.x.25 lib versions for this. Let me know how it goes 🙂

**Comment by raamcosta** [comment]
I haven’t had time to create the release in GitHub project but it is on maven central 🙂

**Comment by yallam08** [comment]
Is it possible to get an instance of `DestinationsNavigator`  inside the activity to navigate to other destination in the graph?

**Comment by raamcosta** [comment]
Hi @yallam08! Not at the moment, at least not without some work.
Maybe you can open a new issue with that request? 🙏

**Comment by AnnSofiAhn** [comment]
I work with @maggud and can confirm that this works like a charm! A little late with the actual confirmation here, but I just added this to a legacy Activity in the app and now I can navigate there the same way as with the Compose stuff.

Many thanks!

**Comment by raamcosta** [comment]
Thanks for the feedback! Glad to hear 🙂

**Comment by raamcosta** [comment]
Open a new issue @dwane13.

You mean that if you don’t specify any ksp arguments, the it works? you can see the generated files?

**Comment by dwane13** [comment]
Well, I tested it and it doesn't work in any case for some reason.

**Comment by raamcosta** [comment]
Ok, in that case you might be experiencing the issue with Android gradle plugin 7.4.

this is ksp issue, the workaround is either to bump ksp to 1.8.0-1.0.9 ( needs Kotlin 1.8 though) or to same as this commit:

https://github.com/raamcosta/compose-destinations/commit/9101a1a03794d2974f43131cbf4de810a53262ab

**Comment by nizam-betterapp** [comment]
@raamcosta you rock! I have been trying to get you a coffee and couldn't find link in your github :)
would appreciate if you can add a link.

we moved all our navigation code to compose destinations in a day and it's been working so well.
what does this line do in addition to setContent? why not just setContent?

     `   setContentView(ComposeView(this).apply {`
