### ISSUE TITLE
Corrupted Destination Files

### ISSUE THREAD

**Issue by Tonnie-Dev** [raamcosta/compose-destinations#282]
I am having a very strange issue when compiling an Android app using compose-destinations lib.

I am using the below versions (got an error while trying to update to the current `1.6.23` for compose 1.2.0)

```
// Compose Nav Destinations
implementation 'io.github.raamcosta.compose-destinations:core:1.5.15-beta'
ksp 'io.github.raamcosta.compose-destinations:ksp:1.5.15-beta'

compose_ui_version = '1.2.1'
kotlin_version = '1.6.10'
```

The first issue I noted was on the `MainActivity` where there is a wrong **NavGraphs** import statement 
as shown on this ![snapshot](https://github.com/Tonnie-Dev/Yummies/blob/master/screenshots/wrong_import_snapshot.png) .
![wrong_import_snapshot](https://user-images.githubusercontent.com/31527935/198939179-a27bb7eb-b154-45d2-acb1-d280097c4625.png)
When I try to navigate from **OverviewScreen** to **DetailsScreen** (takes a _meal:Meal_ argument) the generated `DetailsScreenDestination` class after rebuilding doesn't permit the mill argument. 

I get an ![error](https://github.com/Tonnie-Dev/Yummies/blob/master/screenshots/overviewscreen_error.png) when I add the `meal` argument. 
![overviewscreen_error](https://user-images.githubusercontent.com/31527935/198939446-38264dd0-60e4-4b83-a08e-5ffffa804cfa.png)

This is how the DetailsScreen looks like:

```
@Destination
@Composable
fun DetailsScreen(meal: Meal) {
    
}
```

This is the generated class source code:

```
object DetailsScreenDestination : DirectionDestination {
         //invoke constructor missing the meal argument
    operator fun invoke() = this
    
    @get:RestrictTo(RestrictTo.Scope.SUBCLASSES)
    override val baseRoute = "details_screen"

    override val route = baseRoute
    
    @Composable
    override fun DestinationScope<Unit>.Content(
		dependenciesContainerBuilder: @Composable DependenciesContainerBuilder<Unit>.() -> Unit
    ) {
		val dependencyContainer = remember { DestinationDependenciesContainer(this) }
		dependencyContainer.apply { dependenciesContainerBuilder() }

		DetailsScreen(
			meal = dependencyContainer.require()
		)
    }
```

You will note from the generated Destination class above the invoke() constructor is missing the meal argument.
![overviewscreen_error](https://user-images.githubusercontent.com/31527935/198939172-dcf01b22-27e1-4fe7-8868-c89e5ac3ac07.p

ng)

If run the app without any argument on the Destination, the app clashes when I click the meal item to navigate to the DetailsScreen.

> Process: com.uxstate.yummies, PID: 6767
> java.lang.RuntimeException: Meal was requested, but it is not present at
>               com.ramcosta.composedestinations.navigation.DestinationDependenciesContainer.require(DestinationDependenciesContainer.kt:98)

I tried everything I could to get past the error but I am stuck. Any help is appreciated, I will leave the [link to the GitHubRepository](https://github.com/Tonnie-Dev/Yummies).

**Comment by raamcosta** [comment]
Hi @Tonnie-Dev 👋

First of all, I don’t understand what is wrong with the NavGraphs import? Looks good to me 🙂

Secondly, if you want to pass Meal as a navigation argument (something you pass from one screen to the next) it needs to be of a type that can be passed as a navigation argument. Check here what types you can use: (there is a list close to the top)
https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments

If you don’t use a type like this, the library will assume you want to pass it (in this case the Meal) from the NavHost level, which you would have to do at runtime and hence the library lets you build the app since it’s not possible to know if you are doing it or not.

I’m sure if you follow this, it will work just fine 🙂 
Important question though: what was the error you got when upgrading?

thanks 🙏

**Comment by Tonnie-Dev** [comment]
Thanks @raamcosta for the prompt feedback, I will try your suggestions.

The issue that I am having is a Build Error when I upgrade to `1.6.23`.
  ```
// Compose Nav Destinations
    implementation 'io.github.raamcosta.compose-destinations:core:1.6.23-beta'
    ksp 'io.github.raamcosta.compose-destinations:ksp:1.6.23-beta'
```
These are the Details:

> > Task :app:kspDebugKotlin FAILED
> e: java.lang.NoSuchMethodError: 'kotlin.sequences.Sequence com.google.devtools.ksp.processing.Resolver.getSymbolsWithAnnotation$default(com.google.devtools.ksp.processing.Resolver, java.lang.String, boolean, int, java.lang.Object)'
> 	at com.ramcosta.composedestinations.ksp.processors.Processor.getComposableDestinations(Processor.kt:55)
> 	at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:26)
> 	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:195)
> 	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:193)
> 	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:287)
> 	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:193)
> 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM
> 

Thanks Man

**Comment by raamcosta** [comment]
What version of ksp are you using?

**Comment by Tonnie-Dev** [comment]
My Kotlin version is 1.6.10

`   id 'org.jetbrains.kotlin.android' version '1.6.10' apply false`

So I am using this ksp:

` id 'com.google.devtools.ksp' version '1.6.10-1.0.2'`

**Comment by raamcosta** [comment]
I don’t actually have one, but I mean I’ve been meaning to do one 😅 guess I can arrange that quickly 🙂

thanks a lot!
And that is completely normal Ahah , to be honest I should improve that error message.

About the ksp error, I would try using the same versions of ksp, compose and Kotlin that I’m using on branche compose-1.2 branch (there is a toml file with all versions - catalogs gradle feature).
 I’m guessing it’s some incompatibility with some versions you’re using 🤷‍♂️

**Comment by Tonnie-Dev** [comment]
It was a silly errror :man_shrugging: but I am happy it won't happen next time.

You can sign-up for [Buy-Me-Coffee](https://www.buymeacoffee.com/) and put a button link on all your ReadeMes (especially this Library is a must ).

For example my friend put it on his [app's ReadMe](https://github.com/Felix-Kariuki/Yummy#readme).

![readMe](https://user-images.githubusercontent.com/31527935/199155083-929ee62c-bdb8-4ca5-8f45-b505b0316605.png)

I will have a look at  compose-1.2 branch to hack the update error.

Cheers Rafael :clinking_glasses: :raising_hand:

**Comment by raamcosta** [comment]
Thank you so much for the encouragement! 🙂

I’ll leave it here for starters 😁
https://www.buymeacoffee.com/rafaelamcosta

Any other question, do let me know!

**Comment by Tonnie-Dev** [comment]
Thanks Rafael for everything, I just saw your Buy-Me-Coffee Link and I have left a message.

**Comment by raamcosta** [comment]
Thank you! Means a lot 🙂
