### ISSUE TITLE
Generates Deeplinks that don't match the pattern when using UUID as a required parameter.

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#286]
Hello again. 

I've recently made some changes to how deeplinks are handled in my app, and I can't seem to understand what's going on since then.

I have a screen that looks like the following:

```kotlin
@Composable
@Destination(
    deepLinks = [
        DeepLink(
            uriPattern = "${DeeplinksImpl.SCHEMA}://$FULL_ROUTE_PLACEHOLDER", // SCHEMA = "myapp"
        )
    ]
)
internal fun Some(
    nav: AppNavigator,
    id1: Uuid,
    id2: Uuid? = null,
) {
    SomeScreen(navigator = nav, id1 = id1, id2 = id2)
}
```
For that, the following is generated:

```kotlin
// destination deeplink builder:
navDeepLink {
	uriPattern = "myapp://$baseRoute/{id1}?id2={id2}" //baseRoute = "some"
}
// used later by the compose destinations in the debugger
finalUriPattern = "^\Qmyapp://some/\E([^/]+?)($|(\?(.)*)|(\#(.)*))"

```

And I launch the deeplink using the following uri:
```kotlin
val uri = "myapp://some/537d2e03-46e4-4673-bbdc-68033d702b0a?id2=%02null%03"
```
Which is generated by the following: 
```
activityNavigator.deeplink("$SCHEMA://${direction.route}")
```

What's most interesting now, the regex used by compose-nav matches the one that I start the deeplink with
(considering that the escape sequence is invalid, but somehow in Java that works)
![image](https://user-images.githubusercontent.com/46318640/200174415-3ae9fbe7-60ad-433c-805a-c4de134e3330.png)

But the deeplink is not resolved at all...
It seems to be resolved to completely different things, depending on the order in which deeplinks were declared in the generated code...
The culprit is `androidx.navigation.DeepLinkMatch.compareTo` which overwrites `bestMatch` with the match of another destination for some reason.

**As soon as I change the parameter to be a query parameter, everything works.**

What could in the world be the problem here?

P.S. I've verified that regular navigation works, web navigation works and my activity and deeplink are correctly resolved using intent filters. 
Using compose-navigation 2.5.3 and also tried with 2.6.0-alpha03

**Comment by raamcosta** [comment]
Hi @Nek-12! Thank you once more for reporting :) 

Do you have or can you make a small example? Maybe make it a one file with everything that you could share here?
It's gonna be hard to debug this without having a running example.

**Comment by raamcosta** [comment]
> The culprit is androidx.navigation.DeepLinkMatch.compareTo which overwrites bestMatch with the match of another destination for some reason.

So you have multiple matches for this deep link?

**Comment by Nek-12** [comment]
Yes, but it matches almost any destination for some reason. bestMatch is assigned 10+ times as I see when debugging

**Comment by Nek-12** [comment]
This may be due to me not using the host and just providing a schema. The default compose nav library defines their routes as app://androidx.navigation/route and I'm doing app://route. I'll try changing my schema to this later. However I still think my use case should be supported, however this will now be a task for the authors of the actual compose nav library

**Comment by raamcosta** [comment]
That's fair. 
Yes, I think this is something to be considered in the official library, not on compose destinations.
I'll close this then. Let me know if changing the schema worked!

**Comment by Nek-12** [comment]
Hey @raamcosta , changing the schema did not work. Can I request this to be reopened please? I forgot to mention this before

**Comment by Nek-12** [comment]
Generated code for path parameter:
```kotlin
internal object ChallengeDetailsDestination : NavigationTypedDestination<ChallengeDetailsDestination.NavArgs> {
    
    override fun invoke(navArgs: NavArgs): Direction = with(navArgs) {
        invoke(id)
    }
     
    public operator fun invoke(id: StableId): Direction {
        return Direction(
            route = "$baseRoute" + 
					"/${stableIdNavType.serializeValue(id)}"
        )
    }
    
    @get:RestrictTo(RestrictTo.Scope.SUBCLASSES)
    override val baseRoute: String = "challenge_details"

    override val route: String = "$baseRoute/{id}"
    
	override val arguments: List<NamedNavArgument> get() = listOf(
		navArgument("id") {
			type = stableIdNavType
		}
	)

	override val deepLinks: List<NavDeepLink> get() = listOf(
		navDeepLink {
			uriPattern = "respawn://app/$baseRoute/{id}"
		},
		navDeepLink {
			action = "android.intent.action.VIEW"
			uriPattern = "https://respawn.pro/app/$baseRoute/{id}"
		}
	)

    @Composable
    override fun DestinationScope<NavArgs>.Content() {
		val (id) = navArgs
			ChallengeDetails(
				id = id, 
			)
    }
                    
	override fun argsFrom(bundle: Bundle?): NavArgs {
	    return NavArgs(
			id = stableIdNavType.safeGet(bundle, "id") ?: throw RuntimeException("'id' argument is mandatory, but was not present!"),
	    )
	}
                
	override fun argsFrom(savedStateHandle: SavedStateHandle): NavArgs {
	    return NavArgs(
			id = stableIdNavType.get(savedStateHandle, "id") ?: throw RuntimeException("'id' argument is mandatory, but was not present!"),
	    )
	}

	public data class NavArgs(
		val id: StableId,
	)
}
```

Code for query param version:

```

internal object ChallengeDetailsDestination : NavigationTypedDestination<ChallengeDetailsDestination.NavArgs> {
    
    override fun invoke(navArgs: NavArgs): Direction = with(navArgs) {
        invoke(id)
    }
     
    public operator fun invoke(
		id: StableId?,
    ): Direction {
        return Direction(
            route = "$baseRoute" + 
					"?id=${stableIdNavType.serializeValue(id)}"
        )
    }
    
    @get:RestrictTo(RestrictTo.Scope.SUBCLASSES)
    override val baseRoute: String = "challenge_details"

    override val route: String = "$baseRoute?id={id}"
    
	override val arguments: List<NamedNavArgument> get() = listOf(
		navArgument("id") {
			type = stableIdNavType
			nullable = true
		}
	)

	override val deepLinks: List<NavDeepLink> get() = listOf(
		navDeepLink {
			uriPattern = "respawn://app/$baseRoute?id={id}"
		},
		navDeepLink {
			action = "android.intent.action.VIEW"
			uriPattern = "https://respawn.pro/app/$baseRoute?id={id}"
		}
	)

    @Composable
    override fun DestinationScope<NavArgs>.Content() {
		val (id) = navArgs
	        ChallengeDetails(
		        id = id, 
	        )
    }
                    
	override fun argsFrom(bundle: Bundle?): NavArgs {
	    return NavArgs(
			id = stableIdNavType.safeGet(bundle, "id"),
	    )
	}
                
	override fun argsFrom(savedStateHandle: SavedStateHandle): NavArgs {
	    return NavArgs(
			id = stableIdNavType.get(savedStateHandle, "id"),
	    )
	}

	public data class NavArgs(
		val id: StableId?,
	)
}
```

**Comment by raamcosta** [comment]
I am really low on time these days 😬

What I can say is that we’re using the official APIs under the hood. There’s no magic here.
By looking at the generated Destination you can see how the deep link uris are prepared and that is what we pass to official library API.
So if there is an issue here, it’s for sure something either on official library or in the way you’re setting up the deep links (but if it’s the latter, you would be able to check and fix it).

**Comment by Nek-12** [comment]
Makes sense, I will check on my end using latest CD and report back.
