### ISSUE TITLE
Allow some sort of metadata on destinations

### ISSUE THREAD

**Issue by mattinger** [raamcosta/compose-destinations#290]
I'm looking to try out compose destinations in a reference application.  In this reference application, we have a screen gallery that shows all the possible screens that might be displayed without having to actually navigate around the entire flow. 

My current approach is to use either an enum class, or an interface/sealed class with a global list of the possible screens.

```
enum class Screens(
    val route: String,
    val titleResId: Int,
    val composable: @Composable () -> Unit
)
```

I'd love to use compose destinations for this instead.  The problem is that I don't have any way to get the same effect i get from the "titleResId".  This string resource id is used on the list screen.  I can certainly cycle through the list of destinations, but there's no field i can use to hold that.  It would be great if you could give some sort of metadata or something for things like this.

**Comment by raamcosta** [comment]
For each module, generated Destinations are all part of a sealed interface, so what you could do:

```kotlin
@get:StringRes
val Destination.title
    get(): Int {
        return when (this) {
            GreetingScreenDestination -> R.string.greeting_screen
            ProfileScreenDestination -> R.string.profile_screen
            SettingsScreenDestination -> R.string.settings_screen
            FeedDestination -> R.string.feed_screen
            ThemeSettingsDestination -> R.string.theme_settings_screen
            // ...
        }
    }
```

**Comment by raamcosta** [comment]
@mattinger let me know if this answer is helpful so I can close this if that's the case!

**Comment by raamcosta** [comment]
Closing it, please comment if my answer wasn’t helpful 🙂
