### ISSUE TITLE
IllegalDestinationsSetup: Use argument `start = true` in the @Destination annotation of the 'root' nav graph's start destination!

### ISSUE THREAD

**Issue by gt-rapido** [raamcosta/compose-destinations#291]
I'm trying to annotate a composable as follows

```
@Composable
@Destination(style = DestinationStyle.BottomSheet::class)
fun CancelOrderBottomSheet(
    orderId: String,
    orderStatus: OrderStatus,
    navigator: CancelOrderNavigator,
) {
```

There are many other composables that are bottom sheets that work just fine, but only for this composable I see this issue
It will be great if you can help me figure out what could be the issue

What I've tried:

Adding start = true, to the @Destination, but it says, that start destinations cannot have mandatory arguments. I don't want this to be a start destination first of all

**Comment by gt-rapido** [comment]
Just managed to fix it by changing the ksp args from `navgraphs` to `destinations`. The argument `navgraphs` is for modules that determine their own navgraph, while the other one is `destinations`, which says that the current annotated composable is a destination

```
ksp {
    arg("compose-destinations.mode", "destinations")  // Don't use navgraphs here
    arg("compose-destinations.moduleName", "cancel_order")
}
```

**Comment by raamcosta** [comment]
Yap, use “destinations” if you want your module to output destinations only. In that case in your module which calls DestinationsNavHost you’ll have to gather these destinations and put them in some NavGraphSpec object to pass to that nav host.
