### ISSUE TITLE
Mixing NavGraphSpec & @NavGraph annotations allowed?

### ISSUE THREAD

**Issue by miduch** [raamcosta/compose-destinations#292]
In my multi module project I've NavGraphSpec for settings screen like following (Note: not giving any nestedNavGraphs here)

```
    val settings = object : NavGraphSpec {
        override val route = Consts.SETTINGS_ROUTE
        override val destinationsByRoute = listOf(
            SettingsScreenDestination
        ).associateBy { it.route }
        override val startRoute = SettingsScreenDestination
    }
```

Would it be possible to define a nested navgraph within Settings module using @NavGraph and have something like below

@SomehowTellHereThatParentGraphIsSettingFromNavGraphSpec?
@NavGraph
annotation class LanguageSettingsNavGraph(
    val start: Boolean = false
)

@LanguageSettingsNavGraph
@Destination
@Composable
internal fun LanguageSettingsScreen() {
}
 

Thanks!

**Comment by raamcosta** [comment]
Hey @miduch 👋 

If I understood correctly you want to define that the NavGraph that exists in module A is the parent NavGraph of some other NavGraph that exists in module B.
No this doesn't work. Even on official compose navigation, each module should only expose one or more NavGraphs and then your navigation logic will gather them, put them as nested graphs of some other graph and pass the root graph with all graphs to `NavHost` (`DestinationsNavHost` in our case).

**Comment by raamcosta** [comment]
So what you need to do instead, is go to the settings NavGraphSpec and explicitly add the nested graphs (that can exist on other modules):

```kotlin
    val settings = object : NavGraphSpec {
        override val route = Consts.SETTINGS_ROUTE
        override val destinationsByRoute = listOf(
            SettingsScreenDestination
        ).associateBy { it.route }
        override val startRoute = SettingsScreenDestination
        override val nestedNavGraphs = listOf(
            LanguageSettingsNavGraph,
            // ...
        )
    }
```

**Comment by miduch** [comment]
> So what you need to do instead, is go to the settings NavGraphSpec and explicitly add the nested graphs (that can exist on other modules):
> 
> ```kotlin
>     val settings = object : NavGraphSpec {
>         override val route = Consts.SETTINGS_ROUTE
>         override val destinationsByRoute = listOf(
>             SettingsScreenDestination
>         ).associateBy { it.route }
>         override val startRoute = SettingsScreenDestination
>         override val nestedNavGraphs = listOf(
>             LanguageSettingsNavGraph, // 👈  HERE
>             // ...
>         )
>     }
> ```
> 
> Let me know if this works for you 🙂

thanks for reply. this already in use and works. My question was if these 2 ways (NavGraphSpec & @NavGraph) can be mixed/used together or not. stupid question maybe :)

**Comment by raamcosta** [comment]
Maybe I’m misunderstanding, but what I think is if both graphs are in the same module, then just use @NavGraph in both parent and child.
If they’re not then you need to go to the module that knows both and specify this parent-child link since in the module of the child, it doesn’t know which graph will be its parent (and it shouldn’t).

**Comment by miduch** [comment]
> since in the module of the child, it doesn’t know which graph will be its parent (and it shouldn’t).

👍  thanks a lot!
