### ISSUE TITLE
NavController.navigate issue with TypedDestination

### ISSUE THREAD

**Issue by MaxMichel2** [raamcosta/compose-destinations#293]
Simple issue, when using the `NavController.navigate` extension with a `TypedDestination`, the extension doesn't seem to work. I think that for it to work, you'd need a second one to handle `Route` alongside `Direction`.

I'll submit a PR alongside this to fix the issue.

**Comment by raamcosta** [comment]
Hi @MaxMichel2 👋 

If I understood correctly, this is expected. If it's "typed" destination, it means it needs arguments. So to navigate to it you need to call its invoke function and pass those arguments. This returns a `Direction` and then you can pass this to the `navigate` method.

**Comment by MaxMichel2** [comment]
Oh my god! Of course 😂 I'm sorry, I completely missed that. This is an issue on my part (someone on our team forgot to add default arguments which is why it shouldn't need arguments)

Thanks! I'll close the PR ;)

**Comment by raamcosta** [comment]
If you add defaults to all nav args, the destination will still be a Typed one (since you can pass args) so you will still need to call invoke function. But now you can leave it empty - so just doing SomeDestination() will work.
