### ISSUE TITLE
2 navgraphs drawer and backpressed

### ISSUE THREAD

**Issue by thomasponzo-dev** [raamcosta/compose-destinations#295]
I have 2 navgraphs root and myschooltime
the navigation drawer is inside the root graph. I don't know how I can check inside the myschooltime graph composable when the user pressed backpress to check if  the drawable in the root graph is open or closed. so that I can close the navigation drawer first when its open and not navigate back to the previous myschooltime graph composable. Do you know a solution how I can let root and myschooltime communicate with each other?

**Comment by raamcosta** [comment]
@thomasponzo-dev !

I need more information to try and help you, please.
I must admit I did not understand much 😅 

Can you share some code?

**Comment by raamcosta** [comment]
Closing due to lack of information. Reopen with more information if that is the case :)
