### ISSUE TITLE
Unable to clear stack when navigating to a new destination

### ISSUE THREAD

**Issue by mevans** [raamcosta/compose-destinations#297]
Just started implementing this library, love how much of my navgraph code is getting cleaned up :)
My application requires the ability to navigate to a new screen, with a completely clear back stack (eg. log in).

For example, Screen 1 -> Screen 2 -> (Screen 3 with clear back stack -tapping back would exit app)

Previously I used the code 
```
navigate(route) {
        popUpTo(0)
}
```

Which navigated to the target route, and then also cleared the back stack until the top-most route. This however doesn't seem to work when I switch to the implementation

```
fun DestinationsNavigator.withClearStack(route: DirectionDestination) {
    navigate(route) {
        popUpTo(0)
    }
}
```

Any ideas about workarounds? Is this a known issue?

Thanks

**Comment by raamcosta** [comment]
No issues regarding this, you can do it much better though. Here is a piece of code from the sample app in the repo: (slightly edited)

```kotlin
            navigator.navigate(ScreenYouWantToNavigateToDestination) {
                popUpTo(NavGraphs.root) // IF you want to clear all!  (*)
            }
```

> (*) if you don't want to clear all, you can pass the upper most screen in your stack that you want to keep (or pop if you pass `{ inclusive = true}`. For example, if your stack is [A, B, C] (C being the top one, the one which is visible) and you'll be navigating to D, then you can say `popUpTo(B) { inclusive = true }` and the result will be [A, D]

Hope this is clear 😉  It's not different than with official compose navigation, you simply have these type safe structures to use, but in the end, it's the same logic!

**Comment by mevans** [comment]
Yep that makes perfect sense, thank you!
