### ISSUE TITLE
String route param values being encoded

### ISSUE THREAD

**Issue by mevans** [raamcosta/compose-destinations#298]
When I pass a string value to the destination of a `navigate` call, all the spaces in the string are replaced by +. 

This wasn't the default behaviour when using the normal Jetpack compose routing. Is there a nice way to solve this globally? The solution I came up with was just a holding dataclass:
```
data class SafeString(
    val value: String,
)

fun String.safe() = SafeString(this)
```
With then a custom `DestinationsNavTypeSerializer` to handle the string properly.

Thanks!

**Comment by raamcosta** [comment]
Hi @mevans !

Thank you so much for reporting. I found the issue, it was a regression on my previous version where I changed the URI encoding algorithm to be compatible with unit tests (with no instrumentation).
In the meantime use the version before latest 1.7.25-beta (or 1.x.25-beta where x depends on your compose version).

**Comment by raamcosta** [comment]
In any way, I'm expecting to make a new release with the fix in the next 24h, so stay tuned for that 🙂

**Comment by raamcosta** [comment]
@mevans please retry this with the new version `1.x.27-beta`, and thank you so much again for reporting 🙇
