### ISSUE TITLE
Define start destination dynamically 

### ISSUE THREAD

**Issue by eric-ampire** [raamcosta/compose-destinations#3]
There are scenarios where the initial destination depends on a particular condition, for example if a user is connected or not, is there an alternative way to do this?

**Comment by raamcosta** [comment]
I have to test how you could do it in the normal compose navigation scenario 🤔

But if I'm right, you would just have some logic before calling the `NavHost` and then change the `startDestination` parameter accordingly. If that's the case, I can easily see myself opening that parameter up in `Destinations.NavHost` and `Destinations.Scaffold` and just default to the `start` given by the Annotation.
This way, people can still use the `start` parameter, but they can override it at runtime.

How does this sound? 🙂
