### ISSUE TITLE
View Model Instance

### ISSUE THREAD

**Issue by AdzeB** [raamcosta/compose-destinations#300]
Hello!

I have an issue. I want to pass the value, let's say, email in the VM from one screen to another, but when I get to the other screen, there's no value. Is there a way to share the same instance of the VM?

I appreciate any help you can provide.

**Comment by raamcosta** [comment]
Hi 👋 

I'm not sure I understand your issue. Are you trying to pass email as a navigation argument from one screen to another?
If yes, check this:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments

If you want to share the VM between multiple screens, check this:
https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels#share-viewmodels-between-multiple-destinations

**Comment by AdzeB** [comment]
I tried the share view models methods, but I get errors implementing that.

I get the following `Too many arguments for public inline fun <reified D : Any, T> DependenciesContainerBuilder<T>.dependency(dependency: D): Unit defined in com.ramcosta.composedestinations.navigation`


With regards to the share it to all the screens using activity, I am currently implementing my destinationNavHost in the main activity under a MopdalBottomSheetLayout, so I don't know how I will have access to the facility(I am new to jetpack compose)

**Comment by AdzeB** [comment]
@raamcosta

**Comment by raamcosta** [comment]
That seems like you’re calling the method wrong 😅

Can you paste the code here where you’re calling dependency method?

**Comment by AdzeB** [comment]
this is how it looks now

        setContent {
            CompositionLocalProvider(UserState provides userState) {
                AppLoadTheme {
                    val navController = rememberAnimatedNavController()
                    val bottomSheetNavigator = rememberBottomSheetNavigator()
                    navController.navigatorProvider.addNavigator(bottomSheetNavigator)
                    ModalBottomSheetLayout(bottomSheetNavigator = bottomSheetNavigator ) {
                        DestinationsNavHost(
                            navGraph = NavGraphs.root,
                            navController = navController,
                            engine = rememberNavHostEngine(),
                            dependenciesContainerBuilder = {
                                dependency(hiltViewModel<OTPViewModel>())
                            }
                        )
                    }

                  }


                }
            }

**Comment by AdzeB** [comment]
I tried this as well

dependency(NavGraphs.root){
                                    val parentEntry = remember(navBackStackEntry){
                                        navController.getBackStackEntry(NavGraphs.root.route)
                                    }
                                    hiltViewModel<OTPViewModel>(parentEntry)
                                }

**Comment by raamcosta** [comment]
```kotlin
dependency(NavGraphs.root) {
    val parentEntry = remember(navBackStackEntry) {
    navController.getBackStackEntry(NavGraphs.root.route)
    }

    hiltViewModel<TYPE OF YOUR VIEWMODEL>(parentEntry)
}
```

The above should work if you pass the ViewModel type there, if it doesn't, show me the error.

**Comment by AdzeB** [comment]
I get this

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/59929333/203107276-8b62a940-121a-4023-9db0-372f41dd70fb.png">

**Comment by raamcosta** [comment]
What version of the library are you using?

**Comment by AdzeB** [comment]
implementation 'io.github.raamcosta.compose-destinations:animations-core:1.5.1-beta'
    ksp 'io.github.raamcosta.compose-destinations:ksp:1.5.1-beta'

**Comment by raamcosta** [comment]
I see. update it to 1.5.27-beta please. Documentation is matching latest version only 🙂

**Comment by AdzeB** [comment]
It worked no errors

**Comment by AdzeB** [comment]
Thank you very much, I managed to get the value to different screens.
