### ISSUE TITLE
Does compose-destinations support KMM (Kotlin Multiplatform)?

### ISSUE THREAD

**Issue by DAT4** [raamcosta/compose-destinations#301]
I am wondering if compose-destinations support KMM or if it is gonna support it in the future :)

**Comment by raamcosta** [comment]
This will only happen if official compose navigation supports this in the future. If not, no way to make this happen, at least not without re-implementing the whole navigation logic :)

**Comment by Douvi** [comment]
Hey @raamcosta, JetBrains announced this a couple of months ago -> [site](https://www.jetbrains.com/lp/compose-multiplatform/). 
Does it mean your lib will still work without any change?

**Comment by raamcosta** [comment]
This library uses the official android jetpack compose navigation library. So as long as that only supports android, so does this library.

In short, it will not work with other platforms until android team changes navigation to also support other platforms.
