### ISSUE TITLE
Question) I need NavArgs toBundle function

### ISSUE THREAD

**Issue by way-kis** [raamcosta/compose-destinations#303]
I want toBundle NavArgs, How do I do this?

**Comment by raamcosta** [comment]
Why? What are you trying to do?

**Comment by way-kis** [comment]
Pass destination argument when running new activity

**Comment by raamcosta** [comment]
I guess you can create an extension function that does this 🙂
It will be the best way, I don’t think this is a feature for the library.

**Comment by way-kis** [comment]
The extension function will have too many boilerplate codes.
plz consider #304
