### ISSUE TITLE
Passing parameter to viewmodel

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#305]
Case1:

@Composable
fun ABCScreen(id:String, vm:AbcViewmodel = hiltViewModel()) {
}

In viewmodel I need `id`

Case2:
@Composable
fun ABCScreen(someObject:ABCObject, vm:AbcViewmodel = hiltViewModel()) {
}

In viewmodel I need someObject

Can you please help me with this

**Comment by UKMIITB** [comment]
For case1:

I tried using it this way:

```
class AbcViewmodel @Inject constructor(savedStateHandle: SavedStateHandle) {
private val isFreshOnBoardingCase = savedStateHandle.get<String>("id")
}
```

1. Is this correct way ?
2. Also will it work similarly for objects
3. Android studio shows `id` as unused in composable parameter. Is there any way to make Android studio know that its used ?

**Comment by raamcosta** [comment]
Hi @UKMIITB !

Please read this section 
https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments/#navigation-arguments-class-delegate

**Comment by raamcosta** [comment]
Let me know if you still have questions after 🙂

**Comment by raamcosta** [comment]
Closing this, let me know if I can help any further.
