### ISSUE TITLE
Result return is no longer being passed on back navigation since version 1.7.23-beta

### ISSUE THREAD

**Issue by golovkov-llc** [raamcosta/compose-destinations#307]
Navigation on result does happens but doesn't pass the value older version than 1.7.23-beta works perfectly fine but after this  =(

```
@Destination
@Composable
fun BarcodeScanScreen(
    navigator: DestinationsNavigator,
    resultNavigator: ResultBackNavigator<String>,
    reason: BarcodeScanReason,
    resultRecipientProductList: ResultRecipient<ProductListScreenDestination, Boolean>,
    resultRecipientInboundStock: ResultRecipient<InboundStockScreenDestination, Boolean>,
    resultRecipientQuantityStock: ResultRecipient<QuantityStockScreenDestination, Boolean>
) {
  .
  .
  .
resultRecipientProductList.onNavResult { navResult ->
        when (navResult) {
            NavResult.Canceled -> Unit
            is NavResult.Value -> when (reason) {
                BarcodeScanReason.INBOUND_STOCKING -> viewModel.onInboundedStock(navResult.value)
                BarcodeScanReason.CORRECTION -> viewModel.onQuantityStock(navResult.value)
                else -> Unit
            }
        }
    }
}
```

**Comment by raamcosta** [comment]
Hi @golovkov-llc !

I have this feature working on latest version..can you please give me more information? What was the latest version where things worked? Can you please test it again 1.7.23-beta and 1.7.24-beta?

**Comment by haluzpav** [comment]
Hello, colleague of @golovkov-llc here. I've dug a bit more in the issue and found it.

Our code got broke in [`1.7.23-beta`](https://github.com/raamcosta/compose-destinations/releases/tag/1.7.23-beta) by this change

> Navigating back onlyIfResumed option added. (thanks Petr Stetka aka @petrstetka)

What happened is that we called `resultNavigator.navigateBack(someBoolean)`, assuming the `someBoolean` will be passed into `navigateBack` method as `result` argument. However, thanks to the mentioned change in `1.7.23-beta`, it was now being passed as `onlyIfResumed` argument.

It seems like the change could have been done a bit more carefully. We'll have to use named arguments at places where we pass a Boolean. `resultNavigator.navigateBack(result = someBoolean)`

Anyway, thanks, you can close the issue. 🙂

**Comment by raamcosta** [comment]
Ahhh I see 🤔

yes you are totally right, I didn’t think about the case of result also being a Boolean.

Glad you found it, thank you and sorry for this.
