### ISSUE TITLE
Getting an instance of `DestinationsNavigator` inside activity destination to navigate to other destinations in the graph?

### ISSUE THREAD

**Issue by yallam08** [raamcosta/compose-destinations#308]
Is it possible to get an instance of `DestinationsNavigator`  inside the activity to navigate to other destination in the graph?

_Originally posted by @yallam08 in https://github.com/raamcosta/compose-destinations/issues/279#issuecomment-1335958649_

**Comment by raamcosta** [comment]
Now that I think about this, I don't think this is possible in a reasonable way. Seems like this feature is meant just as a one-way navigation. Of course, the way to return to the previous activity where we have access to the NavController and all that is by navigating back to finish this new activity. Then from there, you can navigate normally to other destinations.

Thanks for opening this regardless 👍
