### ISSUE TITLE
ViewModel lifecycle and @Serializable error

### ISSUE THREAD

**Issue by IssaMansour** [raamcosta/compose-destinations#309]
Hello, I have this code:

`@Destination
@Composable
fun CollectionDetailScreen(
    navigator: DestinationsNavigator? = null,
    collectionDetailViewModel: collectionDetailViewModel = viewModel()
)`

which is working, everything compile fine.

But I want to make my view model serializable to be able to pass it as a parameter of my navigator.
When I add `@Serializable` to my view model, I have this error when building the app:
`CollectionDetailScreenDestination.kt: (27, 18): Functions which invoke @Composable functions must be marked with the @Composable annotation`

I'm not sure it is a bug or me doing something wrong.
Any help? Thanks!

PS: if I removed the `= viewModel()` and let `@Serializable`, it works fine but I want to handle lifecycle of my view model by adding `= viewModel()`

**Comment by raamcosta** [comment]
Hi @IssaMansour!

So you want to pass your `CollectionDetailViewModel` as a navigation argument?! I've never heard of such a crazy idea 😝 
I don't know what exactly you want to achieve, but this is not the way. ViewModels are not passed as navigation arguments. You want to pass only data objects which have no logic. Remember that arguments get serialized so the instance you receive on the other end is not the same (even though all fields have the same content).

Think about a small part of the ViewModel which is the actual data you want to send to the other destination and use that as a navigation argument.

Let me know if this helped!

**Comment by raamcosta** [comment]
No problem, glad it helped!
