### ISSUE TITLE
Generated source dependencies not found under canary AGP 8.0.0-alpha09

### ISSUE THREAD

**Issue by mpost** [raamcosta/compose-destinations#314]
Setting up a project to use compose-destinations with the android gradle plugin `8.0.0-alpha09` does generated the correct sources but they are not correctly picked up by setting the source dir to the generated folder.

Using the current stable version `7.3.1` of the AGP plugin does work as expected. 

Is there some documentation on what version of the AGP plugin is compatible? Also is there a way to make it work with the Canary version?

**Comment by Jacob3075** [comment]
Facing same issue, have not tried using lower versions of AGP.
The IDE gives an error saying it can't find the `NavGraphs` class even tho it is generated, but I'm able to build the project so gradle is picking it up only the IDE can't find it.


Compose destinations version: `1.7.25-beta`
kotlin version: `1.7.20`
ksp: `1.7.20-1.0.8`
AGP: `8.0.0-alpha09`
IDE: `Build #AI-222.4345.14.2221.9321504, built on November 23, 2022`

**Comment by raamcosta** [comment]
Hi guys 👋 

looks like an issue with IDE and AGP indeed.
I found this
https://github.com/google/ksp/issues/37#issuecomment-1330839571

(Last retry says it works if you specify the source sets in a different way? 🤷‍♂️)

And this:
https://issuetracker.google.com/issues/255915317
(Supposed to be fixed though? 🤔)

I’m afraid not much I can do here, let’s see if we have some news soon 🤞

**Comment by mpost** [comment]
Thanks for looking into it. It looks as if https://issuetracker.google.com/issues/255915317 would have solved the issue. Might not have landed in AGP alpha9 yet. Keeping fingers crossed.

**Comment by mpost** [comment]
I think the issue has been resolved in `8.0.0-alpha10`. Could anybody else confirm?

**Comment by Nek-12** [comment]
Change your ksp configuration to 

```
libraryVariants.all { // or applicationVariants
        sourceSets {
            getByName(name) {
                kotlin.srcDir("build/generated/ksp/$name/kotlin")
            }
        }
    }
```

**Comment by MaxMichel2** [comment]
This is also the case with AGP 7.4.0 (I was wondering if this was linked to the library but it seems that AGP is the culprit)

**Comment by raamcosta** [comment]
I was able to fix this in this commit:

COMMIT: https://github.com/raamcosta/compose-destinations/commit/9101a1a03794d2974f43131cbf4de810a53262ab

I used the workaround explained in the google issue.

**Comment by mpost** [comment]
I can confirm that the updated declaration via the java source set works with AGP 7.3.1 (previous min supported version) and AGP 7.4.0 (min not working version. I also tried with 8.1.0-alpha01 but that caused some different issues in my test setup, likely due to an early alpha of the AGP plugin.

**Comment by sc941737** [comment]
> I was able to fix this in this commit:
> 
> COMMIT: [9101a1a](https://github.com/raamcosta/compose-destinations/commit/9101a1a03794d2974f43131cbf4de810a53262ab)
> 
> I used the workaround explained in the google issue and it is working for me.

This worked for me!

**Comment by raamcosta** [comment]
We now have multiple solutions for this KSP related issue. Either use the above mentioned fix, or migrate to KSP 1.8.0-1.0.9 which completely fixes this, so you can remove all these explicit indications of the generated files in the build.gradle.

Given this, I'm closing the issue, let me know if you're still dealing with something similar.

**Comment by mpost** [comment]
I can confirm that removing the explicit source location is not required with ksp 1.8.10 and agp 7.4.0.

**Comment by raamcosta** [comment]
Added a warning on top of readme file too
