### ISSUE TITLE
Companion object constant is not working as default parameter in navArgsDelegate

### ISSUE THREAD

**Issue by epool** [raamcosta/compose-destinations#315]
Hi! 👋🏼 I have the following destination with `navArgsDelegate`

```kotlin
@Destination(
    navArgsDelegate = MyViewModel.ViewState::class,
)
```
where `MyViewModel.ViewState` looks similar to this
```kotlin
@HiltViewModel
class MyViewModel @Inject constructor() : ViewModel() {
    data class ViewState(
        ...
        val verificationCodeLength: Int = VERIFICATION_CODE_LENGTH,
        ...
    )

    companion object {
        const val VERIFICATION_CODE_LENGTH = 6
    }
}
```
but I'm getting this error when the destination is generated
```
e: .../MyScreenDestination.kt: Unresolved reference: VERIFICATION_CODE_LENGTH
``` 
```kotlin
public object MyScreenDestination : TypedDestination<ViewState> {
    ...
    public operator fun invoke(
		...
		verificationCodeLength: Int = VERIFICATION_CODE_LENGTH, // <====== Error HERE!
		...
    ): Direction {
```

Thank you in advance! 🙌🏼

**Comment by raamcosta** [comment]
Hi 👋 

Default values are not given to us by ksp. We are literally reading them from the source file. So put it in top level. It’s gonna be the same and debatable even better as it avoids the instantiation of the companion object

**Comment by epool** [comment]
> Hi 👋
> 
> Default values are not given to us by ksp. We are literally reading them from the source file. So put it in top level. It’s gonna be the same and debatable even better as it avoids the instantiation of the companion object

roger that, thank you so much for you quick  reply!
