### ISSUE TITLE
navArgsDelegate with default values from SavedStateHandle

### ISSUE THREAD

**Issue by epool** [raamcosta/compose-destinations#317]
Hi! 👋🏼 I have the following destination with `navArgsDelegate`

```kotlin
@Destination(
    navArgsDelegate = MyViewModel.ViewState::class,
)
```
where `MyViewModel.ViewState` looks similar to this
```kotlin
@HiltViewModel
class MyViewModel @Inject constructor(
    savedStateHandle: SavedStateHandle,
) : ViewModel() {
    private val _viewState = MutableStateFlow(savedStateHandle.navArgs<ViewState>()) // <===== Error here!
    ...
    data class ViewState(
        ...
        val noDefaultProperty: String,
        val defaultProperty: String = "",
        ...
    )
}
```
but I'm getting this error when I run my unit tests
```
'defaultProperty' argument is not mandatory and not nullable but was not present!
``` 
```kotlin
public object MyScreenDestination : TypedDestination<ViewState> {
    ...
override fun argsFrom(savedStateHandle: SavedStateHandle): UserVerificationPhoneNumberCodeViewState {
	    return ViewState(
			noDefaultProperty = DestinationsStringNavType.get(savedStateHandle, "noDefaultProperty") ?: throw RuntimeException("'noDefaultProperty' argument is mandatory, but was not present!"),
			defaultProperty = DestinationsStringNavType.get(savedStateHandle, "defaultProperty") ?: throw RuntimeException("'defaultProperty' argument is not mandatory and not nullable but was not present!"), // <===== Error here!
	    )
	}
```

this is how I initialize my unit test
```kotlin
        val savedStateHandle = SavedStateHandle(
            listOf(
                "noDefaultProperty" to "Something",
                // Here is where I'm not passing the value for defaultProperty and I would like to use "" since it's its default value
            ).toMap()
        )
        viewModel = MyViewModel(
            savedStateHandle = savedStateHandle,
        )
```

Thank you in advance! 🙌🏼

**Comment by raamcosta** [comment]
> // Here is where I'm not passing the value for defaultProperty and I would like to use "" since it's its default value

Compose Destinations is meant to abstract you away from these details. You shouldn't care how stuff gets into the SavedStateHandle. So your test shouldn't populate the SavedStateHandle manually, and, if it does, then of course you need to set the default value which my library would do for you :) 
Because now you are basically doing part of the job my library does (except you're not making it right, because my library would put there the default value for the other property) and then checking that it doens't work on the other end 😅 
Of course that would never work ahah

**Comment by czarnini** [comment]
Hi! I love your work, this library is generally how Google should've approached navigation in Compose at the beginning ;) 

I've been thinking about similar approach for testing as @epool  have suggested  at his 1st post. ( I was thinking about using mockK to mock SavedStateHandle , but the idea is quite the same).  You wrote that:

 > So your test shouldn't populate the SavedStateHandle manually

So what do you suggest instead? Could you provide us with short code snippet showing how would you refactor OP's code? :)
```
        val savedStateHandle = SavedStateHandle(
            listOf(
                "noDefaultProperty" to "Something",
                // Here is where I'm not passing the value for defaultProperty and I would like to use "" since it's its default value
            ).toMap()
        )
        viewModel = MyViewModel(
            savedStateHandle = savedStateHandle,
        )
```

All the best to you 🍺

**Comment by czarnini** [comment]
Sorry for little bit of spamming but I've realized what how it should be handled

@epool try something like this witk MockK:
```kotlin
    mockkObject(MyScreenDestination )
    every {
        MyScreenDestination.argsFrom(any<SavedStateHandle>())
    } answers {
        CoinDetailViewModel.MyViewModel.ViewState(
            noDefaultProperty = "noDefProp",
            // We're using regular ViewState constructor, so optional args are really optional ;)
        )
    }

    viewModel = MyViewModel(
         savedStateHandle = SavedStateHandle(),
    )
``` 

And you are good to go :)

**Comment by epool** [comment]
Thank you so much guys! 🙌🏼
