### ISSUE TITLE
Generated classes are not visible/accessible at runtime or by lint in the RELEASE build of the app

### ISSUE THREAD

**Issue by SiavashB** [raamcosta/compose-destinations#318]
I just added Compose destinations to one of our modules. It works perfectly fine in the debug build, but in our qa/release build variant, the page containing Destinations is completely blank.
The other clue is that Lint is not able to see the NavGraphs class, and it show up in red, even though the app compiles and runs
![image](https://user-images.githubusercontent.com/3977543/208205678-568c4108-9157-4047-bc45-aa2424dad68a.png)

Again, this lint red highlight only shows up when I select the qa/release variant of the app. In the debug variant, NavGraphs does not get highlighted in red.

here are the differences between our build variants 

   ```
debug {
            
            applicationIdSuffix ".x"
            firebaseCrashlytics {
                mappingFileUploadEnabled false
            }
            debuggable true
            multiDexEnabled true
            signingConfig signingConfigs.debug

            minifyEnabled false
            shrinkResources false

            FirebasePerformance {
                instrumentationEnabled false
            }

            //build speed improvements for dev builds
            aaptOptions.cruncherEnabled = false
            ext.alwaysUpdateBuildId = false
            splits.density.enable = false
            splits.abi.enable = false
        }

        qa {
            firebaseCrashlytics {
                mappingFileUploadEnabled false
            }
            debuggable true
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
            FirebasePerformance {
                instrumentationEnabled false
            }
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            testProguardFiles 'proguard-rules-test.pro'
        }
        
```
Note: in this version I already turned off minify since that was our first suspecion, But it did not make a difference

**Comment by raamcosta** [comment]
Hi 👋 

How are you making the IDE aware of the generated files? Did you follow documentation?

https://composedestinations.rafaelcosta.xyz/setup#3-and-finally-you-need-to-make-sure-the-ide-looks-at-the-generated-folder

**Comment by SiavashB** [comment]
ok so turned out the blank screen issue was something else out side of destinations. But the Lint issue IS a problem and it sounds like it's exactly what you linked above, thank you.
