### ISSUE TITLE
how to navigate to the deep link

### ISSUE THREAD

**Issue by periva101** [raamcosta/compose-destinations#319]
let us say I have this 
```@Destination(
  route = "user",
  deepLinks = [
    DeepLink(
      uriPattern = "https://myapp.com/user/{id}"
    )
  ]
)
@Composable
fun UserScreen(
  navigator: DestinationsNavigator,
  id: Int
)```

now, how can I navigate to UserScreen using deep link from my app

**Comment by raamcosta** [comment]
Hi!

First of all, why would you use deep link instead of normally navigating to it?

Then if you really must, you can do it just like you do it with official compose navigation:

`navController.navigate(URI)`

**Comment by raamcosta** [comment]
Let me know if you're able to solve your issue! 🙂
