### ISSUE TITLE
How to expand BottomSheet to a specific height ?

### ISSUE THREAD

**Issue by amirzeinaly** [raamcosta/compose-destinations#32]
Hi 
Is there a way to expand the BottomSheet to a specific height or full screen?

thanks

**Comment by raamcosta** [comment]
Hi @amirzeinaly !

Do you mean the default height it shows up with?
I don't think so. The only configuration we have is in the `ModalBottomSheetLayout` parameters.

**Comment by raamcosta** [comment]
To give more context:
We use Accompanist Navigation-Material to make this possible. I went through their docs and haven't found a way to request a specific default height.
If they ever implement this feature, then this library will also allow it.
