### ISSUE TITLE
how to push destinations on start?

### ISSUE THREAD

**Issue by periva101** [raamcosta/compose-destinations#320]
Let us say I have screens like this
A -> B -> C

There is A deep link to reach the screen 
B 

the issue is when the user press the back screen 
A should be appear

```
 DestinationsNavHost(navGraph = NavGraphs.root,
                        startRoute = if (bookingId ==null )NavGraphs.root.startRoute else B,
                        dependenciesContainerBuilder = {
                            dependency(signOutUseCase)
                        })
```
how to push screens from the start route

**Comment by raamcosta** [comment]
Hi!

Why are you deep linking from A to B instead of navigating normally?

I didn't necessarily understood your question, what do you mean with "push screens from start route"?

**Comment by periva101** [comment]
let us say I want to start the DestinationsNavHost back stack with
a -> b > c

**Comment by raamcosta** [comment]
I don't know actually, I never had this use case. But if you can do it with normal compose navigation, you should also be able to do it with my library, so I think this is out of the scope of this library.

Maybe check around how to do that with official compose navigation, and it should be the same (or maybe slight adaptations) when using this lib.
