### ISSUE TITLE
how to add custom navigator?

### ISSUE THREAD

**Issue by way-kis** [raamcosta/compose-destinations#321]
I want to close current activity when moving to ActivityDestination or DirectionActivityDestination.
But not supported by the navigation component.
I want to add a custom navigator for this functionality.

**Comment by raamcosta** [comment]
Hi!

Well, you can just create any class, call it "ActivityNavigator" and pass it to whatever screen needs it in one of these two ways:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters
