### ISSUE TITLE
Conditional destination style

### ISSUE THREAD

**Issue by costular** [raamcosta/compose-destinations#323]
Hi! 

First of all thank you so much for this amazing library, it's been really useful! ❤️ 

Since adaptative design is becoming a thing and some of us are trying to design for tablets, wearables, laptops, etc, I wanted to have different destination styles depending on each device. For example, on a phone I'd like to open a screen on full screen or a bottom sheet, but for larger screens I'd rather choose to open a dialog or something similar.

Is there any mechanism to achieve it?

Thanks!

**Comment by yzheka** [comment]
I don't hink it is library related. You can have same destinations for all devices and inside each destination decide what UI to use depending on device

**Comment by raamcosta** [comment]
I admit I haven't had much time to dig through this topic... @yzheka or @costular have you guys seen how this would be done with official compose navigation? I'm interested in that since that would give me good hints on what we may be missing (or not) from Compose Destinations.

**Comment by yzheka** [comment]
@raamcosta [Here](https://developer.android.com/jetpack/compose/layouts/adaptive) are official docs

**Comment by yzheka** [comment]
@raamcosta so as you see it is resolved inside your screen, but not by navigation
