### ISSUE TITLE
How to listen BottomSheet state

### ISSUE THREAD

**Issue by ShellWen** [raamcosta/compose-destinations#325]
How to listen `ModalBottomSheetState`? I want to listen it. I want to know whether it is `ModalBottomSheetValue.HalfExpanded` or `ModalBottomSheetValue.Expanded`. It seems difficult to implement it.
Sorry for my poor English.

**Comment by gt-rapido** [comment]
Use a `LaunchedEffect`

Something like this,
```
val bottomSheetState = rememberModalBottomSheetState
LaunchedEffect(modalBottomSheetState.isVisible){
   // Do whatever you want with it
}
```

**Comment by raamcosta** [comment]
This is a question not for this library, but for accompanist or official libraries since Compose Destinations doesn't atually change how this is done.

I don't also know, but I'm sure you can easily find an answer if you google it.
