### ISSUE TITLE
Detekt warning `CastToNullableType` in generated code. 

### ISSUE THREAD

**Issue by yogurtearl** [raamcosta/compose-destinations#326]
compose-destinations version: `1.7.30-beta`
detekt version: `1.22.0`

`compose-destinations` ksp generates this code: 

```kotlin
    override fun get(bundle: Bundle, key: String): MyLabels? {
        @Suppress("DEPRECATION")
        return bundle.getSerializable(key) as MyLabels?
    }
```

Which triggers this detekt warning: 
```
detekt.CastToNullableType: Line 22: Use the safe cast ('as? MyLabels') instead of 'as MyLabels?'.
```

See detekt docs: https://detekt.dev/docs/rules/potential-bugs/#casttonullabletype

When `bundle.getSerializable(key)` is NOT an instance of `MyLabels` and is NOT null, then `as MyLabels?` will throw `ClassCastException`. If this is the desired behavior, then `@Suppress("DEPRECATION", "CastToNullableType")`  is probably the right thing here. 

If we want to return `null` when `bundle.getSerializable(key)` is NOT an instance of `MyLabels` and is NOT null, then we would need to `s/as MyLabels?/as? MyLabels/` here.

Workaround: 

Consumer of this lib can exclude generated sources in detekt config: https://detekt.dev/docs/introduction/configurations/#path-filters--excludes--includes

**Comment by raamcosta** [comment]
I'm closing this for same reasons I gave on https://github.com/raamcosta/compose-destinations/issues/327. Let me know if I can still help any further :)
