### ISSUE TITLE
Example of using BottomSheet in DestinationsNavHost

### ISSUE THREAD

**Issue by amirzeinaly** [raamcosta/compose-destinations#33]
Hi 
Please give an example of using the BottomSheet in DestinationsNavHost with custom destination generation

thank you

**Comment by raamcosta** [comment]
I'm not sure I completely understand the question. 

Have you read this?
https://github.com/raamcosta/compose-destinations/wiki/Styles-and-Animations#bottomsheet-style

And this?

https://github.com/raamcosta/compose-destinations/wiki/Styles-and-Animations#animations-setup

Closing as this is not an actual issue. Feel free to keep commenting I will read them anyway 🙂
