### ISSUE TITLE
Compare Direction with DirectionDestination/TypedDestination

### ISSUE THREAD

**Issue by rogerr99s** [raamcosta/compose-destinations#330]
I saw you have implemented this:

Created a Direction impl data class which will enable comparisons of two Directions with normal equals (or "=="). Especially useful in unit tests

I have a menu with a selected state

But what I'm trying to do now is comparing full route of a Direction with a DirectionDestination/TypedDestination, which can have args or not for example:
Having some route/{id}
 val currentDestination by navController.appCurrentDestinationFlow.collectAsState(null)
- currentDestination along with arguments is route/1.
- currentDestination == direction. Only works when route has no Arguments

Another thing I'm considering is to save in a viewModel the model of the menu itself and compare it because it's a data class, but i'll prefer to make it independent cause navigation is a little bit complex and you can navigate to a section without using the menu.

Do you have any better idea?
Thank you so much.

**Comment by raamcosta** [comment]
Hi @rogerr99s !

Not sure I follow. But keep this in mind:
- Direction is basically a route with arguments resolved (example "screen/{id}" will be something like "screen/3" in Direction if you passed 3 as the id)
- Destination is just a definition of how to navigate to a Composable. It gets registered in the Nav graph and when navigated to will call your annotated Composable. It can also be a direction if it doesn't need navigation arguments (DirectionDestination case). If it needs nav arguments, then it will be a TypedDestination. To go from TypedDestination to Direction you need to call one of its invoke methods passing in the navigation arguments.

**Comment by raamcosta** [comment]
Closing the issue for lack of feedback, please let me know if I can help any further :)
