### ISSUE TITLE
Add destination screen in destination stack manually

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#332]
Is there any way to add few destination in navigation stack manually
Usecase is :
User is at destination A.
But when user navigates from A to C -> stack should become A->B->C.

Calling navigator.navigate 2 times with B & C respectively works, but I worry in low end devices it might create some flickering UI

**Comment by raamcosta** [comment]
Hi @UKMIITB !

I don't think there is a way how to do it with official APIs (which we depend on). So no.
Also personally, if this pass your QA, I wouldn't think too much with low end devices, I don't believe it will flicker if you call synchronously one navigate call right after the other 🤔
