### ISSUE TITLE
New Gradle version doesn't show ksp generated files in Android Studio

### ISSUE THREAD

**Issue by KavrinDEV** [raamcosta/compose-destinations#335]
Hello Everyone.
Recently I updated my Android Studio to Electric eel and Gradle to version 7.5 and AGP 7.4  and suddenly the Ksp generated files couldn't be accessed in the main project. after some searching, I found a google issue that suggested a workaround that works for me:
```
   applicationVariants.all {
        kotlin.sourceSets {
            getByName(name) {
                kotlin.srcDir("build/generated/ksp/$name/kotlin")
            }
        }
    }

    applicationVariants.all {
        addJavaSourceFoldersToModel(File(buildDir, "generated/ksp/$name/kotlin"))
    }
```
I just wanted to put this here for reference and save some people the headache.
the google issue: [KSP Generated sources not found after upgrading gradle plugin to from 7.4.0-beta02 to 7.4.0-beta03](https://issuetracker.google.com/issues/255915317)

P.S.: I just found out this issue is duplicated. feel free to remove it. Sorry for the Inconvenience

**Comment by mpost** [comment]
This is the same issue as previously reported on canary releases of the AGP plugin. https://github.com/raamcosta/compose-destinations/issues/314.

I hope this can be resolved. It could become a tombstone for the library.
