### ISSUE TITLE
Bottomsheet closes abruptly on back press

### ISSUE THREAD

**Issue by tapandesai** [raamcosta/compose-destinations#338]
Hi there,

I am facing one issue when closing bottomsheet on back press, the bottomsheet just closes abruptly without proper scroll down (dismiss) animation.

I checked on accompanist and found out the issue has been recently fixed in accompanist version `0.28.1` but currently `compose-destination` 1.3 branch has accompanist version `0.28.0` as it can be seen here [https://github.com/raamcosta/compose-destinations/blob/compose-1.3/gradle/libs.versions.toml](url)

Can you please bump up the version for 1.3 release?

Thanks in advance

**Comment by tapandesai** [comment]
Forgot to link the accompanist issue

[https://github.com/google/accompanist/issues/724](url)

**Comment by tapandesai** [comment]
Okay, so the issue is fixed in `v0.29.0-alpha` actually and not in `v0.28.0`
[[v0.29.0-alpha.](https://github.com/google/accompanist/issues/724#issuecomment-1387478582)](url)

**Comment by Nek-12** [comment]
Seconding this

**Comment by raamcosta** [comment]
There is no `0.28.1` and with Compose 1.3 we cannot use 0.29.0-alpha.

So there is no fix if you're using Compose 1.3. I recommend upgrading to Compose 1.4 and to Compose Destinations 1.8.x which already uses the 0.29 version of Accompanist to get this fixed :)
