### ISSUE TITLE
KSP generates broken code when using expression body syntax

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#339]
Hi! Strange that you haven't noticed yet that KSP will generate broken destination code when using expression body syntax for the destination declaration.

Example:
```kotlin
@Composable
@Destination
internal fun EditRitual(nav: RespawnNavigator, ritualId: Uuid? = null) = AnalyticsScreen("EditRitual") {
    EditRitualScreen(nav, ritualId)
}
```
will generate:

```kotlin
internal object EditRitualDestination : NavigationTypedDestination<EditRitualDestination.NavArgs> {
    
    override fun invoke(navArgs: NavArgs): Direction = with(navArgs) {
        invoke(ritualId)
    }
     
    public operator fun invoke(
		ritualId: UUID? = null) = AnalyticsScreen("EditRitual"), // does not compile
    ): Direction {
        return Direction(
            route = "$baseRoute" + 
					"?ritualId=${uUIDNavType.serializeValue(ritualId)}"
        )
    }
    // ... 
```

**Comment by raamcosta** [comment]
Hi @Nek-12 :)

I cannot think of all use cases, especially when my time is so limited.
I rely on helpful people like you to report these things ahah :D So thanks a lot!

Can you please try replacing the order of the arguments of the Destination? Just curious about something :P 
So putting the ritualId first and the navigator second.

**Comment by raamcosta** [comment]
Also, Nek it's funny you open this issue today, just as I'm finishing a feature that will allow us to easily wrap multiple screens with common functionality. Sounds like that's what you're doing with the `AnalyticsScreen`. 
So stay tunned for that 😋

**Comment by raamcosta** [comment]
Anyway, @Nek-12 consider it fixed, I found the issue and fixed it.
It was related to how we read the default values of parameters. Unfortunately, this is our most "glued together" feature because KSP doesn't have this feature, so we're literally parsing the source code manually, and it seems I missed this use case.

I'm expecting to drop a new release during the weekend :)

**Comment by Nek-12** [comment]
Hey, just wanted to let you know that the new wrapper feature is absolutely insane. My destinations are defined so neatly now. 

```
@Composable
@Destination(
    wrappers = [AnalyticsScreen::class],
)
internal fun SelectApp(
    nav: RespawnNavigator,
    backNavigator: ResultBackNavigator<String?>
) = SelectAppScreen(nav, backNavigator.navigator)
```

Any way to provide an injected dependency (using Compose Destinations `dependenciesContainerBuilder`) in the wrapped object?

**Comment by efemoney** [comment]
Love the _progressive mindblowing_. Good job @raamcosta!
