### ISSUE TITLE
Destination Generation fails if the first parameter is non-navigation argument with default value

### ISSUE THREAD

**Issue by carlesaguilar1** [raamcosta/compose-destinations#34]
Hi, i'm trying to add your library to my project, but destinations with viewmodel injection in the constructor doesn't work:

```
@Destination
@Composable
fun myScreen(
    viewModel: myViewModel = hiltViewModel(),
    myObj: myObj
)
```

and the autogenerated code has an empty parameter on myScreen():
```
object myScreenDestination : DirectionDestination {
         
    operator fun invoke() = this
    
    override val route = "my_screen"
    
    @Composable
    override fun Content(
        navController: NavHostController,
        navBackStackEntry: NavBackStackEntry,
        dependencyContainer: DestinationDependenciesContainer
    ) {
		myScreen(,
			myObj= myObj()
		)
    }
    
}
```

Thanks for your work!

**Comment by raamcosta** [comment]
HI @carlesaguilar1 ! Thanks for reporting 👍 

I found a bug here :) It's not related to Hilt or view models.
I'll release a new version (`1.1.5-beta`) with the fix, then please recheck it on your side and let me know :)

**Comment by raamcosta** [comment]
@carlesaguilar1 can you please update your project to use 1.1.5-beta and retry?

Please let me know if that fixes your issue :)
