### ISSUE TITLE
Allow Serializable or Parcelable navArgsDelegate classes

### ISSUE THREAD

**Issue by cvb941** [raamcosta/compose-destinations#342]
Currently, when a `navArgsDelegate` class is also Serializable or Parcelable, it is considered to be of a navigation type and fails the compiler check with the message:
`Composable 'EventDetailScreen': annotated function cannot define arguments of navigation type if using a 'navArgsDelegate' class. (check argument 'navArgs'`

The parameter of the `navArgsDelegate` type should be excluded from the check and allowed.

```kotlin
@Serializable // <- Causes problems
data class TestNavArgs(
    val eventId: EventId,
    val forceShowBottomSheet: Boolean
)

@Destination(
    route = Routes.EVENT_DETAIL,
    navArgsDelegate = TestNavArgs::class,
)
@Composable
fun EventDetailScreen(
    scaffoldState: ScaffoldState,
    navigator: DestinationsNavigator,
    navArgs: TestNavArgs,
    viewModel: EventDetailViewModel = getViewModel { parametersOf(navArgs) }
) { }
```

**Comment by raamcosta** [comment]
Fixed recently!
