### ISSUE TITLE
args.toSavedStateHandle() method and generating Destinations list even for single destination

### ISSUE THREAD

**Issue by pawelsmagala** [raamcosta/compose-destinations#344]
1. can you create a method to convert navArgs data class to savedStateHandle (or at least to map of names and values?). In testing viewModel, I would prefer to use the actual args class and recreate savedStateHandle from that, so viewModel can read those data the same way as in production code. For example:
`fun GroupScreenDestination.argsToSavedStateHandle(args: MyArgsDataClass): SavedStateHandle`
3. can you change that {module}Destinations list be generated even if there is only a single destination in the module? I use that list to register destinations to navgraph. When starting a new module, which initially has only 1 screen, I can't use it, so I have to create mock second screen to have that. 

Thanks for your help!

**Comment by raamcosta** [comment]
Point 2: Done, check next release.

Point 1: It's a bit complex to add this feature. However you couldn't try to in tests convert the SavedStateHandle also to the instance of NavArgs and then comparing both NavArgs instances (expected vs actual).
Right?

**Comment by pawelsmagala** [comment]
point 2: thanks!
point 1: I'm not sure if Im clear, I don't want to test navigation, but viewModel.
Let's say I have viewModel:

```
data class ScreenArgs(
    val number: Int
) 



class AddingViewModel() : ViewModel() {
    private val navArgs = ScreenDestination.argsFrom(savedStateHandle)
    
    val result = navArgs.number + 2
}
```

Now I want to write a test, delivering the proper number to navArgs:
```
val savedState = ScreenDestination.argsToSavedStateHandle(number = 5)
val viewModel = AddingViewModel(savedState)

assertEquals(7, viewModel.result)
```

Now that's impossible, so what I have to do instead is:
```
 private val savedStateHandle: SavedStateHandle = SavedStateHandle(
        /** field names need to match  [ScreenArgs] **/
        mapOf(
            "number" to "5",
        ),
    )

```

This is not perfect though, since obviously if I change the ScreenArgs, this will fail. 

Ideally, I would love to have a function as argsToSavedStateHandle so I can generate the real arguments and pass it to viewModel in tests. If this is too hard, I can write a reflection-based function to do the same, so no problem. I just felt it would be more natural to have the support for it directly in the library.

Let me know if this is possible, thanks!

**Comment by raamcosta** [comment]
If you do:

```kotlin
class AddingViewModel(
    private val navArgs: AddingScreenArgs = ScreenDestination.argsFrom(savedStateHandle)
) : ViewModel() {
    
    val result = navArgs.number + 2
}
```

Then in tests you can just pass the args you're expecting. You don't need to test my library, that part will work. So by skipping that `argsFrom` in tests you can test all your VM.

**Comment by pawelsmagala** [comment]
@raamcosta thanks for answer. I don't mean to test your work, I just want to test mine :D 
The proposition you made would be nice in a world without DI, but with DI I would sadly need to write separate hilt/dagger definitions for all the args, which is a lot of the boilerplate.

I ended up just "simulating" what compose destination will do with this simple reflection method:
```
fun <T : Any> T.toSavedStateHandle(): SavedStateHandle {
    val savedStateHandle = SavedStateHandle()
    this::class.declaredMemberProperties.forEach {
        val field = it as KProperty1<T, Any>
        val name = field.name
        val value = field.get(this)
        savedStateHandle[name] = value
    }
    return savedStateHandle
}
```

and then in tests I can do:
```
   private var navArgs = GroupScreenArgs(... )
    private val savedStateHandle by lazy { navArgs.toSavedStateHandle() }
```
so I can push savedStateHandle in VM tests and still read navArgs in VM body instead of the constructor. 

However, I'm open to suggestions if you think I can make it better - or use it in the constructor but without per-arg dagger provide method.
Still - thanks for help!

**Comment by raamcosta** [comment]
This is where manual DI shines. I have this for free. That's honestly a poor limitation of DI frameworks, but yes you're right it's a bit of a boilerplate. It does also make more sense regardless. I mean, that's the whole purpose of DI: to provide dependencies. I'd much rather leave my VMs as Android-free as possible and just pass the nav args class and some other abstraction instead of passing SavedStateHandle directly.

**Comment by raamcosta** [comment]
I will close this for now. Thank you anyway for reporting. The workaround looks smart and good enough I imagine :D
