### ISSUE TITLE
Getting all the query param as map

### ISSUE THREAD

**Issue by extmkv** [raamcosta/compose-destinations#345]
Hi community,

Before asking the question I want to say that I know that compose-destinations is type safe.

I was wondering if there is any way to get all the query params as map. In my scenario, I have a screen that can receive N query params and I need to make a request as key + value.

Example: schema://screen/{id}?param1=value1&param2=value2&...

I want to extract the query parameters to a map and send it to the ViewModel, again, params can have completely different names.

There is any way to achieve that?

**Comment by raamcosta** [comment]
Hi @extmkv !

So for me it feels like what we want to pass is a Map<String, String> like structure.
Maps are not supported by default but you can use the custom nav types support, read about it here:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments#custom-navigation-argument-types

You can also get creative and pass it as a ArrayList<String> where each even index is the key and odd is the value.
Like: [key1, value1, key2, value2, ....]. Then you just need a couple of extension functions to get from a Map<String, String> to this sort of List, and one from this list into a Map<String, String>.

Finally, you could also define something like a `KeyValue` class that contains two strings, one for key and one for value, make it Parcelable or Kotlinx Serializable and then pass a list of those.

Lots of ways to solve this 😄 

I'm closing, but let me know how it goes!

**Comment by extmkv** [comment]
Hi @raamcosta 

Thanks for your reply. Maybe I didn't explain it very well, let me elaborate.
I'm currently updating the navigation of our app and this is about a deep link that already exists in production for a while, and I can't simply ask the team to change the structure.

The 3 solutions that you shared will need adaptation of the structure of the arguments.

Let's check one by one:

1. Support Map by creating a serializer. This forces me to use one argument with a structure of a map.
2. Using Lists it's very similar to the previous one, an argument will an array.
3. Data class with serialization, one argument.

As explained in the original post, the arguments received on that deeplink (deep links are shared via email, SMS, push notifications, o web) contains N arguments, and the names are simply unknown.

None of the solutions seem to support the ask. Only with access to the original deep link I would be able to do it on the ViewModel.

**Comment by extmkv** [comment]
Update:

Manage to find a solution for the previous problem.

Basically, I create a new dependency that's inspected in every graph that returns an object with a Map. 

```kotlin
public data class Arguments(
    public val value: Map<String, String>
)
````

```kotlin
/**
* Return an [Argument] object with a map of the query params from the [NavBackStackEntry].
*/
public fun NavBackStackEntry.getQueryArguments(): Arguments {
    val intent: Intent? = this.arguments?.get(DEEPLINK_KEY) as? Intent

    val result = intent?.data?.queryParameterNames?.associate { param ->
        param to intent.data?.getQueryParameter(param)!!
    }

    return Arguments(result ?: emptyMap())
}
```

```kotlin
dependenciesContainerBuilder = {
     ...
                     
     // Add the [Arguments] dependency to all graphs.
     graphs.forEach {
         dependency(it) { navBackStackEntry.getQueryArguments() }
     }
}
```


Then on the destinations:
```kotlin
@Destination(
    route = "example"
)
@Composable
internal fun ExampleScreen(
    arguments: Arguments
) {
    ....
}
```

**Comment by raamcosta** [comment]
Looks good, just one important thing: `dependenciesContainerBuilder` gets called for each destination right when its composable is about to be called. So doing a for each here is not needed, in fact, you shouldn't. If you want all destinations to have access to these arguments, you can just do `dependency(navBackStackEntry.getQueryArguments())`. Since you didn't use any of the overloads which take a NavGraphSpec or a DestinationSpec, then all screens can use it :)
