### ISSUE TITLE
Can Navigate and popBackStack work together?

### ISSUE THREAD

**Issue by Buggyy** [raamcosta/compose-destinations#347]
After a succesful login, I wish to navigate away and pop the backstack. But this seem not to work.

```
   LaunchedEffect(key1 = true) {
        viewModel.uiEvent.collect { event ->
            when (event) {
                is UiEvent.Success -> {
                    navigator.navigate(ListScreenDestination)
                    navigator.popBackStack() // Doesn't work
                }
                ...
            }
        }
    }
```

`navigator.navigate(StepListScreenDestination) `alone works, but pressing the backbutton would lead me back to the login screen, which is not the desired behaviour. How can I achieve this?

- loving compose-destinations!

**Comment by raamcosta** [comment]
HI @Buggyy !

Same way as with official compose navigation:

```
            navigator.navigate(ListScreenDestination) {
                popUpTo(LoginScreenDestination) {
                    inclusive = true
                }
            }
```

**Comment by raamcosta** [comment]
(from top of my head, if it doesn't work, quickly google it, but the secret is the lambda parameter and the popUpTo ;) )
