### ISSUE TITLE
Testing in compose-destinations

### ISSUE THREAD

**Issue by bikrammhz1** [raamcosta/compose-destinations#348]
Hello,

I to write a test case for my project with compose-destinations but can't get the call back method can you please explain with example how can we achieve UI testing using compose-destination

**Comment by raamcosta** [comment]
Hi @bikrammhz1 

I need more context to be able to help you. Can you show me an example of a test you're trying to write?

**Comment by raamcosta** [comment]
Close since we have another issue to improve documentation on this topic
