### ISSUE TITLE
Nested graphs without root destination

### ISSUE THREAD

**Issue by STAR-ZERO** [raamcosta/compose-destinations#35]
Is it possible to create a NavGraph without a root destination like below?

```kt
NavHost(
    navController = navController,
    startDestination = "tab_home"
) {
    navigation(
        route = "tab_home",
        startDestination = "start",
    ) {
        composable("start") { /* */ }
        composable("next") { /* */ }
    }
    navigation(
        route = "tab_setting",
        startDestination = "setting"
    ) {
        composable("setting") { /* */ }
    }
}
```

I added `navGraph` option to all `@Destination` but the `NavGaphs` with Exception was generated.

```kt
object NavGraphs {
    val tabHome = NavGraph(/* */)
    val tabSettings = NavGraph(/* */)
    val root: NavGraph = throw RuntimeException("No found destinations for 'root' navigation graph")
}
```

Is there any solution?

I use version 1.1.5-beta.

**Comment by raamcosta** [comment]
HI @STAR-ZERO ! 👋 

So, everything is possible, but at the moment it requires that you disable nav graphs generation and create the object `NavGraphs` manually.
It's not a big deal, those are pretty simple to implement, but yeah.

You can read about it here:
https://github.com/raamcosta/compose-destinations/wiki/Defining-your-navigation-graphs#manually-defining-navigation-graphs

Let me know if that helps!
I will mark this as a possible enhancement and investigate a way to make your case easier.

**Comment by STAR-ZERO** [comment]
Thank you for helping.

I tried to create NavGraphs manually, but I didn't know what to set for root's `startDestination`.

```kt
object NavGraphs {

    val tabHome = NavGraph(
        // ...
    )

    val tabSettings = NavGraph(
        // ...
    )

    val root = NavGraph(
        route = "root",
        startDestination = /* ???? */,
        destinations = emptyList(),
        nestedNavGraphs = listOf(
            tabHome,
            tabSettings
        ),
    )
}
```

I tried setting `tabHome.startDestination`, but it throws `IllegalArgumentException`.

```
java.lang.IllegalArgumentException: navigation destination start_screen is not a direct child of this NavGraph
```

**Comment by raamcosta** [comment]
Yap. I have been trying your use case too and realized this actually needs some changes.

I should make a new release in the next like 12 hours or so with this support.

Basically what I need to do is accept both nav graphs and destinations in `startDestination` of NavGraphSpec. Seems easy enough 🙂

So keep an eye out for 1.1.6-beta. In the mean time, you can fallback to using the normal NavHost and use the lib's extension functions that also make it easier and safer, if you're in a hurry to have something working. (https://github.com/raamcosta/compose-destinations/wiki/NavHosts#vanilla-navhosts)

**Comment by STAR-ZERO** [comment]
Thank you for dealing with it so quickly. 😃

**Comment by raamcosta** [comment]
And then life happened and only now I got time to test the changes properly (hopefully!).
Please try 1.1.6-beta which should be coming up on maven and let me know how it goes. 

Basically I renamed `startDestination` to `startRoute` which takes an actual `Route` (which is implemented by both NavGraph and Destination). So now you can pass a NavGraph there 🙌
