### ISSUE TITLE
[Feature] On Navigate callback

### ISSUE THREAD

**Issue by SammYWin** [raamcosta/compose-destinations#350]
Hello, dear Rafael, I would like to ask for a feature or maybe you can help me to implement it with the current version. 
So, I need to manage some logic everytime there is a navigation happening, including when you navigate back by pressing the back button on your phone (or Swipe from the corner with gestures mode), but I want to manage it for every screen in one place, for example when my root main screen and main view model getting called for the first time, so that I don't need to write a boilerplate code for every composable screen.
At firs I thought that `dependenciesContainerBuilder ` lambda in the `DestinationsNavHost` is getting called every time you navigate (at least that's what a documentation stated [here ](https://composedestinations.rafaelcosta.xyz/navhosts) ). But I realised that this lambda gets called ONLY if you provide some kind of dependency in the screen. I mean not just provide, but actually specify it as a dependency in the Screen composable function. 
So, is there a way to implement this callback already? If not, would it be a possibility for you to add this feature in the next update?

**Comment by raamcosta** [comment]
You can register a listener on the NavController you’re passing to DestinationsNavHost, just like with official compose navigation 🙂

I can’t help you right now more than this (I’m in a hurry) but I’m sure you can find it if you Google.
You can check any solution for official compose navigation and you’ll be able to use it with compose destinations also 🙂

**Comment by raamcosta** [comment]
Let me know if you find it or not! I can help more later today 🙂

**Comment by SammYWin** [comment]
Oh wow, simply solved that with NavController.OnDestinationChangedListener which gets called on every navigation and even when navigate with back button. I don't know why I didn't try to look what a conventional nav controller can do and only tried to implement that using your library classes)
Anyway thank you for a hint and also for such a great library which is still a lot more convenient than what Google offers! And sorry for opening a pretty much useless issue)

**Comment by raamcosta** [comment]
No worries! Glad you like it 🙂
