### ISSUE TITLE
problems with version compose_version = '1.4.0-alpha02'

### ISSUE THREAD

**Issue by gitdaniellopes** [raamcosta/compose-destinations#351]
buildscript {
    ext {
        compose_version = '1.4.0-alpha02'
        hilt_version = "2.44"
        accompanist_version = '0.28.0'
        ext.paging_version = '3.1.1'
        hilt_navigation_compose_version = "1.0.0"
    }
}

plugins {
    id 'com.android.application' version '7.4.0' apply false
    id 'com.android.library' version '7.4.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.21' apply false
    id 'org.jetbrains.kotlin.jvm' version '1.7.21' apply false
    id 'com.google.dagger.hilt.android' version '2.44' apply false
    id 'com.google.gms.google-services' version '4.3.15' apply false
}

build.gragle(app)

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'kotlin-parcelize'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id 'com.google.firebase.firebase-perf'
    id 'com.google.firebase.appdistribution'
    id 'com.google.devtools.ksp' version '1.7.21-1.0.8'
}

  composeOptions {
        kotlinCompilerExtensionVersion '1.4.0-alpha02'
    }

 //Compose Destinations
    implementation 'io.github.raamcosta.compose-destinations:animations-core:1.8.33-beta'
    ksp 'io.github.raamcosta.compose-destinations:ksp:1.8.33-beta'

//Error
import br.com.kipp.presentation.screens.destinations.DirectionDestination

I'm having trouble importing and creating new destinations. It simply does not create, what can I be doing wrong?

**Comment by raamcosta** [comment]
Since AGP (Android Gradle Plugin) 7.4.0, **if you cannot use Kotlin 1.8.0+**, then you need to tell the IDE about the generated files like so:


<details open>
  <summary>groovy - build.gradle(:module-name)</summary>

```gradle
applicationVariants.all { variant ->
    variant.addJavaSourceFoldersToModel(
            new File(buildDir, "generated/ksp/${variant.name}/kotlin")
    )
}
```
</details>

<details>
  <summary>kotlin - build.gradle.kts(:module-name)</summary>  

```gradle
applicationVariants.all {
    addJavaSourceFoldersToModel(
        File(buildDir, "generated/ksp/$name/kotlin")
    )
}
```
</details>

> **Note**: ☝️ inside `android` block and replacing `applicationVariants` with `libraryVariants` if the module is not an application one (i.e, it uses `'com.android.library'` plugin).

If however, you can use Kotlin 1.8.0 or newer, then use KSP version 1.8.0-1.0.9 (or newer) where this issue was fixed and the IDE will automatically see the generated files! 🙌
