### ISSUE TITLE
Feature request: Pass flags to ActivityDestinations

### ISSUE THREAD

**Issue by Rawa** [raamcosta/compose-destinations#352]
[This enhancement](https://github.com/raamcosta/compose-destinations/issues/279) added the support for ActivityDestinations which is pretty darn awesome. But currently there is no way to pass intent flags when using the ActivityDestination from what I can tell which leaves the use-case pretty limited. From my understanding the NavController supports this using [ActivityNavigator.Extras.Builder ](https://developer.android.com/reference/androidx/navigation/ActivityNavigator.Extras.Builder), in a fashion like [this](https://stackoverflow.com/a/63566415/1724097).

Adding something like a `DestinationsNavigator.navigate(destination: ActivityDestination, Extras.Builder.() -> Navigator.Extras)` would open up the possibility to more flexible navigation with activities as well.

Thanks for all the great work you've put into this project! 🙏

**Comment by raamcosta** [comment]
Hi @Rawa !

This is done now, check next release :)

**Comment by Rawa** [comment]
🙏 Thank you very much!
