### ISSUE TITLE
ActivityDestination not being generated unless there is a regular Destination composable in the same module

### ISSUE THREAD

**Issue by lebeshev** [raamcosta/compose-destinations#356]
Hello @raamcosta, found interesting bug with `@ActivityDestination` not being generated unless I define a composable `@Destination` in the same module.

### How to reproduce

Write a simple code like this:
```kotlin
@ActivityDestination
class MainActivity : ComponentActivity()

@Composable
@Destination
fun TestComposable() {}

```
Run `kspDebugKotlin` gradle task. We can find `MainActivityDestination` and `TestComposableDestination` generated files.

Then remove `@Destination` annotation:
```kotlin
@ActivityDestination
class MainActivity : ComponentActivity()

@Composable
// @Destination
fun TestComposable() {}
```

and run `kspDebugKotlin` again.

With this code `TestComposableDestination` is not generated as expected, however `MainActivityDestination` is not generated as well, which is not expected.

My setup is:
- compose-destinations `1.7.33-beta`
- compose `1.3.3`
- kotlin `1.8.10`
- ksp `1.8.10-1.0.9`
- gradle plugin `7.4.1`
- gradle `7.5`
- compose-destinations.mode `destinations`

Bug reproducible in both `application` and `library` modules.

**Comment by raamcosta** [comment]
Should be fixed on latest versions!
