### ISSUE TITLE
SavedStateHandle not working for ViewModel shared within a nested graph

### ISSUE THREAD

**Issue by aabhashshakya** [raamcosta/compose-destinations#358]
I am trying to save some data in the saved state handle upon process death however it seems like if the viewmodel is shared within a nested navigation graph, then the SavedStateHandle returns null after resuming the app. The SavedStateHandle works fine when the ViewModel is shared across the entire Activity.

My code:

MainActivity:

        setContent {
            MyTheme {
                Scaffold {
                    //set up navigation
                    DestinationsNavHost(dependenciesContainerBuilder = { //this: DependenciesContainerBuilder<*>
                        // 👇 To tie SettingsViewModel to "signup" nested navigation graph,
                        // making it available to all screens that belong to it
                        dependency(NavGraphs.signUp) {
                            val parentEntry = remember(navBackStackEntry) {
                                navController.getBackStackEntry(NavGraphs.signUp.route)
                            }
                            hiltViewModel<SignupViewModel>(parentEntry)
                        }

                        // 👇 To tie ActivityViewModel to the activity, making it available to all destinations
                      //  dependency(hiltViewModel<SignupViewModel>(this@MainActivity))
                    }, navGraph = NavGraphs.root)
                }
            }
        }

NavGraph:

`@RootNavGraph
@NavGraph
annotation class SignUpNavGraph(
    val start: Boolean = false
)`

ViewModel:

```
@HiltViewModel
class SignupViewModel @Inject constructor(
    val savedStateHandle: SavedStateHandle
) : ViewModel() {

    val name = mutableStateOf<String>(savedStateHandle["name"] ?: "")
    fun updateName (newName:String){
        name.value = newName
        savedStateHandle["name"] = newName
    }
```

Destination:

```
@SignUpNavGraph(start=true)
@Destination
@Composable
fun Signup(
    navigator: DestinationsNavigator, signupViewModel: SignupViewModel
) {
   //A textfield that has signupViewModel.name as its value and calls updateName(..) when its content changes 
}
```

**Comment by raamcosta** [comment]
Hi @aabhashshakya 

Can you please try again with 1.x.34-beta version?

**Comment by OrganicCat** [comment]
I have a question related to this exact code but with the ViewModel itself. It's not clear on the documentation, but if I'm using the first suggested implementation:

`viewModel: MyScreenViewModel = hiltViewModel()`

And I navigate to another composable and come back, it is not pulling the first instanced viewModel. That one appears be to be lost to time and space, although it doesn't destroy it, it simply instanced a new ViewModel. Is this intended?

The solution I found was to use the users solution about and attach the viewModel to the MainActivity root for the entire app. This also means I have to pass the viewModel down to each child composable that is not a destination, but rather a nested composable underneath a @Destination composable. Is this really the intended pattern or should I open an issue ticket for it?

**Comment by raamcosta** [comment]
@OrganicCat no, this is not supposed to happen. But it sounds like some misconfiguration or similar because I know the library itself shouldn't be causing this.

**Comment by raamcosta** [comment]
I'm closing this issue as I haven't heard news in a while and I have projects where I have this working. Also seems unrelated with this library. But please let me know if you have evidence to the contrary.
