### ISSUE TITLE
Clear all back stack

### ISSUE THREAD

**Issue by sikka77** [raamcosta/compose-destinations#359]
How to clear all back stack say when login is a success or for other use case like when we want to exit from the app on hitting back instead of going to the previous screen?

**Comment by sikka77** [comment]
tried navigator.popBackStack(), no luck.

**Comment by raamcosta** [comment]
Same way as with official compose navigation.
 I believe it’s clearBackStack

**Comment by raamcosta** [comment]
Let me know if you make it work

**Comment by sikka77** [comment]
No luck,
Here is what I'm trying.
Navigating to dashboard scree.
on adding clear backStack it even prevented navigation to Dashboard Screen. 


is VerifyOtpSingleEvent.NavigateToNextScreen -> {
                    navigator.navigate(
                        DashBoardScreenDestination()
                    )
                    navigator.clearBackStack(DashBoardScreenDestination.route)
 }

**Comment by raamcosta** [comment]
If you clear after navigating then you also clear the new one 😉

try clearing before navigating.
The official way to navigate while popping back stack is by passing the lambda parameter where you can specify such things. Google it: compose navigation navigate while popping back stack.

**Comment by sikka77** [comment]
Okay, so there are 2 screens before Dashboard which needs to be cleared.
I tried this way, and it clears only the Otp screen from back stack. 
The screen before that which is for entering mobile number is still there.
When I hit back it takes me to enter mobile number screen but eventually it should be closing the app.


navigator.navigate(
                        DashBoardScreenDestination()
                    ) {
                        popUpTo(EnterOtpScreenDestination.route) {
                            inclusive = true
                        }
 }

**Comment by raamcosta** [comment]
So it just means you need to pass some other route to the popUpTo method right? 🙂

**Comment by sikka77** [comment]
Yeah, its resolved. Thanks :-)
