### ISSUE TITLE
Testing screens that uses DestinationsNavigator and Parcelable args

### ISSUE THREAD

**Issue by asrieltiago** [raamcosta/compose-destinations#36]
Hi,

Previously i was using this to mock the NavHostController, but cannot find a way to do the same with DestinationsNavController.

private val navController = TestNavHostController(ApplicationProvider.getApplicationContext())

I could make it work on the startDestination of the NavGraphs, but i think this is not the correct way.

![image](https://user-images.githubusercontent.com/52663783/150203808-4b9f5665-afbe-4b73-a799-e126e6043c4a.png)

On the detail screen i receive parcelable args, and i'm not able to mock the args on the Destination.
When i tried to run the test, i receive this exception and cannot mock the args:

![image](https://user-images.githubusercontent.com/52663783/150205105-b7c4141d-68d0-437e-beef-cf1a217299cc.png)

I wanna know if already exists a way to mock or test the screens with this library, receiving the args from the DestinationNavigator.

**Comment by raamcosta** [comment]
Hi @asrieltiago ! 👋 

Thanks for reporting.
So yeah, this is something I haven't had time to fiddle with, unfortunately.
The one thing I can think of is that you can create a `DestinationsNavigator` like this:

```kotlin
     val navController = TestNavHostController(ApplicationProvider.getApplicationContext())

     fun destinationsNavigator(navBackStackEntry: NavBackStackEntry): DestinationsNavigator {
         return DestinationsNavController(navController, navBackStackEntry)
     }
    
    //...
        DestinationsNavHost(navGraph = NavGraphs.root, navController = navController)
```

I'm not sure if this helps or not. I'd have to fully understand what you're trying to do, so I can test on my side.
Is this an open-source project I can take a look at?
From my understanding, you want to test after navigating if the Parcelable args are correct on the other side?

**Comment by raamcosta** [comment]
Or you can create an implementation of `DestinationsNavigator` any way you want since it is an interface. Again.. not sure if this helps you.

**Comment by asrieltiago** [comment]
I made the UI test work, following your idea of creating a class inheriting from the DestinationsNavigator interface.

![image](https://user-images.githubusercontent.com/52663783/150340132-8e80e599-5b54-44ad-9920-3bab11bc825c.png)
![image](https://user-images.githubusercontent.com/52663783/150340270-bbfe8054-30d7-45a1-b75a-262ae86cf117.png)


In the end it was something simple, thanks for the quick answer and maybe this will help the next ones who are going to test the UI.

**Comment by raamcosta** [comment]
If you need an empty implementation of DestinationsNavigator, the library has an `EmptyDestinationsNavigator` 😅 
I thought you wanted to test navigating specifically! Yeah if all you need to test is screens on their own, then this will work for you!
