### ISSUE TITLE
Custom Animation for NavGraphSpec

### ISSUE THREAD

**Issue by miduch** [raamcosta/compose-destinations#360]
Is there any way to specify which animation should be applied when navigating: 

for example 
screenA -> screenB (slide in from bottom)
screenC -> screenB (slide in from left)

through defaultAnimationsForNestedNavGraph its always same animation, and not been able to find a way to change that. 

thanks!

**Comment by raamcosta** [comment]
You have to define animated style for both those destinations and you can check where the transition is from and where it is going to. 


https://composedestinations.rafaelcosta.xyz/styles-and-animations/#animated-style

**Comment by raamcosta** [comment]
Let me know if you’re able to do it 🙂

**Comment by miduch** [comment]
thanks i'll give it a try.

**Comment by miduch** [comment]
> https://composedestinations.rafaelcosta.xyz/styles-and-animations/#animated-style

thanks a lot. works nicely
