### ISSUE TITLE
Animations example

### ISSUE THREAD

**Issue by StraleXY** [raamcosta/compose-destinations#363]
I'm not sure did I miss something but I am not able to find an example to how to add animations to navigation.. Could you provide a link with an example or a small snippet of code showing how to do any animations and I'll work from there?

I've found this: https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/navigation/animation/AnimatedNavHostSample.kt

But it's not using @Destination annotation and I can tell that that annotation can take style param but not sure how to init my own

**Comment by raamcosta** [comment]
https://composedestinations.rafaelcosta.xyz/styles-and-animations/#animated-style

You can start here.
Basically you can define a animated style for your destinations, use its class in the destination annotation.

You can also check playground app in repo, I am using animations there.

**Comment by raamcosta** [comment]
I’ll close, but let me know if I can help further.

**Comment by raamcosta** [comment]
https://github.com/raamcosta/compose-destinations/blob/main/playground/src/main/java/com/ramcosta/samples/playground/ui/screens/profile/ProfileScreen.kt

Notice the ProfileTransitions in the destination annotation.

**Comment by StraleXY** [comment]
> https://composedestinations.rafaelcosta.xyz/styles-and-animations/#animated-style

This is the link I've needed! I'm not sure how I missed that but I got it to work as I wanted. Thanks a lot! I appreciate that!

One little question I have left - What is the difference between a normal and pop transition? It works with just the first one overridden so what is the second one for?

(These functions)
`override fun AnimatedContentScope<NavBackStackEntry>.enterTransition(): EnterTransition { }`
`override fun AnimatedContentScope<NavBackStackEntry>.exitTransition(): ExitTransition { }`
`override fun AnimatedContentScope<NavBackStackEntry>.popEnterTransition(): EnterTransition { }`
`override fun AnimatedContentScope<NavBackStackEntry>.popExitTransition(): ExitTransition { }`

**Comment by raamcosta** [comment]
These are some options you have with accompanist navigation.
Pop is when you’re popping from back stack either away or into it

**Comment by StraleXY** [comment]
Oh I see.. Thank you and have a nice day!
