### ISSUE TITLE
Navigation stack not working when system backpress button is used

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#366]
Following is the code flow
 - I have one activity & then there are multiple composable destinations
 
 UseCase:
  - When I get certain type of notification, I manually create navigation stack by calling navigator.navigate() for various destinations.
  Eg:
navigator.navigate(Destination1)
navigator.navigate(Destination2)
navigator.navigate(Destination3)

Then in destination 3, when on any button press I call navigator.navigateUp() it moves back to Destination3 as expected.
But in destination 3 when OS back button is pressed, it behaves as if Destination1 & Destination2 wasn't present in navigation stack.

This issue doesn't happen when I normally navigate each destination one by one by opening corresponding screen & then coming back by pressing system's back button.

What could be the issue in this ?

**Comment by raamcosta** [comment]
I have no idea. When you call navigate, this library is just calling navigate on the official navigation library APIs, so it is not directly responsible for it.

You should look for answers prepared for that lib.. they will also apply here.
