### ISSUE TITLE
Clear navigation stack when in memory variable is cleaned up by OS when app is minimised

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#367]
I have the following project structure
One activity & then multiple composable destinations.

When app is minimised & in memory variable data is cleared by system OS
When user comes back to the app, I want to clear all the navigation stack & start the app from start.
How can I achieve that

**Comment by raamcosta** [comment]
This question is out of scope for this library. You can check any solution for it for any of the jetpack navigation artefacts and you’ll be able to apply it with this library 🙂
Be warned though that solutions you find are going to be workarounds. On Android, after process death, the app is supposed to recover!
