### ISSUE TITLE
`isRouteOnBackStack` always returns false if no recomposition

### ISSUE THREAD

**Issue by Dr-TSNG** [raamcosta/compose-destinations#368]
[The sample code](https://github.com/raamcosta/compose-destinations/blob/main/sample/src/main/java/com/ramcosta/destinations/sample/ui/composables/BottomBar.kt#L30) shows:
```kotlin
@Composable
fun BottomBar(
    navController: NavHostController
) {
    BottomNavigation {
        BottomBarItem.values().forEach { destination ->
            val isCurrentDestOnBackStack = navController.isRouteOnBackStack(destination.direction)
            ...
```
However, if I don't add an unused variable to trigger recomposition as follows:
```kotlin
val unused: Destination = navController.appCurrentDestinationAsState().value
        ?: NavGraphs.root.startAppDestination
```
`isCurrentDestOnBackStack` will always be false since it is calculated at start and never changes in the future.
I think it is a better way to provide a `isRouteOnBackStackAsState` method.

**Comment by raamcosta** [comment]
I see, reason my sample app is working is that I'm using a "SampleScaffold" which is just like the official one (it calls it) but then listens for Destination changes and recomposes things like BottomBar and TopBar passing in the current destination.

And so whenever the destination changes, my bottom bar gets naturally recomposed.

I will look into providing a `isRouteOnBackStackAsState `. Until then, you may use your own, do it like this:

```kotlin
@Composable
fun NavController.isRouteOnBackStackAsState(route: Route): State<Boolean> {
    return currentBackStackEntryFlow.map {
        isRouteOnBackStack(route)
    }.collectAsState(initial = isRouteOnBackStack(route))
}
```
