### ISSUE TITLE
Build error when using @RootNavGraoh

### ISSUE THREAD

**Issue by BrianMwas** [raamcosta/compose-destinations#369]
hi, I am getting an error when trying to follow this recommendation. 
Composable DetailsScreen: Usage of `start` and `navGraph` parameters of @Destination is deprecated.
Use '@RootNavGraph(start = true)' instead.
This is how am using the annotation
`@RootNavGraph
annotation class EventsNavGraph(val start: Boolean = false)`
I am then applying it to the composable like this`
`@EventsNavGraph(start = true)
@Destination(start = true)
@Composable
fun DetailsScreen(){}`

When I remove the start param on the destination it gives me the following error

> com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Use argument start = true in the @Destination annotation of the 'events' nav graph's start destination!.

Neither options is correct am I doing this wrong somehow

**Comment by raamcosta** [comment]
Hi @BrianMwas!

Make sure you are not using `start = true` in any Destination annotation and that you're also not using `navGraph = "something"`.
At the moment, the ksp task deals with both, but you cannot mix both approaches.

Is this an open-source project? I could look into it real quick.. or you can paste here all your `@Destinations` (just make sure you use the right formatting 😅 coz your examples are a bit hard to understand.. or you can take screenshots too).

**Comment by BrianMwas** [comment]
Thanks for replying here are my examples.
`@RootNavGraph(start = true)
@Destination
fun TicketDetail(){} 


@Destination
@Composable
fun EventDetail()
`
This is how am defining the screens. But when I build the project it shows the error. Also am using multi module approach to build the project. It's not a public repo so not sure if it's possible to share it. Its running though its only that I wanted to ensure there are not unforeseen build issues when releasing the product.

**Comment by pjd0501** [comment]
I am getting this error as well. 

> com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Use argument `start = true` in the @Destination annotation of the 'root' nav graph's start destination!

```
@RootNavGraph(start = true)
@Destination
@Composable
fun HomeScreen() {
...
...
}
```

```
@Destination
@Composable
fun DetailScreen() {
...
...
}
```

When I set `@RootNavGraph` back to `@Destination` with `start` parameter as true, I do get a warning, but it works.

**Comment by raamcosta** [comment]
@pjd0501 and @BrianMwas this error happens if the library concludes that you are using the legacy mode of saying the start destination but are not actually doing that. This happens when for a given module, there are no NavGraph annotations used.

So make sure you're not falling into this trap. I really can't see how else this would be possible, barring a bug on KSP which seems really unlikely.

So again, for each module, make sure you have at least one Destination which is annotated with a NavGraph annotation (like `@RootNavGraph(start = true)` or any other custom navgraph annotation that you may have created.
