### ISSUE TITLE
onlyIfResumed on navigate broke on 1.8.34-beta

### ISSUE THREAD

**Issue by Leeonardoo** [raamcosta/compose-destinations#371]
Hey, thanks for the library!

I just found an issue where if you are using the `DestinationsNavigator#navigate` and passing `onlyIfResumed = true` to it, nothing happens and it doesn't navigate to the destination. Looking though the changes, it seems to be directly linked [to this line](https://github.com/raamcosta/compose-destinations/blob/b403efa01dc968b7bd35fc852e8e3fd9fefeaffe/compose-destinations/src/main/java/com/ramcosta/composedestinations/navigation/DestinationsNavController.kt#L28) (and all of the navigate functions), which seems to be incorrect because it's checking if `onlyIfResumed && isResumed` to return. Before it was checking if the `currentState != RESUMED` and now it's the opposite

**Comment by raamcosta** [comment]
hi @Leeonardoo !

You're absolutely right 🤦 

I will be doing a new release today with this fix. Thank you so much 🙏
