### ISSUE TITLE
Clear stack navigation breaks in 1.8.34

### ISSUE THREAD

**Issue by jasco** [raamcosta/compose-destinations#373]
It seems like 1.8.34 created a regression.  The following function has been used to clear the stack on navigation:

```kotlin
fun DestinationsNavigator.navigateOntoEmptyBackstack(direction: Direction, graph: NavGraph) {
    navigate(direction) {
        launchSingleTop = true
        popUpTo(graph.route ?: graph.startDestinationRoute ?: graph.findStartDestination().navigatorName) {
            inclusive = true
        }
    }
}
```

This seemed to work fine up until 1.8.34 when the following error started occurring:

```
java.util.NoSuchElementException: ArrayDeque is empty.
    at kotlin.collections.ArrayDeque.removeLast(ArrayDeque.kt:163)
    at androidx.navigation.NavController.launchSingleTopInternal(NavController.kt:1849)
    at androidx.navigation.NavController.navigate(NavController.kt:1810)
    at androidx.navigation.NavController.navigate(NavController.kt:1773)
    at androidx.navigation.NavController.navigate(NavController.kt:2173)
    at androidx.navigation.NavController.navigate$default(NavController.kt:2168)
    at androidx.navigation.NavController.navigate(NavController.kt:2153)
    at com.example.ScreenKt.navigateOntoEmptyBackstack(Screen.kt:150)
```

**Comment by raamcosta** [comment]
Just to be sure, try `1.8.35-beta` but I'm guessing it doesn't have anything to do with it. If there is a regression here, it's very likely from the version updates that were done to the official compose navigation dependency between these two versions.

But why exactly do you want to do this? just to clear the backstack? Do this instead:

```kotlin

navigator.navigate(YourDirection) {
     popUpTo(NavGraphs.root) {
        inclusive = true
    }
}

```

**Comment by jasco** [comment]
https://issuetracker.google.com/issues/195342722

Reportedly fixed in [Navigation 2.4.0-alpha06](https://developer.android.com/jetpack/androidx/releases/navigation#2.4.0-alpha06)

**Comment by jasco** [comment]
Alright, a further update.

The use of `NavGraphs.root` unfortunately does not clear the stack when switching graphs from my testing.  Maybe I am doing something wrong but the construct I was using continues to work.

However, removing the `launchSingleTop` when clearing the stack like you also suggested does avoid the crash even with the latest library.  I will go with this.  Thanks for your help.

Closing this issue as resolved.

**Comment by RMF09** [comment]
I had updated to 1.8.35-1.8.36. still had this issue.  Back to 1.8.33-beta, the app is safe for now

**Comment by raamcosta** [comment]
Again guys, this most certainly is not something this library is doing. It is very likely some change in the official compose navigation library that broke something for you, I’m guessing a misuse of the APIs that (since it wasn’t an expected usage of it) wasn’t considered when some change happened.

please make sure you’re using appropriate APIs and using them well. I’m pretty sure that if you are, then it will be working correctly.

@RMF09 were you also using launchSingleTop?

**Comment by RMF09** [comment]
> Again guys, this most certainly is not something this library is doing. It is very likely some change in the official compose navigation library that broke something for you, I’m guessing a misuse of the APIs that (since it wasn’t an expected usage of it) wasn’t considered when some change happened.
> 
> please make sure you’re using appropriate APIs and using them well. I’m pretty sure that if you are, then it will be working correctly.
> 
> @RMF09 were you also using launchSingleTop?

Yea.. I am using that

**Comment by raamcosta** [comment]
Are you sure you need it?

**Comment by raamcosta** [comment]
Or that it makes sense to use it?
