### ISSUE TITLE
NavGraphs not found when adding a new destination

### ISSUE THREAD

**Issue by saff1x** [raamcosta/compose-destinations#377]
When adding a new destination and rebuilding the project the old nav graphs and destinations are not found, so i have to comment them all out and rebuild the project which is alot of work every time i add a new destination

**Comment by raamcosta** [comment]
Hi @saff1x!

I've never seen this behaviour. Can you send me version information as well as how you're configuring things on build gradle?

**Comment by saff1x** [comment]
Sure, I use kotlin 1.8.10 and compose 1.3.3
KSP plugin: 
`id 'com.google.devtools.ksp' version '1.8.10-1.0.9'`
and the dependencies:
`implementation 'io.github.raamcosta.compose-destinations:core:1.7.33-beta'
ksp 'io.github.raamcosta.compose-destinations:ksp:1.7.33-beta'`

**Comment by raamcosta** [comment]
Check this table:
https://developer.android.com/jetpack/androidx/releases/compose-kotlin

I'm not sure that it's related, but it seems like kotlin 1.8.10 should use compose 1.4.

Also, when you say "are not found" what exactly do you mean? Are imports all red? Can you re-import easily?

**Comment by balcartomas** [comment]
I have similiar issue with NavGraphs class.
I started to use this library recently and wanted to add it to the new project that I make. I annotated screens with RootNavGraph and re-build the project. I don't see any destinations, NavGraphs class or something else. Is it possible that root destination has to be in MainActivity file?

![image](https://user-images.githubusercontent.com/92251894/225859211-554ca368-2fdd-4901-9c33-6996e7a05cf7.png)

**Comment by raamcosta** [comment]
@saff1x let me know more details when possible :) 

Consider that destinations get generated in the package which has the common parts of all the annotated destinations. So if you add one that doesn't match the current, it will generate Destinations on a different package, so you would need to re-import them.

If that is annoying to you, you can set a fixed package name in the build.gradle file, like this:

```
ksp {
    arg("compose-destinations.codeGenPackageName", "your.preferred.packagename")
}
```
> REPLACE THE PACKAGE NAME TO YOUR PREFERENCE OFC 😄 

This will make it so the package names where the Destinations are being generated never changes anymore :)

**Comment by sam43** [comment]
@raamcosta I am facing the same issue with `kotlin version = 1.8.10`, `compose version = 1.4.4` and `compose destination version = 1.8.42-beta`. I have created the `srcDir` for generated code from the library but `NavGraphs.kt` is not generated. 
`
kotlin {
    sourceSets {
        debug {
            kotlin.srcDir("build/generated/ksp/debug/kotlin")
        }
        release {
            kotlin.srcDir("build/generated/ksp/release/kotlin")
        }
    }
}`

Tried out your last solution and it says `arg` is not recognized. Can you help me out with this one?

**Comment by raamcosta** [comment]
What ksp version are you using?

**Comment by aabadaa** [comment]
@raamcosta 
I have just updated the kotlin,ksp and compose destinations versions , the new versions are:
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
nav = "1.10.2"
In module build file I tried :
    applicationVariants.configureEach {
        kotlin.sourceSets {
            getByName(name) {
                kotlin.srcDir("build/generated/ksp/$name/kotlin")
            }
        }
    }


    ksp {
        arg("compose-destinations.codeGenPackageName", "com.cokids.app.destinations")
    }

and nothing is generated

**Comment by raamcosta** [comment]
Forget about 

>In module build file I tried :
applicationVariants.configureEach {
kotlin.sourceSets {
getByName(name) {
kotlin.srcDir("build/generated/ksp/$name/kotlin")
}
}
}

You can remove all that.

**Comment by raamcosta** [comment]
that was only needed for old kotlin versions

**Comment by aabadaa** [comment]
Thanks

**Comment by gptshubham595** [comment]
For me without setting sourceSets It was generating the code which I can see inside the build folder but  it was still unusable, on adding this I am able to use this inside my `:module:build.gradle.kts`

```
android {
 ....
     sourceSets {
        getByName("main") {
            java {
                srcDirs("../main/java")
            }
            kotlin {
                srcDirs("../main/kotlin")
            }
        }
    }
    }
    ```

**Comment by Aadityarawat** [comment]
> Check this table: https://developer.android.com/jetpack/androidx/releases/compose-kotlin
> 
> I'm not sure that it's related, but it seems like kotlin 1.8.10 should use compose 1.4.
> 
> Also, when you say "are not found" what exactly do you mean? Are imports all red? Can you re-import easily?

Hi raamcosta, I am using kotlin version 2.1.20 same for compose and your library 
implementation("io.github.raamcosta.compose-destinations:core:2.2.0")
   ksp("io.github.raamcosta.compose-destinations:ksp:2.2.0")

But in my main activity when I am trying to use 
DestinationsNavHost(navGraph = )

Not able to find NavGraphs.root & suggesting assign it with NavHostGraphSpec
