### ISSUE TITLE
navigation stack all clear ?

### ISSUE THREAD

**Issue by nari4169** [raamcosta/compose-destinations#379]
I am using this navigation well.
First of all, I would like to thank you.

My question is, in the state that the navigation has been executed several times,
Is there a way to delete all navigations that have been passed at once?

**Comment by raamcosta** [comment]
You mean you want to clear the back stack? Of course! You can do `navigator.popBackStack(NavGraphs.root)` for example. This will clear the backStack up to NavGraphs.root, which should be always the first there.

**Comment by nari4169** [comment]
Um... thanks, I'll use it well in the future내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: Rafael Costa ***@***.***> 날짜: 23/3/13  오전 7:24  (GMT+09:00) 받은 사람: raamcosta/compose-destinations ***@***.***> 참조: nari kang ***@***.***>, Author ***@***.***> 제목: Re: [raamcosta/compose-destinations] navigation stack all clear ? (Issue #379) 
You mean you want to clear the back stack? Of course! You can do navigator.popBackStack(NavGraphs.root) for example. This will clear the backStack up to NavGraphs.root, which should be always the first there.
