### ISSUE TITLE
compose 1.2.0-alpha01 support in 1.1.5 beta ??

### ISSUE THREAD

**Issue by knightsamir** [raamcosta/compose-destinations#38]
Hey there, does the latest version of compose destination 1.1.5 beta contains changes from compose 1.2.0-alpha01? Because it now supports to skipHalfExpaneded State in bottomsheet which i require.

**Comment by raamcosta** [comment]
At the moment the library is still using 1.1.0-rc2 compiler but I don't think this stops you from using the latest on your projects and benefiting from the skipHalfExpanded state in material bottom sheets.
As for the same thing for "navigation bottom sheets" we need to wait for the accompanist team to update it to, if they feel it's worth it.
