### ISSUE TITLE
[Question] Can we inject DestinationNavigator into ViewModel?

### ISSUE THREAD

**Issue by iamarjun** [raamcosta/compose-destinations#380]
As the title read, can we inject DestinationNavigator into our ViewModel? Is it a good practice to do so?

**Comment by raamcosta** [comment]
Just like with official libs’ (which you can also use with compose destinations) NavController, no you shouldn’t .

It is tied to things like the Activity, so you can leak those things if your ViewModel holds it.

**Comment by iamarjun** [comment]
Right, it makes sense, thanks
