### ISSUE TITLE
Execute code on entering nested NavGraph

### ISSUE THREAD

**Issue by mmolosay** [raamcosta/compose-destinations#381]
Hi! I was wondering, is there a possibility to execute (Composable) code, when entering some NavGraph?

My situation: I defined custom nested NavGraph, and I want to collect flow from ViewModel, which is tied to the whole NavGraph. Depending on collected values, respectfully navigate to destinations.
What can I do?

**Comment by raamcosta** [comment]
Hey! You can tie your VM to the NavGraph (see here: https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels#share-viewmodels-between-multiple-destinations) and the init block of that VM will be called when that NavGraph enters the back stack.

After that, you can expose a flow from that VM and listen for it in the Compose code "somewhere". If it's a place that has to be alive throughout the whole nav graph, probably you have to do it in the top level composable (where you call the DestinationsNavHost).

Nothing of this is specific to this library though, so search the web for how people are solving this using offiicial compose navigation. Solution will be very similar, just adapting small details.
