### ISSUE TITLE
Feature 💡

### ISSUE THREAD

**Issue by javierpe** [raamcosta/compose-destinations#385]
Multi module support for navigation

**Comment by pawelsmagala** [comment]
Not sure what you mean exactly, but there is support for multi-module navigation https://composedestinations.rafaelcosta.xyz/codegenconfigs#multi-module-configs

**Comment by raamcosta** [comment]
If there's something else @javierpe , let me know :)

**Comment by javierpe** [comment]
I have modules with specified screens and I want annotate with @Destination to be visible in nav graph.
