### ISSUE TITLE
Compose Destination recomposes on popping from backstack

### ISSUE THREAD

**Issue by SeethalakshmiSoman** [raamcosta/compose-destinations#386]
Hi , I am sorry to put this as an issue. What I wanted to do is, when I pop backstack, i dont want my compose view to get recomposed as the tab inside its getting reset(rememeberPagerState is not helping). It is causing issues for me. When I searched i found below piece of code but not sure how to use with DestinationNavigator. 

`navController.navigate(screen.route) {
              popUpTo(navController.graph.findStartDestination().id) {
                saveState = true
              }
              // Avoid multiple copies of the same destination when
              // reselecting the same item
              launchSingleTop = true
              // Restore state when reselecting a previously selected item
              restoreState = true
            } `

**Comment by raamcosta** [comment]
Hi!

I'm not sure what exactly is your issue and how to help, but you can use that piece of code you found in the exact same way with compose destinations.

**Comment by SeethalakshmiSoman** [comment]
Hi, I have a single activity and compose destinations in my app. In screen A, I have tabs 1,2 and 3. in any of the tab item if i click, it takes user to screen B. If I am clicking on item from tab 2 and navigating to screen B, When I press back from screen B, I want screen A to show tab 2 itself. Currently screen A is being recomposed and it reset to tab1 position.
In our app we are using DestinationsNavigator not NavigationController.

**Comment by raamcosta** [comment]
I still don't quite understand your scenario. 

However, this:

> In our app we are using DestinationsNavigator not NavigationController.

Is not really valid. DestinationsNavigator is only meant to navigate from screen to screen. You still can and should use NavController to do navigations from the top level (like from a bottom bar that's declared around the DestinationsNavHost) since there you won't have access to a DestinationsNavigator.

**Comment by SeethalakshmiSoman** [comment]
Hi, I am not using BottomNavigationBar. All I have is a screen with Tabs and some other screens to which we navigate on click of some views inside each tab screen. My only issue is my screen with tabs gets recomposed, when its loaded back from backstack. 
Thanks for your response. I will check this.
