### ISSUE TITLE
Navigation between DestinationsNavHost

### ISSUE THREAD

**Issue by renanboni** [raamcosta/compose-destinations#387]
Hi there,

I'm struggling to come up with a solution for my use case which is: I have a signup flow and once the user signs in or signs up I send him to the main flow, which is a screen with a bottom nav bar.

How can that be achieved using your library? I went through the documentation and the sample but they didn't cover it.

The way I thought about it is having a RootNavGraph and then inside of it I would have more two, one for the sign-in flow and the other for the main flow.

Any idea about how that can be achieved? 

Thank you.

**Comment by raamcosta** [comment]
Hey @renanboni !

This is not specific to my library, you can check any documentation for the official compose navigation and it will be the same (except the APIs to navigate may be slightly different, i.e, Destinations instead of string routes).

In my sample, I have a screen where I have a login button. You can imagine this being a more complex flow or form to sign up / login. In terms of navigating, it would be the same (at least it's one way of doing it).

**Comment by raamcosta** [comment]
Just an additional note: I see the title says navigation between Navhosts.. you don't need multiple NavHosts to use multiple nav graphs. You have the root one which contains everything else and it's passed to the NavHost and then all other nav graphs are nested in it.

**Comment by renanboni** [comment]
hey @raamcosta thank you for the reply, what I wanted to say is how to navigate between graphs I'm sorry for the confusion, let's say I have this root nav graph

    public val root: NavGraph = NavGraph(
        route = "root",
        startRoute = unLoggedIn,
        destinations = listOf(
            
        ),
		nestedNavGraphs = listOf(
			unLoggedIn,
			loggedIn
		)
    )
    
    How can I navigate from unLoggedIn to the loggedIn graph? when I try to navigate between them I get an exception saying that loggedIn it's not part of the unloggedIn graph

**Comment by raamcosta** [comment]
What nav graph are you passing to DestinationsNavHost?

**Comment by renanboni** [comment]
I have this logic based on login status

      ```
      val startRoute =
                if (!isLoggedIn) NavGraphs.unLoggedIn.startRoute else NavGraphs.loggedIn.startRoute
            val startGraph = if (!isLoggedIn) NavGraphs.unLoggedIn else NavGraphs.loggedIn
```

**Comment by raamcosta** [comment]
> in this case, is the root destinations list expected to be empty?

Yes, if you're not having any destination directly on root graph, then root contains only nested nav graphs.

```
  val startRoute =
            if (!isLoggedIn) NavGraphs.unLoggedIn.startRoute else NavGraphs.loggedIn.startRoute
        val startGraph = if (!isLoggedIn) NavGraphs.unLoggedIn else NavGraphs.loggedIn
```

I still don't know what parameter you're passing to DestinationsNavHost "navGraph". Is it also conditional? Is it the `startGraph` I see above?

**Comment by renanboni** [comment]
hey I made it work following the sample, I tried to avoid it because I've seen these lines here for example and it looks more like a workaround:

`BackHandler(true) { /* We want to disable back clicks */ }`
  ```
  val hasNavigatedUp = remember { mutableStateOf(false) }

    if (isLoggedIn && !hasNavigatedUp.value) {
        hasNavigatedUp.value = true // avoids double navigation

        if (!navigator.navigateUp()) {
            // Sometimes we are starting on LoginScreen (to avoid UI jumps)
            // In those cases, navigateUp fails, so we just navigate to the registered start destination
            navigator.navigate(NavGraphs.root.startAppDestination as DirectionDestination) {
                popUpTo(LoginScreenDestination) {
                    inclusive = true
                }
            }
        }
    }
```

**Comment by raamcosta** [comment]
It's not realy a workaround, but it may be specific to the sample app.

Can you answer my previous questions?

**Comment by renanboni** [comment]
yes both the start route and start graph were conditional in that case

**Comment by raamcosta** [comment]
But I don't know what you mean with "startGraph".. Is it what you're passing in the "navGraph" parameter of the DestinationsNavHost function?

**Comment by renanboni** [comment]
yes exactly, because I had 2 graphs, one to be used when the user is not authenticated and the other one otherwise, so my idea was to pass the navGraph conditionally based on the authentication state

**Comment by raamcosta** [comment]
Ok, so the graph you pass to DestinationsNavHost's "navGraph" parameter needs to contain all your destinations (directly or indirectly via nested graphs). So in your previous approach, you actually had to pass `NavGraphs.root` :) 
Otherwise the NavController inside won't be able to navigate to a nav graph it doesn't know about!

**Comment by raamcosta** [comment]
Unless of course you have multiple NavHosts, but even then you'd have multiple "top level" nav graphs one for each NavHost. With "top level" nav graph, I just mean a graph that doesn't have a parent like "root" one (but you can make more like these) -- these are the ones you want to be passing to NavHost, not the nested ones.

**Comment by renanboni** [comment]
thank you, I'll follow the approach you've taken in the sample and I'll refactor it down the road if needed, so far it seems to cover my use case. What's puzzling me now is after I added your lib into my project, there's a toolbar everywhere even though I disabled it in my theme, now I have to do this `actionBar?.hide()` in my activity.

**Comment by renanboni** [comment]
I had to go back to the separate NavGraphs approach :D 

I have these NavGraphs:

```
public object NavGraphs {

    public val loggedIn: NavGraph = NavGraph(
        route = "logged_in",
        startRoute = HomeScreenDestination,
        destinations = listOf(
            HomeScreenDestination
        )
    )

    public val unLoggedIn: NavGraph = NavGraph(
        route = "un_logged_in",
        startRoute = PreLoginDestination,
        destinations = listOf(
            LoginScreenDestination,
			PreLoginDestination
        )
    )

    public val root: NavGraph = NavGraph(
        route = "root",
        startRoute = unLoggedIn,
        destinations = listOf(
            CoachScreenDestination,
			MyProfileSettingsDestination,
			MyProfileDestination,
			RecoverPasswordDestination,
			SignUpDestination,
			TrainingSheetDestination
        ),
		nestedNavGraphs = listOf(
			loggedIn,
			unLoggedIn
		)
    )
}
```

and these annotations:

```
@RootNavGraph(start = true)
@NavGraph
annotation class LoggedInNavGraph(
    val start: Boolean = false
)

@RootNavGraph(start = false)
@NavGraph
annotation class UnLoggedInNavGraph(
    val start: Boolean = false
)
```

and in main activity I have this

```
   val startRoute =
                if (isLoggedIn) HomeScreenDestination else PreLoginDestination
                
DestinationsNavHost(
                            engine = engine,
                            navController = navController,
                            modifier = Modifier.padding(innerPadding),
                            navGraph = NavGraphs.root,
                            startRoute = startRoute
                        )
```
and I get this exception when I try to navigate from PreLogin to LoginScreen

**navigation destination pre_login is not a direct child of this NavGraph**

So it feels like the root is not considering all its children's destinations maybe?

**Comment by raamcosta** [comment]
Start destinations have to be direct childs I believe. Root doesn't have pre login as a direct child, it has the unloggedIn nav graph which then has the pre login destination as start.

So you need to pass NavGraphs.unloggedIn as the startRoute :)

**Comment by renanboni** [comment]
thanks a lot, and I'm sorry for bothering you this far but I still have one problem (I managed to navigate between NavGraphs following your recommendation)

```
DestinationsNavHost(
                            engine = engine,
                            navController = navController,
                            modifier = Modifier.padding(innerPadding),
                            navGraph = NavGraphs.root,
                            startRoute = startRoute
                        )
```

`    val startRoute =
                if (isLoggedIn) NavGraphs.loggedIn else NavGraphs.unLoggedIn`

and now the problem is whenever I navigate to any of the bottom nav destination the screen is recreated

here's the onClick of my bottom bar menu

`if (isCurrentDestOnBackStack) {
                        navController.popBackStack(destination.direction, false)
                        return@BottomNavigationItem
                    }

                    navController.navigate(destination.direction) {
                        popUpTo(NavGraphs.root) {
                            saveState = true
                        }

                        launchSingleTop = true
                        restoreState = true
                    }`

**Comment by raamcosta** [comment]
Try playing with what you're passing to popUpTo. It needs to be something common between the various tabs. Maybe use NavGraphs.loggedIn (assuming the tabs only show up when logged in).

**Comment by renanboni** [comment]
@raamcosta hey me again, I'm still hitting my head against the wall with the **DestinationsNavHost**.

Basically, I have two graphs besides the root - **loggedIn** and **unLoggedIn**.

`public object NavGraphs {

    public val loggedIn: NavGraph = NavGraph(
        route = "logged_in",
        startRoute = HomeScreenDestination,
        destinations = listOf(
            AccountingScreenDestination,
			CalculatedWorkoutScreenDestination,
			ChangeWorkoutScreenDestination,
			AddPaymentMethodScreenDestination,
			AnamneseFormDestination,
			ChangePasswordScreenDestination,
			ChangePrivateDataScreenDestination,
			CoachScreenDestination,
			InteractionHistoryScreenDestination,
			ComputeTrainingScreenDestination,
			DeleteAccountDialogDestination,
			HomeScreenDestination,
			MyProfileSettingsDestination,
			GenderPictureScreenDestination,
			MyProgressScreenDestination,
			MyProjectsScreenDestination,
			MyProfileDestination,
			NotificationScreenDestination,
			RatingScreenDestination,
			PaymentDestination,
			PaymentMethodScreenDestination,
			PerformanceScreenDestination,
			PlansScreenDestination,
			NewProjectScreenDestination,
			ProjectDetailDestination,
			SearchDestination,
			NotificationSettingsDestination,
			TrainingSheetDestination,
			TrainingCalendarScreenDestination,
			TrainingSheetFromCalendarDestination,
			WorkoutRoutineScreenDestination
        )
    )

    public val unLoggedIn: NavGraph = NavGraph(
        route = "un_logged_in",
        startRoute = PreLoginDestination,
        destinations = listOf(
            LoginScreenDestination,
			PreLoginDestination,
			RecoverPasswordScreenDestination,
			SignUpScreenDestination
        )
    )

    public val root: NavGraph = NavGraph(
        route = "root",
        startRoute = loggedIn,
        destinations = listOf(
            
        ),
		nestedNavGraphs = listOf(
			loggedIn,
			unLoggedIn
		)
    )
}`

And then I listen to a bool variable to decide what to send to user based on his authentication state:

` val startRoute =
                if (isLoggedIn) NavGraphs.loggedIn else NavGraphs.unLoggedIn`

`DestinationsNavHost(
                            engine = engine,
                            navController = navController,
                            modifier = Modifier.padding(innerPadding),
                            navGraph = NavGraphs.root,
                            startRoute = startRoute
                        )`

when isLogged changes from false to true, everything works as expected (note that I don't need to navigate since the recomposition will take care of changing the startRoute), but when it changes from true to false the app crashes saying that says this:

**Restore State failed: destination -424844665 cannot be found from the current destination NavGraph(0x78dcd1ef) route=root startDestination={NavGraph(0xbc16c415) route=logged_in startDestination={Destination(0x442b361f) route=home_screen}}**

Any idea about that? thanks in advance once again

**Comment by raamcosta** [comment]
Ok, I don't have all the context, but changing startDestination based on a compose state, is not a good idea 🤔 

Start route is the "Start" of the app. If you see in my sample, I'm listening for "isLoggedIn" state and if I'm not logged in I manually navigate to LoginScreen. At least this is how I see it.
A good option might also be to check this error on google or on Kotlin slack channel. This is definitely not something the library is doing, so with official compose navigation this would also happen.
