### ISSUE TITLE
[Help Needed] Want to know backStack status of compose destinations

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#389]
I have a usecase where I want to know whether compose navigation backstack is empty or not.

In my activity's oncreate I initialise DestinationNav host

`override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
      
        setContent {
            DestinationsNavHost(navGraph = NavGraphs.root, dependenciesContainerBuilder = {
            dependency(xxActivity)
        })
    }`
    
    
In this same activity I have the following code for onBackPressed,

`override fun onBackPressed() {
         if (isTaskRoot) {
            // Navigate to some other non compose related activity
        } else {
            super.onBackPressed()
        }
    }`

Here what happens is if `super.onBackPressed()` is called then compose navigation works fine & if `isTaskRoot` gets executed then flow goes to some other activity.

What I want to achieve is that 
`if (isTaskRoot && composeDestination.isSizeOne())`

What I mean is in case of compose destination backstack, if only one destination is present (this is the single destination currently in backstack) then only navigate to some other activity else just navigateUp for compose destination.

@raamcosta Can you please guide me on how can I achieve this

**Comment by raamcosta** [comment]
It's hard for me to tell you exactly what to do since I haven't been on this situation before. What I can say is that this is not unique to compose destinations library. You can pass a NavController to DestinationsNavHost and make operations on that NavController, including calling `navigateUp` and checking if that returns true or false. If it returns false, maybe it is some indication for you that you should instead navigate to some other non compose activity.

But this is just my immediate thoughts :) I would search around for official compose navigation approaches and then it should be trivial to do the same with Compose Destinations. If you don't know how to do the same in this library, then I can help :)

**Comment by UKMIITB** [comment]
@raamcosta 
How can I get access to navController in my parent activity.
I was able to find solution for this using navController.

In normal compose navigation onCreate of parent activity we do is 
```
val navController = rememberNavController()
NavHost(
        navController = navController,
        startDestination = "home"
    ) {
}
```

But in your library we just add this in onCreate of parent activity
DestinationsNavHost(navGraph = NavGraphs.root)

How can I get access to navController here.
Because I checked DestinationsNavHost take navController from NavHostEngine
So if I use rememberNavController() will it be the same ?

**Comment by raamcosta** [comment]
Hi @UKMIITB 

Next time it's better to open a new issue, so we are sure I don't miss your question :)

To get NavController you can do exactly the same. rememberNavController and pass that to DestinationsNavHost.

You can also still do the exact same comparation, each generated Destination has a `route` field you can use.

**Comment by UKMIITB** [comment]
@raamcosta 
As it was related conversation hence continued on this itself.

Currently I have only included your library as dependency & not native dependency.
So when calling `rememberNavController(navigators = )` it needs `navigators` as parameter.
Can you please help as to what should I pass in this.
I would prefer to use only your library & not include native dependency if possible

**Comment by raamcosta** [comment]
My dependency also brings native dependency transitively :) So you don't need to add it explicitly, but if you would that would basically be the same ;)

Anyway, you don't need to pass anything in this rememberNavController. This is the exact same method you are calling now that you would call if using native dependency directly.

**Comment by raamcosta** [comment]
So just do `rememberNavController()`. :)

**Comment by UKMIITB** [comment]
Got it.
Was having some sync issues.
Thank You so much for your help :)
