### ISSUE TITLE
Pass data to previous composable in lib

### ISSUE THREAD

**Issue by amirzeinaly** [raamcosta/compose-destinations#39]
I have 2 Screens: Screen A and Screen B. From Screen A, I open Screen B. And when I return Screen B to Screen A, I want to transfer data back to Screen A.

Is there any solution for this?

**Comment by knightsamir** [comment]
use   navController.previousBackStackEntry?.savedStateHandle?.set(key,value) to pass data from Screen B and receive it in A with navController.currentBackStackEntry?.savedStateHandle?.getLiveData<T>(key)

**Comment by raamcosta** [comment]
Yeah at the moment there is no special help or support in the library to make this easier or safer. 
So as @knightsamir said, that is your solution.

Maybe in the future I can explore something to make this also type safe. But that will be low priority enhancement.

I'm closing this issue. Let me know if this helped @amirzeinaly

**Comment by amirzeinaly** [comment]
yes this solution works but i want to know any safer and easier way is exist in Compose destination lib or not

thanks

**Comment by raamcosta** [comment]
It was a totally valid and relevant question! 👍 

As I said, maybe I can check something to improve it later. No promises for now though.

**Comment by raamcosta** [comment]
@amirzeinaly @knightsamir 

New release has a new feature to make this easier and safer. Let me know if you like it 🙂

**Comment by amirzeinaly** [comment]
Thank you you are wonderful
