### ISSUE TITLE
Missing import in generated desinations list for "destinations" mode

### ISSUE THREAD

**Issue by krzysztofdrobek** [raamcosta/compose-destinations#391]
DestinationSpec import is missing in a generated destinations list in a module with only one desination declared and "destinations" mode set.

I'm using version 1.8.37-beta.

This is what's generated:
```
package redactedpackage

import redactedpackage.destinations.*

public val onboardingFeatureDestinations: List<DestinationSpec<out Any>> = listOf(
	OnboardingDestination
)
```

**Comment by raamcosta** [comment]
Thank you so much for reporting. It was my bad here. Should be fixed in new version which is cooking right now 🙂
