### ISSUE TITLE
When is the earliest you can get an instance of DeatinationNavigator?

### ISSUE THREAD

**Issue by dylan-kwon** [raamcosta/compose-destinations#394]
When is the earliest you can get an instance of DeatinationNavigator?

Can I directly create a destinationNavigator outside of NavHost and inject it into each screen?

**Comment by raamcosta** [comment]
Hi!

DestinationsNavigator is a navigator meant ONLY to navigate from a screen to another screen.
Top level navigation needs a NavController just like official compose navigation.

I’m not sure what you mean with injecting it on each screen.. this is what the library already does by default. You only need to add the parameter to the annotated Composable and the library will provide it..

**Comment by raamcosta** [comment]
Hey @dylan-kwon , let me know if this helped 🙂

**Comment by dylan-kwon** [comment]
It's been helpful to me.
