### ISSUE TITLE
Help with @kotlinx.serialization.Serializable as Nav Argument

### ISSUE THREAD

**Issue by Wrakor** [raamcosta/compose-destinations#395]
Current version: 1.8.38-beta, ksp 1.8.10-1.0.9

Hey,

I'm currently trying to have a Serializable class as a nav argument.

```
@Destination
@Composable
fun ArticleDetailScreen(articleResource: ArticleResource) {...}

@Serializable
data class ArticleResource(
    val id: String,
    val title: String,
    val author: String,
    val content: String,
    val publishDateTime: LocalDateTime
)
```

But the generated Destination class is not taking the articleResource into account.

```
public object ArticleDetailScreenDestination : ArticlesDirectionDestination {
         
    public operator fun invoke(): Direction = this
    
    @get:RestrictTo(RestrictTo.Scope.SUBCLASSES)
    override val baseRoute: String = "article_detail_screen"

    override val route: String = baseRoute
    
    @Composable
    override fun DestinationScope<Unit>.Content() {
		val dependencyContainer = buildDependencies()
		ArticleDetailScreen(
			articleResource = dependencyContainer.require()
		)
    }
    
}
```

Or maybe I'm missing something here:
navController.navigate(ArticleDetailScreenDestination() within navGraph) 

How can I achieve this?

**Comment by raamcosta** [comment]
Can you try removing `publishDateTime` from that class? just to see if lib will consider it then?

I also noticed `within navGraph`.. do you have a multi module app? Is `ArticleResource` in the same module of `ArticleDetailScreen` ?

**Comment by Wrakor** [comment]
I do have a multi module app, and `ArticleResource` is actually in another module. 
I have app (navigation) -> feature (screen) -> data (model).

I tried removing the publishDateTime and no luck. 
(I also noticed that if I instead extend java.io.Serializable in ArticleResource, the generated class will add the argument, so it appears to be something to do with kotlinx Serializable)

**Comment by raamcosta** [comment]
I'll close this issue then. We'll have better support for multi module coming this year :)

**Comment by davidmarinangeli** [comment]
@Wrakor I've got the same issue, I tried to include the library in every module and to add the `Serializable` annotation on every object I used: I even tried to convert every list in ArrayList after reading [another issue here](https://github.com/raamcosta/compose-destinations/issues/29). The project still gives me: 

[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Composable **'NameOfMyScreen':** annotated function cannot define arguments of navigation type if using a 'navArgsDelegate' class. (check argument 'level'

**Comment by guessthecar** [comment]
@raamcosta I encountered the same problem now with one single screen. Version 1.9.52

I am trying to pass the same argument to various kinds of screens. On all of them I can do 

`@Destination()
@Composable
fun ScreenB(
    level: Level,`

and then I pass the `Level` object as a parameter by doing `navController.navigate(ScreenBDestination(level))`. In my "Screen C" I'm doing the same

`@Destination()
@Composable
fun ScreenC(
    level: Level,
`

but I can't find the right constructor when I try to do so. 

<img width="308" alt="image" src="https://github.com/raamcosta/compose-destinations/assets/128176152/1da4c927-65a0-4602-a766-2ffb8fcd41ba">

Again, if I try to pass this object as NavArgs it tells me the problem I told you before in my last message. What am I doing wrong? 

Thanks!

**Comment by raamcosta** [comment]
Did you rebuild the app?

**Comment by guessthecar** [comment]
I cleaned it, rebuilt it, I'm trying to read the Destination file and then I'll try another version of the library.

**Comment by raamcosta** [comment]
Can you link your previous message?

**Comment by raamcosta** [comment]
If you use navArgsDelegate = SomeClass::class

then do 

data class SomeClass(val level: Level)


Does it work?

**Comment by guessthecar** [comment]
Then it tells me the same error of @davidmarinangeli . 

`[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Composable 'AttributionDetailScreen': 'navArgsDelegate' cannot have arguments that are not navigation types. (check argument 'level')`

even if the same class is passed as argument in the same project on different screens.

**Comment by raamcosta** [comment]
What is Level class? Is it an enum or Serializable or why do you think it is a nav argument type?

**Comment by guessthecar** [comment]
It's a serializable object with all Arraylists, Strings, Ints, and one enum. It's also used in other screen and passed as an argument in the "Screen B" I wrote above. ☹️

**Comment by raamcosta** [comment]
Ok no worries thanks 😄

is it declared in a different module?

**Comment by raamcosta** [comment]
ScreenC screenB and the Level class are all on the same module?

**Comment by guessthecar** [comment]
Nope!

**Comment by raamcosta** [comment]
Can you tell me which are on which modules?

I think that the module where you’re describing screen C doesn’t see the class Level as Serializable.

**Comment by guessthecar** [comment]
Yeah Screen C is on another module of Screen B but the class Level is on another module of both of them. Could it be a dependency problem on the project?

**Comment by raamcosta** [comment]
Btw if your Level class all fields are also navigation types, then you don’t need to make it serializable.  (And if you do make it serializable and you declare it as its own navigation argument, then it doesn’t really matter what types it has internally, I.e you can use normal Lists instead of ArrayLists for example).

You can do navArgsDelegate = Level::class and instead of ending up with one navigation argument with a complex type you’ll have each field of Level class as its own navigation argument.

I think it may solve your issue.

**Comment by raamcosta** [comment]
> Yeah Screen C is on another module of Screen B but the class Level is on another module of both of them. Could it be a dependency problem on the project?

Yes it could. Probably module where screen C is declared doesn’t use kotlinx serialization? 🤔 let me know if you figure it out, I’d like to check if I can improve the error message for your particular case.

**Comment by guessthecar** [comment]
I'll check it out. It could definitely be because ScreenC is on a brand new module. 

Thanks!

**Comment by guessthecar** [comment]
Solved by adding the kotlinx dependency on the new module ( where ScreenC is ). Thanks a lot and sorry for the objects and screens shenanigans.

**Comment by raamcosta** [comment]
Great!

No worrries at all! Sorry if I sounded annoyed I wasn’t! I was just quick answering on the phone ahah 😝 

glad it was fixed!

**Comment by guessthecar** [comment]
No you were not, no worries and thanks for the lightning speed of response ⚡️
