### ISSUE TITLE
Bottom Sheet Destinations opened via a deeplink are opened over a black screen.

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#396]
I'm not sure if this is a compose-destinations issue, an accompanist issue, google's compose-navigation issue or my fault, so let's start here.
The basic problem is, destinations that have the BottomSheet style, when opened via a deeplink (using Intent.VIEW) are opened over a black screen, regardless of whether there are destinations in the backstack or not. When the bottom sheet is closed by a gesture, a black screen is displayed.
When the bottom sheet is closed via a back button, the app works normally.

**Comment by raamcosta** [comment]
I am pretty confident this is not a compose destinations issue. I will mark this with dependency label. If someone can try to reproduce with a simple accompanist sample that would be great 🙏

**Comment by Nek-12** [comment]
This issue seems to have been fixed in upstream
