### ISSUE TITLE
How to handle pager-like wizards?

### ISSUE THREAD

**Issue by mainrs** [raamcosta/compose-destinations#397]
Is it possible to create wizards (for on-boarding for example) with a progress bar where each page is a `@Destination`? Maybe taking advantage of a sub-`@NavGraph`. 

I currently implement this using the `HorizontalPager` component. But with this approach it is simply a destination inside my `@RootNavGraph`.

**Comment by raamcosta** [comment]
Personally I would have a single Destination with a Pager yes, I think it will be easier and work just as well :)

**Comment by raamcosta** [comment]
This is nothing to do with this library in particular btw, you can check how other people are doing with official compose navigation and apply that here :)
