### ISSUE TITLE
Setting a startRoute that contains a variable?

### ISSUE THREAD

**Issue by chrisdonovan1006** [raamcosta/compose-destinations#398]
Hey first thank you @raamcosta for a great library.

I have an issue when trying to set the startRoute in the app.  I need to set a navArg value (this value is an id that is stored in datastore to persist after a restart.)  However I can't figure out how to set the navarg variable in the Destination item and pass it to the NavHost startRoute.

```
val id by vm.appId.collectAsState()

    val startRoute = if (loginComplete) {
        LandingPageDestination(id = id)          // CAUSE
    } else {
        if (onBoardingComplete) {
            LoginScreenDestination
        } else {
            NavGraphs.root.startRoute
        }
    }


    DestinationsNavHost(
            engine = engine,
            navController = navController,
            navGraph = NavGraphs.root,
            modifier = Modifier.padding(2.dp),
            startRoute = startRoute                // ERROR 
    )
```

If I change _LandingPageDestination(id = id)_ to _LandingPageDestination_  and do some handling of the id in viewmodel/repo I can get it to run ok, just wondering is there a way for me to set a startRoute that contains a variable?

**Comment by raamcosta** [comment]
Hi @chrisdonovan1006 👋

No, not possible. Start route cannot contain navigation arguments. Navigation arguments are used when there is a previous screen sending something to next screen and in this case there is no previous screen 🙂

You can of course pass whatever you need from the NavHost level with these options:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters

Let me know if I can help any further!

**Comment by chrisdonovan1006** [comment]
Hey @raamcosta,

Thanks for the quick response, that makes sense I can handle navarg if null anyways in the viewmodel so I not a major issue. Great work with library.

**Comment by raamcosta** [comment]
Btw this is not a limitation with this lib. It’s a limitation from jetpack compose navigation which we inherit.
