### ISSUE TITLE
[Question] Multiple DestinationNavigationHost

### ISSUE THREAD

**Issue by javierpe** [raamcosta/compose-destinations#399]
Hi, I have the following questions about DestinationNavigationHost:

1. Can coexist two or more host?
2. In true case, how can I navigate between hosts?
3. How can avoid that the navigation host contains all graphs in multi module app?

Im building a multi module app with your library for research the best posible architecture in this repo:
[ArtGallery](https://github.com/javierpe/ArtGallery/tree/task/refactor-modules)

Thanks in advance!

**Comment by raamcosta** [comment]
Hi @javierpe !


1. Yes, you can.

2. When you have Multiple NavHosts (lets say A and B), there will be one Destination of NavHost A that will call NavHost B. This destination has access to both NavControllers (from A and B). To navigate to a Destination that belongs to NavHost A, you use NavController from A, to navigate to a Destination that belongs to NavHost B, you use NavController from B.
You can then use a class like `class NavHostANavigator(val navController: NavController)` and pass that class via `dependencyContainerBuilder` (https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters#use-dependenciescontainerbuilder-to-prepare-dependencies). After that, any destination from NavHost B that requests for a `NavHostANavigator` class will have it and can use that to navigate to NavHostA's destinations.

3. You need to have multiple "top level" NavGraphs you pass one of those for each NavHost. 
https://composedestinations.rafaelcosta.xyz/defining-navgraphs#through-navgraph-annotations (search for "top-level").
Then you use those NavGraph annotations to have either destinations or nested graphs be a part of it. And then you pass those top level NavGraphs one for NavHostA and the other to NavHostB.

**Comment by raamcosta** [comment]
Let me know if this helped :)

**Comment by javierpe** [comment]
@raamcosta Thank you! Only a last question, how can I build a BottomBarNavigation without DestinationsNavHost?
