### ISSUE TITLE
[Request]: Please add GIF to the Readme.md

### ISSUE THREAD

**Issue by Drjacky** [raamcosta/compose-destinations#4]
Please add a GIF to the README.MD so, we can see how does the result look like?

**Comment by raamcosta** [comment]
Hi @Drjacky !
Thanks for the question. Just to be sure I understand, what exactly would you like to see in the GIF? The code or the app running in the device?

**Comment by Drjacky** [comment]
Yes, please. The demo.

**Comment by raamcosta** [comment]
I don't think a GIF showing the app is needed. It is a basic sample that behaves exactly like if it was only using the official navigation for Compose component.
What this lib is great at is at simplifying the code to achieve that final result.
Does that make sense? So the only thing worth featuring is the code itself.

Unless I'm misunderstanding something about your request 😅

Thanks again and let me know what you think 🙂
