### ISSUE TITLE
Navigation issue when have WebView inside compose screen

### ISSUE THREAD

**Issue by Al-khateebBahaa** [raamcosta/compose-destinations#404]
I have a screen that contains a Webview inside it, and when I'm trying to navigate or navigate up, it cause a crash.

Crash message:
**A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 8805 (RenderThread)**

Compose Screen:

  Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
    ) {

        DetailsHeaderCard(Modifier, JobData()) //TODO: update this
        JobSectionAndDateBar()
        WebViewContent(detailsState.data?.jobs?.detailsAr ?: "")

        Spacer(modifier = Modifier.height(LocalSpacing.current.small))

        if (!detailsState.data?.jobs?.urlReg.isNullOrEmpty())
            DetailsButton(
                text = stringResource(id = R.string.reg_url),
                buttonBackgroundColor = PinkColor
            ) {

            }

        Spacer(modifier = Modifier.height(LocalSpacing.current.small))

        if (!detailsState.data?.jobs?.source.isNullOrEmpty())
            DetailsButton(
                text = stringResource(id = R.string.source_url),
                buttonBackgroundColor = Color.Gray
            ) {

            }

        Spacer(modifier = Modifier.height(LocalSpacing.current.small))

        if (!detailsState.data?.jobs?.twitterUrl.isNullOrEmpty())
            DetailsButton(
                text = stringResource(id = R.string.comments_url),
                buttonBackgroundColor = Color.Cyan
            ) {

            }

    }

**Comment by raamcosta** [comment]
HI @Al-khateebBahaa 

I have no idea but it most likely is not caused by this library. Try searching on stackoverflow or Kotlin slack, maybe someone else has experienced this issue.

**Comment by xVemu** [comment]
@Al-khateebBahaa any news on this?
