### ISSUE TITLE
Problem when navigating between NavGraphs

### ISSUE THREAD

**Issue by renanboni** [raamcosta/compose-destinations#406]
Hey!

I'm having a few issues with my navigation graph setup, I have 2 NavGraphs:

```
@RootNavGraph(start = false)
@NavGraph
annotation class LoggedInNavGraph(
    val start: Boolean = false
)

@RootNavGraph(start = true)
@NavGraph
annotation class UnLoggedInNavGraph(
    val start: Boolean = false
)
```

and when I navigate from **UnLoggedInNavGraph** to **LoggedInNavGraph** I want to pop up the **UnLoggedInNavGraph** from the stack (so if I press back the app should close instead of coming back to the **UnLoggedInNavGraph**) - this is working but I'll share the code anyway:

`navController.navigate(HomeScreenDestination) {
                    popUpTo(NavGraphs.root) {
                        inclusive = true
                    }
                }`

but when I want to do the opposite, i.e, navigating from LoggedInNavGraph to **UnLoggedInNavGraph** I want to pop up the **LoggedInNavGraph** from the stack and show the login screen again but it doesn't work all the time, sometimes it does sometimes it doesn't and when it doesn't if I press back I'll be sent to the screen I was before signing out. Here's the code:

```
navController.navigate(PreLoginDestination) {
                    popUpTo(NavGraphs.root) {
                        inclusive = true
                    }
                }
```

and here's the code of my MainActivity:

```                Scaffold(
                    bottomBar = {
                        if (shouldShowBottomNav(currentDestination)) {
                            BottomBar(navController = navController)
                        }
                    },
                ) { innerPadding ->
                    DestinationsNavHost(
                        engine = engine,
                        navController = navController,
                        modifier = Modifier.padding(innerPadding),
                        navGraph = NavGraphs.root,
                        startRoute = NavGraphs.unLoggedIn
                    )

                    if (viewModel.isLoggedIn && !NavGraphs.loggedIn.destinations.contains(
                            currentDestination
                        )
                    ) {
                        navController.navigate(HomeScreenDestination) {
                            popUpTo(NavGraphs.root) {
                                inclusive = true
                            }
                        }
                    }
                }
```

I have that logic to navigate the user to the LoggedInGraph in case he's already authenticated.

Here's the generated NavGraphs.kts:

`public object NavGraphs {

    public val loggedIn: NavGraph = NavGraph(
        route = "logged_in",
        startRoute = HomeScreenDestination,
        destinations = listOf(
            AccountingScreenDestination,
			CalculatedWorkoutScreenDestination,
			ChangeWorkoutScreenDestination,
			AddPaymentMethodScreenDestination,
			AnamneseFormDestination,
			ChangePasswordScreenDestination,
			ChangePrivateDataScreenDestination,
			CoachScreenDestination,
			InteractionHistoryScreenDestination,
			ReceiptScreenDestination,
			ShareReceiptScreenDestination,
			ComputeTrainingScreenDestination,
			CreateProjectDestination,
			DeleteAccountDialogDestination,
			HelpScreenDestination,
			HomeScreenDestination,
			AddNewProjectMemberScreenDestination,
			ManageMembersScreenDestination,
			MyProfileSettingsDestination,
			GenderPictureScreenDestination,
			MyProgressScreenDestination,
			MyProjectsScreenDestination,
			MyProfileDestination,
			NotificationScreenDestination,
			NotificationSetupDestination,
			RatingScreenDestination,
			InstallmentsScreenDestination,
			PaymentDestination,
			PaymentMethodScreenDestination,
			PerformanceScreenDestination,
			PlansScreenDestination,
			NewProjectScreenDestination,
			ProjectDetailDestination,
			ProjectMemberDestination,
			ProjectMembersScreenDestination,
			SearchDestination,
			SelectWorkoutScreenDestination,
			NotificationSettingsDestination,
			TrainingSheetDestination,
			TrainingCalendarScreenDestination,
			TrainingSheetFromCalendarDestination,
			WorkoutRoutineScreenDestination
        )
    )

    public val unLoggedIn: NavGraph = NavGraph(
        route = "un_logged_in",
        startRoute = PreLoginDestination,
        destinations = listOf(
            LoginScreenDestination,
			PreLoginDestination,
			RecoverPasswordScreenDestination,
			SignUpScreenDestination
        )
    )

    public val root: NavGraph = NavGraph(
        route = "root",
        startRoute = unLoggedIn,
        destinations = listOf(
            
        ),
		nestedNavGraphs = listOf(
			loggedIn,
			unLoggedIn
		)
    )
}`

and here is a simple diagram to illustrate the problem:

![IMG_BEB8FC183A33-1](https://user-images.githubusercontent.com/12984721/231584836-ef0e16ca-ae7d-4b8c-86e8-f41ee540022c.jpeg)

Thank you!

**Comment by raamcosta** [comment]
Without having much more time, just a quick thing you can try:

```
navController.navigate(HomeScreenDestination) { popUpTo(NavGraphs.root) }
```

Basically with inclusive = false (default). Same thing when you do the opposite from logged in to unlogged in.

**Comment by raamcosta** [comment]
I'm not 100% sure, but it does make more sense to me this way. The root is something you don't necessarily want to remove from back stack.

**Comment by renanboni** [comment]
I made those changes but still getting the same problem, sometimes it works sometimes it doesn't

**Comment by renanboni** [comment]
@raamcosta do you know what else could be the problem?

**Comment by renanboni** [comment]
also, the viewmodels onCleared don't get called when I navigate from loggedIn to unLoggedin graph, so if I log in a different user, all the data from the previous user will be there

**Comment by Vlado24** [comment]
@renanboni use this block of code to print backQueue (from [tivi project](https://github.com/raamcosta/tivi)):
```
fun ArrayDeque<NavBackStackEntry>.print(prefix: String = "stack") {
    val stack = toMutableList()
        .map { it.destination.route }
        .toTypedArray().contentToString()
    println("$prefix = $stack")
}
```

**Comment by renanboni** [comment]
@Vlado24 thanks!

**Comment by renanboni** [comment]
@Vlado24 thanks!

**Comment by raamcosta** [comment]
Logging the backstack was exactly what i was gonna suggest next. I'm sure there's some issue in your setup. Let me know once you know more and post the logs so I can see it as well.

**Comment by renanboni** [comment]
how can I use that extension function? even in the mentioned project it is not used

**Comment by raamcosta** [comment]
https://github.com/raamcosta/compose-destinations/blob/main/sample/src/main/java/com/ramcosta/destinations/sample/ui/composables/SampleScaffold.kt

**Comment by renanboni** [comment]
ok I found the problem,

`navController.navigate(destination.direction) {
                        popUpTo(HomeScreenDestination) {
                            saveState = true
                        }

                        launchSingleTop = true
                        restoreState = true
                    }`

I had **NavGraphs.loggedIn** in the **popUpTo** function.

But now there is another problem, the viewmodel from the bottom sheet screens aren't getting destroyed when I log out even though the destinations are (I don't see them in the print).

Any idea? thanks!

**Comment by raamcosta** [comment]
Save state and restore state make VMs not be destroyed as it turns out.

Try without those. Let me know what’s the result

**Comment by renanboni** [comment]
But if I remove those the VMs will be recreated whenever I switch tabs from the bottom nav. When I was using the compose library I had those set to true, the difference is that when I popped out a graph - like I'm doing here, the VMs were destroyed altogether

**Comment by raamcosta** [comment]
I mean, this library is not handling any of this, this is handled by the official navigation library 🤔 So the behavior has to be the same...

**Comment by raamcosta** [comment]
@renanboni if you really believe this to be a behaviour that only happens when using compose destinations, please create a small sample that reproduces the issue and one that uses compose navigation directly and doesn't have this issue. I can use these to debug and see if there is indeed some unexpected issue on my side.

You can also just create one of the two samples (with Compose Destiantions or without) and I'll make the counterpart.

**Comment by raamcosta** [comment]
I'll close this for being stale for 3 weeks. I don't see any issue here coming from Compose Destinations. 

I'll still be happy to take a look at those small samples so I can dig deeper.
