### ISSUE TITLE
Firebase breadcrumbs

### ISSUE THREAD

**Issue by nrobi144** [raamcosta/compose-destinations#407]
### Description
A nice extension would be to have automatic firebase screen/destination logs (see [Measure screenviews](https://firebase.google.com/docs/analytics/screenviews#manually_track_screens) for more info)

Currently there are no automatic breadcrumbs if someone is using a Single Activity pattern.

### Implementation 
```
@Composable
    override fun DestinationScope<Destination>.FirebaseContent(
    ) {
        firebaseAnalytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW) {
            param(FirebaseAnalytics.Param.SCREEN_NAME, Destination.name)
            param(FirebaseAnalytics.Param.SCREEN_CLASS, Destination.class.simpleName)
        }
    }
```

**Comment by nrobi144** [comment]
Closing this as the `DestinationWrapper` is a nice way of solving this. 

Example code:
```
object FirebaseDestinationWrapper : DestinationWrapper {

    @Composable
    override fun <T> DestinationScope<T>.Wrap(
        screenContent: @Composable () -> Unit
    ) {
        val context = LocalContext.current
        FirebaseAnalytics.getInstance(context)
            .logEvent(FirebaseAnalytics.Event.SCREEN_VIEW) {
                param(FirebaseAnalytics.Param.SCREEN_NAME, destination.route)
                param(
                    FirebaseAnalytics.Param.SCREEN_CLASS,
                    destination::class.simpleName.toString()
                )
         }
        screenContent()
    }
}
```

Usage:

```
@Destination(wrappers = [FirebaseDestinationWrapper::class])
@Composable
fun YourScreen() {}
```

@extmkv would be nice to set a default wrapper

**Comment by raamcosta** [comment]
Nice thanks @nrobi144

I’ve been toying with the idea of letting developers create their own Destination annotations by using other annotations. This way you could have @FirebaseDestination or just @AppDestination or whatever name you wanted and you’d place the wrapper only once in the definition of said annotation.

**Comment by jorrhe** [comment]
@raamcosta 

I love the idea, it would reduce a lot of code when defining `@Destination` with multiple wrappers.

**Comment by raamcosta** [comment]
@jorrhe and @nrobi144 I just did it! You can now do this on versions 1.x.41-beta! Please do let me know how it goes.

**Comment by jorrhe** [comment]
@raamcosta I have tried it already, and It's exactly what I was hoping for! Thank you so much I love your library!
