### ISSUE TITLE
How to obtain a backstackEntry.destination.route using compose destinations?

### ISSUE THREAD

**Issue by GermanMontejo** [raamcosta/compose-destinations#408]
Hi I'm using a BottomNavigation and I was wondering how I can obtain the backstackEntry.destination.route using ComposeDestinations. It's not listed in the documentation.

**Comment by raamcosta** [comment]
Hi German!

If I understand the question correctly, then the answer is: in the exact same way as with official compose navigation.

Get an instance of NavController with rememberNavController, pass that to DestinationsNavHost and use it to get current destination.

**Comment by raamcosta** [comment]
Let me know if I can help any further

**Comment by raamcosta** [comment]
https://composedestinations.rafaelcosta.xyz/common-use-cases/bottom-bar-navigation

Check this as well
