### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by parthdesai1208** [raamcosta/compose-destinations#409]
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.animation.AnimatedContentScope"

I am using library version:
  ```
  implementation 'io.github.raamcosta.compose-destinations:core:1.8.39-beta'
    implementation 'io.github.raamcosta.compose-destinations:animations-core:1.8.39-beta'
    ksp 'io.github.raamcosta.compose-destinations:ksp:1.8.39-beta'
```
```
plugins {
id 'com.google.devtools.ksp' version '1.8.20-1.0.11'
}
```
compose compiler version - "1.4.5"

**Comment by raamcosta** [comment]
Yes this is known issue with latest version of animated core. I will make a new release today with the fix.

thanks for reporting anyway 🙏
