### ISSUE TITLE
Unable to access generated destination composable

### ISSUE THREAD

**Issue by IshikaEkincare** [raamcosta/compose-destinations#411]
after building the project the destination composables in visible in generated folder but when i try to access that file it is not accessible over there

**Comment by raamcosta** [comment]
Hi! I really need way more info to be able to help 😅

What exactly are you seeing? What isn’t working? Maybe some screenshots would help. Also what versions of Kotlin, Compose and Compose Destinations are you using?

**Comment by raamcosta** [comment]
Closing this for being stale for 3 weeks. I'll be happy to reopen if you have more info for me 🙂
