### ISSUE TITLE
Build Navigation history from startup across multiple navgraphs

### ISSUE THREAD

**Issue by mmeven** [raamcosta/compose-destinations#412]
Hello !

For context, our app has multiple nested nav graphs. To simplify, we can put it like this : 

RootNavGraph -> BottomBarNavGraph -> SettingsNavGraph

The bottom bar navigation is implemented as presented in your documentation.

From the start of the app, ie. a destination contained within RootNavGraph, we'd like to navigate to a destination within SettingsNavGraph, but also going through the BottomBarDestination, so when we press back, the backstack is "as if" all navigation was made by hand. The bottom bar should appear on destinations within BottomBarNavGraph and all nested nav graphs.

We were able to produce this behavior by finding a way so that each destination knows if it must navigate directly on opening, by storing some redirectionDestination in viewModels, etc. We find this tedious and not very clean. 

The next approach we've tried is to navigate several times from the first screen, with multiple `navigator.navigateTo(...)` : the backstack is correct, but the bottombar doesn't appear in the final destination. My guess is that the navigation isn't really made in the nested nav graph.

Is this kind of navigation possible or not ? Are we missing something ?

**Comment by raamcosta** [comment]
Hi @mmeven !

I believe this is going to be a question for official compose navigation and not really for compose destinations. Compose Destinations doesn't mess with anything related to this, it just uses the official library.

I would google it, or open a stackoverflow question or post the question Kotlin slack #compose channel.
