### ISSUE TITLE
BottomSheet Destination Style Not Found on Recent Beta Released

### ISSUE THREAD

**Issue by niyajali** [raamcosta/compose-destinations#413]
Hi, First of all, thank you for the great library,

Recently I updated my project to the latest beta version of this library(1.9.41-beta) and got some errors like 
```An annotation argument must be a compile-time constant ```  in BottomSheet Destination only, In the 1.8.32-beta version it's working fine.

I checked it seems like there's no BottomSheet object inside the DestinationStyle Interface,

I would like to know does it moved to another interface or was removed permanently on the latest version because I used BottomSheet Destination on many screens and unable to run my project, Thank you!

**Comment by raamcosta** [comment]
https://github.com/raamcosta/compose-destinations/releases/tag/1.9.40-beta

Hopefully this will provide all info. Let me know if you have any other question. Also let me know if you make it work 🙂
