### ISSUE TITLE
How to give 'navgraphs' the routedIn option in Multi module configs?

### ISSUE THREAD

**Issue by way-kis** [raamcosta/compose-destinations#414]
I want to give the code generated by the 'navgraphs' option the routedIn option.
How do I do this?

**Comment by raamcosta** [comment]
Hi @way-kis !

Can you tell me more about the use case? What exactly are you trying to achieve?

**Comment by way-kis** [comment]
as-is
`kotlin
public object SampleNavGraph : NavGraphSpec {
    
    override val route: String = "sample"
    
    override val startRoute: Route = SampleScreenDestination
    
    override val destinationsByRoute: Map<String, DestinationSpec<*>> = listOf(
		SampleScreenDestination
    ).associateBy { it.route }

}

`

want-to-be
`kotlin
public object SampleNavGraph : NavGraphSpec {
    
    override val route: String = "sample"
    
    override val startRoute: Route = SampleScreenDestination routedIn this
    
    override val destinationsByRoute: Map<String, DestinationSpec<*>> = listOf(
		SampleScreenDestination
    ).routedIn(this).associateBy { it.route }

}
`

**Comment by raamcosta** [comment]
This is still only the end result in the code. My question is more like what are you trying to achieve with this?

**Comment by way-kis** [comment]
In the NavGraph module, I want to create a graph that is dependent on a specific route.

**Comment by raamcosta** [comment]
@way-kis 😅 my question is about the end goal of doing this, you are answering me with technical goals, I want to understand what are you trying to accomplish. What will the user see?

**Comment by raamcosta** [comment]
Closing this one for lack of feedback. @way-kis let me know if you have an answer, thanks!
