### ISSUE TITLE
Cannot reach testTags while using destinations 

### ISSUE THREAD

**Issue by mobile-pablo** [raamcosta/compose-destinations#416]
Hi
I am checking in espresso & compose if new view is displayed  but  When using destinations I got error 

`java.lang.AssertionError: Failed to perform isDisplayed check.
Reason: Expected exactly '1' node but could not find any node that satisfies: (TestTag = 'id_add_note_screen')`

More context here: 
https://github.com/mobile-pablo/Noteworthy/tree/1208e69a07967dd0d510ea3277a366138cad5d03/app/src/androidTest/java/com/mobile/pablo/iosnotes

**Comment by mobile-pablo** [comment]
@raamcosta

**Comment by raamcosta** [comment]
Hi 👋 

This is not an issue with compose destinations. Please check other possible issues you might have in your test.

Compose destinations doesn’t do any magic on the composable. Doesn’t change the code or anything, it just creates more code around it. So in the end destination composables are just like normal composables.
