### ISSUE TITLE
Custom NavArguments issue

### ISSUE THREAD

**Issue by javierpe** [raamcosta/compose-destinations#417]
Hi, I have a module that contains only data classes and I get exception when I set a custom nav argument 

`Cannot detect default value for navigation argument 'id' because we don't have access to source code. Are you using navArgsDelegate with code from different module?`

My data class module is used by others modules...

**Comment by raamcosta** [comment]
KSP doesn’t allow us to read classes from other modules, so we cannot make this work unfortunately. Nav args class needs to be in the same module where you annotate the corresponding composable with Destiantion.
