### ISSUE TITLE
share screen between tow @NavGraph

### ISSUE THREAD

**Issue by aplha98** [raamcosta/compose-destinations#418]
I have tow nav graphs   IceNavGraph,FlowersNavGraph, after the user pick the flower or ice he will go to PersonalInfoScreen, but this fail as PersonalInfoScreen belong only to FlowersNavGraph
```
@FlowersNavGraph // NavGraph
@IceNavGraph //NavGraph
@Destination
@Composable
fun PersonalInfoScreen()
```

**Comment by raamcosta** [comment]
Hi 👋 

This is not possible at the moment. The solution is to have two Composables each annotated with a different NavGraph and then each of these call a common composable.
