### ISSUE TITLE
Examples with a multi module project

### ISSUE THREAD

**Issue by andreasnaess** [raamcosta/compose-destinations#419]
Hi,

I was wondering if there are any examples showing how to use this library in a multi module project? I.e. where each module has its own navgraph, and is combined into a single DestinationsNavHost.

**Comment by raamcosta** [comment]
I should rename that issue 😅
If you read the comments you’ll see I had important feedback to make me think I need to keep these and just improve them instead.

**Comment by andreasnaess** [comment]
Okay, thanks!
