### ISSUE TITLE
Navigation between nav graphs

### ISSUE THREAD

**Issue by Vlado24** [raamcosta/compose-destinations#420]
Hi, #helpneeded 

just want to ask you if it is possible to navigate between nav graphs. In tivi project you have `root`, `discover`, `following`, `watched` and `search` nav graph. Then bottom navigation item has it own nav graph. 

Is it possible to navigate from `discover` nav graph (or Discover tab) to `watched` nav graph (or Watched tab).
Like in Discover tab, there is a button and onClick you will be redirected to Watched tab.  Maybe deeplinks? Or is there any other way?

Thanks,
Vlado

**Comment by raamcosta** [comment]
Hi 👋 

I’m not 100% sure that I got the question but if I did then the answer is yes. You can freely navigate to different nav graphs with no hurdle.
