### ISSUE TITLE
No Context reference available  in DestinationsNavigator

### ISSUE THREAD

**Issue by mylesbennett** [raamcosta/compose-destinations#422]
First of all, thanks for this library. You saved me a lot of work.
Having said that, I have a request:

In the standard Android Compose Navigation, you were able to do something like this..
```
LaunchedEffect(true) { viewModel.sideEffect.collect { navController.handleNavigation(it) } }
...
private fun NavController.handleNavigation(navigation: HomeNavigation) {
    when (navigation) {
        HomeNavigation.Close -> if(!popBackStack()) (context as? Activity)?.finish()
        ...
    }
}
```
You were able to do this because a `context` was supplied by the NavController as a public field. This was really convenient because, apart from the simple case above, you could easily navigate to a different app.

There's no similar reference to a context in DestinationsNavigator. To do something similar I would need to do this...
```
val ctx: Context = LocalContext.current
LaunchedEffect(true) { viewModel.sideEffect.collect { navigator.handleNavigation(it, ctx) } }
...
private fun DestinationsNavigator.handleNavigation(navigation: HomeNavigation, context: Context) {
    when (navigation) {
        HomeNavigation.Close -> if(!popBackStack()) (context as? Activity)?.finish()
        ...
    }
}
```
Hopefully, you'll agree this is not as neat.
Is there any chance DestinationsNavigator can be updated to supply a Context?

**Comment by raamcosta** [comment]
Hi!

This `context as? Activity` is probably not the safest thing to do.
Instead, you can have this:

```kotlin
val LocalActivity: MainActivity
    @Composable
    get() {
        return LocalContext.current.let {
            var ctx = it
            while (ctx is ContextWrapper) {
                if (ctx is Activity) {
                    return@let ctx
                }
                ctx = ctx.baseContext
            }
            throw IllegalStateException(
                "Expected an activity context for creating but instead found: $ctx"
            )
        }
    }
```

This is taken from Hilt open source code (and adapted a little) btw.

If you need this, you can use NavController instead. I am not going to provide context on DestinationsNavigator, because it is something which needs to be simple to mock on tests.

DestinationsNavigator is an abstraction that can be useful, but it's not mandatory. There are extension functions on NavController so you can use NavController just as easily. Just make sure to use rememberNavController and pass the result to DestinationsNavHost, if you need a NavController at that top level.
After that, you can just "ask" for a NavController and the library will provide that, just like it provides the DestinationsNavigator.

Hope that solves it for you, let me know if it doesn't 🙂

**Comment by mylesbennett** [comment]
Thanks for the code. I've used the recursive version of that before. This is cheaper on the stack, albeit less tidy.

Whilst your advice gave me further insight into your library, it didn't really help my case. If I use a NavController, then I can't use the generated TypedDestination object that is used by DestinationsNavigator - which would defeat the whole purpose of the library.

Thanks for coming back so quickly anyway. I'll see if I can create some extensions that might solve this.

**Comment by raamcosta** [comment]
> There are extension functions on NavController so you can use NavController just as easily

You can pass TypedDestination just like if you were using DestinationsNavigator 🙂
Guess the difference is you’re calling an extension function rather than a member function but it’s same thing in the end.

**Comment by mylesbennett** [comment]
Scratch my last comment.
You can do this
`navController.navigate(GeneratedTypedDestination(parameter).route)`
(note `.route`)
...so you don't have to use DestinationsNavigator. You can use NavController (which, as you say, you "ask" for instead of the DestinationsNavigator) and you can get the fully constructed route to pass to it from the generated TypedDestination - and you get the context from the NavController.

All good.

**Comment by raamcosta** [comment]
Hey @mylesbennett you don’t even need to do that 🙂 as I explained in previous comment, there is an extension function to NavController that accepts “Direction”. Direction is what you get as the result of invoking a Destination and passing in the args (or just the Destination itself can be a Direction if no args are needed). So this extension function works exactly like the DestinationsNavigator 🙂

**Comment by mylesbennett** [comment]
Got it, thanks.
Studio wasn't initially showing up your `navigate` extension as an option, hence my confusion.
