### ISSUE TITLE
NavGraphs file or Any ScreenDestination file isn't autogenerated. Infact have NavGraphSpec to use

### ISSUE THREAD

**Issue by patthhar** [raamcosta/compose-destinations#423]
I was trying out your repository for compose navigation following you READ.me file and saw that in the top level composable where we define our DestinationsNavHost, we have named parameter navGraph that takes in NavGraphs.root as the parameter. 

I have tried to clean project, rebuild it, invalidated cache and restarted AS. Tried with multiple versions of kotlin and the library itself. Switched the versions of ksp but to no luck.

The `NavGraphs` file or any `ScreenDestination` file that is supposed to be autogenerated isnt working, kindly help me out here. 
Here are the versions:
raamcostaComposeDestinations = "1.8.41-beta"
id 'com.google.devtools.ksp' version '1.8.10-1.0.9'
kotlin ''1.8.10''

**Comment by raamcosta** [comment]
Hi @patthhar !

I'm sure there is some issue with configuration. But there can be a couple causes, I need more information. 
The only thing I can do right now with this info is to direct you to the setup documentation:

https://composedestinations.rafaelcosta.xyz/setup/

Also, do you have a screen composable annotated with `@Destination`?

**Comment by arsaniousamgad** [comment]
Hey, 

I've got the same issue which has been solved after making sure that the ksp version is the same as the kotlin version

**Comment by patthhar** [comment]
Thanks for the reply @raamcosta @arsaniousamgad, it was indeed a configuration error and making sure the ksp version was same as the kotlin version seemed to help! Went through the setup page more carefully this time. Thanks!
