### ISSUE TITLE
[Bug] When an unresolved deeplink is encountered, a random destination is opened instead of start destination

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#426]
This is related to #396 https://github.com/google/accompanist/issues/1583
The accompanist team says that start destination should be opened in case a destination is not resolved. But I'm facing an issue where that destination is not opened. Instead, a random one is opened upon trying to open an unresolvable deeplink. Can this be related to compose-destinations? I'm not doing anything specific in terms of the setup. Here's my home composable setup: 
I'm using the standard launchMode for my activity.
```

@Composable
@RootNavGraph(start = true)
@Destination(
    style = BottomNavigationStyle::class,
    wrappers = [AnalyticsScreen::class],
    deepLinks = [
        DeepLink(
            uriPattern = LocalDeeplink,
        ),
        DeepLink(
            uriPattern = RemoteDeeplink,
            action = Intent.ACTION_VIEW,
        )
    ],
)
internal fun Home(nav: AppNavigator) = HomeScreen(nav)
```

**Comment by raamcosta** [comment]
I can't imagine why this would be compose destinations' doing. 
I can try to debug internals if you prepare a small sample where this happens.

**Comment by Nek-12** [comment]
To be honest, me too. I haven't found anything suspicious in the generated code. I'll start working on repro soon

**Comment by raamcosta** [comment]
Hey @Nek-12 do you still have this issue with latest versions?

**Comment by Nek-12** [comment]
Yes, but we haven't updated to the latest nom-accompanist navigation yet

**Comment by Nek-12** [comment]
This issue is still reproducible on the latest version. I forgot about it and will try to repro this

**Comment by raamcosta** [comment]
I am cleaning some old issues and I still think this one is not related to the library. Please let me know if you see indications suggesting otherwise.
