### ISSUE TITLE
adding any kind of code generation configs prevents NavGraphs to be generated in App module

### ISSUE THREAD

**Issue by SiavashB** [raamcosta/compose-destinations#428]
We have a multi module app. 
We want the app module to host all the nav graphs, I was trying to add code generation configs such that the feature modules dont generate a NavGraphs class and I can manually create them in the app module (which is our navigation module).

But the moment I add ANY of the code generation configs, to ANY module, the one in the App module doesn't get generated. 
 for example I tried putting this in the feature module
```
 ksp {
    arg("compose-destinations.generateNavGraphs", "false")
}
```

or this

```
ksp {
    arg("compose-destinations.mode", "destinations") // also tried with nav graphs. 
    arg("compose-destinations.moduleName", "features.faxmsg.presentation")
}

```
I also tried putting this in my app module 

```
ksp {
    arg("compose-destinations.mode", "navgraphs") 
    arg("compose-destinations.moduleName", "app")
}
```

Any one of these or any combination of these makes the app module not generate a NavGraphs class

**Comment by raamcosta** [comment]
Hi!

Can you prepare a small sample where this is happening so I can take a deeper look? Thanks

The reality is, I don't see any reason why this wouldn't work... I have done it in multiple multimodule apps 🤔

**Comment by raamcosta** [comment]
I'll close this for being stale. Please let me know if there's any other feedback. Once again, each module is completely independent in terms of code generation. So having some config in one module will not make any change in how other modules generate code. So I'm guessing this was something else, but please let me know.
