### ISSUE TITLE
Setup of sample project

### ISSUE THREAD

**Issue by RowanG1** [raamcosta/compose-destinations#429]
To run the sample project, I had to do the following:
1) Install gradle (on Mac I used homebrew), since gradle wrapper is not used.
2) Find the installed gradle location using  `brew info gradle`
3) Point Android studio to the gradle folder by: Settings -> Build/Excecution -> Build tools -> Gradle. Note that it is a hidden folder in Finder.
4) In build.gradle.kts, add this to the end: `task("prepareKotlinBuildScriptModel") {}`
5) Now Sync and build.

**Comment by raamcosta** [comment]
Hi @RowanG1 !

Thanks for letting me know. However I have setup this project in multiple computers and I never had to do such things 🤔 

We are in fact using gradle wrapper, it's inside gradle folder 🤔

**Comment by RowanG1** [comment]
Thanks. I had the same experience on Linux and Mac about the need for task
addition in build.gradle
