### ISSUE TITLE
Issues implementing sample code from TIVI App

### ISSUE THREAD

**Issue by szsoftware** [raamcosta/compose-destinations#430]
![Bildschirmfoto vom 2023-05-17 11-00-49](https://github.com/raamcosta/compose-destinations/assets/2539622/4afd58f3-414c-4cfa-ac2f-892676ab5ec3)

Hi, can't thank you enough developing continously this great library.
However, after a half year winter break I reopened an older project were I once began to implement multimodule navigation and as you can see, starting from Tivi-Code.

Tivi App (your fork) is up and running in the IDE too.

It was already working in my app, but probably your api changed meanwhile somehow I don't understand.
Hopefully you see the picture (screenshot) attached.

In Line 81 there's the "receiver type mismatch". The extension function currentNavigator() is defined in Line 52.

Any help highly appreciated and many thanks in advance!

**Comment by raamcosta** [comment]
Replace DestinationScope with DestinationScopeWithNoDependencies in the extension function.


Let me know if that works 🙂

**Comment by szsoftware** [comment]
You're amazing(ly fast)!

Yes it work's. Thanks you soo much.
