### ISSUE TITLE
Allow Destination to take multiple parameters?

### ISSUE THREAD

**Issue by mylesbennett** [raamcosta/compose-destinations#431]
I'm trying to find a way to set an extra parameter/field/argument on my `Destination` that can be a display directive to my MainActivity's `Scaffold`. Specifically, I am trying to add a parameter to say whether or not my Destination should be displayed with or without the bottom nav bar.
This is a multi-module project. The `Destination` is part of a sub-nav graph in a feature module. The main app module defines the `Scaffold` and only knows about the feature modules' sub-nav graphs. I'm using NavController and defining my own NavGraphSpecs for each feature. This is what I have so far in the app module:
```
            val navController = rememberNavController()

            Scaffold(
                bottomBar = { if (navController.shouldShowBottomBar()) BottomBar(navController) }
            ) {
                DestinationsNavHost(
                    navController = navController, ...

```
and then 
```
@Composable
private fun NavController.shouldShowBottomBar(): Boolean =
    currentBackStackEntryAsState().value?.destination?.let { <code?> } == true
```
I need to be able to set something on a standard NavDestination that I can pick up at this point (in `code?`). The only way I can see of doing this currently is by being able to set an extra parameter on the destination's route - and you should be able to because Google says you can do this:
```
composable(
    "profile?userId={userId}",
    arguments = listOf(navArgument("userId") { defaultValue = "user1234" })
) { backStackEntry ->
    Profile(navController, backStackEntry.arguments?.getString("userId"))
}
```
(from here:- https://developer.android.com/jetpack/compose/navigation) which means you can have more than one parameter if you name them, eg:- `"profile?userId={userId}&hideNavBar={hideNavBar}"`

However, I can't see how you can set a second parameter with your library. My `Destination` already has a parameter for the actual content:
```
@Destination(navArgsDelegate = PhotoDetail::class)
@Composable
internal fun DetailScreen(
    navController: NavController,
    viewModel: DetailViewModel = viewModel(),
) {
```

You've been pretty awesome getting back to me before. I'd really appreciate any ideas you might have for this - using a second parameter or otherwise.

**Comment by raamcosta** [comment]
Hi @mylesbennett !

So.. your `PhotoDetail` is not the navigation argument. It is the class where navigation arguments are defined. So if you want more, just add them in there as additional fields :)

Does this help?

**Comment by mylesbennett** [comment]
I thought you might say that. Sure, that is a solution, but it doesn't feel right from a seperation-of-concerns/ single-responsibility/ dependancy-inversion point of view. That data is meant for populating a screen in a particular feature module whereas I also need some hint meant for the module containing the Scaffold (likely the app module).

I would suggest having `PhotoDetail` inherit from some common set of blank interfaces that can be compared against in the app module but data classes can't inherit from anything.

Maybe something else then. Are you able to override the route id? Maybe tag a suffix at the end or something?

It might be worth thinking about supporting multiple parameters for a future release though. Your library is gaining more and more poularity and this is something that's available out of the box from Google (albeit *really* messy) that is kind of blocked here.

**Comment by raamcosta** [comment]
> I would suggest having PhotoDetail inherit from some common set of blank interfaces that can be compared against in the app module but data classes can't inherit from anything.

I don't think this is true, they can implement interfaces.

> It might be worth thinking about supporting multiple parameters for a future release though. Your library is gaining more and more poularity and this is something that's available out of the box from Google (albeit really messy) that is kind of blocked here.

This is the puzzling part to me... We do support multiple parameters and I don't see how it is any different from what the official compose navigation is doing. Referring back to your first paragraph, how is it violating the separation of concerns but the Google solution isn't? You are also passing some navigation arguments that are meant for the screen and others are meant for top level navigation setup. Exactly like with Compose Destinations.

Do you mean that your feature module would be getting the information if you're passsing in the class `PhotoDetail `?
But if that's the case why don't you have a class `PhotoDetailNavArgs` one field would be the `PhotoDetail` that you provide to the destination and the others would only be used at the "navigation module"?

It's likely that I'm missing something, just trying to get to what that is 😄 
I greatly appreciate your help 🙏

**Comment by mylesbennett** [comment]
> ... We do support multiple parameters

I may be missing something too. It's probably in your documentation somewhere. My apologies if I missed it.
So I was specifically talking about _named_ parameters. With Google's arrangement, you can set up a route that looks like this:
```
"photoDetail?scaffold=fullscreen&internal_feature_data=...{serialised complex data}..."
```
That will set up two entirely different entries in the `SavedStateHandle`: - one with the key `scaffold` and one with the key `internal_feature_data`. Now, consider the arrangement where `photoDetail` is part of a nested subgraph in a separate module. Best practices around dependancy inversion would suggest that the separate module should only expose the minimum amount of information to the module that depends on it - "app" in this case.

In the above arrangement, the app module only needs to know about the key `scaffold` and the type of data it represents. Not only does it not need to know about the key`internal_feature_data`, but it doesn't even need to know how to deserialise the data, so that data type can be set as `internal` in the feature module.

Without named parameter support (again, my apologies if I missed it) you have to bundle everything into one public data class containing both the `scaffold` data and `internal_feature_data`. The app module now has access to information that it neither needs nor wants. That's what I meant about violation of seperation of concerns.

In fact, I don't think you can even set a data type internal to a module because
```
@Destination(navArgsDelegate = InternalFeatureData::class)
```
would generate code that forces `InternalFeatureData` to be public (again, my apologies if I missed something).

You were correct about data classes inheriting from blank interfaces. I'm not sure what I was thinking there - probably data classes inheriting from other data classes was in my head. That does improve things slightly. At least the app won't need to unpack the whole parameter to get to the `scaffold` info.

Because everything is public though, only a code review will stop a dev working on the app module from accessing data they shouldn't.

**Comment by raamcosta** [comment]
@mylesbennett Hey!

So.. I get it now. You want to pass a navigation argument to a screen but also keep it invisble from that screen so that you query it from the app module.
I've always felt super weird about this approach that is recommended by official compose navigation... Yes, the screen might not know about it, but the argument will be there, and theoretically the "screen" (naming the entity "screen", but it could be the Composable, or the ViewModel via SavedStateHandle) could retrieve it.

If this is something that the app is deciding (whether or not scaffold is fullscreen) why would we pass a navigation argument to the screen just so that the same app can query it? Isn't it much easier to check what the current destination is and then make a decision on what mode the scaffold should be on based on that? In my opinion, yes it's easier and more logical to not use nav arguments for this purpose.

Notice also, that this
```
@Destination(navArgsDelegate = InternalFeatureData::class)
```
won't mean that we'll have 1 navigation argument which is of this complex type. In reality the library will read each field from this InternalFeatureData class and each of them will be it's own navigation argument. So this is what I meant when I said we do support multiple navigation arguments. Even if you enclose them in a class and pass that in the `navArgsDelegate` it's still going to be multiple arguments in the route, one for each field in that class **named** with the name of the field.

**Comment by mylesbennett** [comment]
>EDIT: don't know anything about each other I mean related to these arguments of course one will depend on the other so they know something about each other in one direction.

Indeed. The app module will know about the feature module but not vv. - and the feature module should be able to share (or not share) any data it wants. I also agree about your comment about the shared "bucket", but we have to do the best we can with what Google have given us to work with. Let's face it, most of it smells. As for the argument names - well, we can do something about that with UUIDs.

**Comment by raamcosta** [comment]
Yes, but we need to keep its limitations in mind. I still think that navigation arguments should be what we use to send things to the next screen, period. Adding something there just as a hint for something else is odd and could potentially have unexpected issues.

I'll close this one, hope that you found a solution you like :) Let me know if I can help.
