### ISSUE TITLE
[BUG] Deeplink working on cold state of the app but not on background

### ISSUE THREAD

**Issue by Kagisojoe** [raamcosta/compose-destinations#432]
Hello 👋 

First and foremost, Thank you for the great library!

When implementing deeplink for my app, I noticed that I didn't have to setup any type of navigation which is great.
When the app is closed and it receives a deeplink intent, it works perfectly and navigates to the URI.

However, when the app is in the background or open, it opens and stays on the home screen even though it receives the intent.

Please let me know any snippets you'd like to see.

Thank you.

**Comment by raamcosta** [comment]
Hi! Thanks :) 

Well, this is not something that this library controls in any way. We simply pass all the info from the annotations back to compose navigation APIs.

You'll be able to find better answers if you google about this issue with official compose navigation. I'm sure you'll be able to adapt whatever the solution is, let me know when you get it! :)

**Comment by Kagisojoe** [comment]
oh okay, I see, Thank you. 

Sure, I will get back to you when I get it!
