### ISSUE TITLE
deep link from notification

### ISSUE THREAD

**Issue by ahmedmuhammedpro** [raamcosta/compose-destinations#433]
i have a notification with pending intent like this "example://order-details/10" i want to navigate to  OrderDetails where 10 is the order id

```
@Composable
@Destination
fun OrderDetails(
val order: Order? = null
) {
 // rest
}


@Parcelize
data class Order(id: Int, title: String? = null)
```

**Comment by ahmedmuhammedpro** [comment]
I tried the same solution its work fine but i have an issue openning a deeplink make a duplication opennjng. When i go back it open the same screen again.
Did you faceed this issue ?

**Comment by ammargitham** [comment]
No, I suspect that the linked screen maybe be already open in the app before you click the notification.

**Comment by ahmedmuhammedpro** [comment]
No i thing its issue from android navigation lib
