### ISSUE TITLE
Steps for Setting-Up Compose Destinations on a Multi Modular Project

### ISSUE THREAD

**Issue by Tonnie-Dev** [raamcosta/compose-destinations#434]
Hi Ram,

I'm completely lost and I don't where to start to set-up Navigation for a Multi-Modular Project. I have also checked other related issues eg. #149 , #419 and even #216 but I still can't get started.

All I know is that I want each feature module _to expose a single destination that belongs to a navigation graph containing destinations from other feature modules._

Thanks for providing [Tivi's link](https://github.com/raamcosta/tivi) but I will be lying if I say I understand what is happening.

Kindly requesting for a short **_List of Steps Involved to set-up Compose Destination in a Multi-Modular Project_**. This way I will try to implement the steps one after the other.

**Comment by raamcosta** [comment]
Hi @Tonnie-Dev !

Thank you for doing this!
Want to contribute it to the docs repository? It will be included in the documentation website automatically as soon as it gets merged.
As you'll see the pages are just markdown with some special capabilities, but nothing crazy. So it's super easy to contribute!

https://github.com/raamcosta/compose-destinations-docs

I think it should go under "common use cases" as a new sub page there.

**Comment by raamcosta** [comment]
Just as a FYI, the reason I haven't done this is because the multi module support is still a bit to rough and manual and I am thinking of providing easier integration in v2 version of this library. So keep in mind that most of this can and probably will still change / be improved.

**Comment by Tonnie-Dev** [comment]
Hello @raamcosta 
Thanks for your kind comments. I am excited that this is being looked at for improvement in Version 2.

I'm not a Pro in Documentation but I will chip in with your approval.

Once again thanks for this great Library, all efforts in improving the libray is really worth it!

**Comment by Tonnie-Dev** [comment]
I finally submitted the documentation although I accidentally messed up on the PR but managed to resolved the confict.

**Comment by Alival-IT** [comment]
> Just as a FYI, the reason I haven't done this is because the multi module support is still a bit to rough and manual and I am thinking of providing easier integration in v2 version of this library. So keep in mind that most of this can and probably will still change / be improved.

Hello @raamcosta , I would like to ask you if there is a roadmap/timeline for the improved multimodule support? I would like to use the library in the upcoming project and just wondering if I should wait a little for the  support. 

Btw great library and exceptional support 👍

**Comment by raamcosta** [comment]
Hi!
Thank you 🙏 

I’m still targeting the end of the year, but it’s possible I’ll need January as well.
And the idea is to start with an alpha version so I can get feedback about it 🙂

**Comment by raamcosta** [comment]
V2 is here and has new and improved multi module setup!

Check it here:

https://composedestinations.rafaelcosta.xyz/v2/multi-module-setup

**Comment by Tonnie-Dev** [comment]
@raamcosta Thanks lots for following through on V2, can't wait to start messing with it soon. 🎆 🍾 😄
