### ISSUE TITLE
Question: possible to determine the deepest destination

### ISSUE THREAD

**Issue by mevans** [raamcosta/compose-destinations#439]
I have 2 `DestinationsNavHost`. The top level one is displaying the Root nav graph, and the second one is displaying a deeper nav graph.

When I'm in the top level one, I'm using the function `appCurrentDestinationAsState` to determine which route the user is currently on. This works fine for the 'flat destinations', however if the user then navigates to the destination which is hosting the second nav graph, and then navigates inside that second graph, the `appCurrentDestinationAsState` won't reflect that change, and the destination reported is still just the host destination for the second graph.

Is there any way to determine the 'deepest destination' the user is on, from that top level?

Thanks

**Comment by raamcosta** [comment]
Hi!

So.. each NavHost is tied to a different NavController. So you’d need the NavController of your deeper NavHost to check what destination the user is on in that NavHost.

Also, the two NavHosts don’t have any relation between them. They’re two completely separate things.. one is not the parent of the other and no one is nested in the other. If that is what you’re looking for, then you still only use a single NavHost and pass to it a NavGraph that contains multiple levels of nested graphs.

All of this is not specific to compose destinations, it is how jetpack compose navigation works.

**Comment by mevans** [comment]
Yeah that makes sense. Thanks for your help :)
