### ISSUE TITLE
SharedViewModel with Activity and composable functions

### ISSUE THREAD

**Issue by ShankarKakumani** [raamcosta/compose-destinations#44]
How can I achieve shared ViewModel using this library?

I want the activity and all the compose functions under this Navigation have same ViewModel instance.
any idea of how I can achieve it?

**Comment by kofiarkoh** [comment]
this has helped me. but can u please provide some explanation to me...android beginner.

**Comment by raamcosta** [comment]
Closing this. Feel free to add comments if there is anything else I can help with
