### ISSUE TITLE
cant generate NavGraph after clean&rebuild

### ISSUE THREAD

**Issue by beyond-godlike** [raamcosta/compose-destinations#440]
Can`t import NavGraph after clean. All deps are the same (they worked)

**Comment by raamcosta** [comment]
Hi 👋 

Can you try removing the import line and checking if the IDE helps you add the import again?

Or, can you check inside the build folder of your module in the generated/ksp (I believe) if the files are there? 

Thanks

**Comment by beyond-godlike** [comment]
> Hi wave
> 
> Can you try removing the import line and checking if the IDE helps you add the import again?
> 
> Or, can you check inside the build folder of your module in the generated/ksp (I believe) if the files are there?
> 
I cant import NavGraphs.root . it should be here kotlin.srcDir("build/generated/ksp/debug/kotlin") but after clean this folder dissapeared and not generating anymore

**Comment by beyond-godlike** [comment]
if i comment NavGraphs.root its okay. DestinationsNavHost imported good, and import com.ramcosta.composedestinations.annotation.Destination also works

**Comment by raamcosta** [comment]
Clean will delete build folder. This is expected. You have to build and they’ll be generated again.

**Comment by beyond-godlike** [comment]
> You have to build and they’ll be generated again.
Ive already built the project. And I cant import NavGraphs. There is no needed folder with generated classes

**Comment by beyond-godlike** [comment]
could you clean&rebuild any of your projects that uses this lib and tell me is it works as should be? please

**Comment by raamcosta** [comment]
Did you change any version lately?

yes I have multiple projects all working..

**Comment by beyond-godlike** [comment]
no, everything stayed the same (this lib), just clean & rebuild. Ok, is simplier to create the project again. Ty 4 lib its amazing

**Comment by raamcosta** [comment]
Not just this lib version.. also Kotlin version or compose.. all stayed the same?

**Comment by beyond-godlike** [comment]
> Not just this lib version.. also Kotlin version or compose.. all stayed the same?

changed compose version

**Comment by raamcosta** [comment]
try going back on the versions you changed just to be sure. If it works, you need to check what version you need to use.

On readme.md file of this repo you'll find a table describing what version to use depending on the compose version you're using :)

**Comment by beyond-godlike** [comment]
[SOLVED] 
app
1) id "com.google.devtools.ksp" version ("1.8.10-1.0.9") 
2) implementation 'io.github.raamcosta.compose-destinations:core:1.8.41-beta'
    ksp 'io.github.raamcosta.compose-destinations:ksp:1.8.41-beta'
Project:
id 'org.jetbrains.kotlin.android' version '1.8.10' apply false (kotlin version 1.8.10)
compose_version = '1.4.2'

Compose to Kotlin Compatibility Map
https://developer.android.com/jetpack/androidx/releases/compose-kotlin

**Comment by raamcosta** [comment]
Glad you made it. closing..
