### ISSUE TITLE
Question: Usage of multiple items on "dependenciesContainerBuilder"

### ISSUE THREAD

**Issue by caiquebrito** [raamcosta/compose-destinations#441]
Hello,
I was looking for a way to pass some functions as a parameter to my destinations, i tried with a "SharedViewModel", which works perfectly, but i'm now trying to avoid pass the full instance and give just some lambdas, on the inner destinations i just invoke it and the flow goes on.
I just realized if you put two dependency in a row, it will just override it, like in this sample:
<img width="716" alt="image" src="https://github.com/raamcosta/compose-destinations/assets/8015744/12c688b6-c9d7-427f-8529-787a57d9a852">
So my question is, can i give multiple functions as a dependency?

**Comment by raamcosta** [comment]
These dependencies work by class, so if you want to do this, just create an interface with those two functions and pass the implementation here 🙂

**Comment by raamcosta** [comment]
It’s even better because your screen will receive one interface with a name instead of two anonymous functions

**Comment by caiquebrito** [comment]
For sure the interface would solve the case, but i'm avoiding pass more information that my screens actually need to know, so my screens are receiving just functions and my composables kind of high-order function, if i understood right, my options for now is to pass an interface to my viewmodel and inside of it implement the interface, and the usage could be either the "#2" or "#3" right?
```kotlin
val homeViewModel = koinViewModel<HomeViewModel>()
val searchScreenActions = object: SearchComposeScreenDestinationActions {
    override fun setThatThing() {}
    override fun setOtherThing(input: String) {}
}
DestinationsNavHost(
    navGraph = NavGraphs.home,
    engine = rememberAnimatedNavHostEngine(),
    navController = it,
    dependenciesContainerBuilder = {
        dependency(NavGraphs.home) {
            homeViewModel
        }
        // #1 just a possible future feature
        dependency(SearchComposeScreenDestination) {
            homeViewModel::setThatThing
            homeViewModel::setOtherThing
        }
        // #2
        dependency(SearchComposeScreenDestination) {
            homeViewModel::searchScreenActions
        }
        // #3
        dependency(SearchComposeScreenDestination) {
            searchScreenActions
        }
    }
)

interface SearchComposeScreenDestinationActions {
    fun setThatThing()
    fun setOtherThing(input: String)
}
```

**Comment by C0deWithAj** [comment]
@raamcosta I am trying to pass an interface - but the NavArgs are not generated for interface. However, when i use any class or  String, the NavArgs is generated for it. What am i missing while passing interface please ? 


@AuthNavGraph
@Destination
@Composable
fun ChooseCompanyScreen(companySelectedListener: CompanySelectedListener) {

}

For the above, I don't see ChooseCompanyScreenDestination.NavAgrs() , However if i use a String or a class in the above composable, the NavArgs is generated for it successfully.

**Comment by raamcosta** [comment]
https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments

Only a specific set of types can be navigation arguments. These will be serializer and stored by Android OS if it kills your app. 
So.. something like a Listener can never be a nav argument.

You can however pass it from the DestinationsNavHost call, like this:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters

**Comment by C0deWithAj** [comment]
@raamcosta In the above comments, you suggested:

"These dependencies work by class, so if you want to do this, just create an interface with those two functions and pass the implementation here 🙂"

That's what I am trying to do here. The listener is an interface. So I created an interface, and passing its implementation. But The NavArgs are not generated for Interface argument. 



interface CompanySelectionListener {
    fun onCompanySelected(string: String)
}


@AuthNavGraph
@Destination
@Composable
fun ChooseCompanyScreen(companyScreenResponse: CompanySelectionListener) {

}

That's all i did. Sorry what am i missing here ?

**Comment by raamcosta** [comment]
You need to understand there are two separate kinds of “things” you can pass to a destination: navigation arguments (which are passed from one screen to the next one) or just “stuff” you want to pass from the DestinationsNavHost call.

My comment about class and interface was related to the second type of arguments, not to navigation arguments. As the title of this issue suggests, we’re talking about “dependencyContainerBuilder” which is a way to pass dependencies from the NavHost level to the screen destination.
Using this, you can indeed pass an impl of an interface to the screen, but that is not a navigation argument because it can never be. It’s just something you can pass from the NavHost level.

What exactly is your interface for? Maybe I can tell you what is the way to achieve what you’re trying to.

**Comment by C0deWithAj** [comment]
@raamcosta  Oops! Sorry, I didn't notice it was the DestinationNavHost call. So basically my scenario is navigation Argument where i wanted to pass an interface to the screen (which I can pass from DestinationsNavHost no prob) , but I also have an ArrayList of type custom object, which is coming from Screen A and i need it to pass to Screen B. I am calling Screen B at the top level using NavController.

In Screen B, i created parameter ArrayList<CustomObject> and rebuild the project, but i Don't see NavArgs taking that parameter. Does this take Serialised classes/objects only ?

**Comment by raamcosta** [comment]
You can see on docs website which types are eligible for navigation argument.
ArrayLists can be nav arguments if their type argument is one of those nav arguments types.

**Comment by C0deWithAj** [comment]
@raamcosta Many Thanks man, I figured it out. And thank you for making our life easier with this library :)

**Comment by raamcosta** [comment]
@caiquebrito let me know if there's anything else I can help you with! I'll be closing this, but still paying attention if you reply!

**Comment by caiquebrito** [comment]
@raamcosta Sorry for late response, things goes a little bit wild, i tried to manually inject multiple annonymous functions to my destinations and worked like a charm, thank you for the help.
> Can you explain to me how is it different? An interface defines the contract your composable is expecting, it doesn’t know anything else about implementation. It’s exactly the same with lambdas. The composable is defining a contract and you “implement” them here, also abstracting it away from the screen.
About this, i don't see any big difference between passing the interface or just annonymous functions, is just a preference of mine, the screens will not know what to do, just call execute the function passed as parameter.
