### ISSUE TITLE
When navigating between screens, if the navigation drawer is used and at the same time slide animation is done, does the drawer appear in the window with the drawer?

### ISSUE THREAD

**Issue by jamshidisoqov** [raamcosta/compose-destinations#442]
When navigating between screens, if the navigation drawer is used and at the same time slide animation is done, does the drawer appear in the window with the drawer? What can I do?

**Comment by raamcosta** [comment]
Im not sure I follow 🤔

can you expand on it? Is there a video of what you want to do and what is not working?

**Comment by raamcosta** [comment]
Closing this one for lack of feedback. @jamshidisoqov keep in mind that this kind of behaviour is not related to this library.
You will find better answers on google, stackoverflow or kotlin slack channel
