### ISSUE TITLE
Get DestinationsNavigator where we call DestinationsNavHost

### ISSUE THREAD

**Issue by C0deWithAj** [raamcosta/compose-destinations#446]
Hello, 

At the place of DestinationsNavHost() call, Is there any way to get DestinationsNavigator from NavController ? I don't want to give compose screens the ability to navigate hence, i want to keep the navigation ability in the calling compose only. 

In NavController I see "navigatorProvider" e.g 

    val navController = rememberNavController()
    val navigator = navController.navigatorProvider
    
    
  But how do i get DestinationsNavigator or any other way to navigate by giving destinations instead of string ? Here's what my code looks like. 
  
    val navController = rememberNavController()

    DestinationsNavHost(
        navGraph = NavGraphs.auth,
        startRoute = ConnectScreen1Destination,
        dependenciesContainerBuilder = {
            dependency(authViewModel)
        }, navController = navController
    )

    val uiState by authViewModel.uiState.collectAsState()
    when (uiState.dialogueFlow) {

        AuthViewModel.UIState.StartUpDialogueFlow.LOADING -> {
       
        }

        AuthViewModel.UIState.StartUpDialogueFlow.AUTH_SCREEN_1 -> {

        }

        AuthViewModel.UIState.StartUpDialogueFlow.AUTH_SCREEN_2 -> {
           //Call  Auth Screen using DestinationNavigator here 
        }

        AuthViewModel.UIState.StartUpDialogueFlow.CHOOSE_COMPANY -> {

        }

        AuthViewModel.UIState.StartUpDialogueFlow.CHOOSE_DEVICE_NAME -> {

        }

    }
  
  
  I found the following in sample app - which i exactly what I need, but I don't see the navigate() supporting Destination argument for version  -> 1.8.42-beta
  
  val engine = rememberAnimatedNavHostEngine()
    val navController = engine.rememberNavController()
    
     navController.navigate(LoginScreenDestination) {
            launchSingleTop = true
        }

**Comment by raamcosta** [comment]
As stated here:
https://composedestinations.rafaelcosta.xyz/navigation/basics

DestinationsNavigator is meant only for screen to screen navigation. At top level you want to use NavController’s extension function which takes a Direction. Then you don’t need to use strings to navigate, you navigate in same way as if it was the DestinationsNavigator.

**Comment by raamcosta** [comment]
> I found the following in sample app - which i exactly what I need, but I don't see the navigate() supporting Destination argument for version -> 1.8.42-beta

Destination is not what gets passed to our navigate calls, we use Destination’s invoke method to get a “Direction” or the Destination is also a Direction (in case that the Destination doesn’t have any nav args). We then pass that “Direction” to the navigate method.

**Comment by C0deWithAj** [comment]
@raamcosta Thank you for prompt Response. 

- navController.navigate(GreetingScreenDestination)
- navController.navigate(ProfileScreenDestination(id = 1, groupName = "Kotlin 4ever <3"))


I don't see my navController accepting Destinations as param ?

**Comment by raamcosta** [comment]
> @raamcosta Thank you for prompt Response.
> 
> * navController.navigate(GreetingScreenDestination)
> * navController.navigate(ProfileScreenDestination(id = 1, groupName = "Kotlin 4ever <3"))
> 
> I don't see my navController accepting Destinations as param ?

Ahah bad timing.. I believe I answered it in my last comment.

**Comment by raamcosta** [comment]
Make sure you import the correct extension function. It should be part of the list the IDE shows you for NavController.
Take the one that accepts a Direction 🙂

**Comment by C0deWithAj** [comment]
@raamcosta  Sorry I am still confused - from the sample it looks like we can pass Destination - This is exactly what i am trying to do - passing Destination to it :/ 

navController.navigate(GreetingScreenDestination)

**Comment by C0deWithAj** [comment]
@raamcosta  Okay I got your point. So we're supposed to do this 

 navController.navigate(ConnectScreen1Destination.invoke())
 
 Now again, the navigate takes "NavDirection" and not "Direction". Trying to find in import suggestions and inside the class, but can't seem to find a method taking "Direction"

**Comment by C0deWithAj** [comment]
@raamcosta Thanks man!!! U answered everything :)

**Comment by raamcosta** [comment]
If you're adding this library as dependency, there must be an extension function.

`com.ramcosta.composedestinations.navigation.navigate`

Add this import ☝️ although it's weird that your IDE is not finding it.

> navController.navigate(ConnectScreen1Destination.invoke())

Not needed, if the Destination does not have any nav args, then it will also be a Direction. 
So in that case this is enough:
`> navController.navigate(ConnectScreen1Destination)`
