### ISSUE TITLE
"Any" is not supported as NavArgument 

### ISSUE THREAD

**Issue by AbdullahJaved-dev** [raamcosta/compose-destinations#447]
I want to pass "Any" as a navigation argument but it is not supported.

**Comment by raamcosta** [comment]
Hi @AbdullahJaved-dev 

Yes, ofc Any it's impossible to pass as nav argument.
Here you have a list of possible nav argument types:

https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments
