### ISSUE TITLE
previewing @Destination Screen in @Preview function

### ISSUE THREAD

**Issue by Vikash-Singh-Bhadoriya** [raamcosta/compose-destinations#45]
Much appreciate the effort you put to make the library. Which really makes navigation in Android Compose a lot easier. Thank you very much.

By the way, I stumbled upon the problem today, which is how can I preview a @Destination Screen in @Preview function.
The MainScreen needs DestinationsNavigator, and I don't know how do I get that in my @Preview function.

Here is an Example for better understanding
``` kotlin
@Destination(start = true)
@Composable
fun MainScreen(
    navigator: DestinationsNavigator
) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(horizontal = 24.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Button(
            onClick = {
                navigator.navigate(SecondScreenDestination(User("Vikash","Today")))
            }
        ) {
            Text("Hello", fontSize = 18.sp)
        }
    }
}

@Preview
@Composable
fun DefaultPreview() {
    MainScreen(?????)
}
```

**Comment by raamcosta** [comment]
Hi @Vikash-Singh-Bhadoriya !

Super easy: pass `EmptyDestinationsNavigator`. `DestinationsNavigator` is an interface, so you can much more easily pass any implementation you want. It just so happens that my library already has an empty implementation for this exact reason!

Hope this helps! Let me know! 👋

**Comment by Vikash-Singh-Bhadoriya** [comment]
Thanks , it works really Well 👍
