### ISSUE TITLE
How to convert DirectionDestination / TypedDestination to Route

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#451]
I want to override root destination at run time.
In startRoute parameter it accepts Route object.
I have DirectionDestination / TypedDestination.
How can I pass this in startRoute

**Comment by raamcosta** [comment]
Hmm Route is superclass of both NavGraph and Destination. So.. they’re already Route, no need to convert anything, you can just pass it in there 😅

**Comment by raamcosta** [comment]
@UKMIITB 

Hope that was enough to unblock you, let me know if you need anything else, happy to help!

**Comment by UKMIITB** [comment]
@raamcosta 
In case if I have a destination which needs some parameter, then I am unable to convert those to Route type.
Can you please help on this
