### ISSUE TITLE
Shared View Model To Nested Graph

### ISSUE THREAD

**Issue by ksw321** [raamcosta/compose-destinations#452]
How to shared view model for screen 1 and 2 ?

Eg.Screen 1 is showing and go to screen 2. In Screen 2, user update data and data are already change in screen 1. 

After Screen 1 is closed, VM will clean.

Please help. Thanks

**Comment by raamcosta** [comment]
@ksw321 did you find the solution?

**Comment by ksw321** [comment]
By checking the following url,
https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels/
