### ISSUE TITLE
Unresolved reference : NavGraphs

### ISSUE THREAD

**Issue by AhmedMaherHosny** [raamcosta/compose-destinations#453]
i'm working with multi modules so i created module called "ui" when i use this library in the ui module gradle file every thing works fine and set RootNavGraph all this works fine the issue occurred when trying to add another screen the error happens **Unresolved reference : NavGraphs**
I got suspicious and i tried the same code with same versions on new project and this project **not uses multi modules** just app module and tried again all things works fine so i figured out that the problem is with **(multi module)** when i use this library **outside** **app module** this error happens "Unresolved reference : NavGraphs".

my versions : 
    id 'com.google.devtools.ksp' version '1.8.21-1.0.11'
    implementation 'io.github.raamcosta.compose-destinations:core:1.9.42-beta'
    ksp 'io.github.raamcosta.compose-destinations:ksp:1.9.42-beta'
    composeOptions {
        kotlinCompilerExtensionVersion "1.4.7"
    }
    id 'org.jetbrains.kotlin.android' version '1.8.21' apply false
    composeBom ==> 2023.05.01

**Comment by raamcosta** [comment]
Hey @AhmedMaherHosny!

So this library will generate code in the modules you set it up on. If you use a multi module approach to navigation, then check these configs on docs:
https://composedestinations.rafaelcosta.xyz/codegenconfigs

Be ware that some of these configs might not be available on v2, but the approach taken on github examples should be similar (especially the one from https://github.com/raamcosta/CalorieTracker
