### ISSUE TITLE
Correct way to nest destinations on one screen?

### ISSUE THREAD

**Issue by zunjae** [raamcosta/compose-destinations#455]
Hello. Consider the following flow:

HomeScreen > DogScreen > DogDetailScreen

**HomeScreen**
A screen with a toolbar and content (Scaffold) that contains a button that brings you to DogScreen

**DogScreen**
A screen with a toolbar and BottomBar with 3 tabs **A**, **B**, **C**. From inside these tabs, a Dialog destination can be opened. From the **A** tab, the user can navigate to **DogDetailScreen**

**DogDetailScreen**
Contains info about the clicked dog in tab **A**. This screen also contains a BottomBar

I tried reading this https://composedestinations.rafaelcosta.xyz/common-use-cases/bottom-bar-navigation/ (bit hard to read in my opinion...) 

Am I correct in understanding that there needs to be two **DestinationsNavHost**? One in **HomeScreen** which hosts the entire app and one in **DogScreen** so you can navigate between **A, B, C** tabs while still showing the toolbar from **DogScreen**

Or is there a better way? I can provide sample project if needed

**Comment by raamcosta** [comment]
Hi @zunjae 👋 

> I tried reading this https://composedestinations.rafaelcosta.xyz/common-use-cases/bottom-bar-navigation/ (bit hard to read in my opinion...)

I'm sorry to hear that, I hope I can improve it with the feedback from this thread :) 

> Am I correct in understanding that there needs to be two DestinationsNavHost? One in HomeScreen which hosts the entire app and one in DogScreen so you can navigate between A, B, C tabs while still showing the toolbar from DogScreen

No, I wouldn't use two DestinationsNavHosts in this case. Also, HomeScreen doesn't contain a DestinationsNavHost, if it is a screen the itself is part of a NavHost. 
Usually, you want to have a DestinationsNavHost in the top composable (call it MainComposable or AppNavigation). This DestinationsNavHost is wrapped by the Scaffold. Then you can listen for the current destination and make your Scaffold react to that (by changing the title of the toolbar or hiding/showing the bottom bar).

There is an example of this in my sample app in this github repo. We are hiding the toolbar and bottom bar while in Login screen, and showing them (I think animating it, but you don't need to do that, you can just wrap the bars in an `if (currentDestination.shouldShowBottomBar)`.

Hope this helps. Let me know 🙂

**Comment by raamcosta** [comment]
I'll close this for being stale. Let me know if you have any feedback!
