### ISSUE TITLE
BackHandler does not respond when activity stopped/resumed. (Known issue)

### ISSUE THREAD

**Issue by cj1098** [raamcosta/compose-destinations#459]
Hello! There is a known issue by google regarding the BackHandler and the lifecycle. https://issuetracker.google.com/issues/279118447

It seems like google might have addressed it in [2.7.0-beta01](https://developer.android.com/jetpack/androidx/releases/navigation#2.7.0-beta01) of the navigation library. When you get a chance could we upgrade compose destinations to this to test? :)

**Comment by raamcosta** [comment]
Hi @cj1098 👋

Yea definitely, I’ll make sure to do this this weekend if I can’t do it before.

**Comment by raamcosta** [comment]
Done. Check version 1.9.50 (cooking atm).
