### ISSUE TITLE
Direct Navigation to Composable with Control or Command + Click on Destination

### ISSUE THREAD

**Issue by xavijimenezmulet** [raamcosta/compose-destinations#461]
## Description of the Proposed Enhancement
Currently, when clicking on a destination created by the library without any modifier keys, it performs navigation based on the specified route. However, it would be useful to have the option to directly navigate to the corresponding composable when clicking with Control (on Windows/Linux) or Command (on macOS) held down.

## Use Case Example
Within an application that utilizes the library, there is a screen with a list of items that have different destinations configured. Currently, when a user clicks on one of these destinations, the application navigates to the specified route instead of taking the user directly to the corresponding composable. This can be inconvenient and require more steps to access the desired content.

With the proposed enhancement, users could click with Control (on Windows/Linux) or Command (on macOS) held down on a destination and be directly taken to the corresponding composable, avoiding the need to navigate through the complete route.

## Benefits of the Enhancement
- Increased efficiency and speed in accessing desired composables.
- Reduction of steps and clicks required for navigation within the application.
- Greater flexibility and control for users in choosing how to navigate the interface.

## Additional Considerations
- This feature request aims to improve the user experience and provide a more convenient option for navigation within the application.
- It would be important to retain the current behavior for cases where no modifier keys are used, as some users may prefer that option.

**Comment by raamcosta** [comment]
@xavijimenezmulet I must admit I am a little confused with the proposal. Is this improvement targeting the IDE time for developers or runtime behaviour of navigation? 😅 

If you want to control-click on IDE and get to Composable instead of the generated Destination, that would probably require an IDE plugin, so I think it's hard work for little benefit, imo.
BUT what I am doing now is that each generated Destination is commented with the Composable and does so with a link. So navigating to a Destination you'll see the link to the Composable right above the Destination, so you can quickly go to the Composable.

How does this sound? Without a LOT more work, it's what we can do :)

**Comment by xavijimenezmulet** [comment]
@raamcosta I think what you have said is enough. Simply having a link that allows you to navigate is enough.
Thanks for your quick response! The solution is perfect.

**Comment by Jon889** [comment]
To get around this I've been adding a typealias above each composable and then using that, eg:

```kotlin
typealias ProfileScreenDestination = com.myapp.destinations.ProfileScreenDestination // deliberately not importing so it's easier to check the type aliases are being used by using Find in project.

@Destination
@Composable
fun ProfileScreen(isMember: Boolean) { ... }
```

and then doing: `navigator.navigate(ProfileScreenDestination(isMember = true))`

Not sure if there are any downsides, apart from it being a bit unobvious which one to use in the IDE autocomplete so it would be nice if there was an option for the library to generate the Destinations with a underscore prefix or something. But I realise this is kind of a niche option.
