### ISSUE TITLE
Build error: ResultRecipient second type argument must be a valid type with no '*' variance

### ISSUE THREAD

**Issue by sahianmol1** [raamcosta/compose-destinations#463]
The code was working fine. I made some changes in the code. Moved the data and domain packages to a separate module and oll of sudden I was getting this error while building the project. Please help:

[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: ResultRecipient second type argument must be a valid type with no '*' variance.

**Comment by raamcosta** [comment]
Hi 👋 

Is the result type you are trying to use in a different module?

**Comment by raamcosta** [comment]
@sahianmol1 let me know about my previous question!

**Comment by arturyn97** [comment]
> @sahianmol1 let me know about my previous question!

Yes! I have the same error and my ResultType is in another module. Any recommendation?
