### ISSUE TITLE
ResultBackNavigation argument Double and KotlinX Serializable

### ISSUE THREAD

**Issue by SammYWin** [raamcosta/compose-destinations#465]
Hello, I encountered some problem while implementing result back navigation.
Here is the argument class that I have:
```
import com.lett.lettdo.features.address_search.domain.models.LatLon
import kotlinx.serialization.Serializable

@Serializable
data class AddressSearchNavBackModel(
    val displayText: String,
    val latLon: LatLon
)
```

and the LatLon class inside it:
```
import kotlinx.serialization.Serializable

@Serializable
data class LatLon(
    val lat: Double,
    val lon: Double
)
```

But the compiler giving me an error "Result types must be one of: String, Long, Boolean, Float, Int, Parcelable, Serializable"

It was a bit confusing for me to find out I can't use Double. And it's much more convenient to use double for lat lon class. Also Im using the kotlinX Serialization and looks like it's not supported as well. 
But it is supported in normal navigation between screens. Why is there such inconsistency between those types of navigation? 
I guess here I will have to use Float and old java serialization, right?

**Comment by raamcosta** [comment]
Hi  @SammYWin 👋 

> But the compiler giving me an error "Result types must be one of: String, Long, Boolean, Float, Int, Parcelable, Serializable"

Note that Serializable refers to Java Serializable not kotlinx.

> Why is there such inconsistency between those types of navigation?

Supporting kotlinx serialisation on result back feature has been requested and is on my radar, but it’s not as easy to do as navigation arguments. I haven’t even confirmed it is even possible. It’s a feature which has way less usage as well and so I have other priorities at the moment.
Hope that explains it a bit 😅

> It was a bit confusing for me to find out I can't use Double

SavedStateHandle (which is where we store these results) doesn’t have a way to pass double if I remember correctly.

> I guess here I will have to use Float and old java serialization, right?

That is one way, yes. Or use a Parcelable class.

**Comment by SammYWin** [comment]
Ok, got it, thank you for a quick answer and your work!

**Comment by SammYWin** [comment]
Btw, it appeared Double is accepted in SavedStateHandle as well as in the navBackArgs, so you might wanna update the doc on that to remove the confusion if future :)
