### ISSUE TITLE
Turning off possibility of dismissing bottom sheet

### ISSUE THREAD

**Issue by pwojtowicz-rg** [raamcosta/compose-destinations#466]
Is it possible to temporarily turn off possibility of dismissing bottom sheet?

I have now some screen defined with: @Destination(style = DestinationStyleBottomSheet::class)
and I am opening it with DestinationsNavigator: navigator.navigate(SelectStopFromListScreenDestination(

I remember that previously when I was not using your library I could achieve it with something like this: 

```
val modalSheetState = rememberModalBottomSheetState(
   initialValue = ModalBottomSheetValue.Hidden,
   confirmStateChange = { it != ModalBottomSheetValue.HalfExpanded },
   skipHalfExpanded = true,
)
```
as it is described here: https://proandroiddev.com/bottom-sheet-in-jetpack-compose-d7e106422606

_"confirmStateChange is necessary to control the behavior of bottom sheet. If you set confirmStateChange = { false } user will not be able to dismiss bottom sheet by dragging or tapping outside."_

Can you help me with it? :)

**Comment by raamcosta** [comment]
Basically what you’re doing with this library would require accompanist navigation material if you were not using this library.

**Comment by raamcosta** [comment]
I was gonna comment on that as well but got interrupted 😁
I admit I’m not sure if it is possible with accompanist material navigation, I need to check it.
If it’s possible there, it should also be possible here though 🙂

**Comment by raamcosta** [comment]
I found this:

https://github.com/google/accompanist/issues/730

I think we can close this issue, we'll get this as soon as accompanist implements it!
