### ISSUE TITLE
I am trying to use 1.9.50 and I am getting this error when I build my project.

### ISSUE THREAD

**Issue by imanih20** [raamcosta/compose-destinations#467]
Hello, I want to use version 1.9.50 but when I building my project I am getting this error.
`Dependency 'androidx.navigation:navigation-common:2.7.0-beta02' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.`
I am using android studio flamingo

**Comment by l2hyunwoo** [comment]
Navigation compose version updated when compose-destination [bump to 1.9.50](https://github.com/raamcosta/compose-destinations/commit/efd4d6fe880a4335dc4d5ea2be3c2f82b9dc5581). I think should be fixed :)

**Comment by raamcosta** [comment]
This is correct, it's using 2.7.0-beta02 jetpack navigation which seems to require 24 as compile sdk.

I'm not sure we want to do something though since if you were directly using jetpack navigation you would also need to compile with version 34 API 🤔

**Comment by raamcosta** [comment]
Is targeting 34 a blocker for you guys? If so, why?

**Comment by ammargitham** [comment]
I can explain my situation. Currently the maximum recommended compile SDK version for Android Gradle plugin 8.1.0 is 33. So to use SDK 34, I have to update AGP to 8.2 or higher. [However the current stable release of Android Studio (Giraffe) max supported AGP version is 8.1](https://developer.android.com/studio/releases#android_gradle_plugin_and_android_studio_compatibility). So I will have to install Android Studio Hedgehog which is a preview canary build and I don't want to do that. So yeah SDK 34 is a blocker for me at-least.

**Comment by raamcosta** [comment]
Latest compose 1.5.0-rc01 also requires sdk 34. So if you cannot use sdk 34 I think you should stick with compose 1.4 (and so 1.8.x versions of compose destinations) since it seems like compose 1.5 is moving to sdk 34.

**Comment by ammargitham** [comment]
You're right. I just wonder if they expect devs to use AS preview builds to use stable compose releases.

**Comment by jonneymendoza** [comment]
Hi. is there a way to use the stable version 2.6.0 of compose navigation instead of the release candidate one?

**Comment by raamcosta** [comment]
The thing is that current compose 1.5 also requires sdk 34 😬
And version 1.9.x of this lib is supposed to be used with compose 1.5. So I don’t think theres a workaround here.

Are you guys using compose 1.5? If so, don’t you have this issue anyway? If not then you should use 1.8.x instead.

**Comment by ammargitham** [comment]
I think this will be resolved once [they remove the warning when targeting SDK 34 in AGP 8.1.1](https://issuetracker.google.com/issues/295235385?pli=1).

**Comment by raamcosta** [comment]
Yes, I also heard about this yesterday in a tweet from Ian Lake:
https://twitter.com/ianhlake/status/1689452195769659392?s=46&t=SO6TS1csmHnkqeqcoVZSwA

**Comment by raamcosta** [comment]
Until then you can just ignore that warning btw.
