### ISSUE TITLE
Documentation Bug: Share ViewModels between multiple destinations

### ISSUE THREAD

**Issue by commonsguy** [raamcosta/compose-destinations#468]
https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels/#share-viewmodels-between-multiple-destinations

The sample code currently is:

```kotlin
@Composable
fun AppNavigation(
    activity: Activity
) {
    DestinationsNavHost(
        //...
        dependenciesContainerBuilder = { //this: DependenciesContainerBuilder<*>

            // 👇 To tie SettingsViewModel to "settings" nested navigation graph, 
            // making it available to all screens that belong to it
            dependency(NavGraphs.settings) {
                val parentEntry = remember(navBackStackEntry) {
                    navController.getBackStackEntry(NavGraphs.settings.route)
                }
                hiltViewModel<SettingsViewModel>(parentEntry)
            }

            // 👇 To tie ActivityViewModel to the activity, making it available to all destinations
            dependency(hiltViewModel<ActivityViewModel>(activity))
        }
    )
}
```

However, for `dependency(hiltViewModel<ActivityViewModel>(activity))`, `activity` needs to be a `ViewModelStoreOwner`. `Activity` does not satisfy that, but `FragmentActivity` does, as would `ComponentActivity` (the superclass of `FragmentActivity`). It feels like the function signature should be `fun AppNavigation(activity: ComponentActivity)`.

My apologies if I am missing some nuance here, and many thanks for writing this library!

**Comment by raamcosta** [comment]
Nice catch, thanks :) 

Should be fixed!
Just as a side note, each page has a "edit this page" button at the bottom which lets you easily create a PR with the change :) 

Each page is just markdown, so it's easily changed by anyone!

**Comment by raamcosta** [comment]
@commonsguy please let me know if you find anything else.

Documentation is definitely needing some attention, but I'm focused on v2 which will change things anyway, so I'll make sure to update and add everything for v2!
