### ISSUE TITLE
Start destination arguments

### ISSUE THREAD

**Issue by AhmedMourad0** [raamcosta/compose-destinations#469]
Hello, right now when adding arguments to a start destination of a graph, the build fails with this error:
```
Start destinations cannot have mandatory navigation arguments!
```
My assumption is that it's possible to pass agruments to the start destination using either `manualComposableCallsBuilder` or `dependenciesContainerBuilder`, if so can this error be removed?

My case is that i'm setting an alarm clock with a pending intent that will start an activity (different than the main activity) at different times of day, that activity has some parameters that I want to pass down the start destination of its graph.

Thank you

**Comment by raamcosta** [comment]
Hi @AhmedMourad0 !

You are right that you'll be able to pass data from the NavHost call level down to your composables via those two NavHost arguments. However, those are NOT navigation arguments. Navigation arguments is something you pass from one destination to the next one, which is not the case. So the error still applies.

If your Composable is defining this argument that is considered to be a navigation argument, but in reality, you just want to pass that from NavHost level, then you need to annotate that argument with @NavHostParam annotation.
In this way, the navigation destination won't be registered with that nav argument, and you'll need to pass it from NavHost via either of the two methods you referred.

Hope this helps! Let me know!
