### ISSUE TITLE
How to use popUpTo

### ISSUE THREAD

**Issue by knightsamir** [raamcosta/compose-destinations#47]
```
 navController.navigate(destination) {
                popUpTo("summary_screen") { inclusive = true }
           }

navigator.navigate(destination)
```
I am using above code to pop summary screen from backstack before navigating but its not working. Am i missing something?

**Comment by jahongir9779** [comment]
I'm also observing this issue, and I am using 
```
navigator.navigate(destination) {
    popUpTo(...Destination.route) {
        inclusive = true
    }
}
```

but when I tried with navController it is working...

**Comment by raamcosta** [comment]
```kotlin
navigator.navigate(direction = destination, onlyIfResumed = false) {
    popUpTo(...Destination.route) {
        inclusive = true
    }
}
```

@jahongir9779 can you try this code and let me know? thank you.

**Comment by jahongir9779** [comment]
No, unfortunately it didn't work

**Comment by raamcosta** [comment]
Other than that, the implementation just calls NavController directly, so I don't see another way that the equivalent code using NavController would work and now with DestinationsNavigator wouldn't.

Try it with NavController again, like this:
```kotlin
@Destination
@Composable
fun MyScreen(
    navController: NavController // <----- switch DestinationsNavigator with NavController
) {
    /....
    navController.navigate(destination.route) {
        popUpTo(...Destination.route) {
            inclusive = true
        }
    }
}
```

**Comment by miduch** [comment]
also facing same issue. for me even directly using navController isn't working 

tried 


```
navigator.navigate(direction = destination) {
    popUpTo(...Destination.route) {
        inclusive = true
    }
}
```

```
navigator.navigate(direction = destination, onlyIfResumed = false) {
    popUpTo(...Destination.route) {
        inclusive = true
    }
}
```
 and also 
 
 ```
navController.navigate(destination.route) {
        popUpTo(...Destination.route) {
            inclusive = true
        }
    }
```

**Comment by raamcosta** [comment]
Hey!

Well, this pretty much has to work :D 
Can you add these lines right before calling the DestinationsNavHost?

```kotlin
    val destination = navController.appCurrentDestinationAsState().value
        ?: startRoute.startAppDestination

    navController.backQueue.print()
```

then somewhere in same file:

```kotlin
private fun ArrayDeque<NavBackStackEntry>.print(prefix: String = "stack") {
    val stack = map { it.destination.route }.toTypedArray().contentToString()
    println("$prefix = $stack")
}
```

**Comment by raamcosta** [comment]
This will print the back stack routes everytime they change, so add that, then reproduce the issue and paste here the logs starting with `stack =`

**Comment by miduch** [comment]
not sure if i understood what to do with : 

 ```
   val destination = navController.appCurrentDestinationAsState().value
        ?: startRoute.startAppDestination
```

i have multi module project

**Comment by raamcosta** [comment]
Oh ok sorry

**Comment by raamcosta** [comment]
```kotlin
    LaunchedEffect(key1 = Unit) {
        navController.currentBackStackEntryFlow.collect {
            navController.backQueue.print()
        }
    }
```

**Comment by raamcosta** [comment]
Do this instead sorry :)

**Comment by miduch** [comment]
i see this line 

Ignoring popBackStack to destination -1928565755 as it was not found on the current back stack

when i'm trying to navigate to screen (by pressing bottom Navigation item) with no navigation/cleared history

**Comment by miduch** [comment]
app has bottom navigation , from content i can click on an item -> go deep -> deeper -> press bottom navigation -> history cleared and you're back on one of main/root level screens/destinations

**Comment by raamcosta** [comment]
It would be helpful to see the back stack routes right before navigating with your pasted code snippet and right after. Also check the route you’re trying to pop up from the back stack and see if that route is actually on the back stack.

**Comment by raamcosta** [comment]
With above LaunchedEffect and the print methods you should see the back stack in real time, as the current screen changes.

**Comment by miduch** [comment]
stack = [newsfeed_route, newsfeed_screen?feedTypes={feedTypes}]
stack = [newsfeed_route, newsfeed_screen?feedTypes={feedTypes}, article_route, article_screen/{assetUrl}]
stack = [newsfeed_route, newsfeed_screen?feedTypes={feedTypes}, article_route, article_screen/{assetUrl}, find_route, section_newsfeed_route, section_newsfeed_screen/{title}?sections={sections}]

```
navigator.navigate(
            direction = FindScreenDestination,
            onlyIfResumed = false
        ) {
            popUpTo(FindScreenDestination.route) {
                inclusive = true
            }
        }

```

 expected this above popUpTo call to cleanup backstack but everything is still on backstack + just navigated find_screen

Ignoring popBackStack to destination -1928565755 as it was not found on the current back stack
stack = [newsfeed_route, newsfeed_screen?feedTypes={feedTypes}, article_route, article_screen/{assetUrl}, find_route, section_newsfeed_route, section_newsfeed_screen/{title}?sections={sections}, find_screen]

**Comment by miduch** [comment]
/**
     * Pop up to a given destination before navigating. This pops all non-matching destination routes
     * from the back stack until the destination with a matching route is found.
     */

I thought it would work like this: 

1. pops up all previously visited screens from backstack , including find screen if it was visited 
2. navigate to findscreen 

what would be correct way to navigate Findscreen + get rid of all history ? 

Thanks a lot!

**Comment by raamcosta** [comment]
You need to popUpTo the first entry in the back stack. Remember it pops from the top to bottom. So if you want to pop all, then you need to give it the one in the bottom of the stack 🙂

**Comment by miduch** [comment]
thanks for helping out. Now it works
