### ISSUE TITLE
Multi module result back case with custom result type

### ISSUE THREAD

**Issue by trod-123** [raamcosta/compose-destinations#470]
Hi there,

I have a multi module project that's configured in a way so that my "feature" modules do not have any dependencies on each other. I have a screen built in a module A that launches a screen in some other module B, and returns a result back to module A. This result is a custom type implemented as a Kotlin data class.

I was reviewing the [documentation](https://composedestinations.rafaelcosta.xyz/navigation/backresult/#multi-module-result-back-case) and from what I gather, it says that the recipient must define a `OpenResultRecipient<T>` with the result data type `T`. However, in my case, since the recipient and sender are defined in different modules, the recipient has no way to reference `T`.

I could work around this by providing a "shared" module C that contains all the data types every "feature" module (e.g. A and B) can access... but I would like to avoid this if possible because it breaks the separation paradigms that this library relies on with the multi module configurations available.

Are custom result types currently supported in multi module projects? I am currently consuming `1.8.42-beta`.

Appreciate your response, and thanks for your continued passion and efforts with this amazing project.

**Comment by raamcosta** [comment]
Hi @trod-123 !
At the moment, for complex types, you'd have to be able to reference the type T from both modules. A workaround might be to use a String (some sort of serialized version of the complex type).

The way you could do this with official compose navigation is not better tbh. You'd be passing a key-value pair via SavedStateHandle. Then on recipient you would need to know both the key and type of value to be able to use it. 

It seems to me like this situation, however, might be an indication that maybe you should rethink how you are modularizing. If it was me, I'd be looking to expose entire navgraphs from each feature module in a way that other modules don't need to know about destinations, they only navigate to the nav graph itself. If you have some kind of modal destination that needs to be used by multiple modules, maybe it should be inside its own module that all clients can depend on.
Of course, I don't know the exact situation, so I can only talk theoretically 😄. I'm sure there are cases where using a non-type-safe approach is warranted.

Let me know if this helped!

**Comment by trod-123** [comment]
Hi @raamcosta , thanks for your response! Appreciate your insight into things.

I think I can afford to make do with defining a shared space for all of my "feature" modules to reference common things such as Result data types. I'd very much prefer having type safety over dealing with serialized versions of things provided as a String.

Regarding your note on modularizing, thought I share some context around how my project is structured and how I plan to leverage Compose Destination's Result APIs with this in mind. Would appreciate your input on whether you think this approach will scale (apologies if the below is a bit long and beyond this issue thread 🙏 ). Thanks in advance! 

(arrows below indicate _dependency on_, e.g. `:app` depends on `:feature`)

![image](https://github.com/raamcosta/compose-destinations/assets/11514412/b810f11d-d38a-415f-aecd-b4161f207bb8)

Some callouts:
- `:app` is a single activity container that hosts `:feature` modules. It can access all generated destinations defined in each `:feature` module, so it manages the nav graph and implements navigation.
- `:feature` modules can access the `:shared` modules, which provides a "shared space" for defining things such as Result data types.

`:feature` modules would typically define a `Navigator` interface which the `:app` module would implement.

Here's some sample code illustrating my project implementation (not intended to be compile-able):

```kotlin
//
// :shared:navigation
//

@Parcelize
data class BarResultArgs(
    val status: Int,
    val message: String,
) : Parcelable

//
// :feature:foo
//

// This is a page that will launch another page for result
@Composable
fun FooPage(
    navigator: FooNavigator,
    barResultRecipient: OpenResultRecipient<BarResultArgs>,
) {
    Button(
        text = "Present Bar",
    ) {
        navigator.navigate(FooNavigationTarget.BarPage(x = 42, y = "Compose Destinations is amazing!"))
    }

    // result
    barResultRecipient.onNavResult { result ->
        when (result) {
            is NavResult.Canceled -> {
                // no-op
            }
            is NavResult.Value -> {
                print(result.value) 
            }
        }
    }
}

// SAM to be implemented in `:app`
interface FooNavigator {
    fun navigate(target: FooNavigationTarget)
}

// Abstraction defining the pages FooPage can navigate to
sealed interface FooNavigationTarget {
    data class BarPage(val x: Int, val y: String): FooNavigationTarget
}

//
// :feature:bar
//

data class BarArgs(
    val x: Int,
    val y: String,
)

// This is a page that can return a result back
@Destination(
    navArgsDelegate = BarArgs::class
)
@Composable
fun BarPage(
    navigator: BarNavigator,
) {
    Button(
        text = "Pass result back",
    ) {
        navigator.navigate(BarNavigationTarget.PassBackResult(BarResultArgs(status = 200, message = "Success!"))
    }
}

// SAM to be implemented in `:app`
interface BarNavigator {
    fun navigate(target: BarNavigationTarget)
}

// Abstraction defining the pages BarPage can navigate to
sealed interface BarNavigationTarget {
    data class PassBackResult(val result: BarResultArgs): BarNavigationTarget
}

//
// :app
//

class AppNavigator(
    private val navController: NavController,
    // all `ResultBackNavigators` for all features will be added here
    private val barResultNavigator: ResultBackNavigator<BarResultArgs>,
) : FooNavigator,
    BarNavigator {

    override fun navigate(target: FooNavigationTarget) {
        when (target) {
            is FooNavigationTarget.BarPage -> {
                navController.navigate(BarPageDestination(x = target.x, y = target.y))
            }
        }
    }

    override fun navigate(target: BarNavigationTarget) {
        when (target) {
            is BarNavigationTarget.PassBackResult -> {
                barResultNavigator.navigateBack(result = target.result)
            }
        }
    }
}

@Composable
fun AppNavHost(
    navController: NavHostController,
    navGraph: NavGraphSpec,
) {
    @Composable
    fun DestinationScopeWithNoDependencies<*>.createNavigator(): AppNavgiator {
        return AppNavigator(
            navController = navController,
            barResultNavigator = resultBackNavigator(),
        )
    }

    DestinationsNavHost(
        navGraph= navGraph,
        navController = navController,
        engine = rememberAnimatedNavHostEngine(),
        dependenciesContainerBuilder = {
            dependency(createNavigator())
        },
        manualComposableCallsBuilder = {
            // all pages that receive results will be added here
            composable(FooPageDestination) {
                FooPage(
                    navigator = createNavigator(),
                    barResultRecipient = resultRecipient<BarPageDestination, BarResultArgs>(),
                )
            }
        }
    )
}
```

Some notes -
- I opted to use my `Navigator` interface for each `:feature` module so we can make it very clear without question where a page can navigate to, and to also facilitate unit testing. I also wanted to avoid littering things like `NavController` and `ResultNavigator` in the Composables themselves.
- I've considered providing `resultRecipient` inside `dependenciesContainerBuilder` instead so that I wouldn't need to use `manualComposableCallsBuilder` for every page that requires a `ResultRecipient`... but I realized under the hood mapping is done with types as keys, and any subsequent `resultRecipient` will overwrite any previous ones
- It's a bit out of scope from this issue... but I am not quite sure how performant `createNavigator()` will be, since it is creating a new instance every time I navigate between pages it seems.

**Comment by raamcosta** [comment]
> It's a bit out of scope from this issue... but I am not quite sure how performant createNavigator() will be, since it is creating a new instance every time I navigate between pages it seems.

As long as you don't do anything expensive as part of that instantiation, you should definitely be fine :) when you navigate, some instantiations are done anyway, the instantiation itself is not expensive enough to be concerning (unless you do TONS of them).

Also, be prepared for some changes around the corner with v2. I think you'll like the changes, but they may require some changes on your side. Of course, I am not dropping v1 (no new features there but still compose, navigation updates and bug fixes), I want to keep both options for some time to give people time to migrate.

**Comment by raamcosta** [comment]
Given it seems like you reached an ok place with this, I'll close it. But please let me know if you find some issue with implementing your approach! :)
