### ISSUE TITLE
Leave the screen visible at the bottom

### ISSUE THREAD

**Issue by TemMax** [raamcosta/compose-destinations#471]
Hello! Thanks a lot for a great library!
I have a question about navigation. I want to make a swipe-back gesture, but there in backstack could be visible only one composable. How can I achieve it?

**Comment by raamcosta** [comment]
Hi @TemMax 

I don't fully understand the question, but I feel like this is probably not the place for it. This library is a wrapper to official library compose navigation, so you're best bet is to search around how to do what you want (or ask on kotlin slack / stackoverflow) and then you should be capable of doing that same thing in compose destinations.
If you have an issue there, do let me know at that point!

Closing it, but let me know how it goes!
