### ISSUE TITLE
Reusing destinations with different set of navigation arguments

### ISSUE THREAD

**Issue by trod-123** [raamcosta/compose-destinations#472]
Hi @raamcosta - me again 😄 

This isn't so much an "issue" as it is a "discussion".

I'm curious if Compose Destinations supports cases where we want to reuse a destination but provide a different set of navigation arguments.

I've done some initial investigating into this which I'm happy to share below.

For example, consider the following scenarios (image)

![image](https://github.com/raamcosta/compose-destinations/assets/11514412/fb58fb31-25a5-4dba-b899-da2f4689365d)

Scenario 1
- User makes a search, and results come back as a `slug` which we pass to the configure screen.
- The configure screen fetches all details pertaining to that slug, and allows users make a configuration based on that. After choosing a configuration, we pass the associated `ids` to the details screen.
- The details screen presents details according to the `ids` provided.

Scenario 2
- User wants to edit an existing search, which is already encapsulated as `ids`, and we pass those `ids` to the configure screen
- The configure screen uses the ids to fetch all the details of the other configurations available, and allows users to update their configuration based on that. After choosing the configuration, we pass the new `ids` back to the search screen.
- Back in the search screen, the existing search is updated according to the new configuration

For both scenarios, the configure screen is the same, but it is used differently. 

There are several ways we could implement this in code.

**Single `navArgsDelegate` and enums**

We can use a single `navArgsDelegate` for both, and leverage an enum to denote how the Configure screen should behave:

```kotlin
data class ConfigureArgs(
    val slug: String?,
    val id1: Int?,
    val id2: Int?,
    val mode: ConfigureMode, // "Search" or "Edit"
)
```

However, this approach isn't "typesafe" as it would open some confusion on how different "combinations" of args would be used, and makes it confusing what exactly is required and not.

**Single `navArgsDelegate` and sealed interfaces**

Alternatively, we could continue using a single `navArgsDelegate`, but leverage Kotlin's `sealed interfaces` to make things "typesafe":

```kotlin
data class ConfigureArgs(
    val mode: ConfigureMode,
)

sealed interface ConfigureMode {
    data class Search(val slug: String): ConfigureMode
    data class Edit(val id1: Int, val id2: Int): ConfigureMode
}
```

However, `ksp` throws an error:

```
[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Composable 'ConfigurePage': 'navArgsDelegate' cannot have arguments that are not navigation types. (check argument 'mode')
``` 

Given that, it seems `sealed interface` is not supported by Compose Destination. I've also tried using `sealed class` instead, but I get the same error.

**Multiple `navArgsDelegate`**

I decided to explore the multiple `navArgsDelegate` approach for each scenario so we can make it clear just what the args are used for. Using Compose Destinations, I've gone ahead and built it like this:

UI (note the `Navigator`, `ViewModel` and `PageContent` are the same)
```kotlin
//
// Scenario 1
//

data class SearchConfigureArgs(
    val slug: String
)

@Destination(
    navArgsDelegate = SearchConfigureArgs::class
)
@Composable
fun SearchConfigurePage(
    navigator: ConfigureNavigator,
    viewModel: ConfigureViewModel = hiltViewModel(),
) {
    ConfigurePageContent()
}

//
// Scenario 2
//

data class EditConfigureArgs(
    val id1: Int,
    val id2: Int,
)

@Destination(
    navArgsDelegate = EditConfigureArgs::class
)
@Composable
fun EditConfigurePage(
    navigator: ConfigureNavigator,
    viewModel: ConfigureViewModel = hiltViewModel(),
) {
    ConfigurePageContent()
}
```

Since we access the navigation arguments from inside the ViewModel's `SavedStateHandle`, we need our `SavedStateHandle` to support both set of arguments, otherwise the app will crash due to casting errors.

I've gone ahead and defined our `ConfigureMode` which is privately scoped to our `ViewModel`.

Mode and ViewModel
```kotlin
private sealed interface Mode {
    data class Search(val args: SearchConfigureArgs) : Mode
    data class Edit(val args: EditConfigureArgs) : Mode

    companion object {
        fun SavedStateHandle.navArgsMode(): Mode {
            try {
                return Search(navArgs())
            } catch (e: Exception) {
                // proceed
            }

            // throw if error
            return Edit(navArgs())
        }
    }

    fun toInput(): GetConfigurationChoicesUseCase.Input = when (this) {
        is Search -> {
            GetConfigurationChoicesUseCase.Input.Slug(
                slug = this.args.slug,
            )
        }
        is Edit -> {
            GetConfigurationChoicesUseCase.Input.Id(
                id1 = this.args.id1,
                id2 = this.args.id2,
            )
        }
    }
}

@HiltViewModel
class ConfigureViewModel @Inject constructor(
    savedStateHandle: SavedStateHandle,
    getConfigurationChoices: GetConfigurationChoicesUseCase,
) {
    private val argsMode = savedStateHandle.navArgsMode()
    private val choices = getConfigurationChoices.invoke(input = argsMode.toInput())

    // [...]

    fun handleActionClick() {
        when (argsMode) {
            is Search -> {
                // navigate user to Details page
            }
            is Edit -> {
                // send result back to previous screen and navigate back
            }
        }
    }
}
```

The above implementation works just as we'd need, but as you can see there's a decent amount of boilerplate we need to add to support this scenario.

💨 

What do you think of this approach? Or is there another way that Compose Destinations can do this for us more easily?

Thank you in advance! 🙏

**Comment by raamcosta** [comment]
Hi @trod-123!

So your second approach with the sealed interface can work if you annotate it with @Serializable from kotlinx serialization or you make the interface extend Parcelable (which is also an interface) which will then force each of your options inside that sealed interface to also be annotated with kotlinx serialization (if you go that route) or implement the Parcelable interface.

Note that destinations are defined by their navigation arguments (they're literally part of their route id when using official compose navigation) so you must only one set of arguments. Like you suggested, either a sealed hierarchy or a class with both nullables can work or by having different Composables annotated with @Destination that then call the same composable. To be honest, I don't dislike the last approach, but I think you might prefer the sealed interface.

Let me know if that fixes it for you!

**Comment by trod-123** [comment]
Hi Rafael,

The `Parcelable` bit did it ✅ .

With the following, I can define a single Configure destination with different "modes".

```kotlin
data class ConfigureArgs(
    val mode: ConfigureMode,
)

sealed interface ConfigureMode : Parcelable {
    @Parcelize
    data class Search(val drugSlug: String) : ConfigureMode

    @Parcelize
    data class Edit(val drugId: Int, val quantity: Int) : ConfigureMode
}

@Destination(
    navArgsDelegate = ConfigureArgs::class
)
@Composable
fun ConfigurePage(
    navigator: ConfigureNavigator,
    viewModel: ConfigureViewModel = hiltViewModel(),
)
```

The `ViewModel` handling is a lot cleaner, and I no longer need all that brittle boilerplate involved with juggling different `navArgsDelegate` types. I think it also looks nicer for the consumer to not need to think about different `ConfigureDestination` to choose from; just pass the mode of interest.

Regarding deep linking... that's something I'll need to explore in more detail next. I know you suggested making each enumeration of the `sealed interface` `Parcelable`, but do you foresee any issues if I wanted to launch a specific mode of Configure screen via deep links?

Thanks again in advance.

**Comment by raamcosta** [comment]
Hi @trod-123 

Deep linking into destinations that have arguments of type Parcelable (or Serializable) means that by default your link is gonna have a long base64 string. So it depends of what your needs are with the deep link. If you’re generating the link inside the app itself and you’re using it to put on a notification for example, then you can easily create the link by calling YourDestination(yourArgs).route and since the link won’t even be visible to the user, it should be fine.
However, if you need to generate the deep links somewhere else and/or the user will see the link, then it will make sense to provide a NavTypeSerializer that basically will let you choose how the argument type will be represented in the route. If you do that, then you won’t need Parcelable anymore and creating the deeplink outside the app will be easierbas well as the link will be prettier 🙂

**Comment by trod-123** [comment]
This is good, thanks @raamcosta.

I'll mark this issue as resolved for the time being, and open a new one for deep linking if I come across anything weird. Hopefully not 😃
