### ISSUE TITLE
Navargs question

### ISSUE THREAD

**Issue by DeemAQ** [raamcosta/compose-destinations#473]
I have Screen A which passes an object to Screen B. This object is only used in the screen and I don't need it in the view model.
However, Screen B needs an object from Screen C, which Screen B will need in the view model.
How should I go about this?

**Comment by raamcosta** [comment]
@DeemAQ 

Did you find the way to do what you wanted? I’m sorry I didn’t answer in time! Do let me know 🙂

**Comment by DeemAQ** [comment]
> 

Yes thank you I've figured out a way but it took me a while. I made it so Screen A sends the object as navarg to ScreenB, Screen B will receive nav result from Screen C. I was lost a little because it kept throwing me compilation errors and it seems Destinations does not support @Serializable (kotlinx).

**Comment by raamcosta** [comment]
Compose destinations does support kotlinx serialization. If you give me more details maybe I can understand why you were not able to use that

**Comment by ryanholden8** [comment]
> Compose destinations does support kotlinx serialization. If you give me more details maybe I can understand why you were not able to use that

@raamcosta - Thanks for all the work on this project! Just a question here, does this project support `kotlinx.serialization`? From your reply here 2 months ago your saying it's not supported but in the README.md Under `Basic Usage` it explicitly DOES state it is supported: 

> Parcelable, Serializable, Enum and classes annotated with [@kotlinx.serialization.Serializable](https://github.com/Kotlin/kotlinx.serialization) (as well as Arrays and ArrayLists of these)

https://github.com/raamcosta/compose-destinations/blob/main/README.md#basic-usage
