### ISSUE TITLE
Opened by deeplink

### ISSUE THREAD

**Issue by rodrirepresa** [raamcosta/compose-destinations#474]
Is there any easy way to check if my @Composable screen has been opened from deeplink?

before I was using:
`fragment.arguments?.containsKey(NavController.KEY_DEEP_LINK_INTENT)`

**Comment by raamcosta** [comment]
This will have the same answer with official compose navigation. I believe you might want to check NavBackStackEntry (or SavedStateHandle in VM) arguments for the same indication. But I’m just guessing 🙂

NavBackStackEntry you can just add as a parameter and the library will provide it when navigating to it
