### ISSUE TITLE
How can I get the current route with the current arguments

### ISSUE THREAD

**Issue by ricardodalarme** [raamcosta/compose-destinations#478]
How can I get the current route already concatenated with the arguments it was provided?

Example, imagine my base route is:

```
myRoute?message={message}"
```

And I navigate to it passing message = "Hey"

How can I get it:

```
myRoute?message=Hey"
```

**Comment by raamcosta** [comment]
Hi!

This is not something specific to my library.
I actually never needed to do this, so I don’t know from the top of my head.
Notice that you can use the same APIs for this as you would with official jetpack compose navigation.
So you’ll surely be able to find a solution for this on stackoverflow or Kotlin slack.

Please let me know when you find it!

**Comment by raamcosta** [comment]
I guess one way to do it is to just pass the received nav arguments to the Destination, like `YourDestination(yourArgs).route`. Notice the .route that will return the same route that was used to navigate to YourDestination.

Let me know if this helps!

**Comment by ricardodalarme** [comment]
Thanks!!! It helped
