### ISSUE TITLE
How can we use this with bottom navigator of Scaffold?

### ISSUE THREAD

**Issue by wangmir** [raamcosta/compose-destinations#48]
Hi, thanks for the exciting library.

I have a question about getting a navigator at the Scaffold bottom navigator.

When using Scaffold with vanilla nav host, we usually do like this,

```kotlin
@Composable
fun RallyApp() {
    RallyTheme {
        val allScreens = RallyScreen.values().toList()
        val navController = rememberNavController()
        val backstackEntry = navController.currentBackStackEntryAsState()
        val currentScreen = RallyScreen.fromRoute(
            backstackEntry.value?.destination?.route
        )
        Scaffold(
            topBar = {
                RallyTabRow(
                    allScreens = allScreens,
                    onTabSelected = { screen -> navController.navigate(screen.name) },
                    currentScreen = currentScreen
                )
            }
        ) { innerPadding ->
            RallyNavHost(
                navController = navController,
                modifier = Modifier.padding(innerPadding)
            )
        }
    }
}
```

But when using Destinations,

how can we give navigator to the top or bottom bar..? In this situation?

```kotlin
@Composable
fun RallyApp() {
    RallyTheme {
        val allScreens = RallyScreen.values().toList()
        Scaffold(
            topBar = {
                RallyTabRow(
                    allScreens = allScreens,
                    // todo: how can we give navigator?
                    onTabSelected = { screen -> navigator.navigate(screen.name) },
                    currentScreen = currentScreen
                )
            }
        ) { innerPadding ->
            DestinationsNavHost(navGraph = NavGraphs.root)
        }
    }
}
```

**Comment by raamcosta** [comment]
Hi @wangmir !

So I have talked with someone via Twitter dm before about this, I'll paste the images he sent me after I explained to him. I think these will help 🙂 

https://ton.twitter.com/i/ton/data/dm/1483909481352536068/1483909449215799296/o2HXpHVC.png:medium
https://ton.twitter.com/i/ton/data/dm/1483909629776375812/1483909622293741568/m9lpjxDa.png:medium

Basically, some notes:

1- For top-level navigation you should use NavController.navigateTo extension function. DestinationsNavigator is meant for navigating between Destinations.
2- You can get the current destination by calling `currentBackStackEntryAsState()?.navDestination`. This will give you a `Destination`.
3- Top level navigation only works if he destination does not have navigation arguments, so as you can see in the images above, you can take advantage of `DirectionDestination` which is a sealed interface that only contains the Destinations that can be navigated to without navigation arguments.
4- In the images, he used a sealed class, but he could have used an enum as well.
5- You get the NavController just as you did in vanilla Compose Destinations and then you need to pass it to DestinationsNavHost, same as you did for NavHost.

Let me know if this is helpful!

**Comment by raamcosta** [comment]
Closing this issue. Let me know how that goes and feel free to add questions below, I will see them 🙂

**Comment by wangmir** [comment]
Thanks for the kind reply, It was very helpful.

Meanwhile, I still have two problems,

Firstly, curDestination cannot be compared with DirectionDestination type as u mentioned in the code.
The error is like this,
`Operator '==' cannot be applied to 'NavDestination' and 'DayLogListViewDestination'`
(note: DayLogListView is my one of destination.)

So, I tried other way to solve this problem, using `route`.

Second thing is that, in this situation, floating action button also have same problem, and in case of my usecase floating action button requires arguments. 

So, I didn't understand deeply about ur library, but how about provide navigator separately from DestinationNavHost..? Is it possbile?

below is my code currently.

```kotlin
    val navController = rememberNavController()
    val backStackEntry by navController.currentBackStackEntryAsState()
    val currentScreen = backStackEntry?.destination
    val scaffoldState = rememberScaffoldState()
//    val enabled = currentScreen!! == DayLogListViewDestination

    CalliopeTheme {
        Scaffold(
            bottomBar = {
                BottomNavigator(
                    items = BottomMenuContent.values().toList(),
                    // todo: change this with regarding state
                    currentRoute = currentScreen?.route ?: BottomMenuContent.LIST_VIEW.route,
                    navigateToRoute = navController::navigate
                )
            },
            floatingActionButton = {
                if (currentScreen?.route == DayLogListViewDestination.route) FloatingActionButton(
                    onClick = {
                        // todo: Make add view
                        Log.d(TAG, "Add DayLog clicked")
                    },
                    backgroundColor = MaterialTheme.colors.primary
                ) {
                    Icon(imageVector = Icons.Default.Add, contentDescription = "Add DayLog")
                }
            },
            scaffoldState = scaffoldState
        ) {
            DestinationsNavHost(navGraph = NavGraphs.root, navController = navController)
        }
    }
```

**Comment by raamcosta** [comment]
I see an issue here:

```kotlin
val currentScreen = backStackEntry?.destination
//SHOULD BE (navDestination is the library extension property)
val currentScreen = backStackEntry?.navDestination
```

**Comment by wangmir** [comment]
oh, ma bad. thanks about that.

> I see an issue here:
> 
> ```kotlin
> val currentScreen = backStackEntry?.destination // <-- WRONG
> 
> //SHOULD BE (navDestination is the library extension property)
> 
> val currentScreen = backStackEntry?.navDestination
> ```

Oh ma bad. Thanks about that.

**Comment by raamcosta** [comment]
> Second thing is that, in this situation, floating action button also have same problem, and in case of my usecase floating action button requires arguments.

As for this, if you need arguments, then you use a normal `Destination` and for specific `Destination` you can call its invoke function which will contain all arguments you need to navigate to that `Destination`.

```kotlin
navController.navigateTo(FabDestination(arg1 = "arg1"))
```

**Comment by wangmir** [comment]
Oh, thanks, it works. it seems with Destination annotation, even navController can navigate to the destination using parcelable arguments.. awesome.

I can do navigate with using this line (note for other people..)
```kotiln
navController.navigateTo(DayLogViewDestination(date = LocalDate.now()))
```

Thanks!!

**Comment by Buggyy** [comment]
@wangmir Do you mind sharing the full implementation?

**Comment by raamcosta** [comment]
If he does not, I can make an example in the sample app of the repo later 🙂

**Comment by wangmir** [comment]
> @wangmir Do you mind sharing the full implementation?

@Buggyy This is my toy project, so it's a public repo, this is it.
https://github.com/wangmir/calliope/commit/c1a6c45213fc57bcb0c7578be99515648718596b

**Comment by raamcosta** [comment]
@Buggyy let me know if there is any way I can help! :)

I plan to have some tutorials for specific cases like this to complement the sample app.
I have a lot of things in mind still, but I want to do that eventually. Meanwhile, if there is any way I can help!
