### ISSUE TITLE
DestinationsNavTypeSerializer in a different module?

### ISSUE THREAD

**Issue by ZhaohuaZeng-at** [raamcosta/compose-destinations#480]
Hi there, 

I have some classes in module 1 and I would like to use them in module 2 as nav arguments.
I have custom type serializers for those classes in module 1 but found that module 2 is not picking the serializers up and are using the default serializer. Is there any setting I can use to make this work?

**Comment by raamcosta** [comment]
Hi 👋

At the moment, NavTypeSerializers need to be defined in the same module that is generating your Destinations that use those classes as nav arguments.

**Comment by ZhaohuaZeng-at** [comment]
Hi @raamcosta , sorry for the late reply. 
Is it possible to request this feature? My use case is that I want to define argument types inside one module A, and then in both module B and C I would have destinations that ref to some argument types I defined in A. 
Right now, I cannot do this because how destinations generate routes based on the argument serializers. 

My project also uses the kotlinx serialization library and notice they have something like `@Serializable(with=MySerializer:class)` that I can add to the class, and then during serialization it will use the correct serializer. 
I wonder if it is possible to provide such kind of features?
E.g. adding one more annotation like 
```
@NavigationSerializer(with=MyArgSerializer:class)
class MyArg(...)
```
and then inside my nav args my arg will be always serialized with `MyArgSerializer`?
or.... is it possible to have it refer to the one in kotlinx serializable somehow?
