### ISSUE TITLE
Permissions request as part of navigation

### ISSUE THREAD

**Issue by ignaciotcrespo** [raamcosta/compose-destinations#481]
Thanks for this library, we have successfully integrated the library to facilitate the separation of navigation logic from the core codebase.

Among the various advantageous functionalities offered by this library, we particularly appreciate the capability to open screens and await corresponding results. We are keen to explore the possibility of extending the library's functionality to incorporate the management of permissions request in a manner analogous to the existing `ResultBackNavigator` and `ResultRecipient` approach employed for waiting on activity results. 

We believe that such an enhancement would further streamline our navigation and result-handling processes, enhancing the overall efficiency and maintainability of our project. We would greatly appreciate your insights and guidance on how to approach this integration effectively.

Looking forward to your valuable input and continued support.

**Comment by trod-123** [comment]
Subscribed to this thread since I have interest in this as well.

**Comment by raamcosta** [comment]
Hey guys!

So... I definitely don't want to include this in the core lib, but we could have another side artifact that people could use to make it easier for them to ask permissions for specific destinations.
Maybe it could expose a bunch of DestinationWrappers to achieve it. I'm not sure btw if you guys know about DestinationWrappers, it is a more or less recent addition that I still didn't have time to document (hence why I'm not surprised that people don't know about it ahah 😅).

Let me give you an example (WARNING: I did this in 5min just to exemplify, we can definitely do better!)

```kotlin
object AskPermissionsWrapper: DestinationWrapper {

    @Composable
    override fun <T> DestinationScope<T>.Wrap(screenContent: @Composable () -> Unit) {
        val context = LocalContext.current
        var isPermissionGranted by remember { mutableStateOf(false) }

        val launcher = rememberLauncherForActivityResult(
            ActivityResultContracts.RequestPermission()
        ) { isGranted ->
            if (isGranted) {
                isPermissionGranted = true
            } else {
                Toast.makeText(context, "NEED THE PERMISSION!", Toast.LENGTH_LONG).show()
            }
        }

        LaunchedEffect(isPermissionGranted) {
            if (!isPermissionGranted) {
                launcher.launch(Manifest.permission.CAMERA)
            }
        }

        if (isPermissionGranted) {
            screenContent()
        }
    }
}

@Destination(
    wrappers = [AskPermissionsWrapper::class]
)
@Composable
fun MyScreen() { //...
```

With this, we're wrapping the screen with the logic to ask the permission and we only show the screen when that permission is granted.
Note that we can always show the screen if we want to, the dialog requesting permissions would show on top of it, we can also add some decorator on the screen etc... we can do pretty much anything here and we have a reusable piece of code (the wrapper) we can just add to our screens that need that permission.

**Comment by ignaciotcrespo** [comment]
Interesting approach, we can change the behavior of any screen without altering the internal code. That's a good idea, and it's worth a try for sure. Thanks for the example 👍 

Still not clear how multiple wrappers adding content will work, but I will experiment a bit.

**Comment by raamcosta** [comment]
With multiple wrappers, the order matters. Each one will be shown in order until all of them are dealt with, then the actual screen shows up.

Closing this one, hope it was helpful.
