### ISSUE TITLE
Bug in code generator for BottomSheet style

### ISSUE THREAD

**Issue by ImangazalievM** [raamcosta/compose-destinations#482]
My code:

```kotlin
@Destination(style = DestinationStyleBottomSheet::class)
@Composable
fun BottomSheetScreen() {
```

The code is correct, but I get this error: 

```
[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Unknown style used on TextSettingsBottomSheetScreen. Please recheck it.
```

The problem is in [KspToCodeGenDestinationsMapper on line 498](https://github.com/raamcosta/compose-destinations/blob/e2baf75e113ede5451bf6d137ac3fb3c5143c767/compose-destinations-ksp/src/main/kotlin/com/ramcosta/composedestinations/ksp/processors/KspToCodeGenDestinationsMapper.kt#L498):

```kotlin
resolver.getClassDeclarationByName("$CORE_PACKAGE_NAME.spec.DestinationStyleBottomSheet")?.asType(emptyList())
```

It must replaced with:

```kotlin
resolver.getClassDeclarationByName("$CORE_PACKAGE_NAME.spec.DestinationStyle.BottomSheet")?.asType(emptyList())
```

Unfortunately I can't create MR with the fix now. Could you fix it ASAP please?

**Comment by raamcosta** [comment]
What version are you using?

**Comment by ImangazalievM** [comment]
The latest version - 1.6.38-beta

**Comment by raamcosta** [comment]
Something is not right here 🤔

in your example, you’re using DestinationStyleBottomSheet (no dot), and you’re saying I should replace DestinationStyleBottomSheet by DestinationStyle.BottomSheet (with dot). 
That doesn’t make sense right? If you’re using without dot then for it to be recognised, also no dot would need to be used.

however if you’re really using 1.6.38-beta, then this version still uses the nested style (I.e with dot) and the ksp mapper class is correct.

So it does seem like everything is correct here. For that version you need to use the nested style (with dot).
