### ISSUE TITLE
Bring full NavGraphSpec to front on bottom bar navigation

### ISSUE THREAD

**Issue by tialawllol** [raamcosta/compose-destinations#484]
Hey @raamcosta !

First things first, awesome library, thanks a lot!

Secondly I am currently trying to reproduce YouTube's bottom navigation pattern.
I created a demo project where you can check out my current solution: https://github.com/tialawllol/compose-destination-navigation

For this example, let's have "home", "search", "something" and "another" as bottom navigation each with a separate navGraphs and of course in separate modules. "search" and "something" are able to access a "details" screen.

The following scenario, starting being on home:
1. click on search
2. click on search screen to go to it's details
3. click on something
4. click on something screen to go to it's details

The stack now looks like this:
root -> home(navGraph) -> home/screen -> search(navGraph) -> search/screen -> search/details -> something(navGraph) -> something/screen -> something/details

And now some scenarios that I would like to achieve:
A) When I use gesture back I want to go back to something, then back again to search details, then back again to search, then back again to home ✅  (I got this one as I am not using popUpTo)
B) When I click on search I would like to have the following stack: root -> home(navGraph) -> home/screen -> something(navGraph) -> something/screen -> something/details -> search(navGraph) -> search/screen -> search/details
C) When I click on home I would like to have the following stack: root -> home(navGraph) -> home/screen -> search(navGraph) -> search/screen -> search/details -> something(navGraph) -> something/screen -> something/details -> home(navGraph) -> home/screen 

Can you point me to a way on how to achieve this?
Maybe I am doing something wrong with how I use the modules destinations?

Thanks upfront!
Best regards,
Richard

**Comment by raamcosta** [comment]
Hi @tialawllol !

If you have your destinations as part of the correct nav graphs and you can navigate to them fine, I think Compose Destinations has helped you here. For your scenarios, that would be the same answer if you were using official compose navigation, so I believe you should do some googling, asking on StackOverflow or Kotlin slack.
I don't have the time to go through your repository to help you here I'm sorry 😞 If I thought there was something wrong or unique about Compsoe Detinations as compared to official library, I would definitely find the time, but as is, I cannot help each person with this sort of questions.

I'm sure you'll find the answers in no time though 🤞 

Let me know if you're ok with closing this!

**Comment by tialawllol** [comment]
@raamcosta thanks for the feedback. I will take another look into achieving this issue and will open a new and specific issue when there is a problem with the lib (which there probably isn't).

Best regards,
Richard
