### ISSUE TITLE
Defining "parent" destinations for deep links

### ISSUE THREAD

**Issue by trod-123** [raamcosta/compose-destinations#488]
Hi Rafael!

I'm back with another question :)

I was exploring the [deep links docs](https://composedestinations.rafaelcosta.xyz/deeplinks), and I was wondering whether this library supports the notion of defining "parents" for deep links, such that I can define a "synthetic stack" of pages to be presented behind the target of the deep link, so that when the user navigates back, they traverse down the stack.

A simple example is something like a `List > Details` flow. The Details page requires args to present the right details page, but the List does not require any args. 
- A user would deep link into Details, and should see the List when tapping the "Back" button. 
- In this scenario, I'd expect both the List and Details to be created in the navigation stack, with the List on top.

A more complex example would be something like: `Search > List > Details`. This is like a funnel, where Details requires arguments that are provided by List, and List requires arguments to provide the right list. 
- A user would deep link into Details, and should be able to traverse back to List and Search when tapping the "Back" button each time.
- In this scenario, I'd expect all these pages (with the right arguments) to be created in the navigation stack.

The idea here is that parents can be _recursive_ as well. So referring back to the examples:
- Details would define a parent > List
- List would define a parent > Search

If I want to present Details "in parent", it would automatically add List to the stack behind Details, as well as add Search to the stack behind List (for the second example).

Does something like this seem possible?

Thanks!

**Comment by raamcosta** [comment]
Hi 👋 

So Compose Destinations only exposes a different api (via annotation) to use the official compose navigation deep linking support.
So what can and can’t be done is solely dependent on the official library.
I honestly haven’t seen that yet, my understanding is that that is still not supported with official compose navigation, but I can totally be wrong here. So please do your own research and let us know if it is possible and how to achieve it 🙏
