### ISSUE TITLE
Missing animations after upgrading to 1.9.52

### ISSUE THREAD

**Issue by hristogochev** [raamcosta/compose-destinations#490]
After upgrading to version 1.9.52 of the library, and replacing `rememberAnimatedNavController()` with `rememberNavController()` because `rememberAnimatedNavController()` is now missing no matter if I'm using `core` or `animations-core`, the default animations for all of my screens are missing.

I would like to know how to restore the default transitions I had before.

**Comment by hristogochev** [comment]
Using the following engine for my DestinationsNavHost seems to provide me with transitions, although they are not of the same duration as the previous ones:
```kotlin
val engine = rememberAnimatedNavHostEngine(
        rootDefaultAnimations = RootNavGraphDefaultAnimations(
            enterTransition = { fadeIn(animationSpec = tween(400)) },
            exitTransition = { fadeOut(animationSpec = tween(400)) }
        )
)
```

**Comment by jakhongirmadaminov** [comment]
Having the same issue, `rememberAnimatedNavController()` is not resolved with `accompanist = "0.31.6-rc"`, so instead I'm using `rememberNavController(bottomSheetNavigator)` but crashing at runtime with 

`IllegalStateException: 'composable' can only be called for a destination of style 'Animated' or 'Default'`

**Comment by raamcosta** [comment]
> Having the same issue, `rememberAnimatedNavController()` is not resolved with `accompanist = "0.31.6-rc"`, so instead I'm using `rememberNavController(bottomSheetNavigator)` but crashing at runtime with
> 
> `IllegalStateException: 'composable' can only be called for a destination of style 'Animated' or 'Default'`

That crash is when you’re using composable in manualCallsBuilder param of DestinationsNavHost for a Dialog or a bottom sheet. Use dialogComposable or bottomSheetComposable instead (name from top of my head 😅)

**Comment by jakhongirmadaminov** [comment]
thank you!

**Comment by raamcosta** [comment]
> Using the following engine for my DestinationsNavHost seems to provide me with transitions, although they are not of the same duration as the previous ones:
> 
> ```kotlin
> val engine = rememberAnimatedNavHostEngine(
>         rootDefaultAnimations = RootNavGraphDefaultAnimations(
>             enterTransition = { fadeIn(animationSpec = tween(400)) },
>             exitTransition = { fadeOut(animationSpec = tween(400)) }
>         )
> )
> ```

You can do `rootDefaultAnimations = RootNavGraphDefaultAnimations.ACCOMPANIST_FADING`.

Hope this helps, let me know! I'll close this in the meantime :)
