### ISSUE TITLE
navigate to a destination from nested graphs

### ISSUE THREAD

**Issue by VivianGit** [raamcosta/compose-destinations#491]
I apologize if I am asking a question that has already been asked, but I couldn't find a solution to the issue.

In MainActivity, I have defined a navigation using DestinationsNavHost(navGraph = NavGraphs.root). This navigation includes a SettingScreen and a MainScreen. The MainScreen contains a bottom navigation. 

When I navigate from one of the pages of the bottom navigation to the SettingScreen, I encounter the error `.`
`"java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/setting_screen } cannot be found in the navigation graph ComposeNavGraph(0xd3a8ec79) route=main_screen_bottom_bar startDestination={Destination(0x3f56ff49) route=generate_screen}"`

Here are the key parts of my code:
MainActivity.kt
`setContent{
 DestinationsNavHost(navGraph = NavGraphs.root)
}`

MainScreen.kt
`@Destination
@Composable
fun MainScreen(){
  val navController = rememberNavController()
  ...
 DestinationsNavHost(
            navGraph = NavGraphs.mainScreenBottomBar,
            navController = navController,
            modifier = Modifier.padding(bottom = paddingValues.calculateBottomPadding())
        )
}
@RootNavGraph
@NavGraph
annotation class MainScreenBottomBarNavGraph(
    val start: Boolean = false
)`

ProfileScreen.kt
`@MainScreenBottomBarNavGraph
@Destination
@Composable
fun ProfileScreen(
    navigator: DestinationsNavigator
){
  Button(onClick = {navigator.navigate(SettingScreenDestination)}){Text("to setting")}
}`

SettingScreen.kt
`@Destination
@Composable
fun SettingScreen(){Text("settings")}`

I have compared my code multiple times with the tutorials, but I still can't figure out what I am doing wrong. Please point out my mistake. Thank you.

**Comment by raamcosta** [comment]
Hi @VivianGit !

If you use more than one NavHost, then each of them has their own NavController which is only able to navigate to its own destinations.
So, the solution here is to receive the outer NavController and use that one if you need to navigate to outer destinations.

So, in your MainScreen:

```kotlin
class OuterNavController(val value: NavController)

@Destination 
@Composable 
fun MainScreen(
    outerNavController: NavController
) {
    DestinationsNavHost(
        //...
        dependencyContainerBuilder = {
            dependency(OuterNavController(outerNavController))
        }
    ) //...
}
```

And then:

```kotlin
@MainScreenBottomBarNavGraph 
@Destination 
@Composable 
fun ProfileScreen(
    outerNavigator: OuterNavController
){ 
    Button(onClick = {outerNavigator.value.navigate(SettingScreenDestination)}){Text("to setting")} 
}
```

Hope this helps!

**Comment by VivianGit** [comment]
Thank you sooooo much, sir. Your work is truly amazing, and I will definitely recommend it to my colleagues. I really appreciate it and look forward to the day when we can directly jump from the sub-navigation to the main navigation.

**Comment by raamcosta** [comment]
Thank you!

Note that this is not a limitation of this library. This is how it works also on official compose navigation which we depend on 🙂
