### ISSUE TITLE
Suggestion: Non beta/rc versions of compose destinations should *not* use beta/rc versions of compose

### ISSUE THREAD

**Issue by sonrohan** [raamcosta/compose-destinations#493]
Let me know if there is a nicer way to surface stuff like this, I understand this is probably not that way. I don't have/nor want twitter.

**Comment by sonrohan** [comment]
I found your email, going to send it there instead. Sorry.

**Comment by raamcosta** [comment]
No worries, let's discuss it here :) 

I understand the point, it's something that has crossed my mind before. I just wonder if I do that how to distinguish between beta because my library has added something new that is in beta VS beta just because it's using a beta dependency.

And maybe there is no need to distinguish between them? I admit I haven't spent enough time researching this topic. 

What do you think?

**Comment by sonrohan** [comment]
Sweet! And I understand there are a lot of opinionated ways to frame this, and there is no “right” or “wrong” way. Just the way that makes the most sense to the maintainer and consumers of the library.

My personal opinion on the matter is that generally you’d want to stay on the stable version of the library where it is a major component of your library.

For some side functionality, it is probably fine. But switching from compose 1.4 stable to 1.5 beta for example has a lot of unknown potential side effects and implications for users of the library.

So what I am saying is, I think generally it makes more sense to stay on stable versions of compose as your library is actually centered around compose (even in naming) (at least for your stable version). Beta/RC versions could potentially be part of your own beta/rc channels.

When your app adds a new feature, it may make sense to add those into a beta/rc channel for testing if there is any risk of API changes or breakages to existing functionality.

**Comment by raamcosta** [comment]
Alright, I think that makes sense. I'll take it into consideration from now on! :)

**Comment by sonrohan** [comment]
Thanks for lending your ear (eyes)!

**Comment by raamcosta** [comment]
Thank you for pointing that out to me! 🙇‍♂️
