### ISSUE TITLE
How to Build NavGraphs with Dynamic Modules?

### ISSUE THREAD

**Issue by BlueSky15171** [raamcosta/compose-destinations#496]
I have multiple modules and dynamic dependencies (adding or removing dependencies) in the app. How should I build NavGraphs so that the project does not report errors?
For example.
```shell
.
├── app
 │    ├──  MainActivity.kt
 │   └── HomeScreen.kt
├─ featureA
 │    ├──  AAScren.kt
 │    └── AScreen.kt
....
└─featureN
      ├──  NNScren.kt
      └── NScreen.kt
```
```kotlin
// app module build.gradke.kts
// now isBuildA  is true
dependencies {
    if(extra["isBuildA"]==true){
        implementation(project(":moduleA"))
    }
 }

ksp {
    arg("compose-destinations.mode", "destinations")
    arg("compose-destinations.moduleName", "main")
}
```
Each nested graph located in a separate module
```kotlin
// featureA
ksp {
    arg("compose-destinations.mode", "navgraphs")
    arg("compose-destinations.moduleName", "moduleA")
}
...
// feature N
ksp {
    arg("compose-destinations.mode", "navgraphs")
    arg("compose-destinations.moduleName", "moduleN")
}

```
```kotlin
// AppNavGraphs
object AppNavGraphs {
val featureA = object : NavGraphSpec {
        override val destinationsByRoute: Map<String, DestinationSpec<*>>
            get() = listOf(
                AScreenDestination,
                AAScreenDestination,
                ...
        ).associateBy
        { it.route }
        override val route: String = AScreenDestination.route
        override val startRoute: Route
            get() = AScreenDestination
    }
    val featureN = object : NavGraphSpec {
        override val destinationsByRoute: Map<String, DestinationSpec<*>>
            get() = listOf(
                NNScreenDestination,
                NAScreenDestination,
                ...
        ).associateBy
        { it.route }
        override val route: String = NScreenDestination.route
        override val startRoute: Route
            get() = NScreenDestination
    }
}
```
```kotlin
// MainScreen.kt
DestinationsNavHost(navGraph = AppNavGraphs){
}
```
How should I build dynamic NavGraphs?
Thanx.

**Comment by raamcosta** [comment]
Hi 👋 


First of all, remove the associateBy calls, you don’t need them most likely and they complicate how you can later navigate to these.
Secondly, you’ll need to make “AppNavGraphs” itself a NavGraph containing only those two nested graphs.

And finally, at the end of the day, removing or adding a module should mean simply add or remove the corresponding feature module graph from the AppNavGraphs nested graphs list. I can’t really tell you how to build a dynamic list, that is not really a concern of this library.

Hope this helps! Let me know 🙂

**Comment by BlueSky15171** [comment]
@raamcosta  Thank you for your answer.
My idea is to dynamically create AppNavGraphs that contain all Desitions, and choose different AppNavGraphs to achieve dynamic implementation depending on different module dependencies. I don't know if this plan is feasible or not?
Or add a dynamic solution in the compose-destination framework, for example:
```kotlin
arg("compose-destinations.mode", "multi-module")
```
Is it feasible to add this property category and automatically generate a NavGraph containing all Destination modules in the main module?

**Comment by raamcosta** [comment]
In a future version I might add annotations to build th nav graph aggregating from a set of packages names if they’re included in the build.
But right now, this doesn’t exist.

**Comment by BlueSky15171** [comment]
Thanks

**Comment by raamcosta** [comment]
Closing this as this is not planned right now.
We'll revisit this if it comes up again.

In the meantime, I would like to know if someone knows whether or not this is possible with fragment jetpack navigation and how that works. Thanks :)
