### ISSUE TITLE
Making bottomSheet stay above bottom bar

### ISSUE THREAD

**Issue by froz3nice** [raamcosta/compose-destinations#497]
I'm trying to make bottom sheet stay above bottom bar, is there a way to do this? This approach with scaffold does not work

    ModalBottomSheetLayout(
        bottomSheetNavigator = bottomSheetNavigator,
    ) {
        Scaffold(
            modifier = modifier.systemBarsPadding(),
            topBar = { topBar(destination, navBackStackEntry) },
            bottomBar = { bottomBar(destination) },
            scaffoldState = scaffoldState,
            snackbarHost = {
           },
           content = {
              DestinationsNavHost(
                navController = navHostController,
                navGraph = NavGraphs.root,
                startRoute = startRoute,
                engine = rememberAnimatedNavHostEngine(),
                manualComposableCallsBuilder = {
                    bottomSheetComposable(ThemeSettingsDestination) {
                        ThemeSettings(
                            resultNavigator = resultBackNavigator(),
                        )
                    }
           },
        )
    }`

**Comment by raamcosta** [comment]
Hi 👋

this is not directly related with compose destinations library.
I think you’ll find better help googling or asking on Kotlin slack. If you replace the DestinationsNavHost with the official NavHost it will be the same so if you find a solution with normal navigation it shouldn’t matter.

**Comment by froz3nice** [comment]
Found that you need to wrap Scaffold content with ModalBottomSheetLayout

**Comment by raamcosta** [comment]
Perfect! Glad you found the solution!
