### ISSUE TITLE
how to pass parameters to the startRoute

### ISSUE THREAD

**Issue by aplha98** [raamcosta/compose-destinations#498]
```
     DestinationsNavHost(
                            navGraph = NavGraphs.root,
                            startRoute = AppNavigationDestination,
```

**Comment by raamcosta** [comment]
You cannot pass navigation arguments, but you can just pass things from the NavHost call level. Check here:

https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters
