### ISSUE TITLE
how to use NavigationBar with composedestinations

### ISSUE THREAD

**Issue by aplha98** [raamcosta/compose-destinations#499]

**Comment by raamcosta** [comment]
https://composedestinations.rafaelcosta.xyz/common-use-cases/bottom-bar-navigation

Search on closed issues before opening a new one

**Comment by aplha98** [comment]
Dea @raamcosta ,

I hope this message finds you well. I wanted to take a moment to address a concern that has been brought to my attention. It appears that there might have been instances where new issues were opened without prior consideration of closed ones. While I understand that sometimes mistakes happen or situations evolve, I'd like to emphasize the importance of searching through closed issues before creating new ones.

Each closed issue represents valuable insights, solutions, and discussions that our team has invested time and effort into. By revisiting these closed issues, we not only prevent duplication of efforts but also have the opportunity to build upon past experiences and find answers that could be relevant to the current challenges we are facing.

Opening new issues without checking the closed ones can lead to a fragmented workflow, unnecessary repetition, and the risk of overlooking potentially effective solutions. It can also make it difficult for the team to track progress and maintain a clear overview of our tasks.

I want to stress that this reminder is not meant to discourage proactive problem-solving or the initiation of meaningful discussions. Rather, it's a plea to maximize the collective wisdom of our team and ensure that our efforts are as efficient and streamlined as possible.

In the end, our goal is to collaborate effectively and achieve the best possible outcomes. Let's work together to make the most of our shared knowledge and create an environment where each issue is carefully considered in light of past resolutions.

Thank you for taking the time to read this message. Your dedication to our team's success is truly appreciated.

Best regards
