### ISSUE TITLE
Support for dialogs

### ISSUE THREAD

**Issue by vvasilev92** [raamcosta/compose-destinations#50]
Can dialogs be added to DestinationsNavHost? That doesn't seem to be currently supported.

**Comment by raamcosta** [comment]
Hi @vvasilev92 !

Yes it is, check this:
https://github.com/raamcosta/compose-destinations/wiki/Styles-and-Animations#dialog-style

**Comment by HuM4NoiD** [comment]
Hi! The link redirects back to repository home page. [new link](https://composedestinations.rafaelcosta.xyz/styles-and-animations#dialog-style)
