### ISSUE TITLE
Navigation not working within the NavResult

### ISSUE THREAD

**Issue by mrtalha** [raamcosta/compose-destinations#501]
I have a screen that sends a result with boolean true if the app has camera permissions. In that results, I then navigate to other corresponding screen. This was working fine in the previous version but in v1.9.52, when I get the NavResult and try to go to the other Composable screen, the screen opens and then a blank screen opens too. If I directly open that composable (not from within the nav result, it works fine).

`resultRecipient?.onNavResult { result ->
        when (result) {
            is NavResult.Canceled -> {}
            is NavResult.Value -> {
                if (result.value) { //permissions were granted

                    if (viewModel.user?.name.isNotNullOrEmpty())
                        ActivityVideoRepBasic.open(context)
                    else
                        navController?.navigate(ScreenCreateVideoProfileDestination)

                }
                println("result received from ScreenVideoReportingDestination = ${result.value}")
            }
        }
    }`

**Comment by raamcosta** [comment]
Hi!

Not sure I fully undestand the issue, could you post a simple reproducer project I can try on my end? 

Thanks.

**Comment by mrtalha** [comment]
There was an issue with combination to some of the Compose version, but it later went away automatically with the update of Compose. So it was I guess the issue with the Jetpack Compose.
