### ISSUE TITLE
Navigating to different graph from NavigationBar, is there a clean way for a full screen?

### ISSUE THREAD

**Issue by pesjak** [raamcosta/compose-destinations#502]
I think I understand how it works, I managed to make it work.

Graph Flow is like this:

- Graph ROOT (has DestinationNavHost)-> Welcome, Login, Settings
- (subgraph of Root) Graph HOME (this is just for NavigationBar, and this one has its own DesinationNavHost, so bottomBar remains and screens can change) -> Dashboard, Explore, Profile

My goal is to establish a connection to the Settings screen from the Profile screen. However, directly utilizing `destinationsNavigator: DestinationsNavigator` for navigation is not viable (or I haven't found a way yet), as it's not the appropriate instance and it won't take full screen.

Profile uses navController from NavigationBar DestinationsNavHost.
I would need the instance from the ROOT graph, primarily to enable fullscreen functionality.

Solution was by manually defining the composable in HomeScreen and pass the lambda to ProfileScreen. Now I can access the settings and show it full screen. 

Here's how I do it. HomeScreen is just a wrapper for NavigationBar, so you can call from Root.

```
@Destination
@Composable
fun HomeScreen(
    destinationsNavigator: DestinationsNavigator,
) {
    HomeContent(destinationsNavigator)
}

@Composable
fun HomeContent(destinationsNavigator: DestinationsNavigator) {
    val navControllerBottomBar = rememberNavController()
    Scaffold(
        modifier = Modifier
            .fillMaxSize(),
        bottomBar = {
            BottomBar(navController = navControllerBottomBar)
        },
    ) { innerPadding ->
        Box(modifier = Modifier.padding(innerPadding)) {
            DestinationsNavHost(
                navController = navControllerBottomBar,
                navGraph = NavGraphs.home,
            ) {
                composable(ProfileScreenDestination) {
                    ProfileScreen(
                        onSettingsClick = {
                            destinationsNavigator.navigate(SettingsScreenDestination)
                        }
                    )
                }
            }
        }
    }
}

@Composable
private fun BottomBar(
    navController: NavController,
) {
    val currentDestination = navController.currentDestinationAsState().value ?: NavGraphs.home.startAppDestination

    NavigationBar {
        BottomBarDestination.values().forEach { destination ->
            NavigationBarItem(
                alwaysShowLabel = false,
                icon = { Icon(destination.icon, contentDescription = stringResource(destination.label)) },
                label = { Text(stringResource(destination.label)) },
                selected = currentDestination == destination.direction,
                colors = NavigationBarItemDefaults.colors(
                    indicatorColor = MaterialTheme.colorScheme.primary,
                    unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant.copy(0.38f),
                    unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant.copy(0.38f),
                ),
                onClick = {
                    navController.navigate(destination.direction) {
                        popUpTo(NavGraphs.home.startRoute)
                        launchSingleTop = true
                    }
                },
            )
        }
    }
}
```

There are few questions if you can help me.
- Do I need to define all screens that I want full screen this way, and have them in root? Or is it okay, to have another DesinationNavHost that has a nestedGraph (SomeDetailsScreen with a flow), because I will need to show everything in full screen. I know that DestinationNavHost != NestedGraphs and you can have only 1 DestinationNavHost. But in this case I think I'll need to do something in this sense. Is there any better way to do this?
- I noticed if i return from Settings screen the BottomItem jumps, because `navController.currentDestinationAsState().value` is called 2 times. First the DashboardScreen is called, and then the ProfileScreen, any ideas how to avoid this (this is probably because we're returning from another navHost)?

Thanks for the help and I love your library, really makes a life easier!

**Comment by pesjak** [comment]
@raamcosta Any chance you took a look at this?

**Comment by raamcosta** [comment]
Hi 👋 

if you want want some screens to show the bottom bar and others to not show it, then you either have multiple DestinationsNavHost or you dynamically show or hide the bottom bar depending on which screen you’re on.
If this is the only thing you need multiple Hosts for, I would personally just show and hide the bottom bar instead. If you run the sample of this repository you’ll see that we are hiding and showing the bottom bar when entering or leaving the login screen respectively. In case you want to check that out.

It becomes easier to manage since you’ll only have one NavController. If you really want to go with multiple nav hosts then yes you need to somehow pass the NavController from the outer NavHost to the inner destination (via either explcitly calling it like you did passing the lambda f.ex or via dependency container builder, you’ll find both approaches in documentation).

Hope this helps!
