### ISSUE TITLE
Deleted Destination is still being generated

### ISSUE THREAD

**Issue by hscissors** [raamcosta/compose-destinations#503]
Hi there,

I have a new destination on git branch X. When I switch to git branch Y and clear and rebuild the project, the destination from X (that is not included in branch Y) still appears in the build directory and throws errors. Any thoughts on why this is happening?

**Comment by raamcosta** [comment]
Hi!
You can’t run the app then? I find that really weird, are you sure there’s nothing in branch Y that would generate that Destination?
I’ve used the lib a ton and never had such issues.. I suspect if this ever happened it likely would be something with ksp and not from compose destinations..
