### ISSUE TITLE
Issue with using ResultRecipient across modules with dependancy

### ISSUE THREAD

**Issue by SiavashB** [raamcosta/compose-destinations#508]
note: I have read the "Multi module result back case" in the docs.

we have a multi-module, multi-navgraph app. I'm trying to send result back from a destination to another destination in a different navgraph and module. 

the Destination I'm trying to send results *to* DOES DEPEND on the the module that I'm trying to send results *from*

for example, I have a featureModule that contains the result receiver destination, and a commonModule that contains result producer destination, and the featureModule ----depends on the----> commonModule.

In my code I can write `ResultRecipient<ResultProducingDestination, Data>` with no lint errors because ResultProducingDestination exists and I have the proper dependancy to access it, but when I build the code I get: 

`IllegalDestinationsSetup: Non existent Destination ('ResultProducingDestination') as the ResultRecipient's result origin!`

I know there is is the OpenResultRecipient, but A I feel like I shouldn't have to use that since I do have a forward dependancy between the the producer and receiver, and also, this screen is using a dependenciesContainerBuilder and it makes things really complicated going this route regarding the viewModel injection.

**Comment by raamcosta** [comment]
Ksp task runs in each module separately and so it doesn’t know about classes in other modules.

This is for now expected and you do have to use the Open approach. I would like to know why does it make things very complicated, can you give me more info about that?

When manually calling your screen, you should be in a position where you can easily prepare the same dependencies you were in dependencyContainerBuilder, right?

I’ll keep this open though maybe I have an idea about how I could improve this for v2.

**Comment by SiavashB** [comment]
Ok so the recepient screen looks like this 

```
fun RecepientScreen(
    viewModel: RecepientViewModel,
    resultRecipient: OpenResultRecipient<CustomType>
) {
}
```
that view model gets injected through your library using dependenciesContainerBuilder. We do this because we are sharing that VM between 2 screens and we want it to stay alive and shared between those 2 screens. 

in the Destinations nav host if I try to manual create the screen then I have to manually pass in the view model and I'm not sure how to do that while maintaining that shared view model functionality 
```
DestinationsNavHost(
 dependenciesContainerBuilder = {  CreateRecepientScreenVM()   }
) {
                    composable(RecepientScreenDestination) {
                        RecepientScreen(
                            viewModel =  / what goes here? /,
                            resultRecipient  = resultRecipient<CityFilterScreenDestination, CityFilterType>())
                    }
                }
```

CreateRecepientScreenVM() is an extension function we created to create the viewModel but it only can be called in the context of dependenciesContainerBuilder

**Comment by raamcosta** [comment]
Sorry for delay in response here 🙏 

There is no reason why CreateRecepientScreenVM() should be able to be called in one place but not the other. Both have similar receivers in the lambda (Some kind of DestinationScope).
Try having the `CreateRecepientScreenVM` be an extension function of `DestinationScopeWithNoDependencies`. Then you should be able to call it on both manual calls and dependency builders cases 🙂 

Hope this helps!

**Comment by raamcosta** [comment]
Good news! I have managed to fix this for v2!

If ModuleA depends on ModuleB, ModuleA can use ModuleB's generated Destinations in their screens "result back recipients".

**Comment by niyajali** [comment]
> Good news! I have managed to improve this for v2!
> 
> If ModuleA depends on ModuleB, ModuleA can use ModuleB's generated Destinations in their screens "result back recipients".

how could we manage if none of the modules depends on each other?
is there any other option or possibility to use destinations in another module "result back recipient"

**Comment by marosseleng** [comment]
Hi @raamcosta, I recently ran into the same problem. Can we somewhere try the v2 with the improved way of handling results in a multimodule project?
