### ISSUE TITLE
navController.navigate not working when upgrade to androidx.navigation:navigation-compose:2.7.1

### ISSUE THREAD

**Issue by Bryant-Yang** [raamcosta/compose-destinations#509]
As the quick test blew,  After upgrading to navigation-compose 2.7.1, the code navController.navigate(LoginDestination()... displays a blank screen. This issue is not present in version 2.7.0. It's unclear if this is a issue of navigation-compose.

```
@SuppressLint("ComposeModifierMissing")
@RootNavGraph(start = true)
@Destination
@Composable
fun Home(navController: DestinationsNavigator) {

    var loginState by remember(mutableStateOf(false))

    LaunchedEffect(loginState) {
        if ( !loginState ) {
            navController.navigate(LoginDestination(), onlyIfResumed = true) {
                popUpTo(HomeDestination.route) { inclusive = false }
            }
        }
    }

    if (loginState) {
        Text("Home view")
    }
    
}

@Destination
@Composable
fun Login(navController: DestinationsNavigator) {
    Text("Login view")
}
```

**Comment by raamcosta** [comment]
You shouldn’t be importing the navigation dependency on your project directly since compose destinations already exposes it transitively.

Compose destinations is still using 2.7.0, should be updating versions very soon!

**Comment by raamcosta** [comment]
Let me know if this helped you!

**Comment by Bryant-Yang** [comment]
ok, thanks, very clear.
