### ISSUE TITLE
issue in generated Destination class

### ISSUE THREAD

**Issue by Dalakoti07** [raamcosta/compose-destinations#510]
kotlin version: "1.8.21"
agp version: "7.3.0"

```
const val navigationLibrary = "io.github.raamcosta.compose-destinations:core:1.8.33-beta"
const val kspPLuginDepen = "io.github.raamcosta.compose-destinations:ksp:1.9.51"
```

When I have screen as following

```
@Destination
@FitnessGraph
@Composable
fun DetailScreen(
    data: Data,
    navigator: DestinationsNavigator,
) {
    MyAppScaffold {
        Column {
            Text(text = "Detail screen: ${data.name}")
        }
    }
}
```

then generated class detailScreenDestination has following code

```
public object DetailScreenDestination : DirectionDestination {
         
    public operator fun invoke(): Direction = this
    
    @get:RestrictTo(RestrictTo.Scope.SUBCLASSES)
    override val baseRoute: String = "detail_screen"

    override val route: String = baseRoute
    
    @Composable
    override fun DestinationScope<Unit>.Content() {
		val dependencyContainer = buildDependencies()
		DetailScreen(
			data = dependencyContainer.require(), 
			navigator = destinationsNavigator
		)
    }
    
}
```

According to project docs this should generate `TypedDestination<DetailScreenDestination.NavArgs>`, but it is not generating that. Is this some issue with kotlin, agp version number

**Comment by raamcosta** [comment]
Is Data of a Navigation type?

https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments

**Comment by Dalakoti07** [comment]
Thanks @raamcosta for reply.

Yes, its annotated with `kotlinx.serialization.Serializable` like `@Serializable`

If use id:Int as required params for destination, then `TypedDestination` is created, and its taking int as params, but still not taking Serializable data object as param

**Comment by raamcosta** [comment]
Thank you as well! 🙂

Is Data class in the same module as the DetailsScreen composable?

**Comment by Dalakoti07** [comment]
No, actually its a KMM setup and hence data class in in differenet module altogether

**Comment by raamcosta** [comment]
In order for your navigation module to be able to serialize that data class, it needs to also use kotlinx serialization dependencies and plugins.

Hope that helps! Let' me know 🙂

**Comment by raamcosta** [comment]
I would go to kotlinx serialization GitHub page and check their setup. I don’t know it from the top of my head, but I believe there’s also a gradle plugin you have to apply.

**Comment by paynd** [comment]
This solution works for me. There was no `implementation(libs.kotlinx.serialization)` in module with navigation.
