### ISSUE TITLE
How to add an attribute to Destinations to indicate whether they should include the bottom bar for example

### ISSUE THREAD

**Issue by naitgacem** [raamcosta/compose-destinations#513]
Idealy, I would be able to achieve something like this:
```kotlin
@Destination(noBottomBar = true )
``` 

Is there an exising way to achieve this ? 
And is there a plan to implement a similar thing ?

PS: In order to avoid making this an XY problem,
 I have a UI where the main interface has a bottom bar, but some screens, such as settings, do not have such a thing.
It would be neat if one would set the attribute once, and read it when rendering the interface.

**Comment by ricardodalarme** [comment]
I'd love such a feature, it could be also used to define the route name and display it in a TopAppBar

**Comment by tully-8888** [comment]
**That would be amazing, did anyone find any solution to this?**

**Comment by tully-8888** [comment]
I fixed it. 
`@Composable
fun BottomBar(
    navController: NavController
) {
    val currentDestination: Destination = navController.appCurrentDestinationAsState().value
        ?: NavGraphs.root.startAppDestination

    if (currentDestination != _The destination where the bottom bar should be hidden)_ {
        val primaryColor = MaterialTheme.colorScheme.primary
        val secondaryColor = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.7f)

        BottomNavigation(
            elevation = 8.dp,
            backgroundColor = Color.Black
        ) {
            BottomBarDestination.values().forEach { destination ->
                BottomNavigationItem(
                    selected = currentDestination == destination.direction,
                    onClick = {
                        navController.navigate(destination.direction, fun NavOptionsBuilder.() {
                            launchSingleTop = true
                        })
                    },
                    icon = {
                        Icon(
                            imageVector = destination.icon,
                            contentDescription = stringResource(destination.label),
                            tint = if (currentDestination == destination.direction) Color.White else Color.Gray,
                            modifier = Modifier.size(24.dp)
                        )
                    },
                    label = {
                        Text(
                            text = stringResource(destination.label),
                            color = if (currentDestination == destination.direction) Color.White else Color.Gray,
                        )
                    },
                    alwaysShowLabel = false,
                    selectedContentColor = primaryColor,
                    unselectedContentColor = secondaryColor
                )
            }
        }
    }
}`

**Comment by tully-8888** [comment]
```kotlin
@Composable
fun BottomBar(
    navController: NavController
) {
    val currentDestination: Destination = navController.appCurrentDestinationAsState().value
        ?: NavGraphs.root.startAppDestination

    // Replace the placeholder with your actual destination
    if (currentDestination != _The destination where the bottom bar should be hidden_) {
        val primaryColor = MaterialTheme.colorScheme.primary
        val secondaryColor = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.7f)

        BottomNavigation(
            elevation = 8.dp,
            backgroundColor = Color.Black
        ) {
            BottomBarDestination.values().forEach { destination ->
                BottomNavigationItem(
                    selected = currentDestination == destination.direction,
                    onClick = {
                        navController.navigate(destination.direction, fun NavOptionsBuilder.() {
                            launchSingleTop = true
                        })
                    },
                    icon = {
                        Icon(
                            imageVector = destination.icon,
                            contentDescription = stringResource(destination.label),
                            tint = if (currentDestination == destination.direction) Color.White else Color.Gray,
                            modifier = Modifier.size(24.dp)
                        )
                    },
                    label = {
                        Text(
                            text = stringResource(destination.label),
                            color = if (currentDestination == destination.direction) Color.White else Color.Gray,
                        )
                    },
                    alwaysShowLabel = false,
                    selectedContentColor = primaryColor,
                    unselectedContentColor = secondaryColor
                )
            }
        }
    }
}
```

**Comment by raamcosta** [comment]
Something like this is not planned for now, doing the if check for the destinations you don't want to show that in, is what I would do.

In the sample app of this git repo, there is also a case where we are showing / hiding the bottom bar for some destinations, you can check it :)
