### ISSUE TITLE
Documentation not updated as per latest version

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#517]
After 1.9.50 there seems to be many breaking changes that happened.
The same is not updated in https://composedestinations.rafaelcosta.xyz/styles-and-animations/#default-style 
Can you please help to update this document, as it's creating a lot of confusion.

**Comment by raamcosta** [comment]
Hi @UKMIITB !

I'm sorry this has caused confusion. The docs website is not versioned, so when things change I can't make it completely correct for all versions.
That said, I do want to try and keep it up to date with the latest version.

Thanks for reminding me!

**Comment by pawelsmagala** [comment]
haha, I just came here to write the same, but I see @UKMIITB was faster ;) 

few things that are definitely different:
there's `DestinationStyleBottomSheet` but in documentation it's `DestinationStyle.BottomSheet`

documentation mentions function `rememberAnimatedNavController` but I think it's no longer there.

The entire section how to setup engine and navController with animation seems outdated, I think it should be something like:
```
val engine = rememberAnimatedNavHostEngine(  )
val bottomSheetNavigator = rememberBottomSheetNavigator()
 navController = engine.rememberNavController(bottomSheetNavigator)
```


I understand the docs are not versioned, but I expect them to reflect the last stable version.  Thanks for updating and writing this great lib!

**Comment by raamcosta** [comment]
I wrote it on release notes, so in case you want the complete picture and while I don’t update the website:

https://github.com/raamcosta/compose-destinations/releases/tag/1.9.50

**Comment by raamcosta** [comment]
Closing this as docs are being reworked for v2!
