### ISSUE TITLE
Override dialog transitions

### ISSUE THREAD

**Issue by elv-stav** [raamcosta/compose-destinations#519]
This might be an issue with how Compose Navigation treats Dialogs, but since DestinationStyle.Dialog and DestinationStyle.Animated are two distinct options, I couldn't find a way to change the default transitions of a destination with DestinationStyle.Dialog.

Is it possible? Am I missing something?

**Comment by raamcosta** [comment]
Hi!

No, not possible, they are registered in the nav graph in different ways, the dialog APIs don't have any animations.
