### ISSUE TITLE
[Help needed] Question related to bottom sheet navigation as destination

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#520]
HI @raamcosta 
This is not a bug. But needed one help.

I am currently using destination bottom sheet.
I have a usecase where bottom sheet should not get dismissed if user taps outside the bottom sheet but as you are also aware that currently its not supported in accompanist library itself.

I wanted to understand how the stack works in this case.

Initially the root destination was A. 
From A I navigated to bottom sheet destination B.

When user taps outside the bottom sheet area, does B gets popped out of stack ?

Also is there a way to get callback when user taps the outside area or basically when B is popped from stack ?

**Comment by UKMIITB** [comment]
@raamcosta 
Can you please help here

**Comment by raamcosta** [comment]
Hi 👋 

sorry for delayed response.

> When user taps outside the bottom sheet area, does B gets popped out of stack ?

Yes, exactly. You can find handy functions in the sample and playground folder of this repo where we log the whole back stack whenever it changes, it may be helpful for you in the future to check these things.

> Also is there a way to get callback when user taps the outside area or basically when B is popped from stack ?

You can add a lifecycle callback to the destination itself and see when that goes to onStop for example.
Or you can use the NavController.currentDestinationAsState, or NavController.addDestinationChangeListener (names might be slightly off, I can recheck later).

hope this helps!
