### ISSUE TITLE
Navigation Animations are laggy and with blank background(?)

### ISSUE THREAD

**Issue by davidmarinangeli** [raamcosta/compose-destinations#521]
Hi!! I'm trying to add animations to the navigation of my app. [I've read the documentation](https://composedestinations.rafaelcosta.xyz/styles-and-animations?_highlight=animation#animated-style) but I'm struggling to understand why the **push** animation is laggy ( the pop is fine, you can see the speed difference ) and, specifically the `slideIn` ( vertically or horizontally ) show a blank background for an instant.

Video for reference, x0.5 speed.

https://github.com/raamcosta/compose-destinations/assets/19487461/8c22f4c2-39fb-44e6-83b3-981f0077a739

```
engine = rememberAnimatedNavHostEngine(
            rootDefaultAnimations = RootNavGraphDefaultAnimations(
                enterTransition = { slideInVertically() },
                exitTransition = { slideOutVertically() }
            ),
        ),
```

What could cause this?

**Comment by raamcosta** [comment]
Hi!

Make sure the "out" animations are synchronized wiht the "In" ones. They should start at the same time and slide the same amount over time so that the white background is not shown.

If you can't do it, I suggest asking on Kotlin compose slack or similar, as this is not something this library is messing with. We're just calling official APIs with the animations provided.

**Comment by davidmarinangeli** [comment]
@raamcosta I'm using the standard animations from AndroidX:

 ```
 import androidx.compose.animation.slideInVertically
```

I don't see how it could be improved further.

**Comment by davidmarinangeli** [comment]
The same thing happens using the snippet from the documentation: 

```
engine = rememberAnimatedNavHostEngine(
            navHostContentAlignment = Alignment.TopCenter,
            rootDefaultAnimations = RootNavGraphDefaultAnimations.ACCOMPANIST_FADING,
        ),
```

As you can see from the video the effect does not always work and sometimes fades to white (?).

https://github.com/raamcosta/compose-destinations/assets/19487461/7346e798-c378-45cd-9615-0ce37e10c06b
