### ISSUE TITLE
Navigating back multiple screens with a result

### ISSUE THREAD

**Issue by Olaleo** [raamcosta/compose-destinations#522]
With a graph that looks like this:
Screen A -> Screen B -> Screen C -> Screen D 
Then i need to navigate back from Screen D to Screen A while passing a result from Screen D to Screen A, is this possible, and if so how would you go about it?

**Comment by raamcosta** [comment]
Not possible at the moment using the result back feature of this lib. But, you can do what the official library docks suggest, get the NavBackStackEntry corresponding to screen A and set some data on its SavedStateHandle.

**Comment by BekzodYusupov** [comment]
thanks, able to solve same problem with NavBackStackEntry
