### ISSUE TITLE
Bottom sheet jumps during upward scroll 1.9.54

### ISSUE THREAD

**Issue by Cheephot** [raamcosta/compose-destinations#523]
When scrolling up, the bottom sheet exhibits an unintended jumping behavior

https://github.com/raamcosta/compose-destinations/assets/49614840/5fd7ea4f-905a-46f7-9a34-7a1c4a4380ee

**Comment by raamcosta** [comment]
Hi!

This would be something to report on Accompanist project, not caused by this lib.
