### ISSUE TITLE
Support for internal classes in navigation arguments

### ISSUE THREAD

**Issue by zoopolitic** [raamcosta/compose-destinations#524]
Hi, there is a similar discussion in https://github.com/raamcosta/compose-destinations/issues/316 but that one is about being able to generate `Destination` with the same visibility as `@Composable`.  This config
```kotlin
    ksp {
        // If set to "true" will use the annotated composable's visibility in the generated Destination
        // otherwise, Destinations will always be public in this module
        arg("compose-destinations.useComposableVisibility", "true")
    }
```
indeed generates an internal destination, however, if the navArg class references `internal` classes, then generated `*NavType` (which is public) results in the same visibility issue during compilation.

I've checked the [NavTypeWriter](https://github.com/raamcosta/compose-destinations/blob/main/compose-destinations-codegen/src/main/java/com/ramcosta/composedestinations/codegen/writers/CustomNavTypesWriter.kt) and seems like it generates public navTypes unconditionally. Is there a workaround or plans to support it similarly to `useComposableVisibility` codegen config?

**Comment by raamcosta** [comment]
Hmmm, yes I see it. Thanks for reporting.

I'll have to think about it, but I definitely want to solve it somehow :+1: 
It may be part of v2 coming later this year.

**Comment by raamcosta** [comment]
I cherry picked this fix for current versions, so should be fixed from 1.9.58 onwards!

**Comment by zoopolitic** [comment]
Is there a ksp flag that is needed for this to work or internal classes in nav args will be supported out of the box?

**Comment by raamcosta** [comment]
If the class is internal, the NavType will have to be internal, so no need to specify any flag 👍
