### ISSUE TITLE
Back Stack Navigation is not working at all

### ISSUE THREAD

**Issue by waheed006** [raamcosta/compose-destinations#525]
When I am navigation to Screen A to B and then C and when clearing all stack when coming back to A. Now navigation system is not working at all. I even not allowing me to back to Login screen. Please provide clear documentation or some help that I might use to navigate properly or clear my back stack.

**Comment by raamcosta** [comment]
Hi @waheed006 

All official documentation applies to compose destinations. The managing of the back stack is not handled by this library so documentation about that is the official compose navigation one.

hope that helps 🙂

**Comment by waheed006** [comment]
Thank you for your reply. I am confused in **route** and **baseRoute** like what to you in popUpTo method:
navigator.navigate(LoginScreenDestination) {
                    popUpTo(HomeScreenDestination.route) {
                        inclusive = true
                    }
                    launchSingleTop = true
                }

**Comment by raamcosta** [comment]
Closing this, let me know if you find something else related to Compose Destinations!
