### ISSUE TITLE
java.lang.IllegalStateException: 'composable' can only be called for a destination of style 'Animated' or 'Default'

### ISSUE THREAD

**Issue by annaharri89** [raamcosta/compose-destinations#528]
java.lang.IllegalStateException: 'composable' can only be called for a destination of style 'Animated' or 'Default'
                                                                                                    	at com.ramcosta.composedestinations.manualcomposablecalls.ManualComposableCallsBuilderKt.composable(ManualComposableCallsBuilder.kt:34)

I'm using version 1.9.54 of the `io.github.raamcosta.compose-destinations:animations-core sdk`. I'm getting the above error when I try to open a DestinationsNavHost. I'm trying to open a bottom sheet using the `@Destination(style = DestinationStyleBottomSheet::class)`
the composable import is `import com.ramcosta.composedestinations.manualcomposablecalls.composable`

Can you help with this?

**Comment by annaharri89** [comment]
I figured this out. I needed to use `bottomSheetComposable`

You should put this in the 1.9.50 release notes or something

**Comment by raamcosta** [comment]
Glad you found it! It’s on documentation website 🙂
