### ISSUE TITLE
How do you use DestinationStyle.Animated::class in destination style on version 1.9.54

### ISSUE THREAD

**Issue by annaharri89** [raamcosta/compose-destinations#529]
<img width="1020" alt="image" src="https://github.com/raamcosta/compose-destinations/assets/16767360/bd7b3080-bf47-41dd-9834-e32e18c73a6a">
I'm getting `Classifier 'Animated' does not have a companion object, and thus must be initialized here` in the generated Destination class when I do `@Destination(style = DestinationStyle.Animated::class)`. How can I fix this? I'm on version 1.9.54

**Comment by raamcosta** [comment]
Hi!

for animated style, you need to define the animation you want by subclassing the Animated interface and  overriding its methods.

Check it here:
https://composedestinations.rafaelcosta.xyz/styles-and-animations#animated-style
