### ISSUE TITLE
Passing ViewModel getting Error

### ISSUE THREAD

**Issue by waheed006** [raamcosta/compose-destinations#533]
Hey sir, I am trying to pass my ViewModel in compose-destinations and I am getting error. I followed the [link](https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels/) but still same error is coming. 

```
@Destination
@Composable
fun AppointmentScreen(
    navigator: DestinationsNavigator,
    visitDetail: VisitResponse,
    viewModel: VisitViewModel = hiltViewModel()
) {
   }
```

but at the navigating to this **AppointmentScreen** then getting error in viewmodel argus:

![image](https://github.com/raamcosta/compose-destinations/assets/46211755/858f6c99-efaa-4fbe-9fbf-350894a72413)

**Comment by deividas717** [comment]
You don't need to pass `viewModel` manually. It should be injected by hilt. Pass only `visisDetails` parameter.

**Comment by waheed006** [comment]
Suppose in HomeViewModel I have data of user and I am moving from HomeScreen to Profile Screen and loading same HomeViewModel in ProfileScreen using hilt then there is no data of user. Like that HomeViewModel loads at new object with empty data. How to resolve this issue?

**Comment by deividas717** [comment]
You can pass user reference as an argument to `AppointmentScreenDestionation`

```
@Destination
@Composable
fun AppointmentScreen(
    navigator: DestinationsNavigator,
    visitDetail: VisitResponse,
    user: User
) {
 // rest of the logic 
}
```

Or better retrieve user info from database or preferences.

**Comment by waheed006** [comment]
So it means there is no way to pass viewmodel with full data from one Composable screen to another just like we did in Fragments in older way?

**Comment by raamcosta** [comment]
ViewModels cannot be navigation arguments, this wasn’t different with Fragments.
If you want, you can share a ViewModel by getting it on the second screen, if you know what that ViewModel is tied to (Maybe the previous back stack entry, or a nav graph back stack entry, or the activity).

Check this:
https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels#share-viewmodels-between-multiple-destinations
