### ISSUE TITLE
DestinationStyle.Dialog with usePlatformDefault properties causes wrong dialog measuring at some devices

### ISSUE THREAD

**Issue by wellwhatever** [raamcosta/compose-destinations#536]
Hi, I have dialog with properties where usePlatformDefaultWith is set to false, so that it 'acts' like full-screen dialog. I noticed a problem on specific devices, that the size of this dialog is calculated wrong when this property is set to false. Tested on: **SM S20FE, A13**

That is the style that I use:

```
object FullScreenDialog : DestinationStyle.Dialog {
    override val properties = DialogProperties(
        usePlatformDefaultWidth = false,
    )
}
```

And that's how I use it:
```
@Destination(style = FullScreenDialog::class)
@Composable
fun MyDialog(){
Box(){...}
}

```
<img width="403" alt="Screenshot 2023-11-07 at 10 05 45" src="https://github.com/raamcosta/compose-destinations/assets/107949853/2f3635ec-6f3b-4715-bad1-cd3b090567c4">

Screenshot is kinda ugly, but anyway it is clearly visible that this dialog is bigger then the viewport.

**Comment by raamcosta** [comment]
Hi!

This is not something we can control on compose destinations library.
We’re simply calling the official APIs with these parameters, so you’d have to open an issue for the official compose navigation library.
