### ISSUE TITLE
2 navgraph with same destination name

### ISSUE THREAD

**Issue by WildOrangutan** [raamcosta/compose-destinations#538]
Hey,

I have 2 nav-graphs, that are not nested in root navgraph. If I use same name for a destination, I get

`com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Multiple Destinations with 'terms_of_service' as their route name`.

I would expect that destinations are generated based on package name. For example, in case of shared terms of service screen:
- com.my.app.signin.destinations.TermsOfServiceDestination
- com.my.app.signup.destinations.TermsOfServiceDestination

That doesn't happen, but instead `com.my.app.destinations.TermsOfServiceDestination` is generated, which I guess is causing the conflict.

Am I doing something wrong here?

```kotlin
// 1st nav (com.my.app.signin package)
@NavGraph
annotation class SignInNavGraph(
    val start: Boolean = false,
)

@Composable
@Destination
@SignInNavGraph(start = true)
fun TermsOfService(navigator: DestinationsNavigator) {
    TermsOfServiceScreen()
}

// 2nd nav graph (com.my.app.signup package)
@NavGraph
annotation class SignUpInNavGraph(
    val start: Boolean = false,
)

@Composable
@Destination
@SignUpInNavGraph(start = true)
fun TermsOfService(navigator: DestinationsNavigator) {
    TermsOfServiceScreen()
}
```

**Comment by raamcosta** [comment]
Hi!

if you need a route different from the defaul one (taken from the composable name), @Destination has a parameter you can use to set whatever route you want.

That would be my recommendation 🙂

**Comment by WildOrangutan** [comment]
Thank you for a one solution.

Would it maybe make sense, to also add a feature, so you could specify under which package specific nav-graph gets generated?

**Comment by raamcosta** [comment]
At this point, there's no plan to do something like that. In this case, I would call your composables `SignUpTermsOfService` and  `SignInTermsOfService`. Even if they're in different packages, it also would help developers understand where they are at a glance. That or specify a route, although I believe Composable names also need to be unique in current version (that will go away with v2).
