### ISSUE TITLE
Using SavedStateHandle in the ViewModel

### ISSUE THREAD

**Issue by mykola-tarchanyn** [raamcosta/compose-destinations#54]
Hi there, thanks for this great library! 

I'm trying to use `navArgsDelegate` to pass the arguments and get them in the ViewModel. While it's pretty straightforward to extract the arguments using `argsFrom(savedStateHandle)`, I can't figure out how to properly inject `SavedStateHandle` in my ViewModel. I'm using koin for DI. 
This is how I inject the ViewModel into my Composable:
```
@Destination(navArgsDelegate = ProfileScreenNavArgs::class)
@Composable
fun ProfileScreen(viewModel: ProfileViewModel = getViewModel()) {}
```

and that's how I declare the ViewModel:
```
viewModel { ProfileViewModel(savedStateHandle = what instance of SaveStateHandl should I inject here?)}
```

Is it even possible using Koin? Thanks again!

**Comment by raamcosta** [comment]
This is not related with this library, so I'm closing it.

Check this:
https://github.com/InsertKoinIO/koin/issues/1140

Seems to be a known issue with Koin. But there seems to be workarounds already,.

**Comment by mykola-tarchanyn** [comment]
@raamcosta thanks for replying quickly. I am aware of the workaround, but unfortunately, I can't apply it using `compose-destinations` library because I inject the ViewModel into my Composable through the constructor, and at that point, there're no references to `navController`. It doesn't look like it's achievable with the current version of Koin.

**Comment by raamcosta** [comment]
Hi @mykola-tarchanyn !

Ok but trust me there is never a thing you can do with Compose Navigation that you cannot with Compose Destinations 💪 
There are multiple ways to achieve it:

```kotlin
@Destination
@Composable
fun MyScreen(
    navController: NavController,
    viewModel: MyViewModel = getMyViewModelSomehow(navController)
)
```

OR call the Composable manually like you would with normal Jetpack Compose Navigation (but better ofc)

```kotlin
DestinationsNavHost(
//stuff here
) {
    composable(MyScreenDestination) {
        // here you have access to navController, navBackStackEntry, navigation arguments, etc
        val vm = getViewModelSomehow(navController)
        MyScreen(
            viewModel = vm
        )
    }
}
```

OR even

```kotlin
DestinationsNavHost(
     // stuff
    dependenciesContainerBuilder = {
       addDependencies()
    }
)

fun DependenciesContainerBuilder<*>.addDependencies() {
    when (destination as Destination) { //cast to the module sealed version of a DestinationSpec, so that the when is always up to date with new destinations added
        FeedDestination -> TODO()
        GoToProfileConfirmationDestination -> TODO()
        GreetingScreenDestination -> TODO()
        SettingsDestination -> TODO()
        ThemeSettingsDestination -> TODO()
        ProfileScreenDestination -> dependency(getYouViewModelSomehow(navController))
        TestScreenDestination -> TODO()
    }
}

// Then you can just ask for that VM type in the Composable, and the lib will give it to you based on the dependency added here.
@Destination
@Composable
fun MyScreen(
    vm: MyViewModel
)
```

**Comment by mykola-tarchanyn** [comment]
ohhh, I can get an instance of the `NavController` in my composable, that's very good to know! Thanks, @raamcosta for this explanation, appreciate it!

**Comment by raamcosta** [comment]
Yes! DestinationsNavigator's purpose is just to wrap NavController and invert the dependency, but you can still use NavController everywhere!

There is an extension function "navigateTo" which also takes a Direction (like DestinationsNavigator)
