### ISSUE TITLE
Not correct docs and error log about BottomSheet Style

### ISSUE THREAD

**Issue by MishkaV** [raamcosta/compose-destinations#540]
When adding a BottomSheet Style, the [documentation](https://composedestinations.rafaelcosta.xyz/styles-and-animations#bottomsheet-style) gives incorrect instructions for implementing this style:
- Destination style
I didn't find `DestinationStyle.BottomSheet`, but after research I found `DestinationStyleBottomSheet` which provide this possibilities, therefore we should use:
```
@Destination(style = DestinationStyleBottomSheet::class)
@Composable
fun ColumnScope.SomeBottomSheetScreen() { /*...*/ }

```

- Initialization of navController:
```
val navController = rememberAnimatedNavController()
```
With using new compose navigation with supporting animation, we should use this:
```
import androidx.navigation.compose.rememberNavController

val navController = rememberNavController()
```

- Internal error logs:
In [code](https://github.com/raamcosta/compose-destinations/blob/09f70d4a027558c671fdeb97bf5168f9285b2183/compose-destinations/src/main/java/com/ramcosta/composedestinations/spec/DestinationStyle.kt#L221C13-L221C13) we have fallback, if we didn't find suitable `DestinationStyle` with old info about `DestinationStyle.BottomSheet` and `DestinationStyleBottomSheet`

So, thank you in advance for your attention, can support with fixing)

**Comment by rafal06** [comment]
It looks like this documentation is very outdated. [Here](https://composedestinations.rafaelcosta.xyz/common-use-cases/bottom-bar-navigation) it tells me to use `navController.navigateTo()` method, but apparently it's deprecated
![image](https://github.com/raamcosta/compose-destinations/assets/70489677/cdbe7366-f6e3-4269-aa38-f2c54869b05f)

Besides, on the [setup page](https://composedestinations.rafaelcosta.xyz/setup/), it doesn't include 1.9.x releases, and lists 1.8.x-beta as the newest version

**Comment by raamcosta** [comment]
Closing this one as docs are being updated now for v2. Also some of these issues were fixed on v1 in the mean time.
