### ISSUE TITLE
ResultRecipient compile time validation fails when generics are declared across multiple lines

### ISSUE THREAD

**Issue by simonkub** [raamcosta/compose-destinations#541]
I am using `ResultRecipient` to retrieve some information from a BottomSheet in a parent composable. Depending on my code formatting preferences, the compilation fails or works as expected. In my opinion it should work regardless of the code formatting, as long as the syntax is valid.

This is my code to retrieve a Result from my BottomSheet:

```kotlin
@Destination
@Composable
fun OverviewScreen(
    navigator: DestinationsNavigator,
    resultRecipient: ResultRecipient<FooDestination, FooResult>
) {
    // ..
}
```

Its all working fine until the point where the result recipient line gets to long and the formatter decides to format the generic types across multiple lines:

```kotlin
@Destination
@Composable
fun OverviewScreen(
    navigator: DestinationsNavigator,
    resultRecipient: 
        ResultRecipient<
            VeryLongDestinationName, 
            VeryLongResultName
        >
) {
    // ..
}
```

This snippet no longer compiles and throws the following error: 
```
com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Non existent Destination ('') as the ResultRecipient's result origin (type aliases are not allowed here).
```
The error occures somewhere along these lines: https://github.com/raamcosta/compose-destinations/blob/09f70d4a027558c671fdeb97bf5168f9285b2183/compose-destinations-codegen/src/main/java/com/ramcosta/composedestinations/codegen/validators/InitialValidator.kt#L189

I found out that the error does not appear, if `ResultRecipient` is on the same line as its first generic parameter, which is the destination:

```kotlin
@Destination
@Composable
fun OverviewScreen(
    navigator: DestinationsNavigator,
    resultRecipient: 
        ResultRecipient<VeryLongDestinationName, 
            VeryLongResultName
        >
) {
    // ..
}
```

**Comment by raamcosta** [comment]
What version are you using? This seems like something that was fixed recently 🤔

**Comment by simonkub** [comment]
Damn, sorry that I forgot to include the version 🤦  I'm on 1.9.55, which should be the latest version, right?

I think you are referring to this issue? https://github.com/raamcosta/compose-destinations/issues/516

**Comment by raamcosta** [comment]
Fixed!

Thanks @simonkub, will release a new version with the fix today.
