### ISSUE TITLE
Question : Multiple DestinationsNavHost handling

### ISSUE THREAD

**Issue by MichaelOliveiraBx** [raamcosta/compose-destinations#546]
Hi 👋 
I would need your navigation expert opinion to make a development related to the library. 
In our application, we use it and we are very satisfied. 
And we have make the choice to use 2 `DestinationsNavHost` 
- first is at root of the content, contain all FullScreen Destination
- second is an `Destination` of the first, and contains the navigation of application (with BottomBar) 

We have see, we can use `ActivityDestination` to handle fullscreen, but is complicated when we want to return in the MainActivity Navigation.
That's why we have make this choice. 

Actually we use `dependenciesContainerBuilder` to can navigate to RootNavController from the NestedNavController. 

```kotlin
@Composable
fun App() {
    val rootNavController = rememberNavController()

    DestinationsNavHost(
        modifier = Modifier.fillMaxSize(),
        navController = rootNavController,
        startRoute = HomeDestination.route,
        dependenciesContainerBuilder = {
            dependency(HomeNavGraph) {
                OpenFullScreen {
                    rootNavController.navigate(FullScreen)
                }
            }
        }
    )
}

@Destination
@Composable
fun Home(
    openFullScreen: OpenFullScreen,
) {
    val homeNavController = rememberNavController()
    Column {
        DestinationsNavHost(
            modifier = Modifier.fillMaxSize(),
            navController = homeNavController,
            dependenciesContainerBuilder = {
                dependency(ProfileNavGraph) {
                    OpenFullScreen {
                        openFullScreen.invoke()
                    }
                }
            }
        )
        
        BottomBar()
    }
}
```

It works, but when we have more than 40 Destination, it's starting to become difficult to maintain 

----- 
My idea is to create an `NavControllerRegistry` (in the idea of your NavGraphRegistry) 
```kotlin
class NavControllerRegistry {
    private val navControllers = mutableListOf<NavController>()

    fun register(navController: NavController) {
        navControllers += navController
    }

    fun unregister(navController: NavController) {
        navControllers.remove(navController)
    }

    fun get(route: String): NavController? =
        navControllers.firstOrNull { it.graph.findNode(route) != null }
}
----

val navHostController = rememberNavController()

DisposableEffect(key1 = navHostController) {
    NavControllerRegistry.register(navHostController)
    onDispose {
        NavControllerRegistry.unregister(navHostController)
    }
}

DestinationsNavHost

----

```

And in use it to retrieve directly the good NavController when we navigate, we can inject it in custom `DestinationsNavigator` and navigate to the good `NavController`. 

Firstly get your opinion, it may not a good practice to do this kind of handling, and maybe there another way to do that.
Otherwise, check with you to implement this in the library 😃 
See you 👋

**Comment by WildOrangutan** [comment]
We're using `CompositionLocalProvider` to obtain the instance of root `DestinationsNavigator`.

**Comment by MichaelOliveiraBx** [comment]
Yes nice idea, I don’t think about using CompositionLocalProvider enough. 
But I think I prefer in this case, to create another DestinationsNavigator and inject it with the dependency builder.
To have it directly in the destination arguments

**Comment by raamcosta** [comment]
Hi @MichaelOliveiraBx 

> It works, but when we have more than 40 Destination, it's starting to become difficult to maintain

You can just do 

```kotlin
dependency(OpenFullScreen { openFullScreen.invoke() })
```

And that will make it available to any destination in this DestinationsNavHost, even if you have a thousand. I also like how you're just passing a specific functionality you need rather than passing a whole NavController. I would go with that if possible.

I see the idea with the registry, but I would personally avoid doing this as much as possible, unless it's the only way. But if you have it and it works for you, nothing against it either :)

**Comment by MichaelOliveiraBx** [comment]
Hi 👋 
Yes ok I see, I know that the interface is available in all destination, we can continue to use the dependency but be more smart, I will make an interface to navigate to all full screen destination 

```
fun interface OpenFullScreen {
    fun invoke(destination: Destination)
}
```

 I agree with you, I am not fan to pass whole NavController
 Thanks for your feed back :)
