### ISSUE TITLE
Question. is there a way to perform whole application tests (instrumented tests)?

### ISSUE THREAD

**Issue by AlexanderKott** [raamcosta/compose-destinations#547]
Hello! thank you for your library.

I have an app that have about 20 compose screens and uses your library to navigate beetwn them. I am looking for a soulution to write ui tests.

here is google codelab for a regular jetpack navigation https://developer.android.com/codelabs/basic-android-kotlin-compose-test-cupcake#3

You can see there
Junit

 @Before   
fun setupCupcakeNavHost() {
    composeTestRule.setContent {
        navController = TestNavHostController(LocalContext.current).apply {
            navigatorProvider.addNavigator(ComposeNavigator())
        }
        CupcakeApp(navController = navController)
    }
}

here:  
they offer us to use a TestNavHostController
CupcakeApp is a regular composable function that represent the entry point (main screen):

@Composable
fun CupcakeApp(
    viewModel: OrderViewModel = viewModel(),
    navController: NavHostController = rememberNavController()
) {
    // Get current back stack entry
    val backStackEntry by navController.currentBackStackEntryAsState()
    // Get the name of the current screen
    val currentScreen = CupcakeScreen.valueOf(
        backStackEntry?.destination?.route ?: CupcakeScreen.Start.name
    )

    Scaffold(
        topBar = {
            CupcakeAppBar(
                currentScreen = currentScreen,
                canNavigateBack = navController.previousBackStackEntry != null,
                navigateUp = { navController.navigateUp() }
            )
.....

you can navigate among screens like this:
   navigateToPickupScreen()
    composeTestRule.onNodeWithText(getFormattedDate())
        .performClick()
    composeTestRule.onNodeWithStringId(R.string.next)
        .performClick()

lets imagine this app is using your navigation library.  How to provide a test navhost to this app?

thank you

**Comment by raamcosta** [comment]
Admitedly, I haven't had timee to think about this yet.
But I believe you can also use NavController in your tests in the exact same way, right?

Ultimately we are using NavController too. If you need DestinationsNavigator in your tests, you can create an instance of it using `TestNavHostController` as the NavController.

You can copy the implementation from here:
https://github.com/raamcosta/compose-destinations/blob/main/compose-destinations/src/main/java/com/ramcosta/composedestinations/navigation/DestinationsNavController.kt

Let me know if you could make it work 🙂

**Comment by AlexanderKott** [comment]
thank you i will try

**Comment by raamcosta** [comment]
We added some of this to v2, check it here:

https://composedestinations.rafaelcosta.xyz/v2/testing#destinationsnavigator-from-testnavhostcontroller
