### ISSUE TITLE
NavigateUp when app is in background

### ISSUE THREAD

**Issue by rubajticos** [raamcosta/compose-destinations#548]
Hello, I would like to ask you about possibility to modify backstack and navigate to previous screen when app is not in foreground.

My case:
- App1 opens list apps screen and then opens App2 (works like launcher)
- App2 finishes work, send broadcast and finish.
- App 1 receives broadcast and then should navigate back. 

The problems is that navigation only works when app return to foreground. Currently it looks like with last screen is visible for ~0,5s and navigate up then.

Maybe do you know is possible to configure your library to fix this problem?

**Comment by raamcosta** [comment]
Hi! 👋 

This library offers you all capabilities that the official one has, but not more.
Unfortunately, I believe this is not possible to do with official library. I wonder if for this use case, you can have a different way to achieve it
