### ISSUE TITLE
[Question] Is any way make navigation from view model?

### ISSUE THREAD

**Issue by rovkinmax** [raamcosta/compose-destinations#549]
I think that navigation from VM is more clean way, because in my mind composable more about UI, not logic. But navigation is related to logic in various cases.

**Comment by raamcosta** [comment]
Same as with official compose navigation, you cannot pass a NavController (in our case you can't pass DestinationsNavigator either) into ViewModels.

You can workaround this if you really want to, something like this where you depend on a component that just emits some event and then in the UI you can listen to it and do the actual navigation:
https://proandroiddev.com/jetpack-compose-navigation-architecture-with-viewmodels-1de467f19e1c
