### ISSUE TITLE
[Question]where to call navigate, which one is the best practices

### ISSUE THREAD

**Issue by ethi1989** [raamcosta/compose-destinations#551]
When I use DestainationNavigator, I want to navigate to next screen ,  which one is recommond in the following way:
a. in each screen 
like this
```
fun MainFeedScreen(
    //1. add an argument of type `DestinationsNavigator` (or `NavController`)
    navigator: DestinationsNavigator
) {
    //2. use the "withArgs" function on the generated Destination to safely create a route to navigate to
    navigator.navigate(ProfileScreenDestination.withArgs(id = $id, isEditable = $isOwnUser))
}
```

b. in the navhost
step like this
define a navigator Interface in MainFeedScreen
```
@Destination(start = true)
@Composable
fun MainFeedScreen(
    navigatorProcessor: NavigatorProcessor
) {
```

then implement
```
class XNavigatorProcessor : NavigatorProcessor{
    override fun onNavigateTo(navigate: KrPageSideEffect.KrNavigation.Navigate) {
        Log.e("TAG", "onNavigateTo")
    }

    override fun onPopBackTo(popBackStack: KrPageSideEffect.KrNavigation.PopBackStack) {
        Log.e("TAG", "onPopBackTo")
    }

}

private fun <T> DestinationScopeWithNoDependencies<T>.currentNavigator(): XNavigatorProcessor {
    return XNavigatorProcessor()
}

```
last use it 
```
dependency(MainFeedScreenDestination) {
           dependency(currentNavigator())
 }

```

**Comment by raamcosta** [comment]
I would go with what you think it’s easier unless you see a specific reason to chose the other 🙂

There’s no single best answer.

**Comment by ethi1989** [comment]
> I would go with what you think it’s easier and simpler unless you see a specific reason to chose the other 🙂
> 
> There’s no single best answer.

Yes，first I choose A, but when i look you tivi project, the screen in this project may like this
```
interface PopularShowsNavigator {
    fun navigateUp()

    fun openShowDetails(showId: Long)
}

@Destination
@Composable
fun PopularShows(
    navigator: PopularShowsNavigator
) 

interface FollowedNavigator {
    fun openUser()

    fun openShowDetails(showId: Long)
}

@Destination
@Composable
fun Followed(
    navigator: FollowedNavigator
)
```
it define a Interface for each screen. So can you give me a suggestion?

**Comment by raamcosta** [comment]
If first option works for you, keep it.
The reason I did it this way on tivi is because we have a multi module setup and all feature modules don’t know how to navigate.
So the answer is the same, use the simpler approach unless you cannot for any reason.

**Comment by ethi1989** [comment]
> If first option works for you, keep it.
> The reason I did it this way on tivi is because we have a multi module setup and all feature modules don’t know how to navigate.
> So the answer is the same, use the simpler approach unless you cannot for any reason.

Thank you , In my project I have many feature modules, but I design a interface for each module. For example , I have login module, but I only define a LoginFinish interface for it. when other module use it , like this
```
                    dependency(LoginNavGraph) {
                        OnLoginFinished {
                            navHostController.navigate(OtherNavGraph){
                                popUpTo(LoginNavGraph)
                            }
                        }
                    }
```
is it right? Or do you have an other good way? Thank you again!

**Comment by raamcosta** [comment]
It looks great 👍

**Comment by ethi1989** [comment]
Thank you
