### ISSUE TITLE
KMP support

### ISSUE THREAD

**Issue by vladraduvidican** [raamcosta/compose-destinations#552]
Are there any plans for KMP support or is this even possible?

**Comment by raamcosta** [comment]
No, we depend on official Android specific navigation library, so we’re not doing it unless they do it. As far as I know, there are no plans.

Just a tip as well, try a quick search on issues before opening one, you would see plenty similar questions.
Just saying since it would have saved you some time ahah

**Comment by vladraduvidican** [comment]
> No, we depend on official Android specific navigation library, so we’re not doing it unless they do it. As far as I know, there are no plans.
> 
> Just a tip as well, try a quick search on issues before opening one, you would see plenty similar questions.
> Just saying since it would have saved you some time ahah 

I'm sorry if this was a duplicate issue but searching KMP yielded me no results in the issues section.


https://blog.jetbrains.com/kotlin/2023/11/kotlin-multiplatform-development-roadmap-for-2024/

The last bullet point specifies a common multiplatform navigation solution for the 2024 roadmap!

**Comment by raamcosta** [comment]
That is from jetbrains though, I’m not expecting it to be a port of the Jetpack compose one. But.. who knows they have been collaborating a lot

**Comment by raamcosta** [comment]
Ahh you’re right, the previous questions used “mmm” still.

absolutely no problem with me though! Thanks for asking 👍

**Comment by maicol07** [comment]
@raamcosta KMP support for Compose Multiplatform has been merged: https://github.com/JetBrains/compose-multiplatform-core/pull/1219
Will you add support for it? It would be great to have a pre-release with KMP support

**Comment by raamcosta** [comment]
I’ll definitely look into it.
But it may take some time, I’ll know more once I start
