### ISSUE TITLE
Feature request: Allow generation of SavedStateHandle from NavArgs for testing

### ISSUE THREAD

**Issue by JWvanV** [raamcosta/compose-destinations#555]
In our current implementation (without destinations) we test our ViewModels constructing with a SavedStateHandle from a specific navArg in the following way:
```
val viewModel = XViewModel(
    savedStateHandle = FragmentXArgs(...).toSavedStateHandle()
)
```

the `.toSavedStateHandle()` method is generated by the Google navigation library.

I bet there is a similar method being generated under the hood for this project, so it would be great if we could also use it for creating an initial SavedStateHandle to be used in our tests.

Is this already on the roadmap? Or is it already implemented but I couldn't find it?

**Comment by raamcosta** [comment]
Good news: implemented this today for v2.

V2 is already delayed considering I wanted to release it Q4 last year, but hopefully it will be Q1 this year instead 🤞

**Comment by JWvanV** [comment]
Awesome!! Really looking forward to V2.
I also have a suggestion of the result recipient lambda, but I'll create a new issue for that :)
