### ISSUE TITLE
Saving history of stacks on nested navigation without multiple nav host.

### ISSUE THREAD

**Issue by rhenwinch** [raamcosta/compose-destinations#557]
I don't know if the title is clear enough to be self-explanatory, but what I'm trying to accomplish is similar to the YouTube app's navigation system (w/ bottom bar):

- Clicking on a youtube channel on the home **tab**, it'll navigate you to it.
- Try to navigate out of a new **tab** (suppose its Profile tab)
- The home tab saves the last destination you navigated inside it; making it easier for you to just go back to that tab and pick up where you've left off.

I've currently achieved this thru multiple nav hosts

But are tthere better ways to achieve this?

**Comment by raamcosta** [comment]
Hi!

it’s a general jetpack navigation question. Not really specific to this library.

You can read about multi stack navigation here
https://medium.com/androiddevelopers/multiple-back-stacks-b714d974f134
