### ISSUE TITLE
Status of v2.0.0-alpha branch?

### ISSUE THREAD

**Issue by bennnjamin** [raamcosta/compose-destinations#559]
HI I'm interested in using this in a project and wanted to know if the 2.0 alpha branch is good to start. I'd like to make sure I am using current versions of navigation-compose that have animation built in along with most recent bug fixes. If not, do you have a timeline? navigation-compose is decent but this project really seems to help with the enormous boiler plate required for any app that has nested navigation with more than a handful of screens.

**Comment by raamcosta** [comment]
Hi @bennnjamin !

Right now it's not released in any shape, however, it may be a good idea soon to release an alpha01 version of it to start having some real feedback from users. Obviously, during the alpha phase, users have to be aware that things can still change, but if you're ok with that 👍 
There is also no documentation beyond kdocs in the code.

So stay tuned during next week, and maybe there will be a v2.0.0 announcement.

**Comment by raamcosta** [comment]
v2 alpha is up! 

I'm working daily on documentation, but until then, if you're already on v1, check this guide:

https://composedestinations.rafaelcosta.xyz/migrating-to-v2

Should be enough to get you started on v2, and please give me any kind of feedback!
