### ISSUE TITLE
Is there an equivalent of Destination.invoke for deeplinks?

### ISSUE THREAD

**Issue by silverAndroid** [raamcosta/compose-destinations#561]
Using this destination as my example

```
@Destination(deepLinks = [DeepLink(uriPattern = "example://$FULL_ROUTE_PLACEHOLDER")])
@Composable
fun TitleRoute(id: Int, navigator: DestinationsNavigator) {
  // ...
}
```

Since my Destination has a parameter, when navigating to TitleRoute, I can navigate to it by calling `TitleRouteDestination(/* id= */ 2)`. However, there doesn't seem to be an equivalent when generating the deeplink.

My workaround right now is to `TitleRouteDestination.deepLinks.first().uriPattern!!.replace("{id}", id)` but I'm hoping there could be a more typesafe alternative

**Comment by raamcosta** [comment]
Hi, 

You can just do:

```kotlin
val id = // ...
val deepLink = "example:://${TitleRouteDestination(id = id).route}"
```
