### ISSUE TITLE
Document Navigation.Extras

### ISSUE THREAD

**Issue by WildOrangutan** [raamcosta/compose-destinations#565]
Hey, it seems like `Navigation.Extras` is  not documented. Can you please provide example usage for it? Thanks!

**Comment by raamcosta** [comment]
What package is this from?
It doesn’t seem like a class from this library 🤔

**Comment by WildOrangutan** [comment]
It's an argument from the method in `DestinationsNavigator`: 

`navigate(navigatorExtras: Navigator.Extras)`

**Comment by raamcosta** [comment]
Our navigate method just calls official library’s navigate method, so it has the same parameters for the most part.

You can find documentation on NavController.navigate method from official library.
