### ISSUE TITLE
NavArgsDelegate fails KSP due to false positive when property code comments include parentheses

### ISSUE THREAD

**Issue by ryanholden8** [raamcosta/compose-destinations#567]
This code works:

```kotlin
data class MyNavArgs(
    /** This is an awesome property. */
    val myProperty: Boolean = false
)

@WmsDestination(navArgsDelegate = MyNavArgs::class)
@Composable
fun MyScreen(navigator: DestinationsNavigator, navArgs: MyNavArgs) {}
```

---

This code results in `IllegalDestinationsSetup: Navigation arguments using function calls with parameters as their default value...` - https://github.com/raamcosta/compose-destinations/blob/6ea4ab7ca3f26fd712552d108f28ae67def33093/compose-destinations-ksp/src/main/kotlin/com/ramcosta/composedestinations/ksp/commons/DefaultParameterValueReader.kt#L114

--- 

```kotlin
data class MyNavArgs(
    /** This is an awesome (usually) property. */
    val myProperty: Boolean = false
)

@WmsDestination(navArgsDelegate = MyNavArgs::class)
@Composable
fun MyScreen(navigator: DestinationsNavigator, navArgs: MyNavArgs) {}
```

---
 
Took me a quite to figure out because the error message did not seem related to the default property at all.

Thanks for the awesome library! I removed the parentheses for now but wanted to provide an FYI for any that run across this issue.

**Comment by raamcosta** [comment]
Thanks!

Yes in this manual parsing of the default value there are limitless possibilities and there will always be some case it doesn’t support well.
Of course I will fix it everytime something unexpected is found, such as this one. I’m also adding new cases to unit tests so that there’s no regression as I fix more and more of these.

**Comment by raamcosta** [comment]
@ryanholden8 Can you tell me which version are you using? I cannot reproduce it with the exact nav args class you used in the example. I was able to reproduce it if I put the comment in the line after the parameter though.

I just want to make sure that it is the same issue you have.

**Comment by raamcosta** [comment]
Please try 1.9.63 (or 1.10.0 for compose 1.6) and let me know if it fixes it for you :)
