### ISSUE TITLE
PopBackStack does not have a check for lifecycle state like navigate does

### ISSUE THREAD

**Issue by cj1098** [raamcosta/compose-destinations#570]
I noticed in navigate you're checking for lifecycle isResumed before navigating. I think popBackStack should also do a check for this as you can have people clicking fast and popping the backstack multiple times unnecessarily. 
if this is fixed in a newer version let me know! I'm currently on 1.9.59

**Comment by Rawa** [comment]
I've been missing this feature as well. It would also come in handy to prevent duplicate back presses. E.g now if we use `navigateUp` on a back button it might to one too many `navigateUp` if the user accidentally enters two taps.

**Comment by raamcosta** [comment]
I saw this the other day:

https://x.com/ianhlake/status/1760413602564157779?s=20

Also here:
https://developer.android.com/jetpack/androidx/releases/lifecycle#2.8.0-alpha02

So, I think what's going to happen is that will deprecate the now "onlyIfResumed" parameter in favor of official solution like this. Then you can use that also for navigating back.

**Comment by Rawa** [comment]
Sounds good! Just for anyone looking into this issue later, there is a similar API if you are collecting a flow of side effect from the ViewModel, `Flow.flowWithLifecycle` .

Reference: https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda
