### ISSUE TITLE
Deeplink pattern

### ISSUE THREAD

**Issue by pm-nchain** [raamcosta/compose-destinations#572]
Would it be possible to support pattern for deeplinks? For example `DeepLink(action = ".*/dashboard")`.

**Comment by raamcosta** [comment]
Hi!
We simply pass whatever you provide as the pattern back to official compose navigation library. So, I don't know whether this is possible or not, but I suppose it isn't, given you're opening the issue 😅 

So if it isn't, I would suggest you opening an issue on the official compose navigation library.
