### ISSUE TITLE
Generated code isn't internal 

### ISSUE THREAD

**Issue by ghasemdev** [raamcosta/compose-destinations#576]
Hello, one of the issues with using the single-module or multi-module approach is that the generated codes cannot be configured for access levels. I need all generated items to be internal.

```kotlin
ksp {
   arg("compose-destinations.isInternal", "true")
}
```

or 

```kotlin
@Destination
@Composable
internal fun ProfileScreen() {
    //...
}

internal object ProfileScreenDestination : TypedDestination<ProfileScreenNavArgs> {
    //...
}
```

**Comment by raamcosta** [comment]
Hi!
There is a `compose-destinations.useComposableVisibility` which you can use on v1 to achieve this. However, on v2, things will change a bit and you'll be able to control visibility on a per destination basis. (check that here:  https://composedestinations.rafaelcosta.xyz/migrating-to-v2#7-if-you-have-set-compose-destinationsusecomposablevisibility-on-gradle-ksp-config)
