### ISSUE TITLE
Best way to implement / sample code with master-detail for tablets?

### ISSUE THREAD

**Issue by careful7j** [raamcosta/compose-destinations#577]
The master-detail: 
https://francois-jouvelot.medium.com/implementing-a-master-detail-user-interface-using-android-navigation-component-d9bd0aa3fcaf

Any advice/suggestion of best implementation or **sample code** is welcome! 
I think it may contribute to the **documentation** also.

**Comment by raamcosta** [comment]
This is not something this library will particularly help with, so I would say, just follow whatever guidelines are there for official library, making the parallel with how Compose Destinations registers destinations/graphs and navigates. Everything else should be the same.
