### ISSUE TITLE
Forbid navigation into subgraphs from other than start destinations of the subgraph

### ISSUE THREAD

**Issue by topnax** [raamcosta/compose-destinations#579]
I map my domain objects to destinations in a following way:
```kotlin
private fun RouterDestination.toNavigationDestination() = when (this) {
    RouterDestination.MainMenuScreen -> MainMenuScreenDestination

    is RouterDestination.TransactionSetupInitialScreen -> TransactionSetupInitialScreenDestination(
        navArgs = TransactionSetupNavArgs(terminalInfo = ...)
    )
    RouterDestination.CustomIdentifierScreen -> CustomIdentifierScreenDestination
    ...
}
```
Additionally, I have a custom `NavGraph` defined:
```kotlin
@RootNavGraph
@NavGraph(route = "txsetup")
annotation class TransactionSetupNavGraph(
    val start: Boolean = false
)
```

Finally, definition of destinations is following:

```kotlin
@TransactionSetupNavGraph(start = true)
@Destination(
    navArgsDelegate = TransactionSetupNavArgs::class, // mandatory arguments
)
@Composable
fun TransactionSetupInitialScreen(viewModel: TransactionSetupViewModel) {
     ...
}

@TransactionSetupNavGraph
@Destination
@Composable
fun CustomIdentifierScreen(
    viewModel: TransactionSetupViewModel,
) {
    ...
}
```

**Is there a way to forbid navigating into a navgraph via other than start destinations?**

I am currently facing a bug where if the user rapidly presses back and next buttons, the app navigates outside the current navgraph and then navigates back into the navgraph but via a non-start destination.

Since viewmodel initialization is done in the start destination, the app crashes.

**Comment by raamcosta** [comment]
I don't think this is possible with Compose navigation, and so, it isn't with Compose Destinations either.

I can't say I fully understand the need you have, but I have not had this requirement yet. Is it possible that you can get to the same end goal with a different approach?
