### ISSUE TITLE
Update to compose navigation 1.7.0-alpha02

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#581]
Compose nav 1.7.0-alpha02 includes predictive back.
If it isn't too hard to publish a new release, we would love to upgrade and evaluate predictive back support.

**Comment by raamcosta** [comment]
HI @Nek-12 

Please try artifact 1.11.0-alpha which includes updates of compose navigation and compos UI to latest 1.7 alpha versions and let me know how it goes 👍

**Comment by raamcosta** [comment]
(build is still ongoing, should be up in 30min or so)

**Comment by Nek-12** [comment]
Thank you! We were able to get it working
