### ISSUE TITLE
WearOS: Disable swipe-to-dismiss gesture on a destination.

### ISSUE THREAD

**Issue by matecode** [raamcosta/compose-destinations#582]
Hi. 

Im using a simple approach of destinations on a wear app. As I have one destination showing a map, the swipe-to-dismiss (in fact to go back) gesture collides with the gestures of the map, and that is why i want to turn of this gesture on one destination. But i cannot figure out how I can achive this. 

Simple setup:
```
val engine = rememberWearNavHostEngine()

WatchTheme {
    Scaffold() {
        DestinationsNavHost(
            engine = engine,
            navGraph = NavGraphs.home,
        )
    }
}
```

Since `1.3.0` androidx.wear.compose:compose-navigation has a `userSwipeEnabled: Boolean` which pretty much does what I want (as far as I understood)
https://androidx.tech/artifacts/wear.compose/compose-navigation/1.3.0-source/androidx/wear/compose/navigation/SwipeDismissableNavHost.kt.html
Unfortunately this api is not reflected in the wear engine of compose destination (and I guess the androidx.wear.compose:compose-navigation is set to `1.1.2`)

Edit:
Found on https://developer.android.com/jetpack/androidx/releases/wear-compose#1.3.0
> Recommendations for implementation
> 
> If your app allows users to pan around the screen's content, such as in a map-based app, turn off swipe handling by setting userSwipeEnabled to false in the [SwipeDismissableNavHost](https://developer.android.com/reference/kotlin/androidx/wear/compose/navigation/package-summary#SwipeDismissableNavHost(androidx.navigation.NavHostController,androidx.navigation.NavGraph,androidx.compose.ui.Modifier,kotlin.Boolean,androidx.wear.compose.navigation.SwipeDismissableNavHostState)) composable, and include a button that allows users to go to the previous screen.

Are there some recommendations (or hints ;) ) to achieve my goal?

Thanks for your great library to make compose navigation easier!

**Comment by matecode** [comment]
@raamcosta Any ideas how i could use userSwipeEnabled and still using DestinationsNavHost ?

**Comment by raamcosta** [comment]
Hi!
To be honest our wear implementation was contributed by someone else and I haven’t prioritised wear artifact in a long while.
I’m also not up to date in wear navigation 😬

I will try to update wear dependencies soon, but no promises.

**Comment by raamcosta** [comment]
Hi @matecode !

I've updated wear dependencies for v2. If this is needed for you, please check v2's migration guide and try it! :) 

https://composedestinations.rafaelcosta.xyz/migrating-to-v2
