### ISSUE TITLE
Bottom Sheet Navigation Different Behavior Requirement

### ISSUE THREAD

**Issue by tarikyasar** [raamcosta/compose-destinations#587]
Hi,

I was just wondering that is it possible to use different behavior with different bottom sheets? What if I need a bottom sheet which is supposed to be not dismissible? I looked around the documentation but could not find an answer for it. Thanks in advance.

**Comment by raamcosta** [comment]
Our bottom sheet destinations come from accompanist and I don’t think there’s such option.

If you don’t need to make it a destination you can always just embbed the bottom sheet in the other screen with material bottom sheet and I believe in that case you do have more options.
