### ISSUE TITLE
resultRecipient() support for Destinations from other modules when one depends on the other module

### ISSUE THREAD

**Issue by jakhongirmadaminov** [raamcosta/compose-destinations#59]
Would be awesome if resultRecipient() supported Destinations from other modules when the recipient module depends on the sender.

In the current state, this error is thrown.

`Non existent Destination as the ResultRecipient's result origin!`

**Comment by ildar2** [comment]
@raamcosta will the new NavGraph annotations fix this issue?

**Comment by jahongir9779** [comment]
A workaround I did is that you can implement ResultRecipient and ResultBackNavigator on a common module and use only that in different modules

**Comment by raamcosta** [comment]
> @raamcosta will the new NavGraph annotations fix this issue?

No. Because KSP processes nav graph annotations only per module. The solution to this will require some manual work in the navigation module. I just want to see if I can provide some tools to make that work easier.
I am planning to look into this in the coming weeks 🙂

**Comment by ildar2** [comment]
to whom it may concern, my workaround is to make a proxy destination in each module that would be a Destination and use my screen directly:
```
/**
 * Auxiliary screen to use SearchUserScreen between modules
 * https://github.com/raamcosta/compose-destinations/issues/59
 */
@Composable
@Destination
fun SearchUserProxy(
    resultNavigator: ResultBackNavigator<String>?
) {
    SearchUserScreen(resultNavigator)
}
```

**Comment by raamcosta** [comment]
We'll have a solution in the next release, pay attention to release notes :)

**Comment by raamcosta** [comment]
Wasn't able to allow this without losing some type safety at compile time + some manual work when calling DestinationsNavhost. So the fix is not ideal for this particular scenario where the recipient module actually depends on the sender module.

Since I need to have information about the Destination to check if it also contains a correspondently typed result, I didn't find a better solution.
I think I will reopen this however, so I can maybe explore more in the future :)

In the meantime, I wanted to make this possible even when modules don't depend on eachother, so that's why the solution went this way.

**Comment by Onvistlex** [comment]
> to whom it may concern, my workaround is to make a proxy destination in each module that would be a Destination and use my screen directly:
> 
> ```
> /**
>  * Auxiliary screen to use SearchUserScreen between modules
>  * https://github.com/raamcosta/compose-destinations/issues/59
>  */
> @Composable
> @Destination
> fun SearchUserProxy(
>     resultNavigator: ResultBackNavigator<String>?
> ) {
>     SearchUserScreen(resultNavigator)
> }
> ```

Is this still the best solution for this problem?

**Comment by raamcosta** [comment]
Hi @Onvistlex !

No, we did some changes to enable this better:
https://composedestinations.rafaelcosta.xyz/navigation/backresult#multi-module-result-back-case

I actually think I'm going to close this one, as there are no plans to do anything else here for foreseeable future.
