### ISSUE TITLE
Lifecycle for screens that then shows a dialog

### ISSUE THREAD

**Issue by Rawa** [raamcosta/compose-destinations#591]
Hello!

Consider the following Screen A, and dialog B

I want screen A to listen to side effects (doing a LaunchedEffect and collecting a flow from view model), but I only want it to be active when it is the current currentBackStackEntry. How do I achieve this? 

Looking at how navigate `onlyIfResumed` works I can see that the DestinationsNavigator has a reference to its' nav entry, but there is no way to access it from the current destination. In the scenario above the `LocalLifecycleOwner.lifecycle.currentState` would also return `STARTED`, and only if I navigate to a new screen does it seem to lower state to `CREATED`, while navigating to a dialog keeps it as `STARTED` so it is of no help when it comes to aborting the subscription. Getting the current backStackEntry for a destination feels like it becomes a bit of a guess work.

Thanks in advance.

**Comment by raamcosta** [comment]
Hi @Rawa 

You can receive the NavBackStackEntry in the annotated Composable, just add that as a parameter and the lib will provide that to you. (documented here: https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters)

Dialogs AFAIK don't move previous destinations to STOPPED, but should move them to PAUSED. You can also receive the NavController and get the `currentDestinationAsState`, then start / stop the collection based on that.
