### ISSUE TITLE
Unresolved reference: rememberAnimatedNavController

### ISSUE THREAD

**Issue by nizam-betterapp** [raamcosta/compose-destinations#593]
Thanks for the awesome library!

I am trying to change the bottomsheet animation. This documentation says we need to use rememberAnimatedNavController but I am not able to import it. Can you please help?
https://composedestinations.rafaelcosta.xyz/styles-and-animations/#animations--bottom-sheet-setup

**Comment by raamcosta** [comment]
Hi!

I’m sorry, you can ignore that and just use normal one since animations is now part of official navigation, there’s no distinction anymore.

I’ll update the docs. Thanks 🙏
