### ISSUE TITLE
DestinationStyleBottomSheet transition from BottomSheet not smooth

### ISSUE THREAD

**Issue by nizam-betterapp** [raamcosta/compose-destinations#596]
We are using DestinationStyleBottomSheet to navigate from home page to bottomsheets.
Our transition is Home Page -> Bottom Sheet 1 (BS1) -> Bottom Sheet 2 (BS2)

When we move from BS1 to BS2, BS1 closes with animation to the bottom and then BS2 opens to the top. We want the BS2 to open directly like youtube settings for changing speed to 1.5x. How to achieve this? We tried the following approaches

1. Overriding the rememberAnimatedNavHostEngine but this affects only the full page destinations and not DestinationStyleBottomSheet
2. We tried passing anim inside the builder of navigator.navigate() function call. that didn't work as well.

Following is our initialization of the ModalSheetLayout

```
val navController = rememberNavController()
                   val sheetState = rememberModalBottomSheetState(
                       initialValue = ModalBottomSheetValue.Hidden,
                       skipHalfExpanded = true,
                       confirmValueChange = { false },
                   )
                   val bottomSheetNavigator = remember { BottomSheetNavigator(sheetState) }
                   navController.navigatorProvider += bottomSheetNavigator
                   AppTheme {
                       ModalBottomSheetLayout(
                           bottomSheetNavigator = bottomSheetNavigator,
                           sheetShape = RoundedCornerShape(topStart = 16.dp, topEnd = 16.dp),
                           sheetBackgroundColor = neutral5,
                       ) {
DestinationsNavHost(
                               navController = navController,
                               navGraph = NavGraphs.root,
                               engine = rememberAnimatedNavHostEngine(),
                               modifier = Modifier.semantics {
                                   testTagsAsResourceId = true
                               },
                           ) {
                               composable(HomePageScreenDestination) {
                                       HomePageScreen(
                                           navigator = destinationsNavigator,
                                           shouldShowWeeklyImpactCard = showWeeklyImpactModal.value,
                                           navigateToBatchedNotifications = navigateToBatchedNotifications.value,
                                           openNotificationTab = openNotificationTab,
                                           continueToNBPermission = continueToNBPermission,
                                           showNbSetupCompletedConfetti = showNbSetupCompletedConfetti,
                                           resultRecipientEdit = resultRecipient<ZenModeEditorBottomSheetDestination, Serializable>(),
                                           resultRecipientFocusSession = resultRecipient<FocusSessionStartBottomSheetDestination, Serializable>(),
                                           resultRecipientOnGoingSession = resultRecipient<SessionOngoingScreenDestination, Serializable>(),
                                           streakZenModeID = if (streakZenModeID != -1) streakZenModeID else null,
                                       )
                                   }
                               }
```

**Comment by raamcosta** [comment]
Hi 👋 

If I understand correctly, it's not really that it isn't smooth, its just that you didn't want to the close and open animation when going from a bottom sheet destination to another. Is this correct?

**Comment by raamcosta** [comment]
What you could do is inside of the first bottom sheet, have a condition to show either content A or B  (B being what you currently are registering as a different destination).

When user clicks on something that should "navigate" to B, you change some compose state that makes it show content B inside the same bottom sheet, instead of opening another one. If you take Youtube's example, it wouldn't make sense to register resolution options bottom sheet separately, because you never navigate directly to it, it goes always firstly through general video settings.

So I think you should do the same. Register one bottom sheet destination, show different content inside of it with simple if condition (or when if you have multiple different contents and sub menus)

**Comment by nizam-betterapp** [comment]
We were doing that state management for all bottomsheets and this made the whole viewmodel full of states. After moving to your bottomsheet based destinationstyle, each component is a separate page. 

If we actually see bottomsheet is nothing but a screen but not fully visible. 
We will go with your state management solution for now. It will be really good if this can be improved in future.

Thanks for your time @raamcosta

**Comment by raamcosta** [comment]
This is not something we can improve in this library, we’ll be dependent on Google, since it’s their code that defines how this works
