### ISSUE TITLE
Support for navigation material

### ISSUE THREAD

**Issue by nizam-betterapp** [raamcosta/compose-destinations#598]
Accompanist library says they are moving from accompanist to material navigation. Is compose-destinations library planning to migrate this?

With the release of [Compose Material 1.7.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-material#1.7.0-alpha04), the Material team has added a new artifact: androidx.compose.material:material-navigation, which fully replaces Accompanist Navigation Material.

https://github.com/google/accompanist/issues/657#issuecomment-1985137658

**Comment by raamcosta** [comment]
Hi @nizam-betterapp !

Yes ofc! I have already done and released this for v2. For v1 I actually have also done it for Compose 1.7 dependency, but I forgot to release it 🤦 

So thank you for reminding me. v1.11.2-alpha coming up!

**Comment by raamcosta** [comment]
Release is ready! Thank you once again!
