### ISSUE TITLE
How to use in groovy?

### ISSUE THREAD

**Issue by eggham0518** [raamcosta/compose-destinations#6]
DestinationsScaffold?

**Comment by raamcosta** [comment]
I'm guessing you mean how to setup gradle to be able to use Destinations.Scaffold, right?

You need the compose material dependency. 
I'll add this to the setup section of the Readme :)

**Comment by eggham0518** [comment]
We migrated the project from groovy to kts.
Thank you

**Comment by raamcosta** [comment]
Cool! May I ask you to close the issue then?  Thanks 😊
