### ISSUE TITLE
What does `navigators` argument in `engine.rememberNavController()` do?

### ISSUE THREAD

**Issue by pm-nchain** [raamcosta/compose-destinations#601]
Hey,

I'm wondering what kind of effect does `navigators` argument have. Can you maybe better document this feature?

https://github.com/raamcosta/compose-destinations/blob/4338cf140f21805c9e7368591041d5c1376d7e9f/compose-destinations/src/main/java/com/ramcosta/composedestinations/spec/NavHostEngine.kt#L45-L47

**Comment by raamcosta** [comment]
Hi Peter.

Here we’re just exposing the same API that exists with official compose navigation.

I myself am not super familiar with it, I just use it when there are features for it, for example with bottom sheets.

so, you can ignore this unless it’s documented otherwise 😅
