### ISSUE TITLE
Bottom Sheet navigation problem when onlyIfResumed = true

### ISSUE THREAD

**Issue by pen-drive** [raamcosta/compose-destinations#603]
I'm having a problem when navigating to a Bottom Sheet destination

### onlyIfResumed = false:
If i use **navigator.navigate(BottomSheetDestination(), onlyIfResumed = false)**, i have the following result, what is espected:

[navigation onlyIfResumed = false.webm](https://github.com/raamcosta/compose-destinations/assets/80865395/82c57817-b21a-4f1e-92de-c2cdbc07b655)

### onlyIfResumed = true:
But when i use navigator.navigate(BottomSheetDestination(), onlyIfResumed = true) i have this problem:

 The state stays STARTED.

[navigation.onlyIfResumed.true.webm](https://github.com/raamcosta/compose-destinations/assets/80865395/ec00d087-107b-4eee-99e2-c8dab6cf57a2)

If you want to see the code:
https://github.com/pen-drive/Bottom-Sheet-Navigation-Problem

**Comment by raamcosta** [comment]
`onlyIfResumed` will be deleted as an API due to the fact that we now have official ways to ignore calls if lifecycle is not resumed in the `dropUnlessResumed` API.
