### ISSUE TITLE
How to make bottom bar navigation work with a nested graph using v2

### ISSUE THREAD

**Issue by w2sv** [raamcosta/compose-destinations#604]
I don't quite get how to make the above stated work. I'm using version `2.0.0-beta01`. I'd like to nest a `BottomNavGraph` inside of the `RootGraph`, such as to be able to navigate from destinations of the latter to destinations of the former and vice-versa.  However, if I annotate the `BottomNavGraph` as `@NavGraph<RootGraph>`, the resulting `NavGraphs.bottom` will be of type `DirectionNavGraphSpec`, rather than `DirectionNavHostGraphSpec`, due to which I can't pass it to the `DestinationsNavHost` inside of the `HomeScreen` `Scaffold` where I'd like my `BottomNavGraph` destinations to appear. 

```kotlin
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        setContent {
            AppTheme {
                DestinationsNavHost(
                    navGraph = NavGraphs.root
                )
            }
        }
    }
}

@NavGraph<RootGraph>
annotation class BottomNavGraph(
    val start: Boolean = false
)

@Destination<RootGraph>(start = true)
@Composable
fun HomeScreen() {
    val navController = rememberNavController()

    Scaffold(
        bottomBar = {
                BottomBar(navController = navController)
        }
    ) {
            DestinationsNavHost(
                navController = navController,
                navGraph = NavGraphs.bottom  // Type mismatch. Required: NavHostGraphSpec /* = TypedNavHostGraphSpec<*> */ Found: BottomGraph
            )
    }
}

@Composable
private fun BottomBar(navController: NavController) {
    val currentDestination =
        navController.currentDestinationAsState().value ?: NavGraphs.bottom.startDestination

    TabRow(
        selectedTabIndex = HomeScreenPage.entries.first { it.direction == currentDestination }.ordinal 
    ) {
        HomeScreenPage.entries.forEach { page ->
            Tab(
                selected = currentDestination == page.direction,
                onClick = {
                    navController.navigate(page.direction) {
                        launchSingleTop = true
                    }
                },
                content = {
                    TabContent(tab = page.tab)
                }
            )
        }
    }
}
```

I hope I didn't overlook some crucial piece of information in the documentation, in any case I really couldn't figure out how to make this work. Appreciate the library btw :)

**Comment by raamcosta** [comment]
Hi!

Just some quick feedback, maybe it’s enough to unblock you. If not I can come back with more time later.

If a graph is used to pass to a DestinationsNavHost, then it is not a nested graph. There is no relation between that graph and the one used by another NavHost in the UI tree.

So, try annotating your bottom graph with @NavHostGraph instead.

**Comment by w2sv** [comment]
Thank you for the super quick reply. I had already tried that, however I then can't navigate from BottomNavGraph destinations to RootGraph destinations due to, e.g.,  
`java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/category_selection_screen } cannot be found in the navigation graph ComposeNavGraph(0x99a4dbf8) route=bottom startDestination={Destination(0x7830bab8) route=discover_page}
`  (category_selection_screen belongs to RootGraph).

Is there a way to navigate between destinations of the two top-level graphs?

**Comment by raamcosta** [comment]
You need the NavController correspondent to the NavHost where you passed root to navigate within root, and you need a NavController correspondent to the NavHost where you pass the bottom graph to navigate within that one.

This is interesting.. it seems like you probably had this graph both as a top level one and nested on root 🤔
This is definitely not the right way to do it, because then, when navigating to a Destination of bottom graph, the hierarchy of the graph may not be expected and it will be different depending on where you’re navigating from.
That said, I can see how it could be possible to never meet any actual consequence of using it this way… so that’s probably where you were.

**Comment by Psihey** [comment]
Hello I have faced with same problems. I have two Graphs and when i open second one, I need to implement Scaffold with bottomBar but inside DestinationsNavHost i can pick only root Graph , when i need to use another.

```
internal object NavGraphs {

    val root = RootNavGraph

    val main = MainNavGraph
}
```
Maybe i am doing something wrong. Thank for any advice.

**Comment by raamcosta** [comment]
@Psihey make sure your "main" graph annotation uses @NavHostGraph and not @NavGraph<RootGraph> if you want to use it as a root level graph.

**Comment by raamcosta** [comment]
@w2sv let me know how that goes :)

**Comment by w2sv** [comment]
Yeah I made it work by using two separate NavHostControllers as you suggested, thank you. I got a follow-up question though: it seems to me as though navigating back with a result is not possible in between top-level navigation graphs, is there any way of making that work or does one have to resort to the likes of a ViewModel to convey screen results? I'll already close the issue in any case though, since that goes beyond the scope of the original question

**Comment by raamcosta** [comment]
Yeah, no, those graphs each have their own back stacks so there's no way to sending result to previous back stack. Although doing it manually, if you have access to nav control of the other graph, may be possible 🤔 . I have not tried it though.

Other than that, is there a reason you need two DestinationsNavHosts? That is what I would try to change if it was me, I haven't come across a case where they're justified.

**Comment by Velord** [comment]
I have faced same issue. 
I would definitely disagree with that statement "you probably had this graph both as a top level one and nested on root 🤔
This is definitely not the right way to do it".
All navigation holders that split navigation on branches should be the both at the same time. Maybe lib lacks of special DestinationsNavHost that can apply NavGraph.
Voyager amends that situation by introducing new type of Navigator -> TabNavigator. 
At the same time time in Vanilla compose you can nest graphs in another as much as you want and they can be nested in another. Correct me if I am wrong.
Default implementation of tab navigation can be as that:
https://makb.medium.com/building-bottom-tabs-with-jetpack-compose-a-step-by-step-guide-7360cfd015b4

```kotlin
private const val MAIN_GRAPH = "main_nav_graph"
@NavHostGraph(
    defaultTransitions = DefaultTransitions::class,
    route = MAIN_GRAPH,
    visibility = CodeGenVisibility.INTERNAL
)
annotation class MainGraph {
    @ExternalNavGraph<BottomNavigationNavGraph>(start = true)
    companion object Includes
}

private const val BOTTOM_NAVIGATION_GRAPH = "bottom_navigation_graph"
@NavGraph<ExternalModuleGraph>(
    route = BOTTOM_NAVIGATION_GRAPH,
    start = true,
    navArgs = Nothing::class,
    deepLinks = []
)
internal annotation class BottomNavigationGraph

    Scaffold(
        bottomBar = {
           ...
        },
        content = {
           I need to create new NavHost. But I can't
          Cause my BottomNavigationGraph is not NavHostGraph
            DestinationsNavHost(
                navGraph = BottomNavigationGraph,
                navController = navController
            )
        },
    )
```

Can you suggest solution ?

**Comment by raamcosta** [comment]
First, having bottom bar navigation does not equal having multiple `DestinationsNavHost`. Multiple `DestinationsNavHost`s is not encouraged and should be left for the extreme cases that do need it. 

Secondly, on official compose navigation (it's not this library's limitation, it's the same with the official jetpack library), `DestinationNavHosts` don't have any relation with one another. So, the graphs passed into them should not be nested in any other because it won't be in reality. Whatever you pass to the NavHost WILL be the root top level graph of that NavHost, and that's it.

So, I maintain my statement: a graph is either a top level one that is passed to the NavHost or it's nested in another graph but is NOT used to pass to a NavHost. What you did with v1, is that you basically copied the entire graph on both NavHosts, and that is not great because you are not really aware of what NavHost you are on when you navigate to a given Destination that belongs to both of them.

If you want a better example of how to achieve bottom bar navigation with a single NavHost, check this:
https://composedestinations.rafaelcosta.xyz/v2/common-use-cases/bottom-bar-navigation

or even from official jetpack developer' writing (to achieve multi back stack behaviour)
https://medium.com/androiddevelopers/multiple-back-stacks-b714d974f134

**Comment by Velord** [comment]
Thanks for the answer. If someone need to look how you can achieve multiple nav hosts I left code here. I added destination that belonged to bottom navigation graph strictly to main graph. In that case graphs work independently as they must do.
```kotlin
private const val MAIN_GRAPH = "main_nav_graph"
@NavHostGraph(
    defaultTransitions = DefaultTransitions::class,
    route = MAIN_GRAPH,
    visibility = CodeGenVisibility.INTERNAL
)
annotation class MainGraph {
    @ExternalDestination<BottomNavigationScreenDestination>(start = true)
    companion object Includes
}

@Destination<ExternalModuleGraph>(start = true)
@Composable
fun BottomNavigationScreen() {
    val viewModel = koinViewModel<BottomNavigationDestinationsVM>()
    
    val navController = rememberNavController()
    Scaffold(
        bottomBar = { ... },
        content = {
            DestinationsNavHost(
                navController = navController,
                navGraph = NavGraphs.bottomNavigationGraph,
                modifier = Modifier
                    .padding(it)
                    .fillMaxSize(),
                startRoute = DemoScreenDestination,
            )
        },
    )
}
```
