### ISSUE TITLE
How to use bottom sheets with material 3

### ISSUE THREAD

**Issue by JP-Labs** [raamcosta/compose-destinations#605]
Hi there,
I don't quite understand how to use this library with the newest material 3 compose library. I am not sure if I am understanding something wrong or if it is even possible in the current state of alpha and betas between all libraries. 

The goal is to open a bottom sheet with compose destinations while using the compose material 3 dependency. It should be possible to configure the bottom sheet state with e.g. `skipPartiallyExpanded`.

**Dependencies:** 
- `compose-destinations` `2.1.0-beta01`
- `compose-material3` `1.3.0-alpha03`

The recommended usage of this library is to implement the `ModalBottomSheetLayout` component as a wrapper together with a `BottomSheetNavigator`. Both of them are imported from the `compose-material` (Not Material 3) library which I do not declare explicitly in my dependencies. Android Studio will show following warning.

```
Using a material import while also using the material3 library
```

I would prevent using different versions of compose material components since it could become a source for bugs. But even if I use the mentioned components, I am unable to set a `sheetState` (`ModalBottomSheetState`) since the `rememberModalBottomSheetState` method from material returns a `SheetState` object while a `ModalBottomSheetState` is expected (mismatching material versions). 

I want to prevent declaring and using the dependencies for both material 2 and material 3. Is this currently possible?

**Comment by JP-Labs** [comment]
Thanks for the quick response!

Different kinds of bottom sheets makes sense, I was aware of this concept. What bothers me is the lack of customization for the bottom sheet behavior when using explicitly material 3. 

I am currently using compose 1.6 which means I could prevent material 2 & material 3 warnings by implementing `com.google.accompanist.navigation.material`. However if I want to customize the sheet state in the `BottomSheetNavigator` it takes a `ModalBottomSheetState` argument, which is part of the `androidx.compose.material:material` package. As I am not importing this package and I would like to avoid, I see no possibility to customize the sheet state.

If I understand correctly `androidx.compose.material.navigation` isn't a separate package and imported with the material 2 compose library too. So compose 1.7 would not help either with this issue.

This issue was presented in this thread https://github.com/google/accompanist/issues/657 which I think you were aware of.

Am I missing something here?

**Comment by JP-Labs** [comment]
Maybe a should clarify a bit more what I am trying to achieve or what the issue is.

I have a compose destination to a bottom sheet in which an input field is provided. Since the property `skipHalfExpanded` is `false` by default the keyboard is overlapping the input on small devices in my case. 

To address this issue a workaround was presented in the mentioned thread (https://github.com/google/accompanist/issues/657#issuecomment-1183279512). This works flawlessly with the exception that requires the `compose-material` library, which I do not import currently since the app is build fully on Material 3 and I didn't plan to do in the future.

**Comment by raamcosta** [comment]
I see.

Well, this is a question for the official libraries. It seems like given the workaround is, well... a workaround, they haven't considered this case where the dev may not even be using material 2. These APIs are not from Compose Destinations, the only thing we do is taking the bottom sheet style from the annotation and calling the right official APIs to register that bottom sheet in the navigation graph.

All these APIs about ModalBottomSheetLayout and BottomSheetNavigator are not from this library.

For what is worth, I see that even with Compsoe 1.7, they're internally important `compose.material` package, so I wonder if it's really an issue to import just this bit of material 2 🤔  - they seem to be doing it regardless of what you are using in your app code, so 🤷

**Comment by JP-Labs** [comment]
Yes, I guess there is currently no other possibility. Let's hope that this issue is addressed in the near future. And as you said, that issue needs to be addressed elsewhere. 
Since there was a warning about using both libraries at the same time I hoped there had to be another way to solve the challenge. It's really confusing with the amount of different libraries... So many experimental features, deprecated components and alpha versions of packages at the same time.

But thank you for helping me clarifying the current package architecture.

**Comment by haluzpav** [comment]
The sad issue is that `androidx.compose.material3.ModalBottomSheet` supports predictive back animations ([as shown in M3](https://m3.material.io/components/bottom-sheets/guidelines#3d7735e2-73ea-4f3e-bd42-e70161fc1085)), while `androidx.compose.material.navigation.ModalBottomSheetLayout` (usable in navigation) does not. 😕

We have a ton of bottom sheets in the app and I sure as hell won't migrate them out of navigation graph. I hope Google creates M3 variant with support for predictive back animations, or something. 🤞
