### ISSUE TITLE
Any plans to support kotlin 1.9.23?

### ISSUE THREAD

**Issue by shaharKeisarApps** [raamcosta/compose-destinations#608]

**Comment by raamcosta** [comment]
Are you seeing any specific issue when using 1.9.23?

**Comment by shaharKeisarApps** [comment]
there was an error with kotlin compiler compatibility..
but if you say it supported than it might be a problem in our project.

**Comment by raamcosta** [comment]
Sorry, no that’s not what I meant. I honestly haven’t tried it. But historically I think it has worked well..

If you can paste the error maybe that will help. I will check it once I have time.

**Comment by shaharKeisarApps** [comment]
> Sorry, no that’s not what I meant. I honestly haven’t tried it. But historically I think it has worked well..
> 
> If you can paste the error maybe that will help. I will check it once I have time.

I will check soon for logs and update:)

**Comment by raamcosta** [comment]
Closing this as I'm updating all dependencies today. Still unsure if there was any issue, but there was, It should now work.
Let me know if the issue persists!
