### ISSUE TITLE
NestedGraph destinations not in parent NavGraphSpec.allDestinations

### ISSUE THREAD

**Issue by s0nance** [raamcosta/compose-destinations#611]
Hello!

I encountered an issue where calling my current NavGraph _.allDestinations_ extension is not returning the nested nav graphs destinations.

Here is my generated tree:
 ```
 * * 🗺️[MenuNavGraph]
 * * ∙∙∙∙∙∙∙∙↳🗺️🏁[Page1NavGraph]
 * * ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙↳📍🏁[Page1Screen]
 * * ∙∙∙∙∙∙∙∙↳🗺️[SettingsNavGraph]
 * * ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙↳📍🏁[SettingsScreen]
 * * ∙∙∙∙∙∙∙∙↳🗺️[FromSettingsLoginGraph]
 * * ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙↳📍🏁[LoginScreen]
 * * ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙↳🗺️[FromSettingsRegisterGraph]
 * * ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙↳📍🏁[RegisterScreen]
 * * ∙∙∙∙∙∙∙∙↳🗺️[Page2NavGraph]
 * * ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙↳📍🏁[Page2Route]
 * * ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙↳📍[Page2-1Route]
 * * ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙↳📍[Page2-3Route]
 *
```
I expect the extension to return, for **FromSettingsLoginGraph**, the given destinations:
`[FromSettingsLoginLoginScreenDestination, FromSettingsRegisterRegisterScreenDestination]`, but it seems to only return `FromSettingsLoginLoginScreenDestination`.

Is this an expected behavior ?

I used a small function to check if my current destination is well a part of the nested navigation: 
```
appCurrentDestinationState?.route?.let {
   topLevelDestination.graph.findDestination(it) // here topLevelDestination represents FromSettingsLoginGraph
} != null
```

and it returns **true** when I navigate to (so when appCurrentDestinationState route equals:) `FromSettingsRegisterRegisterScreenDestination`. So it seems it is indeed a part of the nested graphs!

By looking at your code, inside the `SpecExtension.kt` file, it seems you are recursively returning all destinations, even those from _nestedNavGraphs_, so I guess it is a bug?

I'm looking forward to hear your advice on this! Thank you

**Comment by raamcosta** [comment]
What Compose Destinations version are you using?

**Comment by s0nance** [comment]
**Compose Destinations** _v2.0.0-beta01_
**Jetpack Compose** version _1.6.5_

**Comment by raamcosta** [comment]
Yes, you are right. Will be fixed on next versions. Thanks for reporting!

**Comment by raamcosta** [comment]
Included on beta07 building now. Thank you once again! 🙏

**Comment by s0nance** [comment]
No problem, it's been a pleasure!

Thanks for your work.
