### ISSUE TITLE
Looking for advice: Would like to know to to set nested graph with it's own Scaffold + shared viewmodel

### ISSUE THREAD

**Issue by shaharKeisarApps** [raamcosta/compose-destinations#612]
I'm developing a Jetpack Compose app with a navigation structure that includes a main home screen and a multi-step "Create Group" flow. To ensure UI consistency and manage shared state efficiently, my aim is to implement a shared Scaffold and ViewModel for all screens within each navigation graph. However, I'm encountering challenges with the best approach to structure this using Jetpack Compose Navigation, especially considering the potential use of multiple NavHosts and its implications for deep linking.

note: I want to avoid using NavHost for each nested graph, but, should I?

Primary Goals:

Maintain a consistent UI (e.g., TopAppBar) across all screens within the "Create Group" flow without redefining the Scaffold in each composable. Share a ViewModel across these screens to handle state and data effectively. Concerns and Questions:

Shared Scaffold Implementation: What's the recommended practice for sharing a Scaffold across multiple screens within a nested graph in Jetpack Compose Navigation? Should each screen in the flow share the same Scaffold instance, and if so, how is this best achieved?

ViewModel Sharing: How can a ViewModel be shared effectively across all composables within a specific nested graph (like the "Create Group" flow) for cohesive state and data management?

Multiple NavHosts Consideration: In aiming for the above setup, could employing multiple NavHosts be a solution or would it complicate the architecture unnecessarily? Specifically, how might using multiple NavHosts affect deep linking across the app? Is there a risk of complicating deep link implementation or handling with multiple NavHosts, and if so, how can this be mitigated?

Deep Linking Concerns: Given the structured navigation, are there specific challenges or best practices to consider for implementing deep linking effectively in a setup with shared Scaffold and ViewModel across nested graphs or multiple NavHosts?

I am looking for insights into structuring navigation and shared UI/state management efficiently in a scalable Jetpack Compose application, particularly in regard to the use of nested graphs/ multiple NavHosts, and ensuring deep linking remains robust.

What about using DestinationWrapper?

Any examples, advice on best practices, or pointers to resources would be greatly appreciated:)

**Comment by raamcosta** [comment]
Hi.

I'm sorry If I don't go too deep in my suggestions, time is short these days :P 

What I would do:

- Single DestinationsNavHost and single Scaffold. Have logic around those to show / hide components of the Scaffold based on the current destination visible on screen. (you can check the sample of this repo for an example.. but it's really just if(currentDestination != .... or if (currentDestination in listOf(<destinations>) or if(SomeNavGraph.contains(currentDestination).

- Have nested graphs for each flow, and create a VM tied to that nested graph. The same instance will be available and used by all destinations of that graph. (https://composedestinations.rafaelcosta.xyz/v2/common-use-cases/providing-viewmodels#share-viewmodels-between-multiple-destinations)

> DestinationWrapper

Probably unrelated to your questions.
