### ISSUE TITLE
Mandatory navigation argument for start destination

### ISSUE THREAD

**Issue by saff1x** [raamcosta/compose-destinations#613]
In my project I have a Nested NavHost inside Screen A. Screen A has an "id" navigation argument that is used in the viewmodel via SavedStateHandle. My Problem is that i need this id for all child screens/viewmodels inside the Nested NavHost aswell. When I tried to put the id as a nav arg for the child screen i just got the error "composable: Start destinations of NavHostGraphs cannot have mandatory navigation arguments!".
Is there any other way i can access the id inside the child view models?

**Comment by Jon889** [comment]
Just came across this issue as well. You can annotate the argument as `@NavHostParam` and then provide it in the `dependenciesContainerBuilder`. See here: https://github.com/raamcosta/compose-destinations/issues/174 (@TopLevelParam was named @NavHostParam when it was implemented) If your ID is just a string you might need to wrap it in a class so the dependency can be picked up.
