### ISSUE TITLE
Support for material3 bottom sheets

### ISSUE THREAD

**Issue by cj1098** [raamcosta/compose-destinations#614]
Hello! Is there any work going on to support using material3 bottom sheets? 
I noticed accompanist hasn't updated to support it and from what I can tell v2 of this library also didn't mention it

**Comment by raamcosta** [comment]
Hi @cj1098 

The bottom sheets used on navigation is the same that official libraries provide (not just accompanist - it was imported to official library too).
Material bottom sheets can still be used, just not as a navigation destination.

There is no work to be done here 🙂

**Comment by cj1098** [comment]
@raamcosta Thanks for replying! 
So you're saying if we move to material3's bottom sheets it's not possible to have them be destinations?
Previously when we declared our BottomSheetLayout we would say something like:
`ModalBottomSheetLayout(
            bottomSheetNavigator = bottomSheetNavigator,
        )`
        Where we could pass in a bottomSheetNavigator that was provided via accompanist. In the m3 version it doesn't support a bottomSheetNavigator. 
        I do see that official libraries from androidx do support bottom sheets as navigation. So if we wanted to use m3 and still be able to navigate to bottom sheets we'd need to look to use one of those libraries?

**Comment by raamcosta** [comment]
Im saying those are two different kinds of bottom sheets. You can use both material and navigation bottom sheets.
Material ones cannot be destinations, they’re something you show or hide as part of another screen.
Navigation ones are something else, they’re not material 2 or 3, they are their own thing.

**Comment by cj1098** [comment]
Gotcha. Thanks for the clarification!
