### ISSUE TITLE
Providing title to Destinations on v2

### ISSUE THREAD

**Issue by ymaniz09** [raamcosta/compose-destinations#615]
Hi Rafael, thanks for such a fantastic library!

I was taking a look at starting the migration to v2.
Currently, I define the title for my destinations at a module level:

```
val TaskDirectionDestination.title: Int
    get() = when (this) {
        is ScanOperatorsScreenDestination -> R.string.task_qpl_drinkware_title
        is ScanCartScreenDestination -> R.string.task_qpl_drinkware_title
        is PerformQplScreenDestination -> R.string.task_qpl_drinkware_title
       ...
    }
```  

and on my app module:

```
currentDestination?.let {
        LaunchedEffect(currentDestination) {
            LoggerFactory.getLogger("DockNavigation").info("Navigated to: ${it.route}")

            val title = when (it) {
                is PackingDirectionDestination -> it.title
                is TaskDirectionDestination -> it.title
                is SupervisorScreenDestination -> it.title
                else -> null
            }

            onUpdateToolbarTitle(title)
        }
    }
```

I need help implementing that on v2. Am I missing something, or is there a better way of doing it?

Thank you so much

**Comment by raamcosta** [comment]
On v2, Destinations are no longer a part of a sealed hierarchy, so you can still do the exact same I believe, but the compiler won't help you when you add a new Destination (probably you'd throw on the else clause, so at runtime it would crash and you'd notice you need to add the new Destination).

There are lots of reasons why we decided to not use sealed hierarchy anymore. 
Let me know if this is good enough!
