### ISSUE TITLE
Provide a default Destination AnimatedContent Scope to support the Shared Element Transition API

### ISSUE THREAD

**Issue by whitescent** [raamcosta/compose-destinations#616]
Compose 1.7.0-alpha07 has released the first Shard Element Transition API, and after my initial experience with it, I realized that Compose Destination might need to make some encapsulations for this

A simplest example of a Shared Element would look like this:

```kotlin
SharedTransitionLayout {
  NavHost(
    navController = navController,
    startDestination = "first",
  ) {
    composable("first") {
      Column {
        LazyColumn(...) {
          items(100) {
            CenterRow {
              Text(text = "items $it")
              AsyncImage(
                model = "...",
                contentDescription = null,
                modifier = Modifier
                  .sharedElement(
                    state = rememberSharedContentState(key = "image $it"),
                    animatedVisibilityScope = this@composable
                  )
                  .clickable {
                    navController.navigate("second/$it")
                  },
              )
            }
          }
        }
      }
    }
    composable(
      route = "second/{imageId}",
      arguments = listOf(
        navArgument("imageId") { type = NavType.IntType }
      )
    ) { backStackEntry ->
      Box {
        AsyncImage(
          model = "...",
          contentDescription = null,
          modifier = Modifier
            .fillMaxWidth()
            .size(300.dp)
            .sharedElement(
              state = rememberSharedContentState(key = "image ${backStackEntry.arguments?.getInt("imageId")}"),
              animatedVisibilityScope =  this@composable
            )
        )
      }
    }
}
```

As you can see from the code above, a `sharedElement` requires an `animatedVisibilityScope` parameter, and if the code above were done with `Compose Destination`, it would need to be written as composable(...).

For me, I mostly use DestinationsNavHost in Compose Destination because it automatically generates all composable("xxx") with KSP, but if I want to use the Shared Elements API in some screens, I need to provide an `AnimatedVisibilityScope parameter`, and DestinationsNavHost can't automatically inject AnimatedVisibilityScope for the screen.

My idea is that the `AnimatedContentScope` can be injected by default into a different composable in Compose Destination, Just like DestinationNavigator.

```kotlin
@AppNavGraph
@Destination
@Composable
fun SharedTransitionScope.StatusMediaScreen(
  animatedVisibilityScope: DestinationAnimatedVisibilityScope,
  navigator: DestinationNavigator,
  attachments: Array<Attachment>,
  targetMediaIndex: Int,
)
```

**Comment by ammargitham** [comment]
Technically, we can use the `manualComposableCallsBuilder` for the destinations where we need to pass the animatedVisibilityScope. It's not pretty but it allows us to not write `composable()` for each destination.

```kotlin
manualComposableCallsBuilder = {
    composable(HomeScreenDestination) {
        CompositionLocalProvider(
            LocalNavAnimatedVisibilityScope provides this,
        ) {
            HomeScreen(
                navController = navController,
                nestedScrollConnectionGetter = { nestedScrollConnection },
            )
        }
    }
    composable(WallpaperScreenDestination) {
        CompositionLocalProvider(
            LocalNavAnimatedVisibilityScope provides this,
        ) {
            WallpaperScreen(
                navController = navController,
                source = navArgs.source,
                wallpaperId = navArgs.wallpaperId,
                thumbData = navArgs.thumbData,
            )
        }
    }
},
```

Then use the scope inside the composable.

But yeah, auto injected scope would be better.

**Comment by raamcosta** [comment]
Hey guys 

I haven’t had time to properly check shared element transitions but if you just need the animated scope, that is something that hm the lib already knows how to provide to the destination without any setup whatsoever.

check this

https://composedestinations.rafaelcosta.xyz/v2/styles-and-animations#animated-style

**Comment by whitescent** [comment]
@raamcosta but if we use shared element transition api, we also need `SharedTransitionScope` in my function, just like this:

![image](https://github.com/raamcosta/compose-destinations/assets/31311826/a7099c38-c7ae-40d9-aa27-6e98cf176fb3)

![image](https://github.com/raamcosta/compose-destinations/assets/31311826/4f753573-33eb-4d4d-beba-895fad269870)

![image](https://github.com/raamcosta/compose-destinations/assets/31311826/18fef4b1-de9f-48b7-9114-f6143f0b2282)

but, compose destination seems cannot resolve `SharedTransitionScope` ?🤔.

**Comment by raamcosta** [comment]
I just made use of shared element transitions with no issue. I don't think the "glichyness" is related to Compose Destinations.

That said, I will with next release do some changes that should make using it easier. Specifically with the way to send SharedTransitionScope and AnimatedVisibilityScope.

**Comment by ammargitham** [comment]
@raamcosta I have created a sample project which shows the shared element bug when the screens are in nested navhost.
In the sample, Click rows which go to "Detail in List" will correctly work with shared transition, where as those with "Detail in Root" won't work.

[ComposeDestinationSharedElemBug.zip](https://github.com/raamcosta/compose-destinations/files/15221353/ComposeDestinationSharedElemBug.zip)

**Comment by raamcosta** [comment]
@ammargitham have you tried the same code without Compose Destinations and with official compose navigation lib?

I really don’t think Compose Destinations is causing this issue as we just bridging things from the official lib.

**Comment by ammargitham** [comment]
@raamcosta Okay, I tried with the official lib. Same behavior. Will raise issue in Google issue tracker.
