### ISSUE TITLE
Navigate to another module with args 

### ISSUE THREAD

**Issue by bahromzodabehruz27** [raamcosta/compose-destinations#621]
Hi @raamcosta  I am using destination library in our multi module project. Now I want to screen from main module to details module with args. As arguments I want to use data class.
Example 
My data class looks like this 

```
@Parcelize
data class Things(val first: String = "", val second: String = ""):Parcelable
```

```

@Destination(
    route = "testScreen/{things}"
)
@Composable
fun TestScreen(things: Things,viewModel: TestViewModel = hiltViewModel()){


}
```

And from main module using navigator I did navigate by route like this 

```
  val data = Things("Behruz","items")
  navigator.navigate("testScreen/things/${data}")
```

But I got java.lang.IndexOutOfBoundsException: Index: 1, Size: 1 exceptions

What here I am doing wrong ?

**Comment by raamcosta** [comment]
You shouldn't navigate with strings. Compose Destinations is here to help you NOT do that.

Change it to:

```kotlin
@Destination
@Composable
fun TestScreen(things: Things,viewModel: TestViewModel = hiltViewModel()){


}
```

And navigate:
```kotlin
val data = Things("Behruz","items")
navigator.navigate(TestScreenDestination(data))
```

**Comment by bahromzodabehruz27** [comment]
Can you give me a example of multi module navigation ? thanks

**Comment by raamcosta** [comment]
It's just like single module navigation. Or do you mean how to set it up?
For that, check here:

https://composedestinations.rafaelcosta.xyz/v2/multi-module-setup
