### ISSUE TITLE
[ksp] java.lang.NullPointerException when using custom NavArgument type

### ISSUE THREAD

**Issue by KarolCieslar** [raamcosta/compose-destinations#624]
When i try to add custom NavGraph Argument to my custom Graph (SettingGraph) i have error `[ksp] java.lang.NullPointerException`.
Everythings is ok when i use String, Int, Double etc as a argument type.

NavGraph:
![image](https://github.com/raamcosta/compose-destinations/assets/5437671/b0cfc470-342a-4fb1-a141-e10f36a96d6f)

Model:
![image](https://github.com/raamcosta/compose-destinations/assets/5437671/3c8c0c44-c773-43fc-b617-55125fc9a51b)

Stacktrace: https://hastebin.skyra.pw/kikuleweru.php

Compose Destinations version: 2.1.0-beta02
KSP Version: 1.9.23-1.0.20

**Comment by raamcosta** [comment]
Hi 👋 

Can you provide again the stack trace? Seems I cannot reproduce this 🤔

**Comment by KarolCieslar** [comment]
@raamcosta
There is a StackTrace: [https://pastebin.com/jm9FHf1x](https://pastebin.com/jm9FHf1x)

**Comment by raamcosta** [comment]
This doesn’t seem like the same one.
This looks not even related to this library. You mentioned a NullPointerException?

**Comment by KarolCieslar** [comment]
Oh.. i provided wrong stacktrace. Sorry for that. Here is correct one: [https://pastebin.com/Y9TYRY7K](https://pastebin.com/Y9TYRY7K)

**Comment by KarolCieslar** [comment]
@raamcosta can You look at this?

**Comment by raamcosta** [comment]
Sorry I have been busy these last days. I will be checking it this week.

**Comment by raamcosta** [comment]
You are absolutely right, thank you for reporting 🙏 

Will be fixing this in the coming days!

**Comment by raamcosta** [comment]
Fix is up!

**Comment by KarolCieslar** [comment]
@raamcosta there is a another error after update.
[https://pastebin.com/tSNithPr](https://pastebin.com/tSNithPr)

**Comment by raamcosta** [comment]
Is `CardWithMask` an: Enum or Parcelable or java Serializable or Ktx Serializable or has a custom type serializer?

**Comment by KarolCieslar** [comment]
Oooppss i forgot about @Parcelize ;/
My bad. Now everythings is working but i still do not understand how to retrive NavGraphs arguments from "nonstart" Destination. Here more info [https://github.com/raamcosta/compose-destinations/issues/633](https://github.com/raamcosta/compose-destinations/issues/633)

**Comment by raamcosta** [comment]
Not just your bad. I also missed throwing a more helpful message in this case for graph nav args. will do so for next release.
Will also get back to you on that one later.
