### ISSUE TITLE
No NavGraphs in V2

### ISSUE THREAD

**Issue by whitescent** [raamcosta/compose-destinations#625]
My project is Single Module, and this is my NavGraphs looks like in V1

![image](https://github.com/raamcosta/compose-destinations/assets/31311826/bce6b7fa-bcbc-45f2-9d81-8c908b75460d)

There are also some destinations that don't belong to any NavGraph of these(LoginNavGraph, AppNavGraph) two

but my NavGraphs in V2 is:

![image](https://github.com/raamcosta/compose-destinations/assets/31311826/66b92e65-da05-427e-a462-833f15417180)

If I'm not mistaken, I have changed all the code in v1 from
```

@RootNavGraph(start = true)
@NavGraph
annotation class LoginNavGraph(
  val start: Boolean = false
)

@RootNavGraph
@NavGraph
annotation class AppNavGraph(
  val start: Boolean = false
)


@AppNavGraph
@Destination
@Composable()
```
to

```
@NavGraph<RootGraph>(start = true)
annotation class LoginNavGraph

@NavGraph<RootGraph>
annotation class AppNavGraph

@Destination<AppNavGraph>
@Composable
```

but the generated NavGraphs still seem to have this error 🤔.

**Comment by whitescent** [comment]
Just created a new project to test it, but still encountering this issue

<img width="1737" alt="image" src="https://github.com/raamcosta/compose-destinations/assets/31311826/41f48a67-5b69-47d6-967f-e5fb22b50ab3">

**Comment by raamcosta** [comment]
Is this sample on GitHub? Can I get the link?

**Comment by whitescent** [comment]
> Is this sample on GitHub? Can I get the link?

ok i will create

**Comment by whitescent** [comment]
https://github.com/whitescent/compose-destination-issue @raamcosta

**Comment by raamcosta** [comment]
Can you try adding `, start = true)`  to one of your graphs? Login for example?

**Comment by whitescent** [comment]
> Can you try adding `, start = true)` to one of your graphs? Login for example?

<img width="1566" alt="image" src="https://github.com/raamcosta/compose-destinations/assets/31311826/e0d2e432-0b76-4f49-8dc4-6e8a7a56c7db">

yes, still missing

**Comment by raamcosta** [comment]
Ok let me run it locally

**Comment by raamcosta** [comment]
Found it 🐞 

For now, please add this:

```
@NavHostGraph
annotation class MainGraph
```

And use MainGraph instead of RootGraph. Also on Activity, NavGraphs.main.

Later when I release a new version, you can go back to using RootGraph 😄 

Thank you for reporting 🙏

**Comment by whitescent** [comment]
So I can start by writing code like this:

```
@NavHostGraph
annotation class MainNavGraph

@NavGraph<MainNavGraph>
annotation class LoginNavGraph

@NavGraph<NavHostGraph>
annotation class AppNavGraph

@Destination<AppNavGraph>
@Composable
```

right?

> Later when I release a new version, you can go back to using RootGraph 😄

Thank you for all your hard work 😄👍

**Comment by raamcosta** [comment]
Don't forget that each nav graph needs a start. So probably missing `start = true` on some of those :)

**Comment by whitescent** [comment]
@raamcosta i just test the SharedElement Transition in last v2 version(2.1.0-beta02), But `AnimatedVisibilityScope` it is not automatically provided.

<img width="1912" alt="image" src="https://github.com/raamcosta/compose-destinations/assets/31311826/8d5fae9e-d592-4506-a3f1-2d928d2087f6">

code:

```kotlin
SharedTransitionLayout {
  DestinationsNavHost(
    navGraph = NavGraphs.main,
    dependenciesContainerBuilder = {
      dependency(this@SharedTransitionLayout)
    }
  )
}

@OptIn(ExperimentalSharedTransitionApi::class)
@Destination<HomeNavGraph>(start = true)
@Composable
fun SharedTransitionScope.Home(
  navigator: DestinationsNavigator,
  animatedVisibilityScope: AnimatedVisibilityScope
) {
  Column {
    Text(
      text = "home Screen",
      modifier = Modifier.sharedElement(
        state = rememberSharedContentState(key = "text"),
        animatedVisibilityScope = animatedVisibilityScope
      )
    )
    Button(
      onClick = { /*TODO*/ }
    ) {
    }
  }
}

@OptIn(ExperimentalSharedTransitionApi::class)
@Destination<LoginNavGraph>(start = true)
@Composable
fun SharedTransitionScope.Login(
  navigator: DestinationsNavigator,
  animatedVisibilityScope: AnimatedVisibilityScope
) {
  Box(
    modifier = Modifier.fillMaxSize(),
    contentAlignment = Alignment.Center
  ) {
    Column {
      Text(
        text = "Login Screen",
        modifier = Modifier.sharedElement(
          state = rememberSharedContentState(key = "text"),
          animatedVisibilityScope = animatedVisibilityScope
        )
      )
      Button(
        onClick = {}
      ) {
      }
    }
  }
}
```

could you please check this issue? 🤓

**Comment by raamcosta** [comment]
ahh, I missed the import. The example I had was already importing it for some other reason 😛 

Will fix this, thank you!

**Comment by raamcosta** [comment]
Try 2.1.0-beta03 coming up within 30min or so.
