### ISSUE TITLE
Support for Shared Element Transition.

### ISSUE THREAD

**Issue by chirag38-unity** [raamcosta/compose-destinations#626]
Hey team, Compose API recently launched Shared Element Transition, When can we expect support for the same.

**Comment by raamcosta** [comment]
It has been available ever since they published it!

on latest releases we added something to make it easier to use with Compose Destinations. Check releases page 🙂

**Comment by fjr619** [comment]
May i know where i can get the information? Cause in https://composedestinations.rafaelcosta.xyz/styles-and-animations#animations-setup, i didnt find any do umentation about shared element. Thank you

**Comment by raamcosta** [comment]
https://github.com/raamcosta/compose-destinations/releases/tag/2.1.0-beta02

Check the “improvements” section.
