### ISSUE TITLE
Can not make dependenciesContainerBuilder example work

### ISSUE THREAD

**Issue by Yakoot** [raamcosta/compose-destinations#628]
```
            DestinationsNavHost(
                navGraph = NavGraphs.root,
                dependenciesContainerBuilder = {
                    destination(TestScreenDestination) {
                        dependency(scaffoldState)
                    }
                }
            )
```
my screens
```
@Destination<RootGraph>(
    start = true,
)
@Composable
fun WelcomeScreen() {
    Text("welcome")
}

@Destination<RootGraph>
@Composable
fun TestScreen(
    scaffoldState: ScaffoldState
) {
    Text("testtest")
}
```

and I'm getting an error
Type mismatch: inferred type is TestScreenDestination but Nothing was expected
<img width="870" alt="image" src="https://github.com/raamcosta/compose-destinations/assets/4795345/fb86f621-7a82-427f-a691-28b4dd099c77">

destinations version 2.0.0-beta01
compose bom version 2024.04.01

**Comment by Yakoot** [comment]
https://github.com/Yakoot/TestComposeDestinations

**Comment by raamcosta** [comment]
Just need to import the function, rather than trying to call what's not even the function 😅 

this is the import btw, but the IDE will help you as well:
`import com.ramcosta.composedestinations.navigation.destination`
