### ISSUE TITLE
Business Logic support

### ISSUE THREAD

**Issue by mattinger** [raamcosta/compose-destinations#63]
This library is a great step forward, but the one thing I'm curious about is how you would get business logic down into your graph.

With the raw navigation library, I would create the navigation graph by hand, passing along the appropriate view model which contained the business logic.  That could then be used inside the destination's composables to pull data and pass it to the view layer, as well as creating the appropriate event handlers for button clicks and other things.

What I'm missing here is if i create a destination that needs a view model, where is that view model coming from?

I'd hate to rely on things like composition locals to do this for us.

**Comment by raamcosta** [comment]
Hi @mattinger ! 👋 

So, there are quite a few ways to do this. 
It will really depend on you (or your team) to decide which convention to adopt in this regard.

I'll be answering in detail, hoping I will get to take some of these notes to the documentation website (https://composedestinations.rafaelcosta.xyz).

### 1. Using default parameters feature

This is probably the most simple approach (especially if you're using Hilt) and it's one I've seen used even with the official library.

```kotlin
@Destination
@Composable
fun MyScreen(
    viewModel: MyScreenViewModel = hiltViewModel(),
    navigator: DestinationsNavigator,
) { /*...*/ }
```
If you're not using hilt, you can create your own method to get the ViewModel.

### 2. Using a setup Composable

This is actually my favorite, especially if you have additional setup you benefit from doing outside the actual screen. And it is also something people do even with the official navigation library.
With official compose navigation, you could do setup for your screen (like you said) in the same place you build the navigation graph and handle navigation arguments (which is arguably too many responsibilities in one place, but that's a conversation for another day).
With Compose Destinations, whatever you did there, you could do in what I call a. "setup" Composable. A setup Composable is a place to get all state and "event handlers" and then call the actual screen with the content which can then just receive state and lambdas.

```kotlin
// Think of this method as you would think about the setup code you would do inside NavGraphBuilder
@Destination
@Composable
fun MyScreen(
    navigator: DestinationsNavigator,
) { 
    val viewModel = getYourViewModelHere()
    
    MyScreenContent(
        isButtonEnabled = viewModel.isButtonEnabled, // for example of state
        onButtonClick = viewModel::onButtonClicked // for example of events
    )
}
```

Notice how your "Content" is a "pure" Composable. It only takes things that don't depend on the platform, it could even be part of a module shared in Kotlin Multiplatform. (Of course, you can accomplish the same thing with the other approaches)

### 3. Manually calling your screen

This is the closest way to how you'd do it in official compose navigation. But with Compose Destinations the only thing you're doing is calling the Composable. No navigation arguments or navigation graphs declaration done in the same place:

```kotlin
@Destination
@Composable
fun MyScreen(
    viewModel: MyScreenViewModel,
    navigator: DestinationsNavigator,
    someNavigationArgument: String //as an example of a nav arg
) { /*...*/ }

// -------------------

DestinationsNavHost(
    //....
) {
        composable(MyScreenDestination) { //this: DestinationScope<MyScreenDestination.NavArgs>
            MyScreen(
                viewModel = getYourViewModelHere(),
                navigator = destinationsNavigator,
                someNavigationArgument = navArgs.someNavigationArgument
            )
        }
}
```

As I said before, you are not building the navigation graph here. So you don't need to do this for all your screens, just the ones that need some parameters that the library cannot provide.

If there is some detail missing or some other way I can help, please don't hesitate.

**Comment by mattinger** [comment]
We are definitely using pure composables.  We put a layer on top of them that pulls things out of the view model and exposes them as properties (potentially state), and then passes navigation logic via lambda functions:

```
@Composable
fun MyComposable(
    val title: String,
    val button: String,
    val onButtonClick: () -> Unit
)
```

We then wrap this with another composables that would pull the title and button text from the view model, and create the click lambda which will trigger navigation.

I think we can use the third approach (manual creation) still do that conversion, but take advantage of the type safe features of destinations.

This might just be a matter of additional documentation, as it wasn't entirely clear to me from what i found in the docs.


Thanks.

**Comment by raamcosta** [comment]
> We put a layer on top of them that pulls things out of the view model and exposes them as properties (potentially state), and then passes navigation logic via lambda functions

> We then wrap this with another composables that would pull the title and button text from the view model, and create the click lambda which will trigger navigation.

Ok. Where is that layer being done? Can't it also get the view model? And isn't this the same as my second approach and thus solving your issue without the need to manually call your screens?

> I think we can use the third approach (manual creation) still do that conversion, but take advantage of the type safe features of destinations. However, this does mean that we would have to create every destination manually, since we don't want individual screens caring where they navigate to. It's not really their responsibility to know that IMHO.

You can definitely use the third approach and yes that will mean you need to do it for all screens that need a ViewModel. However, approaches one and two don't mean that individual screens need to care where they navigate to, so I'm a bit confused 😅 
Again, the setup Composable (second approach), is an annotated Composable that sets up all things for your actual pure Screen Composable. 

Example:

```kotlin
@Destination
@Composable
fun MyScreen(
    navigator: DestinationsNavigator,
) { 
    val viewModel = getYourViewModelHere() //replace with actual logic to get the ViewModel
    
    MyScreenContent(
        isButtonEnabled = viewModel.isButtonEnabled, // example of state
        onButtonClick = viewModel::onButtonClicked, // example of events
        // example of navigation, but you can also call a ViewModel method here
        // and wait for some UI Event (shared flow or channel exposed on ViewModel for example) to come 
        // with a `Direction` effectively delegating the decision to where you navigate to to the ViewModel
        onAnotherButtonClick = { navigator.navigate(SomeOtherDestination) }
    )
}

@Composable
fun MyScreenContent(
    isButtonEnabled: Boolean,
    onButtonClick: () -> Unit,
    onAnotherButtonClick: () -> Unit
)
```

Btw, just as a side note, even if you go with approach three, you may still extract methods to not end up with a big lambda all in one place:


```kotlin
DestinationsNavHost(
    //....
) {
    myScreen()
    mySecondScreen()
}

// Notice how close this function resembles the annotated Composable with approach 2.
private fun ManualComposableCallsBuilder.myScreen() {
    composable(MyScreenDestination) {
      val viewModel = getYourViewModelHere() //replace with actual logic to get the ViewModel
      
      MyScreen(
          isButtonEnabled = viewModel.isButtonEnabled,
          onButtonClick = viewModel::onButtonClicked,
          onAnotherButtonClick = { destinationsNavigator.navigate(SomeOtherDestination) }
      )
    }
}

private fun ManualComposableCallsBuilder.mySecondScreen() {
    // ...
}
```

Anyway, was this enough and satisfactory for your use case or would you like the lib to work differently in some way?

Thank you for feedback and sorry for long responses 🙏

**Comment by mattinger** [comment]
It can't "get" the view model unless it's going to refer to the activity so it can pull the view model from the activity's ViewModelStore.  The other option is to make it a composition local and have it fetched that way.  Not ideal, but doable I suppose

**Comment by raamcosta** [comment]
But there is already a `LocalViewModelStoreOwner.current`. No need to create new composition local or access activity directly.

And if you need the `NavBackStackEntry` to get the ViewModel, that is something the lib can provide. 
> Curiosity: The `LocalViewModelStoreOwner.current` should be the `NavBackStackEntry`, in most cases, you can safely cast it. Unless you're doing something not so common, the cast will succeed.

**Comment by raamcosta** [comment]
Hi @mattinger !

I've just launched a comprehensive documentation page on the lib's website about this:
https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels

If there is anything I can help with or any suggestion to make any of this better, please please get in touch!

I'll close this issue, but feel free to answer here or create a new issue / DM on twitter.
Thank you once again 🙇
