### ISSUE TITLE
[2.1.0-beta03] Navgraphs.* cannot be imported in the generated NavGraphs

### ISSUE THREAD

**Issue by SorrowBlue** [raamcosta/compose-destinations#630]
I had a problem after updating to 2.1.0-beta03. No problem with 2.1.0-beta02.

I created MainGraph in the app module and only included `XXXDestination` and `XXXXNavGraph` in another module.
※There is no `@Destination<MainGraph>` in the app module.
```kotlin:
@NavHostGraph
annotation class MainGraph {

    @ExternalNavGraph<BookshelfNavGraph>(start = true)
    @ExternalDestination<FavoriteAddScreenDestination>
    companion object Includes
}
```

`navgraphs.*` cannot be imported in the generated `NavGraphs`. 
![image](https://github.com/raamcosta/compose-destinations/assets/25735189/a44ee1ac-073b-4c71-a4cc-d90e269f53e8)

This problem does not occur if create a destination that is not used.
```kotlin:
@Destination<MainGraph>
@Composable
fun EmptyScreen() {}
```

**Comment by raamcosta** [comment]
Definitely seems like a bug.
Will look into it later in the evening, thank you for reporting 🙏

**Comment by raamcosta** [comment]
beta04 builds are running, expect to see them available in about 30min or so.

Let me know that it fixed the issue! Thank you once again.

**Comment by szymonchaber** [comment]
@raamcosta This fix is super important for multi-module projects, so it would be great to add that to releases tab in the repository as well
