### ISSUE TITLE
navargs.* cannot be imported in ArgsToSavedStateHandle.kt

### ISSUE THREAD

**Issue by SorrowBlue** [raamcosta/compose-destinations#631]
current version is 2.1.0-beta04.

`navargs.*` cannot be imported in ArgsToSavedStateHandle.kt.
I have a Destination in another module that does not define NavArgs.

![image](https://github.com/raamcosta/compose-destinations/assets/25735189/2697d207-47cf-400e-a2b5-754d2b88d3f3)

I can solve it by creating a meaningless Destination, but it's not pretty.  
For Example:
```kotlin
// :tutorial module
@Destination<ExternalModuleGraph>
@Composable
internal fun EmptyScreen(value: Int = 0) {
    Text(text = "$value")
}
```

***

I'm having a problem with the following code.
```kotlin
// :app module
@NavHostGraph
internal annotation class MainGraph {

    @ExternalNavGraph<BookshelfNavGraph>(start = true)
    @ExternalNavGraph<TutorialNavGraph>
    @ExternalDestination<FavoriteAddScreenDestination>
    companion object Includes
}
```
```kotlin
// :tutorial module
@NavGraph<ExternalModuleGraph>
internal annotation class TutorialGraph

@Destination<TutorialGraph>(start = true)
@Composable
internal fun TutorialScreen(navigator: TutorialScreenNavigator) {
TutorialScreen(onComplete = navigator::onComplete)
}
```

**Comment by raamcosta** [comment]
Fixed! Should be up later today.

Thank you once again for reporting 🙏

**Comment by raamcosta** [comment]
beta05 are building. should be up in 30min or so
