### ISSUE TITLE
Removing from composition and re-adding when navigating

### ISSUE THREAD

**Issue by marosseleng** [raamcosta/compose-destinations#634]
Hello, I wanted to check something, because I'm not sure where the problem resides. I have 2 destinations:

```kotlin
@RootNavGraph
@Destination
@Composable
fun ListScreen(navigator: DestinationsNavigator, viewModel: ListViewModel = koinViewModel()) {
    LaunchedEffect(viewModel) {
        // I want this to be called only on the first "open"
        viewModel.reloadList()
    }
    val list by viewModel.list.collectAsStateWithLifecycle()
    List(onItemClick = { navigator.navigate(DetailScreenDestination(it)) }
}
```

and
 
```kotlin
@RootNavGraph
@Destination
@Composable
fun DetailScreen(navigator: DestinationsNavigator, id: String, viewModel: ListViewModel = koinViewModel()) {
    LaunchedEffect(id) {
        viewModel.loadDetail()
    }
    val list by viewModel.list.collectAsStateWithLifecycle()
    Detail(onBackClick = { navigator.navigateUp() }
}
```

The thing is, when I navigate from list to detail and back, `LaunchedEffect` in `ListScreen` is executed again, which I think is unwanted.

It doesn't matter if I pass `Unit` as an argument to `LaunchedEffect`, it is still executed again on the next recomposition.

I wanted to ask if this is desired/expected behavior and if so - are there any ways to go around this? The problem is that I don'w want to reload the list each time I come back from the detail screen.

Thank you!

**Comment by raamcosta** [comment]
Hi!

yes, this is expected. When you navigate forward, the back stack entry and the ViewModels are kept but the Composable leaves composition and re enters it when you navigate back. So the LaunchedEffect runs again.

for this use case, what I do usually is I load list on the constructor of the ViewModel. This is better in my opinion for multiple reasons.

**Comment by marosseleng** [comment]
@raamcosta Thanks for the quick reply, sorry if it's a bad question, but is this feature of navigation or Compose Destinations?

The problem with loading something in constructor is that you have no control over it, eg in testing - your side effects are started by DI creating the instance, not you.

**Comment by raamcosta** [comment]
Neither. It’s how Compose works in general. Not related with navigation official or this library.

The ViewModel is created as the corresponding screen becomes visible, so I would say you do have control over when it gets instantiated and you should also have control over when it happens on tests. This has never been an issue for me.
As a bonus, the UI shouldn’t be saying things like “load the list” to the VM. The VM is the one that decides what to do. 
at most the UI can say “hey the UI is now visible” and then the VM makes the decision to load the list or not.
