### ISSUE TITLE
Missing classes detected while running R8 on AGP 8.4.0

### ISSUE THREAD

**Issue by dzgeorgy** [raamcosta/compose-destinations#636]
Hello! Thank you for this amazing library. However, after upgrading the AGP version to 8.4.0, I encountered a problem with a failed build due to missing classes.

`Missing class com.ramcosta.composedestinations.generated.featurex.navgraphs.FeatureXNavGraph (referenced from: com.ramcosta.composedestinations.generated.featurex.navgraphs.FeatureXNavGraph com.ramcosta.samples.playground.ui.screens.navgraphs.ProfileNavGraph$External_FeatureXNavGraph.$$delegate_0 and 15 other contexts)
Missing class com.ramcosta.composedestinations.generated.featurex.navgraphs.FeatureXNavGraphArgs (referenced from: com.ramcosta.composedestinations.generated.featurex.navgraphs.FeatureXNavGraphArgs com.ramcosta.samples.playground.ui.screens.navgraphs.ProfileNavGraph$External_FeatureXNavGraph.argsFrom(android.os.Bundle) and 3 other contexts)
`

Can be reproduced in your playground project by updating to AGP 8.4.0 and enabling minification for featureX. AGP 8.3.0 works fine.

**Comment by raamcosta** [comment]
Hello @dzgeorgy!

Interesting.. I will take a look at this, thank you for reporting 🙏

**Comment by raamcosta** [comment]
Fix should be up in the next 30min or so!
