### ISSUE TITLE
[DEEPLINK][2.1.0] Request to bring back withDeepLink()

### ISSUE THREAD

**Issue by extmkv** [raamcosta/compose-destinations#639]
Hi,

During the migration to V2 of the library, we noticed that you mentioned that withDeeplink was removed.

```These APIs were removed on v2. There are new and better ways to achieve the same thing.```

In our case, we can't achieve the same without it. Our app has different URI schemas by flavors that only the parent module has visibility and injects on our DI. We were building our own graphs and adding the deeplinks to the destinations over there by using the provided schema from DI. Not important, but we had an extension for it, and it is reusing the route + schema.

Unfortunately, we can't achieve the same just by using the annotation, our feature modules don't have the visibility of the schemas so using a constant is not an option, since the schema is provided via DI.

**Extension:**
```Kotlin
public fun <T> DestinationSpec.withDefaultDeeplink(scheme: DeeplinkScheme): DestinationSpec {
    return withDeepLink { uriPattern = "${scheme.value}://${this@withDefaultDeeplink.route}" }
}
```

**Example of a graph:**
```kotlin
 destinations =
                listOf(
                    ChatSupportScreenDestination.withDefaultDeeplink(schema),
                    ChatRateScreenDestination,
                ),
```

Any possibility of bringing this back? 🙏🏽

**Comment by raamcosta** [comment]
Hey 👋 

So essentially you need to be able to set deep links at runtime. The problem is not _where_ it is set, since there's ways to override things like deep links when importing destinations or graphs. The problem is that you cannot use annotations coz those can only take constants.

Is that it?

**Comment by extmkv** [comment]
I think that will solve our problem

**Comment by extmkv** [comment]
Just realized that by doing your approach we can start generating instead of building our owns.

**Comment by raamcosta** [comment]
So, is that good or bad? I'm not sure I understand what you mean 🤔

**Comment by extmkv** [comment]
It's better. We had to have the custom graphs just to include deeplinks, by using that approach it will be not necessary because the deeplinks will be added to the DestinationsNavHost trailing lambda.

**Comment by raamcosta** [comment]
Ahh, yes. With v2 there should be no reason for implementing NavGraphSpec of core library manually.

**Comment by raamcosta** [comment]
Went with above approach. It is included in beta07 that is currently building, so probably up in about 30min or so.
That version will also contain your PR changes (thanks for that! 🙏 )
