### ISSUE TITLE
Accompanist Navigation Material functionality now available in androidx.compose.material.navigation.*

### ISSUE THREAD

**Issue by SpiritualForest** [raamcosta/compose-destinations#644]
Migration guide is here: https://google.github.io/accompanist/navigation-material/#migration

Are you planning to start using it instead of accompanist, which has been deprecated?

**Comment by raamcosta** [comment]
We are already using official material navigation -> not from accompanist.

**Comment by raamcosta** [comment]
I updated the README. I think at some point I had done that already, but probably was lost in some merge conflict or something. Thanks for pointing it out!
