### ISSUE TITLE
Multiple Backstacks

### ISSUE THREAD

**Issue by saff1x** [raamcosta/compose-destinations#647]
Hi,
I'm thinking about implementing a multiple backstack system in my app. Each item in the bottom navigation bar should have its own backstack. However there are quite a few screens that are shared between each bottom navigation item. Is there a way to add multiple NavHostGraphs to a Destination? Or is there another way to implement a multiple back stack feature with this library?

Thanks in advance

**Comment by raamcosta** [comment]
The way to have multi back stacks with this library is the same we have with official compose navigation library.

I recommend checking this:
https://medium.com/androiddevelopers/multiple-back-stacks-b714d974f134

and this:
https://composedestinations.rafaelcosta.xyz/v2/common-use-cases/bottom-bar-navigation
