### ISSUE TITLE
Sharing a view model between destinations but with a view model factory

### ISSUE THREAD

**Issue by Jon889** [raamcosta/compose-destinations#650]
I've seen the docs [here](https://composedestinations.rafaelcosta.xyz/v2/common-use-cases/providing-viewmodels#share-viewmodels-between-multiple-destinations) and also [here](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-apis)

But I'm not sure how to go about sharing a ViewModel that needs to be created with a factory as it takes in some initial data which comes from the navigation arguments of the first screen it's used.

I've done this now, but I'm not sure if it's a good thing to do, because it seems like it would be something that is built in if it was a good thing?

```kotlin
@JvmInline
value class NavGraphViewModelStoreOwner(val value: ViewModelStoreOwner) : ViewModelStoreOwner by value

@Composable
fun Screen() {
    val engine: NavHostEngine = rememberNavHostEngine()
    val navController: NavHostController = engine.rememberNavController()
    DestinationsNavHost(
        navGraph = NavGraphs.loggedIn,
        engine = engine,
        navController = navController,
        dependenciesContainerBuilder = {
            dependency(NavGraphs.loggedIn) {
                NavGraphViewModelStoreOwner(remember(navBackStackEntry) {
                    navController.getBackStackEntry(NavGraphs.loggedIn.route)
                })
            }
        }
    )
}
```

Then in the destination I do the following, after having loaded some data in the FirstScreen and passing it to the SecondScreen to create the ViewModel. A ThirdScreen would then access it the same way but without the factory being provided.

```kotlin
@Destination
@Composable
fun SecondScreen(
    initialData: InitialData,
    navGraphViewModelStoreOwner: NavGraphViewModelStoreOwner
) {
    val viewModel = viewModel<SomeViewModel>(
        key = "somekey",
        viewModelStoreOwner = navGraphViewModelStoreOwner,
        factory = viewModelFactory {
            SomeViewModel(
                initialData = initialData,
            )
        }
    )
}

```

**Comment by raamcosta** [comment]
Hi 👋 

If you're always expecting the same type of arguments (in the example you used `InitialData`), then you can create the ViewModel in the place where you are creating your `NavGraphViewModelStoreOwner `.
Your screen can then receive the VM already created. Note that you have access to the navigation arguments in the `dependenciesContainerBuilder`.

**Comment by Jon889** [comment]
Thanks, that's through the `navArgs` field right? and they'll have to be cast from Any to the destination's NavArg type?

**Comment by raamcosta** [comment]
Yes. Although now that you mention it, at least for specific destinations, I could do better (so expect this on next lib versions):

```kotlin
destination(ProfileScreenDestination) { // this: DependenciesContainerBuilder<ProfileScreenNavArgs>
    val args: ProfileScreenNavArgs = navArgs // will compile just fine!
    dependency(viewModel<ProfileViewModel>())
}
```
