### ISSUE TITLE
Standalone Sealed Classes as NavArgs in Android

### ISSUE THREAD

**Issue by rodrirepresa** [raamcosta/compose-destinations#655]
**Issue Description:**
I am confused about the inability to use standalone sealed classes as navigation arguments (NavArgs) in our Destinations. However, I noticed that using data classes that hold sealed classes is allowed. This seems to be related to an issue with Kotlin Symbol Processing (KSP) when generating code.

_Not allowed:_

```
public sealed class MyArgument : Parcelable {

    @Parcelize
    public data class Type1(
        val text: String,
    ) : MyArgument()

    @Parcelize
    public data class Type2(
        val text: String,
    ) : MyArgument()
}
```

_Allowed:_

```
public data class MyArgument(
    val argumentType: ArgumentType,
)

public sealed class ArgumentType : Parcelable {

    @Parcelize
    public data class Type1(
        val text: String,
    ) : ArgumentType()

    @Parcelize
    public data class Type2(
        val text: String,
    ) : ArgumentType()
}
```

_In my screen:_

```
@Destination<Graph>(
    start = true,
    style = DestinationStyle.Dialog::class,
    navArgs = MyArgument::class,
)
@Composable
internal fun MyScreen()
```

**Comment by raamcosta** [comment]
When setting the navArgs in the destination annotation, the class is not the navigation argument, it’s just a class where navigation arguments are defined. So it doesn’t make sense for such a class to be a sealed type: you need a predefined set of arguments, you can’t tell the official nav lib “my arguments can either be these or these other”.

Im on the phone sorry for not formatting the reply, hopefully it’s understandable.

I’ve seen this confusion lately. Maybe I’ll enforce these classes to be named always SomehtingNavArgs to make it clear the args are its fields not itself.

**Comment by raamcosta** [comment]
Another thing: the class passed to Destination annotation navArgs does not need to be itself Parcelable or any other valid navigation type, precisely because it will not be serialised. Instead its fields will.

**Comment by raamcosta** [comment]
@rodrirepresa should I close this? Does it make sense?

**Comment by raamcosta** [comment]
I'm closing it, please comment below if there's anything else I can help you with :)

**Comment by rodrirepresa** [comment]
Yes, we can. Sorry for not answering!
