### ISSUE TITLE
Deeplink to nested graph destination not working

### ISSUE THREAD

**Issue by cwsiteplan** [raamcosta/compose-destinations#659]
Hi,

using `2.1.0-beta09` i can't get deeplinks to nested graph destinations working.

calling 

```
override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        intent?.let {
            lifecycleScope.launch {
navController.handleDeepLink(intent)
            }
        }
    }
```

and debugging the navcontroller - i do see that the

`_graph!!.matchDeepLink(NavDeepLinkRequest(intent))` fails.
as the _graph (root graph) does not have the deeplinks added from the nested destinations.

i assumed that the deeplinks are propagated to the root so it can handle those.

**Comment by raamcosta** [comment]
Try `navController.navigate(URI)` method instead of `handleDeepLinlk`.

This sounds similar to what I got reported previously by @extmkv .

Regardless, it is very likely nothing related with this library itself. But please do keep me posted 🙏

**Comment by cwsiteplan** [comment]
Tried to pass the URI - same thing.
debugging the URI matching i find the same problem that the graph only has one deeplink "registered"
`android-app://androidx.navigation/root`

**Comment by cwsiteplan** [comment]
created a sample app here: https://github.com/cwsiteplan/DeeplinkTest

**Comment by cwsiteplan** [comment]
updated to latest beta and still have the same issue that the deeplinks are not added to the root graph.

Attached you'll find the new debug logs

[c9b21e25_511b_43fe_92c9_a5aa854e1023.txt](https://github.com/user-attachments/files/16466104/c9b21e25_511b_43fe_92c9_a5aa854e1023.txt)

**Comment by cwsiteplan** [comment]
found sth interesting.

using the sample app from above - deeplinking does not work.
If I add navigation calls between the screens (linking them up) it does start working. (pushed the changes to the `fixed` branch in the repo)

**Comment by cwsiteplan** [comment]
using this in the sample app

```
override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        intent.data?.let {
            navController.navigate(it)
        }
    }
```

does crash with 
> java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=myapp://projects/660d429e2185771526403b9e/photo/be10a24d-5e17-4547-b006-1ed428dd82c3 } cannot be found in the navigation graph ComposeNavGraph(0x78dcd1ef) route=root startDestination={Destination(0x53d4b0bc) route=root_screen}

**Comment by cwsiteplan** [comment]
sorry, for the consuion - it was a simple mismatch of the URIs (subdomain) :/
