### ISSUE TITLE
(Open)ResultRecipient seems to cause recompositions

### ISSUE THREAD

**Issue by cwsiteplan** [raamcosta/compose-destinations#662]
Hi,

i'm working on compose performance improvements and looking for unnecessary re-compositions.

It seems that the `ResultRecipient` is causing recomposition as it is detected as unstable.

Can we mark those interfaces as stable?

**Comment by raamcosta** [comment]
We sure can! I was gonna swear they were already marked as Stable 😅 

Will come with next release in coming days. Thank you for reporting! 🙏
