### ISSUE TITLE
Could not find navigator with name "BottomSheetNavigator" Using compose 1.7

### ISSUE THREAD

**Issue by cj1098** [raamcosta/compose-destinations#665]
Hello 👋 
I saw this [issue](https://github.com/raamcosta/compose-destinations/issues/657)
and tried to update my compose version to the latest and I still get the same error. I checked my app dependencies and there are no compose dependencies lower than 1.7.0-beta05 now. I'm still getting the same error. I'm also using 
`androidx.compose.material:material-navigation:1.7.0-beta01` explicitly. 

>  java.lang.IllegalStateException: Could not find Navigator with name "BottomSheetNavigator". You must call NavController.addNavigator() for each navigation type.

My setup looks like this:
```
val sheetState = rememberModalBottomSheetState(
        initialValue = ModalBottomSheetValue.Hidden,
        skipHalfExpanded = true,
    )
val bottomSheetNavigator = remember { BottomSheetNavigator(sheetState) }
val navController = rememberNavController(bottomSheetNavigator)
    
ModalBottomSheetLayout(
        bottomSheetNavigator = bottomSheetNavigator,
    ) {}
```

Were you saying in your answer in that post that you don't need to explicitly add the androidx.compose.material:material-navigation:1.7.0-beta01 dependency because destinations has it? I'm on destinations 1.10.2 as well and don't have access to the ModalBottomSheetLayout in the material-navigation library.

Edit: I looked in 1.10.2 and it looks like you guys are still depending on accompanist material in that library. That's probably the problem 😅 https://github.com/raamcosta/compose-destinations/blob/1.10.2/gradle/libs.versions.toml
Could you update that to use the material-navigation library?

**Comment by raamcosta** [comment]
Hi 👋 

Answer is still the same, don't worry about compose navigation or navigation material version used underneath the hood. Don't explicitly set either of them, just use whatever this lib gives you.

1.10.2 is a stable version, there won't be anymore updates to that. The new versions use compose 1.7 which means for us 1.11.x or 2.1.x. So if you must use some of the new versions for whatever reason, then you need to update to compose 1.7 and to compose destinations corresponding versions.
