### ISSUE TITLE
Working with dropdown menu

### ISSUE THREAD

**Issue by filipus959** [raamcosta/compose-destinations#67]
Are there any specific circumstances for this to work with dropdown menu? navigation works perfectly but if i set it to onclick inside dropdown menu nothing happens?

`DropdownMenuItem(onClick = {
            Toast.makeText(
                context, "blahblah", Toast.LENGTH_SHORT).show()
            navigator.navigate(HomeDestinationScreenDestination)
        }) {
            Text("Destinations")
        }`

Toast is shown but navigation isnt working. when i use same navigation code for any other element it works

**Comment by raamcosta** [comment]
Not that I know of 🤔

What version are you using? There was a feature on older versions where by default we would not navigate if the screen was not on resumed state. That feature is no longer the default behaviour, you need to opt in. So can you try the latest version? And if it still happens can you try using navController? (Just switch DestinationsNavigator with NavController in the composable function and call extension method “navigateTo”)

Thanks!

**Comment by filipus959** [comment]
Im using newest version. Switching to navController fixed it but t im unable to use compose preview as EmptyDestinationsNavigator will no longer work. Anyway thanks for the fix

**Comment by raamcosta** [comment]
Hmmm 🤔 

but then I really want to understand why 😅 because the DestinationsNavigator pretty much just calls the NavController.

would you do me the favor of trying to debug with DestinationsNavigator and check if that ends up calling the NavController?
Or can you share that repository so I can take a look at it?

**Comment by raamcosta** [comment]
This is the code from the `DestinationsNavigator` implementation:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/80427734/157780121-b8692ad0-ceea-49d0-b756-5f31df662d33.png">

The `onlyIfResumed` is false by default at the interface level. So if you say the `NavController` works and you were really on the last version, I really don't see how `DestinationsNavigatior` would not work as well 🤔 

Is it possible that you were not using the latest version before? The `onlyIfResumed` was `true` by default before version 1.3.0-beta.

**Comment by raamcosta** [comment]
I'll close this issue, as I'm convinced that this was not an issue with DestinationsNavigator. But please @filipus959 if you can answer my questions of the last comment, I would really appreciate it!

**Comment by filipus959** [comment]
Hi sorry for late response i changed code back to DestinationsNavigator debug and code was working. Seems like you were right and maybe gradle files werent synchronized and it was using old version. But now DestinationsNavigator works perfectly thanks !
