### ISSUE TITLE
Is there any ideomatic way to navigate to the top level destination?

### ISSUE THREAD

**Issue by AlexanderKott** [raamcosta/compose-destinations#671]
Rafael, thank you for this amazing library 

I have an app with Bottom bar menu. Say:
[Home], Products, Settings

[ ] - here means selected

Home leads to A1 -> A2-> ....
Products leads to B1 -> B2-> ....
Settings leads to C1 -> C2-> ....

I want to navigate from A2 to C1.
So the bottom bar looks like this:
[Home], Products, Settings
to 
Home, Products, [Settings]

For user this will looks like somethig on tab Home opens tab Settings  (the graph of Home should be left like it is)

looks like i cannot achieve this by using the DestinationsNavigator, right?

**Comment by raamcosta** [comment]
You can achieve everything you can also with the official library, in a very similar manner.

Take a look here https://composedestinations.rafaelcosta.xyz/v2/common-use-cases/bottom-bar-navigation (there's also an official article link inside you should look at).
