### ISSUE TITLE
Is there a way to use ResultBackNavigator in ActivityDestination?

### ISSUE THREAD

**Issue by silverAndroid** [raamcosta/compose-destinations#673]
Based on https://composedestinations.rafaelcosta.xyz/v2/navigation/backresult, I can pass a result via ResultBackNavigator to a composable annotated with Destination. 

Is there a way I can inject it to the Activity?

**Comment by raamcosta** [comment]
Unfortunately no. Support for activities is very shallow from official library. It's probably technically possible, but there are no plans to have this any time soon.
