### ISSUE TITLE
Error in multimodule v2 NavHostGraph

### ISSUE THREAD

**Issue by davisoqt** [raamcosta/compose-destinations#677]
I have a profile module with a few destinations. Inside that module i create
`@NavGraph<ExternalModuleGraph>
internal annotation class ProfileGraph` then in app module i create a  
`@NavGraph<ExternalModuleGraph>
internal annotation class ProfileGraph
@NavHostGraph
annotation class MainGraph {

    @ExternalNavGraph<ProfileNavGraph>(start = true)
    companion object Includes
}`
 
When i create the `DestinationsNavHost(
                            modifier = Modifier.fillMaxSize(),
                            navGraph = MainGraph,
                            navController = navController
                        )`  i get these error 
`Type mismatch.
Required:
NavHostGraphSpec /* = TypedNavHostGraphSpec<*> */
Found:
MainGraph.Includes`

**Comment by raamcosta** [comment]
You’ll want to pass the generated NavGraph, not your annotation class. Probably MainNavGraph or NavGraphs.root.

**Comment by raamcosta** [comment]
I'll assume this is solved!
