### ISSUE TITLE
When to expect rc/ release version of v2 

### ISSUE THREAD

**Issue by miduch** [raamcosta/compose-destinations#681]
Hi, is it possible to get some rough idea when to expect rc/release version of v2 lib ? 

thanks!

**Comment by raamcosta** [comment]
I’ve been hesitant only because I’m working on KMP support and it may cause some changes to the library APIs or behaviour.
Given I’m on this beta state, the changes would be more expected.

That said, v2 works great with no known issues. So you don’t have to be hesitant to adopt it. Changes will be well documented on release notes and I don’t expect anything that would be hard to adapt to.

**Comment by wukaicheng** [comment]
Release a version using Navigation 2.8.0-release first?

**Comment by raamcosta** [comment]
Already done. Oops I may have forgotten about the GitHub release and release notes though 😅

anyway last v2 and v1 versions already using stable compose 1.7 and navigation 2.8

**Comment by miduch** [comment]
> I’ve been hesitant only because I’m working on KMP support and it may cause some changes to the library APIs or behaviour. Given I’m on this beta state, the changes would be more expected.
> 
> That said, v2 works great with no known issues. So you don’t have to be hesitant to adopt it. Changes will be well documented on release notes and I don’t expect anything that would be hard to adapt to.

https://github.com/raamcosta/compose-destinations/issues/661 is blocker to take v2 in use (atleast for us). Other than this, have not really find any issue and v2 seems to work great

**Comment by raamcosta** [comment]
Fair enough, note that it is only for start destinations with arguments and seems to be under specific situations. But it’s a strange thing for sure, I will be checking it asap 🙂

**Comment by miduch** [comment]
> note that it is only for start destinations with arguments and seems to be under specific situations

call us unlucky but we exactly have this situation :) ending up with TitleBar showing `{title}` as title text for a while before it shows actual title  :)

**Comment by miduch** [comment]
https://github.com/raamcosta/compose-destinations/issues/661#issuecomment-2348725527

**Comment by raamcosta** [comment]
I'm closing this as I don't think it's really tracking anything useful, but thanks for opening!

**Comment by UKMIITB** [comment]
@raamcosta 
Any tentative timeline to mark v2 as stable.
As long as it has beta tagged to it, we cannot use it in our production app

**Comment by UKMIITB** [comment]
@raamcosta 
Bumping this up
