### ISSUE TITLE
Navigation Multi-stack clear 

### ISSUE THREAD

**Issue by Lokesh-30** [raamcosta/compose-destinations#683]
i am using Bottom navigation with multi-stack 

Some stacks are saved and restore on navigating between them, so is there a way to clear all the stacks that are saved in the savestate ?

**Comment by raamcosta** [comment]
Hey @Lokesh-30 👋 

Sorry I'm not sure I understand the question but it doesn't seem like anything specific to Compose Destinations. You may want to check how to do this with official library and then it should be obvious how to achieve the same with this library.
