### ISSUE TITLE
dependenciesContainerBuilder / dependency() related question

### ISSUE THREAD

**Issue by miduch** [raamcosta/compose-destinations#685]
Hi, Is it possible to achieve following 

```
    val somethingA: Something<A>()
    val somethingB: Something<B>()

    DestinationsNavHost(
        dependenciesContainerBuilder = {
            dependency(somethingA)
            dependency(somethingB)
        }
    )
```

get dependency in screen side 

```
@Composable
fun MyScreen(
    somethingA: Something<A>,
    somethingB: Something<B>,
) {
}   
```

dependency map in DestinationDependenciesContainerImpl has only one entry in my case and value is somethingB. Other somethingA is no where to be found

**Comment by raamcosta** [comment]
Hey @miduch 👋 

Unfortunately not like that. I don't want to turn this feature into a full fledged DI framework 😄 
Personally, I would wrap these in some other classes with different types and use those instead, or I would call the composables manually (as described here: https://composedestinations.rafaelcosta.xyz/v2/arguments/nav-host-parameters#manually-call-your-screen-composable).

**Comment by miduch** [comment]
> Hey @miduch 👋
> 
> Unfortunately not like that. I don't want to turn this feature into a full fledged DI framework 😄 Personally, I would wrap these in some other classes with different types and use those instead, or I would call the composables manually (as described here: https://composedestinations.rafaelcosta.xyz/v2/arguments/nav-host-parameters#manually-call-your-screen-composable).

that dependency wasn't 100% UI related and was able to move to hilt where it belonged
