### ISSUE TITLE
Nav graph with variable start / multiple entry points

### ISSUE THREAD

**Issue by TomBell-Trove** [raamcosta/compose-destinations#686]
Is it possible to have multiple entry points into a nav graph?

Eg. if I have a particular flow, with different combinations of screens depending on the exact user action...

- Red (start) -> Green -> Blue
- Green (start) -> Blue
- Yellow (start) -> Red
- Yellow (start) -> Green -> Blue

Do I have to make three nav graphs with different starts? Or is there a cleaner way?

**Comment by raamcosta** [comment]
Hi @TomBell-Trove 👋 
I'm not sure I understand the question 🤔 . Each graph has a start destination which is used if you directly navigate to the graph, but you can also navigate directly to the graph's destinations.

**Comment by TomBell-Trove** [comment]
Oh, perfect. I didn't know that - thank you :)
