### ISSUE TITLE
How to send the cancelation result?

### ISSUE THREAD

**Issue by margarita-v** [raamcosta/compose-destinations#69]
Now it's possible to use `resultNavigator.navigateBack` for sending confirmation result from screen. Is there any opportunity to send the cancelation result when the result screen composable is gone in order to handle both results in the same callback of recipient screen?
For example:
```
@Destination
@Composable
fun FeedScreen(
    openForResultClicked: () -> Unit,
    onResult: (Boolean) -> Unit,
    resultRecipient: ResultRecipient<ResultScreenDestination, Boolean>
) {
    resultRecipient.onResult { succeed ->
        onResult(succeed)
    }
    // open screen for result
}

@Destination
@Composable
fun ResultScreen(
    navBackStackEntry: NavBackStackEntry,
    resultNavigator: ResultBackNavigator<Boolean>
) {
   // Doesn't work: when the ResultScreen composable is gone, I'd like to send this cancelation result in order to handle in the same `onResult` callback of FeedScreen
    DisposableEffect(key1 = Unit) {
        onDispose {
            resultNavigator.setResult(false)
        }
    }
    Box(modifier = Modifier.fillMaxSize()) {
        Button(
            onClick = {
                // the confirmation result works when action is performed
                resultNavigator.navigateBack(true)
            },
            modifier = Modifier.align(Alignment.Center)
        ) {
            Text(textAlign = TextAlign.Center, text = "Success!")
        }
    }
}
```
This `DisposableEffect` for `ResultScreen` doesn't work too:
```
    DisposableEffect(key1 = Unit) {
        val observer = LifecycleEventObserver { source, event ->
            when (event) {

                Lifecycle.Event.ON_DESTROY -> {
                    resultNavigator.setResult(false)
                }

                else -> Unit
            }
        }

        navBackStackEntry.lifecycle.addObserver(observer)

        onDispose {
            navBackStackEntry.lifecycle.removeObserver(observer)
        }
    }
```
Is there any best practice to solve it or should I use different callbacks for cancelation based on composable lifecycle and confirmation based on action?

**Comment by raamcosta** [comment]
I remember thinking if this would ever be helpful when I was implementing the nav result feature. Turns out it is.

Would this work for your use case?
- If `ResultScreen` becomes visible and after that, the `FeedScreen` becomes visible again and no value is received, then we consider it canceled. This would be done by the library, and the result received on `onResult` would be a wrapper to the current value which would allow us to check if nav result was canceled or there is actually a value:

```kotlin
sealed interface NavResult<out R> {
    object Canceled: NavResult<Nothing>
    data class Value<R>(val value: R): NavResult<R>
}
```

```kotlin
//...
    resultRecipient.onResult { confirmed ->
        when (confirmed) {
            is NavResult.Canceled -> println("canceled!!")
            is NavResult.Value -> if (confirmed.value) {
                navigator.navigate(SomeDestination)
            }
        }
    }
```

**Comment by margarita-v** [comment]
I think it would be perfect 👍

**Comment by raamcosta** [comment]
Hey @margarita-v !

So the new 1.3.5-beta release contains this new enhancement and deprecates the old `onResult` to replace it with `onNavResult`. 
Please try it and let me know if that works well for you! 🙂

**Comment by margarita-v** [comment]
Thank you, now it works perfectly 🔥
