### ISSUE TITLE
How to deal with multiple NavGraphs in BottomNavigation

### ISSUE THREAD

**Issue by robertlinsener** [raamcosta/compose-destinations#73]
Maybe an easy issue, but I was just not able to solve it yet. 
How can I just accomplish following: 

I have one Scaffold Bottom Navigation Bar at my home screen. Lets say with 3 different items. Each item leads into a own NavGraph containing all the linked screens. While I navigate within this NavGraph I want the Bottom Bar Item to stay active. 
I tried so solve it with this nice library but I am still struggeling and I get so confused with all those setting. I would need a simple example. Unfortunately the provided DestinationsTodoSample App does not behave the way I need it.

**Comment by raamcosta** [comment]
Hi @robertlinsener !

Have you checked this from documentation website?
https://composedestinations.rafaelcosta.xyz/common-use-cases/bottom-bar-navigation

Notice the final considerations in that page, particularly the number 2.
There is also a link to the tivi fork where I used this approach (in that case I also had to declare my destinations in a slight more complicated way with “routedIn” function, but you can likely ignore that part).

Let me know if this helps 🙂

**Comment by robertlinsener** [comment]
@raamcosta Thank you so much for your quick answer. Yes, you are right, the tivi fork helped me a lot. :)
