### ISSUE TITLE
Using XML based navigation and compose destinations in the same app?

### ISSUE THREAD

**Issue by slickorange** [raamcosta/compose-destinations#75]
Is it possible to use XML based navigation and compose destinations in the same app?

I have only started learning Compose and I am considering to migrate my existing app fully to Compose.

I want build new screens as Compose screens and I want to gradually migrate my fragments to Compose screens.

Is is possible to navigate from a fragment in my existing XML based navgraph to a composable?
I guess the composable screens will need to live in a separate navgraph, but I am unsure if this is possible and how I would hook the two navgraphs up together.

Any suggestions?

**Comment by raamcosta** [comment]
In this case, your best bet is to use Composable inside Fragments. Then you can just use your normal methods to navigate to those Fragments and in onCreateView you return a ComposeView, I think it’s called.

As seen here for example 
https://stackoverflow.com/questions/59368360/how-to-use-compose-inside-fragment
