### ISSUE TITLE
Minimal working example/implementation guide

### ISSUE THREAD

**Issue by szsoftware** [raamcosta/compose-destinations#77]
Hi there,

thanks a lot for the very promising contribution.

However, I have problems to implement the solution, because it is not clear to me what steps in the sample app are "just" good code/architecture practises and which are mandatory.

The README howto is not complete from my personal perspective.
For instance, it is not clear to me where exactly to init the framework/to put DestinationsNavHost(...).

Many thanks in advance!

**Comment by raamcosta** [comment]
Hi @szsoftware !

First of all, have you looked at https://composedestinations.rafaelcosta.xyz ?

Also, a good video to get you started is this from Phillip Lackner:
https://youtu.be/Q3iZyW2etm4

Finally, it may be advisable to know a little about official Compose Navigation.

Let me know if this helps! 
many question feel free to add it here and I’ll help you 🙂

**Comment by szsoftware** [comment]
Hi Rafael!

Thank you very much for your quick reply.

Your questions:
1. yes I did. Probably not good enough
2. Woah, I "love" this guy and his tutorials. Thanks for the hint. His further sources are also worth to be mentioned. You both guys are a very cool symbiosis.
3. Yes I do, and used it already in another project. But because of the already known, rediculous verbosity and redundancy I decided to wait for the savior who brings us a nice library. Thanks for that.

That was a dry one, right? I really can't emphasize enough how stoked I am from your work.
As you say in your medium.com article: You can really be proud of it.

Using your library will be a game changer in my app development, because now I have the glue to put all my functional prototypes together and assign them to navigatable views/screens/gui.

Did I mention, that my current use case is working now? It took me really no efforts to implement ComposeDestinations after considering the hints mentioned above.

Again, thank you very much and have a nice time!
