### ISSUE TITLE
The Destination Screen is full size white backgrounded

### ISSUE THREAD

**Issue by mykola-tarchanyn** [raamcosta/compose-destinations#82]
Hey @raamcosta. I have a composable B that's covering a certain portion of the screen. My composable A is a start destination and when I navigate to composable B the full screen is white with composable B on top of it. How can I get rid of that white background? I don't see the white background when using Compose Navigation library though.

example attached
<img width="234" alt="Screen Shot 2022-03-30 at 11 18 05 AM" src="https://user-images.githubusercontent.com/10888016/160884502-2f2cd945-6dd0-4953-9f16-4c6d0ebe8f9c.png">
.

**Comment by raamcosta** [comment]
Hi @mykola-tarchanyn !

What exactly do you want to accomplish? I’m not sure I understood 100%.
Do you want composable B to be shown on top of A? Like a dialog or a bottom sheet?

**Comment by raamcosta** [comment]
And you mentioned you had it working with Compose Navigation. Can I see that code?

**Comment by raamcosta** [comment]
That’s not so easy, regardless of if you’re using Compose Destinations or official compose navigation, unless you’re ok with a dialog styled screen or a bottom sheet.  
Everything else is custom made, there isn’t anything ready out of the box for that, even for traditional XML, let alone Compose world. At least that I know of.

From your example screenshots it doesn’t seem too far of from a bottom sheet. So maybe try that and see if that looks fine to you.
To use bottom sheets with Compose Destinations, read this:  
https://composedestinations.rafaelcosta.xyz/styles-and-animations#bottomsheet-style

And also check the last section of the same web page. Any questions, I’m here to help.
I’ll close the issue, but please feel free to question whatever down below 👇

**Comment by mykola-tarchanyn** [comment]
I think the dialog-styled screen is the closest to what I want (with `usePlatformDefaultWidth = false`) but not ideal as it adds the dialog-styled elevation etc.

To my little testing using vanilla compose navigation the white background wasn't there and I was able to see the composable A behind the composable B, that's why I thought your library sets that kind of white background. I don't really have the code to show but it should be as simple as calling the composable from 
`NavHost() { 
composable(pathToA) {
       A()
}
composable(pathToB) {
       B() 
}
}`

**Comment by raamcosta** [comment]
No, my library literally just calls official compose navigation APIs. I really think this is the normal behaviour even with oficial compose navigation. In fact, we had a discussion about a similar request on kotlin slack and even Ian Lake said this had to be done outside the NavHost level.

Check if you have access to that discussion:

https://kotlinlang.slack.com/archives/CJLTWPH7S/p1647816927842829

Anyway, when I have some time I will retest your simple code with official navigation, just to be sure.

**Comment by mykola-tarchanyn** [comment]
thanks.  What Ian Lake is saying is that if you need something to persist even while you change to a different screen, then that content should never have been a part of your NavHost. In my case, I don't need it to persist while I change to a different screen, I just need to be able to set a transparent background.

**Comment by raamcosta** [comment]
Yes, but we were also talking about bottom sheets, so I thought it could be relevant.

Anyway, what you need feels like a variation of dialog and bottom sheet which both had their specific development. If this was so simple, I feel like we could just center a screen on top of the previous one, but that's not the case.
Maybe later today I get to check this with official Compose navigation, but I really don't see how my library could be impacting anything like this 🤔

**Comment by mykola-tarchanyn** [comment]
yeah, dialogs and bottom sheets have their own difficulties to work with such as listening to back button clicks.

I appreciate you checking this out!

**Comment by raamcosta** [comment]
Hi @mykola-tarchanyn !

I just tested with the most simple code possible and I have always white background. 
On Screen B, I have only a `Text` composable, nothing else.

Are you sure when you had that working with official navigation it was just this simple? Were you not doing something else?

**Comment by mykola-tarchanyn** [comment]
Hi @raamcosta , my Screen B was setup like this:
```
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Transparent),
        contentAlignment = Alignment.BottomCenter,
    ) {

        Column(
            modifier = Modifier
                .fillMaxWidth()
        ) {
            Text(text= "Text")
        }
    }

**Comment by raamcosta** [comment]
Ok, replaced my Screen B with that, still have the white background.

**Comment by raamcosta** [comment]
Yeah, each screen always has a max-sized white background.
