### ISSUE TITLE
previewing @Composable Animated Screen in @Preview function  

### ISSUE THREAD

**Issue by Deamonangel** [raamcosta/compose-destinations#88]
I'm trying to use transition but the **import won't work** 🔽. I didn't find any thing of the sample that use the preview with "AnimatedVisibilityScope", nothing on the doc too. I'm a bit worry that not implemente.
Did i miss something ?

<details open> 
 <summary>Settings Screen</summary>

![previewing_animated_screen](https://user-images.githubusercontent.com/57954853/161723439-9d8eccf8-42e8-4151-a7ba-11239598ea7d.png)

</details>

I will show my NavGraph & my screen transition 🔽.

<details open> 
 <summary>NavGraph</summary>

```kotlin
@ExperimentalAnimationApi
@ExperimentalMaterialNavigationApi
@Composable
fun NavGraph(
    modifier: Modifier = Modifier,
    navController: NavHostController,
) {
    val navHostEngine = rememberAnimatedNavHostEngine()

    DestinationsNavHost(
        navGraph = NavGraphs.root,
        startRoute = NavGraphs.root.startRoute,
        navController = navController,
        engine = navHostEngine,
        modifier = modifier,
    ) {
        settingsScreen()
        welcomeScreen()
    }
}

@ExperimentalAnimationApi
private fun ManualComposableCallsBuilder.welcomeScreen() {
    composable(WelcomeScreenDestination) {
        WelcomeScreen(navigator = destinationsNavigator)
    }
}

@ExperimentalAnimationApi
private fun ManualComposableCallsBuilder.settingsScreen() {
    animatedComposable(SettingsScreenDestination) {
        SettingsScreen(navigator = destinationsNavigator)
    }
}
```

</details>

<details open> 
 <summary>Settings Transitions</summary>

```kotlin
@ExperimentalAnimationApi
object SettingsTransitions : DestinationStyle.Animated {

    override fun AnimatedContentScope<NavBackStackEntry>.enterTransition(): EnterTransition? {

        return when (initialState.navDestination) {
            WelcomeScreenDestination ->
                slideInHorizontally(
                    initialOffsetX = { 1000 },
                    animationSpec = tween(700)
                )
            else -> null
        }
    }

    override fun AnimatedContentScope<NavBackStackEntry>.exitTransition(): ExitTransition? {

        return when (targetState.navDestination) {
            WelcomeScreenDestination ->
                slideOutHorizontally(
                    targetOffsetX = { -1000 },
                    animationSpec = tween(700)
                )
            else -> null
        }
    }

    override fun AnimatedContentScope<NavBackStackEntry>.popEnterTransition(): EnterTransition? {

        return when (initialState.navDestination) {
            WelcomeScreenDestination ->
                slideInHorizontally(
                    initialOffsetX = { -1000 },
                    animationSpec = tween(700)
                )
            else -> null
        }
    }

    override fun AnimatedContentScope<NavBackStackEntry>.popExitTransition(): ExitTransition? {

        return when (targetState.navDestination) {
            WelcomeScreenDestination ->
                slideOutHorizontally(
                    targetOffsetX = { 1000 },
                    animationSpec = tween(700)
                )
            else -> null
        }
    }
}

```

</details>

**Comment by raamcosta** [comment]
Hi @Deamonangel!

First of all: do you really need the AnimatedVisibilityScope in the Composable? I see that it is not used in the screen shot sent.
If you don’t, you can just remove it.
If you really do need it, then you can either use it and call other Composable without it and just preview this second one, OR you can just implement the AnimatedVisibilityScope interface with all empty methods and use that implementation on Preview.

Let me know if this helps 🙂

**Comment by raamcosta** [comment]
On a side matter, I noticed you are manually calling your Settings Screen Composable and you are passing an EmptyDestinationsNavigator. Why? EmptyDestinationsNavigator is only meant for previews as it won’t actually navigate or do anything. Also you probably don’t need to manually call it? At least it looks like you don’t. Also, the real destinations navigator can be accessed via `destinationsNavigator` inside the scope of that lambda function.

**Comment by Deamonangel** [comment]
Hi @raamcosta,

I changed some screenshots because I was working on it. I try to change/modify the animations in order to match the expectations.  
I need the AnimatedVisibilityScope since I will be animating transitions to and from this screen (and others). The issue lies in the fact that having a preview (which usually isn't an extension of AnimatedVisibilityScope) doesn't work when the Compose screen is marked as AnimatedVisibilityScope.

Is there a way of having a preview of a composable that is supposed to be animated ?

**Comment by raamcosta** [comment]
>  need the AnimatedVisibilityScope since I will be animating transitions to and from this screen (and others).

This does not mean you need the `AnimatedVisibilityScope`. You can do that by just adding the style in the annotation as you did. Meaning: you can just remove that receiver. 

```kotlin
@Destination(style = SettingsTransitions::class)
@Composable
fun SettingsScreen( //...
```

👆 this will work and it will be animated even without the `AnimatedVisibilityScope` receiver. The `AnimatedVisibilityScope` is only needed if you're going to need to use it inside the function, for example, to know the progress of the animation.

> The issue lies in the fact that having a preview (which usually isn't an extension of AnimatedVisibilityScope) doesn't work when the Compose screen is marked as AnimatedVisibilityScope.
> Is there a way of having a preview of a composable that is supposed to be animated ?

If you really need `AnimatedVisibilitySCope`, as I said in my previous answer, you can just make an object that implements `AnimatedVisibilityScope` and use that in your preview:

```kotlin
@Preview
@Composable
fun SettingsScreenPreview() {
    EmptyAnimatedVisibilityScope.SettingsScreen(EmptyDestinationsNavigator)
}

// Put this in some core file
object EmptyAnimatedVisibilityScope : AnimatedVisibilityScope {
    @ExperimentalAnimationApi
    override val transition: Transition<EnterExitState>
        get() = error("Empty implementation of AnimatedVisibilityScope should not be called")

}
```

**Comment by raamcosta** [comment]
Also, you don't need to manually call your screens in your example, unless you have some reason that is not clear in the snippet you pasted.

So your DestinationsNavHost call can just be:

```kotlin
@Composable
fun NavGraph(
    modifier: Modifier = Modifier,
    navController: NavHostController,
) {
    val navHostEngine = rememberAnimatedNavHostEngine()

    DestinationsNavHost(
        navGraph = NavGraphs.root,
        navController = navController,
        engine = navHostEngine,
        modifier = modifier
    )
}
```

**Comment by Deamonangel** [comment]
I came across another issue (i will open an other issue 😉) and I think that answers my question.
