### ISSUE TITLE
Dialog is lost

### ISSUE THREAD

**Issue by MakarenkoVlad** [raamcosta/compose-destinations#92]
I navigated: 1. composable with default style -> 2. composable with dialog style -> 3. composable with default style. When I navigated up - 2nd composable was lost

**Comment by MakarenkoVlad** [comment]
Saw the related issue and fixed it

**Comment by raamcosta** [comment]
So this is expected as explained here: 
https://github.com/raamcosta/compose-destinations/issues/78#issuecomment-1080666464

(probably what you found then 🙂 )
Thanks anyway!
