### ISSUE TITLE
DestinationStyle.Animated in multi module

### ISSUE THREAD

**Issue by STAR-ZERO** [raamcosta/compose-destinations#95]
Is there a way to use `DestinationStyle.Animated` in multi module?
I can't access Destination in other modules.

```kt
object SampleTransitions : DestinationStyle.Animated {

    override fun AnimatedContentScope<NavBackStackEntry>.enterTransition(): EnterTransition? {
        return when (initialState.navDestination) { // Error: Unresolved reference: navDestination
            AnotherModuleScreenDestination -> { // Error: Unresolved reference: OtherModuleScreenDestination
                // ...
            }
            else -> null
        }
    }
}
```

**Comment by raamcosta** [comment]
Hi @STAR-ZERO !

So, I can see a couple of ways but none is ideal. I will think of a way to improve this.

What do you think about declaring this object in the navigation module (the one that calls DestinationsNavHost)? Since that is the module that knows the whole navigation graph and its Destinations.  
Im thinking about creating an annotation to use in these objects to say where to install them in, making the link from the opposite direction.  
Does this sound good?

**Comment by STAR-ZERO** [comment]
It's a good idea to define this object in the navigation module 👍

**Comment by raamcosta** [comment]
This was fixed @STAR-ZERO !

Check it here:
https://composedestinations.rafaelcosta.xyz/styles-and-animations#runtime-style

**Comment by raamcosta** [comment]
Please let me know if this fixes the issues for you 🙂

**Comment by STAR-ZERO** [comment]
It works! Thanks 👍 

I have a question.
If NavGraphs is not generated  by KSP, `NavBackStackEntry.appDestination` is not generated.
So, I should use [`NavBackStackEntry.destination`](https://github.com/raamcosta/compose-destinations/blob/dcbf1883129a6899ddc130e67499ab89c95d3574/compose-destinations/src/main/java/com/ramcosta/composedestinations/utils/SpecExtensions.kt#L13-L15) instead of `NavBackStackEntry.appDestination`, right?

```kotlin
override fun AnimatedContentScope<NavBackStackEntry>.exitTransition(): ExitTransition? {
    return when (targetState.destination(MyGraphs.root)) { // instead of targetState.appDestination()
        FooScreenDestination -> // ...
        else -> null
    }
}
```

**Comment by raamcosta** [comment]
Correct! the reason for `appDestination` is just to return a sealed version of `DestinationSpec` which can only happen in single module apps!
For all others, you need to call `destination`. Note that it is easy to create your own extension function that calls `destination` and passes the appropriate NavGraph!

```kotlin
fun NavBackStackEntry.rootDestination() = destination(NavGraphs.root) //example
```

**Comment by raamcosta** [comment]
I'll close this!.

**Comment by raamcosta** [comment]
@STAR-ZERO 

Just in case what I said was misleading, you don't need to pass the NavGraph where the navBackStackEntry belongs to, you can just give the top level nav graph that contains all others, the same you pass to the `DestinationsNavHost`.

Just wanted to make that clear :D

**Comment by STAR-ZERO** [comment]
Thanks 👍
