### ISSUE TITLE
[Bottom Sheet - Background]

### ISSUE THREAD

**Issue by cogito666** [raamcosta/compose-destinations#99]
Thanks for the nice library which makes code snippets simple and clear.

While I am using this library, I got to have a question for bottom-sheet.
It works fine, but I want to know if it's possible to show background when the sheet pops up.

**Comment by raamcosta** [comment]
What do you mean with showing a background? Usually the background is the previous screen, right? So you want to change that “previous screen background” by something else? Like what for example?

sorry for all the questions 😅

**Comment by cogito666** [comment]
Thanks for your questions! I am happy to answer.

When a button sheet pops up, I expected the background (previous screen background - as you mentioned) still be shown.
However, I couldn't see it on my device. 

Plus, once I turned off bottom sheet "by pressing down the sheet on the ground direction", the screen is empty.

I wonder if I can use this library for bottom sheet UI.
FYI, I am using "ModalBottomSheetLayout" to make up my buttom sheet.  😁

**Comment by raamcosta** [comment]
This is most likely some wrong setup on your end. Please check how we do it in the Sample app(DestinationsSampleScaffold.kt) or check it here:

https://google.github.io/accompanist/navigation-material/ (just remember that you want to use `DestinationsNavHost` instead of `NavHost`)

**Comment by raamcosta** [comment]
Let me know if you get it to work! 🙂

**Comment by cogito666** [comment]
I checked the link you gave and found out that I was mis-using "ModalBottomSheetLayout".

Since I had little experience of Android development especially just got into Jetpack Compose.
I considered "ModalBottomSheetLayout" is similar with SwiftUI's ".sheet" and I didn't specify anything on the rest-content area. 

Now I know what's the best practice. 🙈🙈🙈
I am sorry to bother you and thanks for your effort!
